/**
 * ============================================================================
 * ADL Gazetteer Reference Dataset & USGS GNIS Benchmark Catalog
 * ============================================================================
 * Curated dataset based on the Alexandria Digital Library (ADL) Project testbed
 * (UC Santa Barbara / MIL) and the USGS Geographic Names Information System (GNIS).
 * ============================================================================
 */

export const ADL_BENCHMARK_DATA = [
  // --- UCSB & SANTA BARBARA CHANNEL (ADL CRADLE) ---
  {
    adlId: "ADL-US-GNIS-244120",
    gnisId: 244120,
    primaryName: "University of California, Santa Barbara",
    normalizedName: "university of california santa barbara",
    fttCode: "manmade",
    gnisFeatureClass: "School",
    stateAlpha: "CA",
    countyName: "Santa Barbara",
    latitude: 34.4140,
    longitude: -119.8489,
    elevationMeters: 14.0,
    elevationFeet: 46.0,
    usgsQuadName: "Goleta",
    bbox: [-119.8550, 34.4090, -119.8400, 34.4190],
    variantNames: ["UCSB", "UC Santa Barbara", "Alexandria Digital Library Project Headquarters"],
    metadata: {
      research_initiative: "NSF/NASA/DARPA DLI-1 ADL Testbed (1994-1998)",
      lead_pi: "Larry Carver / Terence Smith / Linda L. Hill / Greg Janée",
      notes: "Cradle of georeferenced digital library research and ADL GCS development."
    }
  },
  {
    adlId: "ADL-US-GNIS-254421",
    gnisId: 254421,
    primaryName: "Santa Barbara",
    normalizedName: "santa barbara",
    fttCode: "pop.city",
    gnisFeatureClass: "Populated Place",
    stateAlpha: "CA",
    countyName: "Santa Barbara",
    latitude: 34.4208,
    longitude: -119.6982,
    elevationMeters: 15.0,
    elevationFeet: 49.0,
    usgsQuadName: "Santa Barbara",
    bbox: [-119.7500, 34.3800, -119.6500, 34.4600],
    variantNames: ["La Ciudad de Santa Bárbara", "Santa Barbara de la Costa", "Queen of the Missions"],
    metadata: { population: 88665, fips_place: "69070", established: 1782 }
  },
  {
    adlId: "ADL-US-GNIS-165987",
    gnisId: 165987,
    primaryName: "Isla Vista",
    normalizedName: "isla vista",
    fttCode: "pop.town",
    gnisFeatureClass: "Populated Place",
    stateAlpha: "CA",
    countyName: "Santa Barbara",
    latitude: 34.4133,
    longitude: -119.8608,
    elevationMeters: 10.0,
    elevationFeet: 33.0,
    usgsQuadName: "Goleta",
    bbox: [-119.8700, 34.4070, -119.8500, 34.4200],
    variantNames: ["I.V.", "Campus Town", "Isla Vista CDP"],
    metadata: { census_designated_place: true, student_community: true }
  },
  {
    adlId: "ADL-US-GNIS-253810",
    gnisId: 253810,
    primaryName: "Santa Barbara Channel",
    normalizedName: "santa barbara channel",
    fttCode: "hydro.marine",
    gnisFeatureClass: "Channel",
    stateAlpha: "CA",
    countyName: "Santa Barbara",
    latitude: 34.2500,
    longitude: -119.7800,
    elevationMeters: 0.0,
    elevationFeet: 0.0,
    usgsQuadName: "Santa Barbara",
    bbox: [-120.4000, 34.0000, -119.2000, 34.5000],
    variantNames: ["Canal de Santa Bárbara", "Santa Barbara Strait"],
    metadata: { sanctuary: "Channel Islands National Marine Sanctuary", area_sq_mi: 1470 }
  },
  {
    adlId: "ADL-US-GNIS-253245",
    gnisId: 253245,
    primaryName: "Santa Cruz Island",
    normalizedName: "santa cruz island",
    fttCode: "phys.island",
    gnisFeatureClass: "Island",
    stateAlpha: "CA",
    countyName: "Santa Barbara",
    latitude: 34.0200,
    longitude: -119.7200,
    elevationMeters: 740.0,
    elevationFeet: 2428.0,
    usgsQuadName: "Santa Cruz Island",
    bbox: [-119.9200, 33.9500, -119.5200, 34.0900],
    variantNames: ["Isla de Santa Cruz", "Devils Peak Island", "Limuw"],
    metadata: { highest_peak: "Devils Peak", island_group: "Northern Channel Islands" }
  },
  {
    adlId: "ADL-US-GNIS-253248",
    gnisId: 253248,
    primaryName: "Santa Rosa Island",
    normalizedName: "santa rosa island",
    fttCode: "phys.island",
    gnisFeatureClass: "Island",
    stateAlpha: "CA",
    countyName: "Santa Barbara",
    latitude: 33.9700,
    longitude: -120.1000,
    elevationMeters: 484.0,
    elevationFeet: 1589.0,
    usgsQuadName: "Santa Rosa Island",
    bbox: [-120.2400, 33.8800, -119.9600, 34.0400],
    variantNames: ["Isla de Santa Rosa", "Wi'ma"],
    metadata: { national_park: "Channel Islands National Park" }
  },
  {
    adlId: "ADL-US-GNIS-165842",
    gnisId: 165842,
    primaryName: "Goleta",
    normalizedName: "goleta",
    fttCode: "pop.city",
    gnisFeatureClass: "Populated Place",
    stateAlpha: "CA",
    countyName: "Santa Barbara",
    latitude: 34.4358,
    longitude: -119.8276,
    elevationMeters: 17.0,
    elevationFeet: 56.0,
    usgsQuadName: "Goleta",
    bbox: [-119.8800, 34.4100, -119.7800, 34.4700],
    variantNames: ["The Good Land", "La Goleta"],
    metadata: { technology_corridor: true }
  },
  {
    adlId: "ADL-US-GNIS-254425",
    gnisId: 254425,
    primaryName: "San Marcos Pass",
    normalizedName: "san marcos pass",
    fttCode: "phys.valley",
    gnisFeatureClass: "Gap",
    stateAlpha: "CA",
    countyName: "Santa Barbara",
    latitude: 34.4983,
    longitude: -119.8258,
    elevationMeters: 678.0,
    elevationFeet: 2225.0,
    usgsQuadName: "San Marcos Pass",
    variantNames: ["Highway 154 Summit", "Chumash Pass"],
    metadata: { santa_ynez_mountains: true }
  },
  {
    adlId: "ADL-US-GNIS-254430",
    gnisId: 254430,
    primaryName: "Lake Cachuma",
    normalizedName: "lake cachuma",
    fttCode: "hydro.lake",
    gnisFeatureClass: "Reservoir",
    stateAlpha: "CA",
    countyName: "Santa Barbara",
    latitude: 34.5847,
    longitude: -119.9806,
    elevationMeters: 230.0,
    elevationFeet: 755.0,
    usgsQuadName: "Lake Cachuma",
    bbox: [-120.0400, 34.5500, -119.9200, 34.6100],
    variantNames: ["Cachuma Reservoir", "Bradbury Dam Reservoir"],
    metadata: { capacity_acre_ft: 193305 }
  },

  // --- SIERRA NEVADA & CALIFORNIA LANDMARKS ---
  {
    adlId: "ADL-US-GNIS-253489",
    gnisId: 253489,
    primaryName: "Yosemite Valley",
    normalizedName: "yosemite valley",
    fttCode: "phys.valley",
    gnisFeatureClass: "Valley",
    stateAlpha: "CA",
    countyName: "Mariposa",
    latitude: 37.7456,
    longitude: -119.5936,
    elevationMeters: 1218.0,
    elevationFeet: 3996.0,
    usgsQuadName: "Yosemite Falls",
    bbox: [-119.6800, 37.7000, -119.5000, 37.7800],
    variantNames: ["Ahwahnee", "Yo-semite", "Incomparable Valley", "Valle de Yosemite"],
    metadata: { unesco_world_heritage: true, national_park: "Yosemite National Park" }
  },
  {
    adlId: "ADL-US-GNIS-261543",
    gnisId: 261543,
    primaryName: "Half Dome",
    normalizedName: "half dome",
    fttCode: "phys.peak",
    gnisFeatureClass: "Summit",
    stateAlpha: "CA",
    countyName: "Mariposa",
    latitude: 37.7460,
    longitude: -119.5332,
    elevationMeters: 2694.0,
    elevationFeet: 8839.0,
    usgsQuadName: "Half Dome",
    variantNames: ["Tis-sa-ack", "South Dome", "Rock of Tis-sa-ack"],
    metadata: { prominence_m: 414, granite_monolith: true }
  },
  {
    adlId: "ADL-US-GNIS-261490",
    gnisId: 261490,
    primaryName: "El Capitan",
    normalizedName: "el capitan",
    fttCode: "phys",
    gnisFeatureClass: "Cliff",
    stateAlpha: "CA",
    countyName: "Mariposa",
    latitude: 37.7340,
    longitude: -119.6377,
    elevationMeters: 2307.0,
    elevationFeet: 7569.0,
    usgsQuadName: "El Capitan",
    variantNames: ["To-to-kon-oo-lah", "The Captain", "El Cap"],
    metadata: { granite_wall_vertical_ft: 3000 }
  },
  {
    adlId: "ADL-US-GNIS-254067",
    gnisId: 254067,
    primaryName: "Mount Whitney",
    normalizedName: "mount whitney",
    fttCode: "phys.peak",
    gnisFeatureClass: "Summit",
    stateAlpha: "CA",
    countyName: "Inyo",
    latitude: 36.5785,
    longitude: -118.2923,
    elevationMeters: 4421.0,
    elevationFeet: 14505.0,
    usgsQuadName: "Mount Whitney",
    variantNames: ["Tumanguya", "Fishermans Peak", "Whitney Peak"],
    metadata: { highest_point_contiguous_us: true, sierra_crest: true }
  },
  {
    adlId: "ADL-US-GNIS-165495",
    gnisId: 165495,
    primaryName: "Lake Tahoe",
    normalizedName: "lake tahoe",
    fttCode: "hydro.lake",
    gnisFeatureClass: "Lake",
    stateAlpha: "CA",
    countyName: "Placer",
    latitude: 39.0968,
    longitude: -120.0324,
    elevationMeters: 1897.0,
    elevationFeet: 6224.0,
    usgsQuadName: "Homewood",
    bbox: [-120.1500, 38.9000, -119.9200, 39.2800],
    variantNames: ["Lake Bigler", "Da ow", "Tahoe"],
    metadata: { max_depth_ft: 1645, alpine_lake: true }
  },
  {
    adlId: "ADL-US-GNIS-253360",
    gnisId: 253360,
    primaryName: "Mount Shasta",
    normalizedName: "mount shasta",
    fttCode: "phys.peak",
    gnisFeatureClass: "Summit",
    stateAlpha: "CA",
    countyName: "Siskiyou",
    latitude: 41.4092,
    longitude: -122.1949,
    elevationMeters: 4322.0,
    elevationFeet: 14179.0,
    usgsQuadName: "Mount Shasta",
    variantNames: ["Mt Shasta Volcano", "Waka", "Sasti Mountain"],
    metadata: { stratovolcano: true, cascade_volcanic_arc: true }
  },
  {
    adlId: "ADL-US-GNIS-241280",
    gnisId: 241280,
    primaryName: "Death Valley",
    normalizedName: "death valley",
    fttCode: "phys.valley",
    gnisFeatureClass: "Valley",
    stateAlpha: "CA",
    countyName: "Inyo",
    latitude: 36.5323,
    longitude: -116.9325,
    elevationMeters: -86.0,
    elevationFeet: -282.0,
    usgsQuadName: "Badwater",
    bbox: [-117.4000, 35.8000, -116.6000, 37.2000],
    variantNames: ["Tumpisa", "Furnace Creek Valley"],
    metadata: { lowest_elevation_north_america: true, national_park: true }
  },
  {
    adlId: "ADL-US-GNIS-254500",
    gnisId: 254500,
    primaryName: "Salton Sea",
    normalizedName: "salton sea",
    fttCode: "hydro.lake",
    gnisFeatureClass: "Lake",
    stateAlpha: "CA",
    countyName: "Imperial",
    latitude: 33.3500,
    longitude: -115.8500,
    elevationMeters: -71.0,
    elevationFeet: -234.0,
    usgsQuadName: "Salton Sea East",
    bbox: [-116.1000, 33.1500, -115.6000, 33.6000],
    variantNames: ["Lake Cahuilla Modern", "Salton Sink"],
    metadata: { endorheic_rift_lake: true }
  },
  {
    adlId: "ADL-US-GNIS-277594",
    gnisId: 277594,
    primaryName: "San Francisco Bay",
    normalizedName: "san francisco bay",
    fttCode: "hydro.marine",
    gnisFeatureClass: "Bay",
    stateAlpha: "CA",
    countyName: "San Francisco",
    latitude: 37.7500,
    longitude: -122.3500,
    elevationMeters: 0.0,
    elevationFeet: 0.0,
    usgsQuadName: "San Francisco North",
    bbox: [-122.5500, 37.4000, -122.1500, 38.1000],
    variantNames: ["Bahía de San Francisco", "Golden Gate Estuary"],
    metadata: { estuary_square_miles: 1600 }
  },

  // --- AMERICAN WEST, ROCKIES & SOUTHWEST ---
  {
    adlId: "ADL-US-GNIS-213948",
    gnisId: 213948,
    primaryName: "Grand Canyon",
    normalizedName: "grand canyon",
    fttCode: "phys.valley",
    gnisFeatureClass: "Canyon",
    stateAlpha: "AZ",
    countyName: "Coconino",
    latitude: 36.0544,
    longitude: -112.1401,
    elevationMeters: 732.0,
    elevationFeet: 2402.0,
    usgsQuadName: "Grand Canyon",
    bbox: [-113.9000, 35.8000, -111.7000, 36.4500],
    variantNames: ["Big Canyon", "Grand Cañon of the Colorado", "Ongtupqa"],
    metadata: { river: "Colorado River", national_park: "Grand Canyon National Park", length_miles: 277 }
  },
  {
    adlId: "ADL-US-GNIS-213955",
    gnisId: 213955,
    primaryName: "Colorado River",
    normalizedName: "colorado river",
    fttCode: "hydro.stream",
    gnisFeatureClass: "Stream",
    stateAlpha: "AZ",
    countyName: "Coconino",
    latitude: 36.1000,
    longitude: -112.0000,
    elevationMeters: 700.0,
    elevationFeet: 2296.0,
    usgsQuadName: "Phantom Ranch",
    bbox: [-115.0000, 31.5000, -105.8000, 40.4000],
    variantNames: ["Rio Colorado", "Red River of the West", "Hawekeem"],
    metadata: { length_miles: 1450, states: ["CO", "UT", "AZ", "NV", "CA"] }
  },
  {
    adlId: "ADL-US-GNIS-847290",
    gnisId: 847290,
    primaryName: "Hoover Dam",
    normalizedName: "hoover dam",
    fttCode: "manmade",
    gnisFeatureClass: "Dam",
    stateAlpha: "NV",
    countyName: "Clark",
    latitude: 36.0156,
    longitude: -114.7378,
    elevationMeters: 376.0,
    elevationFeet: 1234.0,
    usgsQuadName: "Hoover Dam",
    variantNames: ["Boulder Dam", "Black Canyon Dam"],
    metadata: { concrete_arch_gravity_dam: true, impounds: "Lake Mead" }
  },
  {
    adlId: "ADL-US-GNIS-145550",
    gnisId: 145550,
    primaryName: "Zion Canyon",
    normalizedName: "zion canyon",
    fttCode: "phys.valley",
    gnisFeatureClass: "Canyon",
    stateAlpha: "UT",
    countyName: "Washington",
    latitude: 37.2000,
    longitude: -112.9800,
    elevationMeters: 1219.0,
    elevationFeet: 3999.0,
    usgsQuadName: "Springdale East",
    bbox: [-113.1000, 37.1500, -112.8500, 37.3500],
    variantNames: ["Little Zion Valley", "Mukuntuweap Canyon"],
    metadata: { navajo_sandstone_cliffs: true }
  },
  {
    adlId: "ADL-US-GNIS-159670",
    gnisId: 159670,
    primaryName: "Yellowstone Lake",
    normalizedName: "yellowstone lake",
    fttCode: "hydro.lake",
    gnisFeatureClass: "Lake",
    stateAlpha: "WY",
    countyName: "Teton",
    latitude: 44.4200,
    longitude: -110.3500,
    elevationMeters: 2357.0,
    elevationFeet: 7733.0,
    usgsQuadName: "Lake",
    bbox: [-110.5500, 44.2500, -110.1500, 44.5500],
    variantNames: ["Sublette Lake", "Eustis Lake"],
    metadata: { high_elevation_supervolcano_caldera: true }
  },
  {
    adlId: "ADL-US-GNIS-160230",
    gnisId: 160230,
    primaryName: "Old Faithful Geyser",
    normalizedName: "old faithful geyser",
    fttCode: "hydro.spring",
    gnisFeatureClass: "Spring",
    stateAlpha: "WY",
    countyName: "Teton",
    latitude: 44.4605,
    longitude: -110.8281,
    elevationMeters: 2243.0,
    elevationFeet: 7359.0,
    usgsQuadName: "Old Faithful",
    variantNames: ["Old Faithful", "The Erupting Cone"],
    metadata: { hydrothermal_geyser: true, national_park: "Yellowstone National Park" }
  },
  {
    adlId: "ADL-US-GNIS-153344",
    gnisId: 153344,
    primaryName: "Mount Rainier",
    normalizedName: "mount rainier",
    fttCode: "phys.peak",
    gnisFeatureClass: "Summit",
    stateAlpha: "WA",
    countyName: "Pierce",
    latitude: 46.8529,
    longitude: -121.7604,
    elevationMeters: 4392.0,
    elevationFeet: 14411.0,
    usgsQuadName: "Mount Rainier East",
    variantNames: ["Tahoma", "Tacoma", "Ti'Swaq'"],
    metadata: { cascade_stratovolcano: true, most_glaciated_peak: true }
  },
  {
    adlId: "ADL-US-GNIS-113980",
    gnisId: 113980,
    primaryName: "Crater Lake",
    normalizedName: "crater lake",
    fttCode: "hydro.lake",
    gnisFeatureClass: "Lake",
    stateAlpha: "OR",
    countyName: "Klamath",
    latitude: 42.9467,
    longitude: -122.1090,
    elevationMeters: 1883.0,
    elevationFeet: 6178.0,
    usgsQuadName: "Crater Lake East",
    bbox: [-122.1800, 42.8900, -122.0400, 43.0000],
    variantNames: ["Deep Blue Lake", "Lake Majesty", "Giiwas"],
    metadata: { deepest_lake_usa_depth_ft: 1949, caldera_lake: true }
  },
  {
    adlId: "ADL-US-GNIS-188770",
    gnisId: 188770,
    primaryName: "Pikes Peak",
    normalizedName: "pikes peak",
    fttCode: "phys.peak",
    gnisFeatureClass: "Summit",
    stateAlpha: "CO",
    countyName: "El Paso",
    latitude: 38.8405,
    longitude: -105.0442,
    elevationMeters: 4302.0,
    elevationFeet: 14115.0,
    usgsQuadName: "Pikes Peak",
    variantNames: ["Americas Mountain", "El Capitán de Colorado", "Tava"],
    metadata: { front_range_fourteener: true }
  },

  // --- MISSISSIPPI BASIN, GULF COAST & EASTERN SEABOARD ---
  {
    adlId: "ADL-US-GNIS-160933",
    gnisId: 160933,
    primaryName: "Mississippi River",
    normalizedName: "mississippi river",
    fttCode: "hydro.stream",
    gnisFeatureClass: "Stream",
    stateAlpha: "LA",
    countyName: "Plaquemines",
    latitude: 29.1500,
    longitude: -89.2500,
    elevationMeters: 0.0,
    elevationFeet: 0.0,
    usgsQuadName: "Pilottown",
    bbox: [-95.0000, 29.0000, -89.0000, 47.5000],
    variantNames: ["Misi-ziibi", "Father of Waters", "Old Man River", "Fleuve Saint-Louis"],
    metadata: { drainage_basin_km2: 3220000, length_km: 3766 }
  },
  {
    adlId: "ADL-US-GNIS-558230",
    gnisId: 558230,
    primaryName: "New Orleans",
    normalizedName: "new orleans",
    fttCode: "pop.city",
    gnisFeatureClass: "Populated Place",
    stateAlpha: "LA",
    countyName: "Orleans",
    latitude: 29.9511,
    longitude: -90.0715,
    elevationMeters: -1.0,
    elevationFeet: -3.0,
    usgsQuadName: "New Orleans East",
    bbox: [-90.2000, 29.8500, -89.9000, 30.1500],
    variantNames: ["La Nouvelle-Orléans", "Crescent City", "Big Easy"],
    metadata: { historic_delta_port: true, established: 1718 }
  },
  {
    adlId: "ADL-US-GNIS-558245",
    gnisId: 558245,
    primaryName: "Lake Pontchartrain",
    normalizedName: "lake pontchartrain",
    fttCode: "hydro.lake",
    gnisFeatureClass: "Lake",
    stateAlpha: "LA",
    countyName: "Orleans",
    latitude: 30.2000,
    longitude: -90.1000,
    elevationMeters: 0.0,
    elevationFeet: 0.0,
    usgsQuadName: "Spanish Fort",
    bbox: [-90.4500, 30.0500, -89.7500, 30.3500],
    variantNames: ["Lac Pontchartrain", "Okkwaata"],
    metadata: { brackish_estuary_sq_mi: 630 }
  },
  {
    adlId: "ADL-US-GNIS-284920",
    gnisId: 284920,
    primaryName: "Everglades National Park",
    normalizedName: "everglades national park",
    fttCode: "admin.park",
    gnisFeatureClass: "Park",
    stateAlpha: "FL",
    countyName: "Miami-Dade",
    latitude: 25.3500,
    longitude: -80.8500,
    elevationMeters: 1.0,
    elevationFeet: 3.0,
    usgsQuadName: "Flamingo",
    bbox: [-81.4000, 24.9500, -80.5000, 25.8500],
    variantNames: ["River of Grass", "Pa-hay-okee"],
    metadata: { unesco_world_heritage: true, subtropical_wetland_wilderness: true }
  },
  {
    adlId: "ADL-US-GNIS-970100",
    gnisId: 970100,
    primaryName: "Niagara Falls",
    normalizedName: "niagara falls",
    fttCode: "hydro",
    gnisFeatureClass: "Falls",
    stateAlpha: "NY",
    countyName: "Niagara",
    latitude: 43.0800,
    longitude: -79.0700,
    elevationMeters: 157.0,
    elevationFeet: 515.0,
    usgsQuadName: "Niagara Falls",
    variantNames: ["Horseshoe Falls", "American Falls", "Onguiaahra"],
    metadata: { flow_rate_cfs: 85000, border: "USA / Canada" }
  },
  {
    adlId: "ADL-US-GNIS-874200",
    gnisId: 874200,
    primaryName: "Mount Washington",
    normalizedName: "mount washington",
    fttCode: "phys.peak",
    gnisFeatureClass: "Summit",
    stateAlpha: "NH",
    countyName: "Coos",
    latitude: 44.2705,
    longitude: -71.3033,
    elevationMeters: 1917.0,
    elevationFeet: 6288.0,
    usgsQuadName: "Mount Washington",
    variantNames: ["Agiocochook", "Home of the Great Spirit"],
    metadata: { highest_peak_northeast_us: true, highest_wind_speed_record: "231 mph" }
  },
  {
    adlId: "ADL-US-GNIS-141200",
    gnisId: 141200,
    primaryName: "Denali",
    normalizedName: "denali",
    fttCode: "phys.peak",
    gnisFeatureClass: "Summit",
    stateAlpha: "AK",
    countyName: "Denali",
    latitude: 63.0692,
    longitude: -151.0070,
    elevationMeters: 6190.0,
    elevationFeet: 20310.0,
    usgsQuadName: "Mount McKinley A-3",
    variantNames: ["Mount McKinley", "Deenaalee", "Bolshaya Gora"],
    metadata: { highest_peak_north_america: true, bgn_official_decision: "2015" }
  },
  {
    adlId: "ADL-US-GNIS-360100",
    gnisId: 360100,
    primaryName: "Mauna Kea",
    normalizedName: "mauna kea",
    fttCode: "phys.peak",
    gnisFeatureClass: "Summit",
    stateAlpha: "HI",
    countyName: "Hawaii",
    latitude: 19.8206,
    longitude: -155.4681,
    elevationMeters: 4207.0,
    elevationFeet: 13803.0,
    usgsQuadName: "Mauna Kea",
    variantNames: ["Maunakea", "White Mountain"],
    metadata: { tall_base_to_peak_ft: 33500, astronomical_observatory: true }
  }
];

export const ADL_COLLECTION_TAXONOMY_TREE = [
  {
    id: "root-pacific",
    title: "Pacific & California Coastal Basin",
    fttFacet: "Physiographic & Hydrographic",
    featuresCount: 145000,
    bbox: [-124.5, 32.5, -114.0, 42.0],
    children: [
      { id: "col-sb-channel", title: "Santa Barbara Channel & Channel Islands (ADL Testbed Core)", gnisClass: "Marine & Island", count: 840 },
      { id: "col-sierra", title: "Sierra Nevada & Yosemite High-Altitude Transect", gnisClass: "Summit & Valley", count: 4210 },
      { id: "col-sf-bay", title: "San Francisco Bay Estuarine System", gnisClass: "Bay & Channel", count: 1890 }
    ]
  },
  {
    id: "root-colorado",
    title: "Colorado River Basin & Desert Southwest",
    fttFacet: "Physiographic & Hydrographic",
    featuresCount: 98000,
    bbox: [-115.0, 31.0, -105.5, 40.5],
    children: [
      { id: "col-grand-canyon", title: "Grand Canyon & Colorado Plateau Geomorphic Province", gnisClass: "Canyon & Stream", count: 3120 },
      { id: "col-great-basin", title: "Great Basin & Mojave Endorheic Depressions", gnisClass: "Valley & Basin", count: 2450 }
    ]
  },
  {
    id: "root-mississippi",
    title: "Mississippi River Drainage & Gulf Coast",
    fttFacet: "Hydrographic & Administrative",
    featuresCount: 220000,
    bbox: [-95.5, 28.5, -88.0, 48.0],
    children: [
      { id: "col-delta-wetlands", title: "Mississippi Deltaic Estuary & Coastal Sanctuaries", gnisClass: "Stream & Swamp", count: 5600 },
      { id: "col-basin-tributaries", title: "Upper Mississippi & Ohio River Confluence", gnisClass: "River & Canal", count: 12800 }
    ]
  },
  {
    id: "root-appalachian",
    title: "Appalachian Mountain System & Atlantic Seaboard",
    fttFacet: "Physiographic & Populated",
    featuresCount: 180000,
    bbox: [-84.0, 34.0, -69.0, 47.0],
    children: [
      { id: "col-white-mountains", title: "White Mountains & Northern Highlands", gnisClass: "Summit & Range", count: 1980 },
      { id: "col-chesapeake", title: "Chesapeake Bay Watershed", gnisClass: "Bay & Estuary", count: 6400 }
    ]
  }
];
