import * as THREE from "../vendor/three.module.min.js";import{OrbitControls}from"../vendor/OrbitControls.js";import{BODIES,METEOR_STREAMS,orbitalPosition,orbitPath,daysSinceJ2000,bodyById}from"./astronomy.js";
const $=id=>document.getElementById(id);const st={view:"orrery",days:daysSinceJ2000(),speed:10,paused:false,focus:"earth",objects:new Map(),labels:new Map(),stream:"perseids"};let scene,camera,renderer,controls,root,orbitGroup,meteorGroup,stars,last=performance.now();
const scalePos=(p,m=1)=>{const s=Math.log1p(p.r)*3*m/(p.r||1);return new THREE.Vector3(p.x*s,p.y*s,p.z*s)};
function init(){renderer=new THREE.WebGLRenderer({canvas:$("sky"),antialias:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.setClearColor(0x01030a);scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x01030a,.018);camera=new THREE.PerspectiveCamera(52,1,.03,200);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=1;controls.maxDistance=80;scene.add(new THREE.AmbientLight(0x7799bb,.4));const l=new THREE.PointLight(0xffd88a,3,80);scene.add(l);addStars();resize();addEventListener("resize",resize);build();requestAnimationFrame(loop)}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight,false)}
function addStars(){const a=[];let s=987654321;for(let i=0;i<2200;i++){s=(Math.imul(s,1664525)+1013904223)>>>0;const u=s/2**32;s=(Math.imul(s,1664525)+1013904223)>>>0;const v=s/2**32;const z=u*2-1,t=v*Math.PI*2,r=45+(i%37);const q=Math.sqrt(1-z*z);a.push(Math.cos(t)*q*r,z*r,Math.sin(t)*q*r)}const g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.Float32BufferAttribute(a,3));stars=new THREE.Points(g,new THREE.PointsMaterial({color:0x6d91ad,size:.07,transparent:true,opacity:.6}));scene.add(stars)}
function dispose(g){if(!g)return;scene.remove(g);g.traverse(o=>{o.geometry?.dispose?.();o.material?.dispose?.()})}
function orbitLine(body,color,opacity=.22){const a=[];for(const p of orbitPath(body,220)){const v=scalePos(p);a.push(v.x,v.y,v.z)}const g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.Float32BufferAttribute(a,3));return new THREE.Line(g,new THREE.LineBasicMaterial({color,transparent:true,opacity}))}
function build(){dispose(root);root=new THREE.Group();orbitGroup=new THREE.Group();meteorGroup=new THREE.Group();root.add(orbitGroup,meteorGroup);st.objects.clear();$("labelsLayer").replaceChildren();st.labels.clear();const sun=new THREE.Mesh(new THREE.SphereGeometry(.34,24,16),new THREE.MeshBasicMaterial({color:0xfbbf24}));root.add(sun);for(const b of BODIES){if(b.kind==="moon"&&!$("moons").checked)continue;const geo=b.kind==="moon"?new THREE.SphereGeometry(.045+b.size*.025,10,8):new THREE.SphereGeometry(.045+Math.sqrt(b.size)*.07,12,9);const mat=new THREE.MeshBasicMaterial({color:b.color});const m=new THREE.Mesh(geo,mat);m.userData.id=b.id;root.add(m);st.objects.set(b.id,m);if(b.kind!=="moon"&&$("orbits").checked)orbitGroup.add(orbitLine(b,b.color,b.kind==="planet"?.28:.12));const label=document.createElement("span");label.className="body-label";label.textContent=b.name;$("labelsLayer").append(label);st.labels.set(b.id,label)}if(st.view==="meteors")buildMeteors();scene.add(root);updatePositions();resetCamera();renderMetrics()}
function buildMeteors(){if(!$("trails").checked)return;for(const stream of METEOR_STREAMS){const pos=[],col=new THREE.Color(stream.color);for(let i=0;i<180;i++){const M=i/180*Math.PI*2;const p=orbitalPosition({...stream,period:Math.sqrt(stream.a**3)*365.256,M0:0},0,M);const v=scalePos(p);pos.push(v.x,v.y,v.z)}const g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.Float32BufferAttribute(pos,3));meteorGroup.add(new THREE.Points(g,new THREE.PointsMaterial({color:col,size:.045,transparent:true,opacity:stream.id===st.stream?.85:.22})));meteorGroup.add(orbitLine({...stream,period:1,M0:0},stream.color,stream.id===st.stream?.35:.08))}}
function updatePositions(){const raw=new Map();for(const b of BODIES){if(b.kind!=="moon")raw.set(b.id,orbitalPosition(b,st.days))}const earth=raw.get("earth");for(const b of BODIES){const mesh=st.objects.get(b.id);if(!mesh)continue;let p;if(b.kind==="moon"){const parent=raw.get(b.parent),local=orbitalPosition(b,st.days);p={x:parent.x+local.x*14,y:parent.y+local.y*14,z:parent.z+local.z*14,r:Math.hypot(parent.x+local.x*14,parent.y+local.y*14,parent.z+local.z*14)}}else p=raw.get(b.id);let v=scalePos(p);if(st.view==="radar"){const dx=p.x-earth.x,dy=p.y-earth.y,dz=p.z-earth.z,d=Math.hypot(dx,dy,dz);const k=5/(.15+d);v=new THREE.Vector3(dx*k,dy*k,dz*k);mesh.visible=b.kind==="neo"||b.id==="earth"||b.kind==="comet"}else mesh.visible=true;mesh.position.copy(v)}updateSelected(raw);updateLabels();$("clock").textContent=`J2000 + ${st.days.toFixed(1)} days`}
function updateSelected(raw){const b=bodyById(st.focus)||bodyById("earth"),p=raw.get(b.kind==="moon"?b.parent:b.id);if(!p)return;$("bodyKind").textContent=b.kind.toUpperCase();$("bodyName").textContent=b.name;$("distance").textContent=`${p.r.toFixed(4)} AU from Sun`;$("axis").textContent=`${b.a} AU`;$("ecc").textContent=b.e.toFixed(4);$("period").textContent=b.period<1000?`${b.period.toFixed(2)} days`:`${(b.period/365.256).toFixed(1)} years`;$("inclination").textContent=`${b.i.toFixed(2)}°`;$("hudFocus").textContent=`${b.name.toUpperCase()} · ${p.r.toFixed(3)} AU`;for(const[id,l]of st.labels)l.classList.toggle("focus",id===b.id);const near=[...raw.entries()].filter(([id,p])=>bodyById(id)?.kind==="neo"&&Math.hypot(p.x-raw.get("earth").x,p.y-raw.get("earth").y,p.z-raw.get("earth").z)<.25);$("approach").textContent=near.length?`${near.length} model body`:`none < 0.25 AU`}
function updateLabels(){const show=$("labels").checked;for(const[id,label]of st.labels){const o=st.objects.get(id);if(!show||!o?.visible){label.style.display="none";continue}const v=o.position.clone().project(camera);if(v.z>1){label.style.display="none";continue}label.style.display="block";label.style.left=`${(v.x*.5+.5)*innerWidth+6}px`;label.style.top=`${(-v.y*.5+.5)*innerHeight-4}px`}}
function loop(t){const dt=Math.min(.1,(t-last)/1000);last=t;if(!st.paused&&st.speed){st.days+=dt*st.speed;updatePositions()}controls.update();stars.rotation.y+=.00002;renderer.render(scene,camera);updateLabels();requestAnimationFrame(loop)}
function resetCamera(){const p=st.view==="radar"?[8,7,9]:st.view==="meteors"?[12,9,14]:[11,8,13];camera.position.set(...p);controls.target.set(0,0,0);controls.update()}
function focus(){st.focus=$("body").value;updatePositions();const o=st.objects.get(st.focus);if(o?.visible){controls.target.copy(o.position);camera.position.copy(o.position).add(new THREE.Vector3(1.5,1.2,2));controls.update()}}
function renderMetrics(){$("bodyCount").textContent=BODIES.length;$("neoCount").textContent=BODIES.filter(b=>b.kind==="neo").length;$("streamCount").textContent=METEOR_STREAMS.length;renderStream()}
function renderStream(){st.stream=$("stream").value||st.stream;const s=METEOR_STREAMS.find(x=>x.id===st.stream)||METEOR_STREAMS[0];$("streamInfo").textContent=`${s.name} · parent ${s.parent} · nominal peak ${s.peak}`;const cv=$("meteorChart"),c=cv.getContext("2d");c.fillStyle="#01040a";c.fillRect(0,0,cv.width,cv.height);c.strokeStyle=`#${s.color.toString(16).padStart(6,"0")}`;c.beginPath();for(let i=0;i<=180;i++){const p=orbitalPosition({...s,period:1,M0:0},0,i/180*Math.PI*2),x=10+(p.x/s.a*.45+.5)*(cv.width-20),y=10+(p.z/s.a*.45+.5)*(cv.height-20);i?c.lineTo(x,y):c.moveTo(x,y)}c.stroke()}
function setView(v){st.view=v;document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("on",b.dataset.view===v));const x={orrery:["Solar Orrery","Every catalog body advances on an approximate heliocentric Kepler orbit."],radar:["Near-Earth Radar","Earth-centered transformed distance highlights modeled NEO and comet geometry."],meteors:["Meteor Stream Atlas","Sun-orbiting debris streams follow the approximate orbit of their named parent body."]}[v];$("viewTitle").textContent=x[0];$("viewNote").textContent=x[1];build()}
function bind(){const d=new Date(Date.now()-new Date().getTimezoneOffset()*60000);$("date").value=d.toISOString().slice(0,10);for(const b of BODIES){const o=document.createElement("option");o.value=b.id;o.textContent=`${b.name} · ${b.kind}`;$("body").append(o)}$("body").value=st.focus;for(const s of METEOR_STREAMS){const o=document.createElement("option");o.value=s.id;o.textContent=s.name;$("stream").append(o)}$("stream").value=st.stream;$("views").onclick=e=>{const b=e.target.closest("[data-view]");if(b)setView(b.dataset.view)};$("date").onchange=()=>{st.days=daysSinceJ2000(new Date($("date").value+"T12:00:00Z"));updatePositions()};$("now").onclick=()=>{st.days=daysSinceJ2000();const n=new Date(Date.now()-new Date().getTimezoneOffset()*60000);$("date").value=n.toISOString().slice(0,10);updatePositions()};$("pause").onclick=()=>{st.paused=!st.paused;$("pause").textContent=st.paused?"Resume":"Pause"};$("speed").onchange=()=>st.speed=Number($("speed").value);$("focus").onclick=focus;$("body").onchange=focus;$("stream").onchange=()=>{st.stream=$("stream").value;renderStream();if(st.view==="meteors")build()};for(const id of["orbits","labels","moons","trails"])$(id).onchange=()=>build();$("resetCamera").onclick=resetCamera;$("panelToggle").onclick=()=>{const p=$("panel"),o=p.classList.toggle("open");$("panelToggle").setAttribute("aria-expanded",o)};$("share").onclick=()=>window.webxdc?.sendUpdate?.({payload:{type:"helios",view:st.view,days:st.days,focus:st.focus,stream:st.stream},info:`Shared ${st.focus} in Helios Observatory`,summary:`☉ ${st.view} · ${st.focus}`},"helios view")}
async function main(){bind();init();if(window.webxdc?.setUpdateListener)await window.webxdc.setUpdateListener(u=>{const p=u.payload;if(p?.type!=="helios"||!["orrery","radar","meteors"].includes(p.view))return;st.days=Number(p.days)||st.days;st.focus=bodyById(p.focus)?p.focus:"earth";st.stream=METEOR_STREAMS.some(s=>s.id===p.stream)?p.stream:"perseids";$("body").value=st.focus;$("stream").value=st.stream;setView(p.view)},0)}main().catch(e=>{$("viewNote").textContent=`Observatory error: ${e.message||e}`;console.error(e)});