/* GENERATED by calc/tools/c2js.py from calc/core/*.c — do not edit.
   Same source that sdcc builds for the TI-83/85/90 and gcc4ti builds for the
   TI-89/92. Keep calc/core/*.c as the single source of truth. */

/* --- sitek.h --- */
const FB_MAX = 3840;
const DEV_TI83 = 0;
const DEV_TI85 = 1;
const DEV_TI89 = 2;
const DEV_TI90 = 3;
const DEV_TI92 = 4;
const DEV_HOST = 5;
const SCR_BOOT = 0;
const SCR_GRID = 1;
const SCR_KEYS = 2;
const SCR_TERR = 3;
const SCR_INFO = 4;
const SKK_NONE = 0;
const SKK_LEFT = 1;
const SKK_RIGHT = 2;
const SKK_UP = 3;
const SKK_DOWN = 4;
const SKK_ENTER = 5;
const SKK_EXIT = 6;
const SKK_ACT = 7;
const SKK_1 = 8;
const SKK_2 = 9;
const SKK_3 = 10;
const SKK_4 = 11;
const SKK_5 = 12;
const PX_CLEAR = 0;
const PX_SET = 1;
const PX_FLIP = 2;
const FILL_CLEAR = 0;
const FILL_SOLID = 1;
const FILL_HALF = 2;
const FILL_QUARTER = 3;
const KS_MAX_WORDS = 24;
const TR_MAXW = 48;
const TR_MAXH = 24;
/* --- tables.c --- */
const FONT3x5 = new Uint8Array([7, 5, 5, 5, 7, 2, 6, 2, 2, 7, 7, 1, 7, 4, 7, 7, 1, 7, 1, 7, 5, 5, 7, 1, 1, 7, 4, 7, 1, 7, 7, 4, 7, 5, 7, 7, 1, 1, 1, 1, 7, 5, 7, 5, 7, 7, 5, 7, 1, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 7, 0, 0, 0, 2, 0, 2, 0, 0, 2, 7, 2, 0, 1, 1, 2, 4, 4, 5, 2, 5, 0, 0, 5, 7, 5, 7, 5, 7, 5, 7, 5, 5, 6, 5, 6, 5, 6, 7, 4, 4, 4, 7, 6, 5, 5, 5, 6, 7, 4, 7, 4, 7, 7, 4, 7, 4, 4, 7, 4, 5, 5, 7, 5, 5, 7, 5, 5, 7, 2, 2, 2, 7, 1, 1, 1, 5, 7, 5, 5, 6, 5, 5, 4, 4, 4, 4, 7, 5, 7, 7, 5, 5, 6, 5, 5, 5, 5, 7, 5, 5, 5, 7, 7, 5, 7, 4, 4, 7, 5, 5, 7, 1, 7, 5, 7, 6, 5, 7, 4, 7, 1, 7, 7, 2, 2, 2, 2, 5, 5, 5, 5, 7, 5, 5, 5, 5, 2, 5, 5, 7, 7, 5, 5, 5, 2, 5, 5, 5, 5, 2, 2, 2, 7, 1, 2, 4, 7]);
const SIN_Q12 = new Int16Array([0, 401, 799, 1189, 1567, 1931, 2276, 2598, 2896, 3166, 3406, 3612, 3784, 3920, 4017, 4076, 4096, 4076, 4017, 3920, 3784, 3612, 3406, 3166, 2896, 2598, 2276, 1931, 1567, 1189, 799, 401, 0, -401, -799, -1189, -1567, -1931, -2276, -2598, -2896, -3166, -3406, -3612, -3784, -3920, -4017, -4076, -4096, -4076, -4017, -3920, -3784, -3612, -3406, -3166, -2896, -2598, -2276, -1931, -1567, -1189, -799, -401]);
const LOG2_MANT = new Uint8Array([0, 1, 3, 4, 6, 7, 9, 10, 11, 13, 14, 16, 17, 18, 20, 21, 22, 24, 25, 26, 28, 29, 30, 32, 33, 34, 36, 37, 38, 40, 41, 42, 44, 45, 46, 47, 49, 50, 51, 52, 54, 55, 56, 57, 59, 60, 61, 62, 63, 65, 66, 67, 68, 69, 71, 72, 73, 74, 75, 77, 78, 79, 80, 81, 82, 84, 85, 86, 87, 88, 89, 90, 92, 93, 94, 95, 96, 97, 98, 99, 100, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 178, 179, 180, 181, 182, 183, 184, 185, 185, 186, 187, 188, 189, 190, 191, 192, 192, 193, 194, 195, 196, 197, 198, 198, 199, 200, 201, 202, 203, 203, 204, 205, 206, 207, 208, 208, 209, 210, 211, 212, 212, 213, 214, 215, 216, 216, 217, 218, 219, 220, 220, 221, 222, 223, 224, 224, 225, 226, 227, 228, 228, 229, 230, 231, 231, 232, 233, 234, 234, 235, 236, 237, 238, 238, 239, 240, 241, 241, 242, 243, 244, 244, 245, 246, 247, 247, 248, 249, 249, 250, 251, 252, 252, 253, 254, 255, 255]);
/* --- util.c --- */
function idiv(a, b) {
return Math.trunc(a / b) | 0;
}
function imod(a, b) {
return (a % b) | 0;
}
function iabs(a) {
if (a < 0) return -a;
return a;
}
function imin(a, b) {
if (a < b) return a;
return b;
}
function imax(a, b) {
if (a > b) return a;
return b;
}
function iclamp(v, lo, hi) {
if (v < lo) return lo;
if (v > hi) return hi;
return v;
}
function u32w(v) {
return v >>> 0;
}
function shr32(v, n) {
return (v >>> n) >>> 0;
}
function mul32(a, b) {
return Math.imul(a, b) >>> 0;
}
function add32(a, b) {
return (a + b) >>> 0;
}
function ror32(v, n) {
return (((v >>> n) | (v << (32 - n))) >>> 0);
}
let rng_state = 0;
function rng_seed(s) {
if (s == 0) s = 0x9E3779B9;
rng_state = u32w(s);
}
function rng_next() {
let x = 0;
x = rng_state;
x = u32w(x ^ (x << 13));
x = u32w(x ^ shr32(x, 17));
x = u32w(x ^ (x << 5));
rng_state = x;
return x;
}
function rng_range(n) {
if (n == 0) return 0;
return (rng_next() % n);
}
function sin_index(deg) {
let i = 0;
i = imod(deg, 360);
if (i < 0) i = i + 360;
i = idiv(i * 64, 360);
if (i >= 64) i = i - 64;
return i;
}
function fsin(deg) {
return SIN_Q12[sin_index(deg)];
}
function fcos(deg) {
return SIN_Q12[sin_index(deg + 90)];
}
function isqrt(v) {
let i = 0;
if (v <= 0) return 0;
i = 1;
while (i * i <= v) i = i + 1;
return i - 1;
}
function log2_q8(v) {
let b = 0;
let t = 0;
if (v == 0) return 0;
b = 0;
t = v;
while (t >= 256) {
t = shr32(t, 1);
b = b + 1;
}
while (t < 128) {
t = t << 1;
b = b - 1;
}
return (b + 7) * 256 + LOG2_MANT[(t - 128) * 2];
}
/* --- fb.c --- */
let SK_FB = new Uint8Array(FB_MAX);
function fb_clear() {
let i = 0;
for (i = 0; i < SK_FBB; i = i + 1) SK_FB[i] = 0;
}
function fb_px(x, y, mode) {
let o = 0;
let m = 0;
if (x >= SK_W) return;
if (y >= SK_H) return;
o = (y * SK_ROWB + (x >> 3));
m = (128 >> (x & 7));
if (mode == PX_SET) SK_FB[o] = (SK_FB[o] | m);
else if (mode == PX_CLEAR) SK_FB[o] = (SK_FB[o] & (~m));
else SK_FB[o] = (SK_FB[o] ^ m);
}
function fb_get(x, y) {
let o = 0;
let m = 0;
if (x >= SK_W) return 0;
if (y >= SK_H) return 0;
o = (y * SK_ROWB + (x >> 3));
m = (128 >> (x & 7));
if ((SK_FB[o] & m) != 0) return 1;
return 0;
}
function fb_hline(x0, x1, y, mode) {
let x = 0;
if (x1 < x0) return;
for (x = x0; x <= x1; x = x + 1) fb_px(x, y, mode);
}
function fb_vline(x, y0, y1, mode) {
let y = 0;
if (y1 < y0) return;
for (y = y0; y <= y1; y = y + 1) fb_px(x, y, mode);
}
function fb_line(x0, y0, x1, y1, mode) {
let x = 0;
let y = 0;
let dx = 0;
let dy = 0;
let sx = 0;
let sy = 0;
let err = 0;
let e2 = 0;
x = x0;
y = y0;
dx = iabs(x1 - x0);
dy = iabs(y1 - y0);
if (x0 < x1) sx = 1;
else sx = -1;
if (y0 < y1) sy = 1;
else sy = -1;
err = dx - dy;
while (true) {
fb_px(x, y, mode);
if (x == x1 && y == y1) break;
e2 = err * 2;
if (e2 > -dy) {
err = err - dy;
x = x + sx;
}
if (e2 < dx) {
err = err + dx;
y = y + sy;
}
}
}
function fb_rect(x, y, w, h, mode) {
if (w < 1) return;
if (h < 1) return;
fb_hline(x, (x + w - 1), y, mode);
fb_hline(x, (x + w - 1), (y + h - 1), mode);
fb_vline(x, y, (y + h - 1), mode);
fb_vline((x + w - 1), y, (y + h - 1), mode);
}
function fb_box(x, y, w, h, fill) {
let i = 0;
let j = 0;
let on = 0;
for (j = 0; j < h; j = j + 1) {
for (i = 0; i < w; i = i + 1) {
on = 0;
if (fill == FILL_SOLID) on = 1;
else if (fill == FILL_HALF) {
if (((x + i + y + j) & 1) == 0) on = 1;
} else if (fill == FILL_QUARTER) {
if (((x + i + y + j) & 3) == 0) on = 1;
}
if (on != 0) fb_px((x + i), (y + j), PX_SET);
else if (fill != FILL_CLEAR) fb_px((x + i), (y + j), PX_CLEAR);
}
}
}
function font_index(c) {
if (c >= 48 && c <= 57) return (c - 48);
if (c >= 65 && c <= 90) return (18 + (c - 65));
if (c == 32) return 10;
if (c == 46) return 11;
if (c == 45) return 12;
if (c == 58) return 13;
if (c == 47) return 14;
if (c == 43) return 15;
if (c == 42) return 16;
if (c == 35) return 17;
return 10;
}
function fb_textm(x, y, s, mode) {
let i = 0;
let cx = 0;
let gi = 0;
let r = 0;
let b = 0;
let bits = 0;
i = 0;
cx = x;
while (s[i] != 0) {
gi = font_index(s[i]);
for (r = 0; r < 5; r = r + 1) {
bits = FONT3x5[gi * 5 + r];
for (b = 0; b < 3; b = b + 1) {
if ((bits & (4 >> b)) != 0) fb_px((cx + b), (y + r), mode);
else if (mode == PX_CLEAR) fb_px((cx + b), (y + r), PX_CLEAR);
}
}
cx = (cx + 4);
i = i + 1;
}
}
function fb_text(x, y, s) {
fb_textm(x, y, s, PX_SET);
}
function fb_text2(x, y, s) {
let i = 0;
let cx = 0;
let gi = 0;
let r = 0;
let b = 0;
let bits = 0;
i = 0;
cx = x;
while (s[i] != 0) {
gi = font_index(s[i]);
for (r = 0; r < 5; r = r + 1) {
bits = FONT3x5[gi * 5 + r];
for (b = 0; b < 3; b = b + 1) {
if ((bits & (4 >> b)) != 0) {
fb_px((cx + b * 2), (y + r * 2), PX_SET);
fb_px((cx + b * 2 + 1), (y + r * 2), PX_SET);
fb_px((cx + b * 2), (y + r * 2 + 1), PX_SET);
fb_px((cx + b * 2 + 1), (y + r * 2 + 1), PX_SET);
} else {
fb_px((cx + b * 2), (y + r * 2), PX_CLEAR);
fb_px((cx + b * 2 + 1), (y + r * 2), PX_CLEAR);
fb_px((cx + b * 2), (y + r * 2 + 1), PX_CLEAR);
fb_px((cx + b * 2 + 1), (y + r * 2 + 1), PX_CLEAR);
}
}
}
cx = (cx + 8);
i = i + 1;
}
}
function fb_text_w(s) {
let n = 0;
n = 0;
while (s[n] != 0) n = n + 1;
if (n == 0) return 0;
return (n * 4 - 1);
}
function str_copy(dst, src) {
let n = 0;
n = 0;
while (src[n] != 0) {
dst[n] = src[n];
n = n + 1;
}
dst[n] = 0;
return n;
}
function str_copy_at(dst, at, src) {
let n = 0;
n = 0;
while (src[n] != 0) {
dst[at + n] = src[n];
n = n + 1;
}
dst[at + n] = 0;
return n;
}
function num_to(dst, at, v) {
let div = 0;
let d = 0;
let n = 0;
let started = 0;
let rest = 0;
div = 10000;
n = 0;
started = 0;
rest = v;
while (div > 0) {
d = idiv(rest, div);
if (d > 0 || started != 0 || div == 1) {
dst[at + n] = (48 + d);
n = n + 1;
started = 1;
}
rest = (rest - d * div);
div = idiv(div, 10);
}
return n;
}
/* --- keys.c --- */
const SHA_K = new Uint32Array([0x428A2F98, 0x71374491, 0xB5C0FBCF, 0xE9B5DBA5, 0x3956C25B, 0x59F111F1, 0x923F82A4, 0xAB1C5ED5, 0xD807AA98, 0x12835B01, 0x243185BE, 0x550C7DC3, 0x72BE5D74, 0x80DEB1FE, 0x9BDC06A7, 0xC19BF174, 0xE49B69C1, 0xEFBE4786, 0x0FC19DC6, 0x240CA1CC, 0x2DE92C6F, 0x4A7484AA, 0x5CB0A9DC, 0x76F988DA, 0x983E5152, 0xA831C66D, 0xB00327C8, 0xBF597FC7, 0xC6E00BF3, 0xD5A79147, 0x06CA6351, 0x14292967, 0x27B70A85, 0x2E1B2138, 0x4D2C6DFC, 0x53380D13, 0x650A7354, 0x766A0ABB, 0x81C2C92E, 0x92722C85, 0xA2BFE8A1, 0xA81A664B, 0xC24B8B70, 0xC76C51A3, 0xD192E819, 0xD6990624, 0xF40E3585, 0x106AA070, 0x19A4C116, 0x1E376C08, 0x2748774C, 0x34B0BCB5, 0x391C0CB3, 0x4ED8AA4A, 0x5B9CCA4F, 0x682E6FF3, 0x748F82EE, 0x78A5636F, 0x84C87814, 0x8CC70208, 0x90BEFFFA, 0xA4506CEB, 0xBEF9A3F7, 0xC67178F2]);
const KS_ENTBITS = new Uint16Array([128, 160, 192, 224, 256]);
let sha_h = new Uint32Array(8);
let sha_blk = new Uint8Array(64);
let sha_w = new Uint32Array(64);
let ks_ent = new Uint8Array(32);
let ks_dig = new Uint8Array(32);
let ks_idx = new Uint16Array(KS_MAX_WORDS);
let ks_hist = new Uint16Array(256);
let ks_words_n = 0;
let ks_entn = 0;
function sha_compress() {
let a = 0;
let b = 0;
let c = 0;
let d = 0;
let e = 0;
let f = 0;
let g = 0;
let h = 0;
let s0 = 0;
let s1 = 0;
let t1 = 0;
let t2 = 0;
let ch = 0;
let maj = 0;
let i = 0;
for (i = 0; i < 16; i = i + 1) {
sha_w[i] = u32w((sha_blk[i * 4] << 24) | (sha_blk[i * 4 + 1] << 16) |
(sha_blk[i * 4 + 2] << 8) | sha_blk[i * 4 + 3]);
}
for (i = 16; i < 64; i = i + 1) {
s0 = u32w(ror32(sha_w[i - 15], 7) ^ ror32(sha_w[i - 15], 18) ^ shr32(sha_w[i - 15], 3));
s1 = u32w(ror32(sha_w[i - 2], 17) ^ ror32(sha_w[i - 2], 19) ^ shr32(sha_w[i - 2], 10));
sha_w[i] = add32(add32(add32(sha_w[i - 16], s0), sha_w[i - 7]), s1);
}
a = sha_h[0];
b = sha_h[1];
c = sha_h[2];
d = sha_h[3];
e = sha_h[4];
f = sha_h[5];
g = sha_h[6];
h = sha_h[7];
for (i = 0; i < 64; i = i + 1) {
s1 = u32w(ror32(e, 6) ^ ror32(e, 11) ^ ror32(e, 25));
ch = u32w((e & f) ^ ((~e) & g));
t1 = add32(add32(add32(add32(h, s1), ch), SHA_K[i]), sha_w[i]);
s0 = u32w(ror32(a, 2) ^ ror32(a, 13) ^ ror32(a, 22));
maj = u32w((a & b) ^ (a & c) ^ (b & c));
t2 = add32(s0, maj);
h = g;
g = f;
f = e;
e = add32(d, t1);
d = c;
c = b;
b = a;
a = add32(t1, t2);
}
sha_h[0] = add32(sha_h[0], a);
sha_h[1] = add32(sha_h[1], b);
sha_h[2] = add32(sha_h[2], c);
sha_h[3] = add32(sha_h[3], d);
sha_h[4] = add32(sha_h[4], e);
sha_h[5] = add32(sha_h[5], f);
sha_h[6] = add32(sha_h[6], g);
sha_h[7] = add32(sha_h[7], h);
}
function sha256_hash(msg, len, out) {
let i = 0;
let bits = 0;
for (i = 0; i < 64; i = i + 1) sha_blk[i] = 0;
for (i = 0; i < len; i = i + 1) sha_blk[i] = msg[i];
sha_blk[len] = 0x80;
bits = (len * 8);
sha_blk[62] = (bits >> 8);
sha_blk[63] = (bits & 0xFF);
sha_h[0] = 0x6A09E667;
sha_h[1] = 0xBB67AE85;
sha_h[2] = 0x3C6EF372;
sha_h[3] = 0xA54FF53A;
sha_h[4] = 0x510E527F;
sha_h[5] = 0x9B05688C;
sha_h[6] = 0x1F83D9AB;
sha_h[7] = 0x5BE0CD19;
sha_compress();
for (i = 0; i < 32; i = i + 1) {
out[i] = (shr32(sha_h[i >> 2], 24 - (i & 3) * 8) & 0xFF);
}
}
function ks_seed(s) {
rng_seed(s);
}
function ks_ent_bits() {
let k = 0;
k = idiv(ks_words_n - 12, 3);
if (k < 0) k = 0;
if (k > 4) k = 4;
return KS_ENTBITS[k];
}
function ks_cs_bits() {
return idiv(ks_ent_bits(), 32);
}
function ks_words() {
return ks_words_n;
}
function ks_stream_bit(i) {
let ebits = 0;
let byte = 0;
let bit = 0;
ebits = ks_ent_bits();
if (i < ebits) byte = ks_ent[i >> 3];
else byte = ks_dig[(i - ebits) >> 3];
bit = (7 - (i & 7));
return ((byte >> bit) & 1);
}
function ks_gen(words) {
let i = 0;
let b = 0;
let n = 0;
let ebits = 0;
let v = 0;
if (words < 12) words = 12;
if (words > 24) words = 24;
ks_words_n = words;
ebits = ks_ent_bits();
ks_entn = idiv(ebits, 8);
for (i = 0; i < ks_entn; i = i + 1) ks_ent[i] = (rng_next() & 0xFF);
sha256_hash(ks_ent, ks_entn, ks_dig);
n = 0;
for (i = 0; i < ks_words_n; i = i + 1) {
v = 0;
for (b = 0; b < 11; b = b + 1) {
v = ((v << 1) | ks_stream_bit(n));
n = n + 1;
}
ks_idx[i] = (v & 0x7FF);
}
}
function ks_set_entropy(ent, nbytes) {
let i = 0;
let b = 0;
let n = 0;
let v = 0;
if (nbytes < 16) nbytes = 16;
if (nbytes > 32) nbytes = 32;
ks_entn = nbytes;
for (i = 0; i < nbytes; i = i + 1) ks_ent[i] = ent[i];
ks_words_n = idiv(nbytes * 8 + idiv(nbytes * 8, 32), 11);
sha256_hash(ks_ent, nbytes, ks_dig);
n = 0;
for (i = 0; i < ks_words_n; i = i + 1) {
v = 0;
for (b = 0; b < 11; b = b + 1) {
v = ((v << 1) | ks_stream_bit(n));
n = n + 1;
}
ks_idx[i] = (v & 0x7FF);
}
}
function ks_word(i) {
if (i >= ks_words_n) return 0;
return ks_idx[i];
}
function ks_gray(n) {
return (n ^ (n >> 1));
}
function ks_gray_inv(g) {
let n = 0;
n = g;
n = (n ^ (n >> 1));
n = (n ^ (n >> 2));
n = (n ^ (n >> 4));
n = (n ^ (n >> 8));
return (n & 0x7FF);
}
function ks_hilbert(d, order) {
let rx = 0;
let ry = 0;
let t = 0;
let s = 0;
let x = 0;
let y = 0;
let tmp = 0;
t = d;
x = 0;
y = 0;
s = 1;
while (s < (1 << order)) {
rx = (1 & shr32(t, 1));
ry = (1 & (t ^ rx));
if (ry == 0) {
if (rx == 1) {
x = (s - 1 - x);
y = (s - 1 - y);
}
tmp = x;
x = y;
y = tmp;
}
x = (x + (s * rx));
y = (y + (s * ry));
t = shr32(t, 2);
s = s << 1;
}
return ((x << 8) | (y & 255));
}
function ks_morton(d, order) {
let x = 0;
let y = 0;
let bit = 0;
let i = 0;
x = 0;
y = 0;
for (i = 0; i < order; i = i + 1) {
bit = (d >> (2 * i)) & 1;
x = (x | (bit << i));
bit = (d >> (2 * i + 1)) & 1;
y = (y | (bit << i));
}
return ((x << 8) | (y & 255));
}
function ks_ones() {
let n = 0;
let i = 0;
let b = 0;
n = 0;
for (i = 0; i < ks_entn; i = i + 1) {
for (b = 0; b < 8; b = b + 1) {
if (((ks_ent[i] >> b) & 1) != 0) n = (n + 1);
}
}
return n;
}
function ks_h8() {
let acc = 0;
let i = 0;
let n = 0;
let lg = 0;
for (i = 0; i < 256; i = i + 1) ks_hist[i] = 0;
for (i = 0; i < ks_entn; i = i + 1) ks_hist[ks_ent[i]] = (ks_hist[ks_ent[i]] + 1);
acc = 0;
for (i = 0; i < 256; i = i + 1) {
if (ks_hist[i] > 0) {
acc = add32(acc, mul32(ks_hist[i], log2_q8(ks_hist[i])));
}
}
n = ks_entn;
if (n <= 0) return 0;
lg = log2_q8(n);
return (lg - idiv(acc, n));
}
/* --- grid.c --- */
let grid_seed_v = 0;
let tr_a = new Uint8Array(TR_MAXW * TR_MAXH);
let tr_b = new Uint8Array(TR_MAXW * TR_MAXH);
let tr_wv = 0;
let tr_hv = 0;
let tr_gen_v = 0;
function grid_seed(s) {
if (s == 0) s = 0x5A17E1;
grid_seed_v = u32w(s);
}
function grid_nodes(sector) {
let h = 0;
h = u32w(grid_seed_v ^ mul32(sector, 0x9E3779B1));
h = u32w(h ^ shr32(h, 13));
h = mul32(h, 0x85EBCA6B);
h = u32w(h ^ shr32(h, 16));
return (h % 13);
}
function grid_node_xy(sector, slot) {
let h = 0;
let x = 0;
let y = 0;
h = u32w(grid_seed_v ^ mul32(((sector * 31) + slot), 0xC2B2AE35));
h = u32w(h ^ shr32(h, 15));
h = mul32(h, 0x27D4EB2F);
h = u32w(h ^ shr32(h, 13));
x = (h & 255);
y = ((h >> 8) & 255);
return ((x << 8) | y);
}
function tr_w() {
return tr_wv;
}
function tr_h() {
return tr_hv;
}
function tr_gen() {
return tr_gen_v;
}
function tr_init(s, maxw, maxh) {
let i = 0;
let n = 0;
let r = 0;
if (maxw > TR_MAXW) maxw = TR_MAXW;
if (maxh > TR_MAXH) maxh = TR_MAXH;
if (maxw < 8) maxw = 8;
if (maxh < 8) maxh = 8;
tr_wv = maxw;
tr_hv = maxh;
tr_gen_v = 0;
rng_seed(s);
n = (maxw * maxh);
for (i = 0; i < n; i = i + 1) {
r = rng_next();
if ((r & 3) == 0) tr_a[i] = 1;
else tr_a[i] = 0;
}
}
function tr_get(i) {
if (i >= (tr_wv * tr_hv)) return 0;
return tr_a[i];
}
function tr_step() {
let x = 0;
let y = 0;
let i = 0;
let n = 0;
let left = 0;
let right = 0;
let up = 0;
let down = 0;
let alive = 0;
for (y = 0; y < tr_hv; y = y + 1) {
up = ((y + tr_hv - 1) % tr_hv);
down = ((y + 1) % tr_hv);
for (x = 0; x < tr_wv; x = x + 1) {
left = ((x + tr_wv - 1) % tr_wv);
right = ((x + 1) % tr_wv);
n = 0;
n = (n + tr_a[up * tr_wv + left]);
n = (n + tr_a[up * tr_wv + x]);
n = (n + tr_a[up * tr_wv + right]);
n = (n + tr_a[y * tr_wv + left]);
n = (n + tr_a[y * tr_wv + right]);
n = (n + tr_a[down * tr_wv + left]);
n = (n + tr_a[down * tr_wv + x]);
n = (n + tr_a[down * tr_wv + right]);
i = (y * tr_wv + x);
alive = tr_a[i];
if (alive != 0) {
if (n >= 1 && n <= 4) tr_b[i] = 1;
else tr_b[i] = 0;
} else {
if (n == 3) tr_b[i] = 1;
else tr_b[i] = 0;
}
}
}
n = (tr_wv * tr_hv);
for (i = 0; i < n; i = i + 1) tr_a[i] = tr_b[i];
tr_gen_v = ((tr_gen_v + 1) & 0xFFFF);
}
/* --- app.c --- */
let SK_W = 0;
let SK_H = 0;
let SK_ROWB = 0;
let SK_FBB = 0;
let SK_DEV = 0;
let SK_SCREEN = 0;
let SK_CURSOR = 0;
let SK_SUB = 0;
let SK_SELWORD = 0;
let SK_TICK = 0;
let SK_QUIT = 0;
const T_SITEK = new Uint8Array([83, 73, 84, 69, 45, 75, 0]);
const T_TAG = new Uint8Array([72, 84, 77, 76, 53, 32, 67, 79, 82, 69, 0]);
const T_PRESS = new Uint8Array([80, 82, 69, 83, 83, 32, 75, 69, 89, 0]);
const T_GRID = new Uint8Array([71, 82, 73, 68, 0]);
const T_KEYS = new Uint8Array([75, 69, 89, 83, 0]);
const T_TERR = new Uint8Array([84, 69, 82, 82, 0]);
const T_INFO = new Uint8Array([68, 69, 86, 73, 67, 69, 0]);
const T_SEC = new Uint8Array([83, 69, 67, 32, 0]);
const T_NPREF = new Uint8Array([32, 78, 0]);
const T_LCDPFX = new Uint8Array([76, 67, 68, 32, 0]);
const T_RAMPFX = new Uint8Array([82, 65, 77, 32, 0]);
const T_ONES = new Uint8Array([32, 79, 78, 69, 83, 32, 0]);
const T_GEN = new Uint8Array([71, 69, 78, 32, 0]);
const T_PAR = new Uint8Array([80, 65, 82, 65, 76, 76, 69, 76, 0]);
const T_HIL = new Uint8Array([72, 73, 76, 66, 69, 82, 84, 0]);
const T_BIT = new Uint8Array([66, 73, 84, 83, 0]);
const T_IDX = new Uint8Array([73, 68, 88, 32, 0]);
const T_WORDS = new Uint8Array([87, 79, 82, 68, 83, 0]);
const N_TI83 = new Uint8Array([84, 73, 45, 56, 51, 0]);
const N_TI85 = new Uint8Array([84, 73, 45, 56, 53, 0]);
const N_TI89 = new Uint8Array([84, 73, 45, 56, 57, 0]);
const N_TI90 = new Uint8Array([84, 73, 45, 57, 48, 0]);
const N_TI92 = new Uint8Array([84, 73, 45, 57, 50, 0]);
const N_HOST = new Uint8Array([72, 79, 83, 84, 0]);
const C_Z80 = new Uint8Array([90, 56, 48, 0]);
const C_M68K = new Uint8Array([77, 54, 56, 75, 0]);
function dev_name(dev) {
if (dev == DEV_TI85) return N_TI85;
if (dev == DEV_TI89) return N_TI89;
if (dev == DEV_TI90) return N_TI90;
if (dev == DEV_TI92) return N_TI92;
if (dev == DEV_HOST) return N_HOST;
return N_TI83;
}
function dev_cpu(dev) {
if (dev == DEV_TI89) return C_M68K;
if (dev == DEV_TI92) return C_M68K;
return C_Z80;
}
function dev_ram_k(dev) {
if (dev == DEV_TI89) return 256;
if (dev == DEV_TI92) return 128;
return 32;
}
function scr_name() {
if (SK_SCREEN == SCR_GRID) return T_GRID;
if (SK_SCREEN == SCR_KEYS) return T_KEYS;
if (SK_SCREEN == SCR_TERR) return T_TERR;
if (SK_SCREEN == SCR_INFO) return T_INFO;
return T_SITEK;
}
function fmt_dims(buf) {
let n = 0;
n = str_copy(buf, T_LCDPFX);
n = (n + num_to(buf, n, SK_W));
buf[n] = 88;
n = (n + 1);
n = (n + num_to(buf, n, SK_H));
buf[n] = 0;
return n;
}
function fmt_ram(buf) {
let n = 0;
n = str_copy(buf, T_RAMPFX);
n = (n + num_to(buf, n, dev_ram_k(SK_DEV)));
buf[n] = 75;
n = (n + 1);
buf[n] = 0;
return n;
}
function fmt_sec(buf, sector) {
let n = 0;
let col = 0;
let row = 0;
col = (sector & 7);
row = (sector >> 3);
n = str_copy(buf, T_SEC);
buf[n] = (65 + col);
n = (n + 1);
buf[n] = (49 + row);
n = (n + 1);
return n;
}
function fmt_q8(buf, at, v) {
let n = 0;
let frac = 0;
n = at;
n = (n + num_to(buf, n, (v >> 8)));
buf[n] = 46;
n = (n + 1);
frac = idiv((v & 255) * 100, 256);
buf[n] = (48 + idiv(frac, 10));
n = (n + 1);
buf[n] = (48 + imod(frac, 10));
n = (n + 1);
return n;
}
function draw_status() {
let nm = 0;
let x = 0;
fb_box(0, 0, SK_W, 8, FILL_SOLID);
fb_textm(2, 2, scr_name(), PX_CLEAR);
nm = dev_name(SK_DEV);
x = (SK_W - 2 - fb_text_w(nm));
if (x < 24) x = 24;
fb_textm(x, 2, nm, PX_CLEAR);
}
function draw_footer(s) {
let y = 0;
y = (SK_H - 9);
fb_hline(0, (SK_W - 1), y, PX_SET);
fb_text(2, (y + 2), s);
}
function render_boot() {
let buf = new Uint8Array(24);
let cx = 0;
let y = 0;
y = idiv(SK_H - 44, 2);
if (y < 8) y = 8;
cx = idiv(SK_W - fb_text_w(T_SITEK) * 2, 2);
fb_text2(cx, y, T_SITEK);
fb_hline(0, (SK_W - 1), (y + 12), PX_SET);
fb_text(2, (y + 16), T_TAG);
fb_text(2, (y + 23), dev_name(SK_DEV));
fmt_dims(buf);
fb_text(2, (y + 30), buf);
fb_text(2, (y + 37), T_PRESS);
}
function render_grid() {
let buf = new Uint8Array(24);
let gw = 0;
let gh = 0;
let ox = 0;
let oy = 0;
let i = 0;
let x0 = 0;
let y0 = 0;
let k = 0;
let n = 0;
let xy = 0;
let px = 0;
let py = 0;
let col = 0;
let row = 0;
gw = idiv(SK_W - 4, 8);
gh = idiv(SK_H - 26, 8);
if (gw < 4) gw = 4;
if (gh < 3) gh = 3;
ox = idiv(SK_W - gw * 8, 2);
oy = 11;
for (i = 0; i < 64; i = i + 1) {
col = (i & 7);
row = (i >> 3);
x0 = (ox + col * gw);
y0 = (oy + row * gh);
if (i == SK_CURSOR) fb_box(x0, y0, gw, gh, FILL_HALF);
else fb_rect(x0, y0, gw, gh, PX_SET);
n = grid_nodes(i);
for (k = 0; k < 3; k = k + 1) {
if (n > k * 4) {
xy = grid_node_xy(i, k);
px = (x0 + 1 + idiv((xy >> 8) * (gw - 2), 255));
py = (y0 + 1 + idiv((xy & 255) * (gh - 2), 255));
fb_px(px, py, PX_SET);
}
}
}
n = fmt_sec(buf, SK_CURSOR);
n = (n + str_copy_at(buf, n, T_NPREF));
n = (n + num_to(buf, n, grid_nodes(SK_CURSOR)));
buf[n] = 0;
draw_footer(buf);
}
const T_H8 = new Uint8Array([32, 72, 56, 32, 0]);
function keys_footer(buf) {
let n = 0;
n = 0;
buf[n] = 87;
n = (n + 1);
n = (n + num_to(buf, n, ks_words()));
n = (n + str_copy_at(buf, n, T_H8));
n = fmt_q8(buf, n, ks_h8());
n = (n + str_copy_at(buf, n, T_ONES));
n = (n + num_to(buf, n, ks_ones()));
buf[n] = 0;
}
function render_keys() {
let buf = new Uint8Array(32);
let i = 0;
let x = 0;
let y = 0;
let prevx = 0;
let prevy = 0;
let sc = 0;
let ox = 0;
let oy = 0;
let d = 0;
let p = 0;
let nbits = 0;
let bx = 0;
let by = 0;
let hgt = 0;
let top = 0;
top = 11;
hgt = (SK_H - 22);
if (SK_SUB == 0) {
prevx = 0;
prevy = 0;
for (i = 0; i < ks_words(); i = i + 1) {
x = (2 + idiv(i * (SK_W - 4), (ks_words() - 1)));
y = (top + idiv(ks_word(i) * hgt, 2047));
fb_vline(x, top, (top + hgt), PX_SET);
if (i > 0) fb_line(prevx, prevy, x, y, PX_SET);
prevx = x;
prevy = y;
}
fb_box((prevx - 1), (prevy - 1), 3, 3, FILL_SOLID);
fb_text(2, (top + 1), T_PAR);
} else if (SK_SUB == 1) {
sc = idiv(hgt, 16);
if (sc < 1) sc = 1;
ox = idiv(SK_W - 16 * sc, 2);
oy = (top + idiv(hgt - 16 * sc, 2));
prevx = 0;
prevy = 0;
for (d = 0; d < 256; d = d + 1) {
p = ks_hilbert(ks_gray(d), 4);
x = (ox + (p >> 8) * sc);
y = (oy + (p & 255) * sc);
if (d > 0) fb_line(prevx, prevy, x, y, PX_SET);
prevx = x;
prevy = y;
}
fb_text(2, (top + 1), T_HIL);
} else {
nbits = (ks_ent_bits() + ks_cs_bits());
for (i = 0; i < nbits; i = i + 1) {
if (i >= 132) break;
bx = (3 + imod(i, 22) * 4);
by = (top + idiv(i, 22) * 4);
if (ks_stream_bit(i) != 0) fb_box(bx, by, 3, 3, FILL_SOLID);
else fb_rect(bx, by, 3, 3, PX_SET);
}
fb_text(2, (top + 1), T_BIT);
}
keys_footer(buf);
draw_footer(buf);
}
function render_terr() {
let buf = new Uint8Array(24);
let i = 0;
let x = 0;
let y = 0;
let ox = 0;
let oy = 0;
let sc = 0;
let n = 0;
sc = 1;
if (SK_W >= 200) sc = 2;
ox = idiv(SK_W - tr_w() * sc, 2);
oy = 11;
n = (tr_w() * tr_h());
for (i = 0; i < n; i = i + 1) {
if (tr_get(i) != 0) {
x = (ox + imod(i, tr_w()) * sc);
y = (oy + idiv(i, tr_w()) * sc);
fb_box(x, y, sc, sc, FILL_SOLID);
}
}
fb_rect((ox - 1), (oy - 1), (tr_w() * sc + 2), (tr_h() * sc + 2), PX_SET);
n = str_copy(buf, T_GEN);
n = (n + num_to(buf, n, tr_gen()));
buf[n] = 0;
draw_footer(buf);
}
function render_info() {
let buf = new Uint8Array(32);
let y = 0;
let n = 0;
y = 12;
fb_text(2, y, dev_name(SK_DEV));
y = (y + 8);
fb_text(2, y, dev_cpu(SK_DEV));
y = (y + 8);
fmt_dims(buf);
fb_text(2, y, buf);
y = (y + 8);
fmt_ram(buf);
fb_text(2, y, buf);
y = (y + 8);
n = str_copy(buf, T_WORDS);
buf[n] = 32;
n = (n + 1);
n = (n + num_to(buf, n, ks_words()));
buf[n] = 0;
fb_text(2, y, buf);
y = (y + 8);
n = str_copy(buf, T_IDX);
n = (n + num_to(buf, n, ks_word(SK_SELWORD)));
buf[n] = 0;
fb_text(2, y, buf);
}
function sitek_init(dev, w, h) {
let terrw = 0;
let terrh = 0;
SK_DEV = dev;
SK_W = w;
SK_H = h;
SK_ROWB = ((w + 7) >> 3);
SK_FBB = (SK_ROWB * h);
if (SK_FBB > FB_MAX) SK_FBB = FB_MAX;
SK_SCREEN = SCR_BOOT;
SK_CURSOR = 0;
SK_SUB = 0;
SK_SELWORD = 0;
SK_TICK = 0;
SK_QUIT = 0;
grid_seed(u32w(0x5A17E1 ^ mul32(dev, 0x9E3779B9)));
ks_seed(u32w(0x53495445 ^ mul32(dev, 0x85EBCA6B)));
ks_gen(12);
terrw = (w - 8);
terrh = idiv(h - 24, 2);
if (terrw > TR_MAXW) terrw = TR_MAXW;
if (terrh > TR_MAXH) terrh = TR_MAXH;
tr_init(u32w(0x7EBBA12 ^ mul32(dev, 0xC2B2AE35)), terrw, terrh);
}
function grid_key(k) {
let col = 0;
let row = 0;
col = (SK_CURSOR & 7);
row = (SK_CURSOR >> 3);
if (k == SKK_LEFT) col = ((col + 7) & 7);
else if (k == SKK_RIGHT) col = ((col + 1) & 7);
else if (k == SKK_UP) row = ((row + 7) & 7);
else if (k == SKK_DOWN) row = ((row + 1) & 7);
else if (k == SKK_ACT) {
grid_seed(u32w(grid_nodes(0) + rng_next()));
return;
} else return;
SK_CURSOR = (row * 8 + col);
}
function keys_key(k) {
if (k == SKK_UP) {
if (SK_SUB == 0) SK_SUB = 2;
else SK_SUB = (SK_SUB - 1);
return;
}
if (k == SKK_DOWN) {
SK_SUB = ((SK_SUB + 1) % 3);
return;
}
if (k == SKK_LEFT) {
if (SK_SELWORD == 0) SK_SELWORD = (ks_words() - 1);
else SK_SELWORD = (SK_SELWORD - 1);
return;
}
if (k == SKK_RIGHT) {
SK_SELWORD = ((SK_SELWORD + 1) % ks_words());
return;
}
if (k == SKK_ENTER) {
ks_seed(rng_next());
ks_gen(ks_words());
return;
}
if (k == SKK_ACT) {
if (ks_words() >= 24) ks_gen(12);
else ks_gen((ks_words() + 3));
}
}
function sitek_key(k) {
if (k == SKK_EXIT) {
SK_QUIT = 1;
return;
}
if (SK_SCREEN == SCR_BOOT) {
if (k != SKK_NONE) SK_SCREEN = SCR_GRID;
return;
}
if (k == SKK_1) {
SK_SCREEN = SCR_GRID;
return;
}
if (k == SKK_2) {
SK_SCREEN = SCR_KEYS;
return;
}
if (k == SKK_3) {
SK_SCREEN = SCR_TERR;
return;
}
if (k == SKK_4) {
SK_SCREEN = SCR_INFO;
return;
}
if (k == SKK_5) {
SK_SCREEN = SCR_BOOT;
return;
}
if (SK_SCREEN == SCR_GRID) grid_key(k);
else if (SK_SCREEN == SCR_KEYS) keys_key(k);
else if (SK_SCREEN == SCR_TERR) {
if (k == SKK_ENTER) tr_step();
else if (k == SKK_ACT) tr_init(u32w(rng_next()), tr_w(), tr_h());
} else if (SK_SCREEN == SCR_INFO) {
if (k == SKK_ENTER) SK_SCREEN = SCR_GRID;
}
}
function sitek_set_screen(scr) {
if (scr > SCR_INFO) scr = SCR_BOOT;
SK_SCREEN = scr;
}
function sitek_get_screen() {
return SK_SCREEN;
}
function sitek_set_cursor(cur) {
SK_CURSOR = (cur & 63);
}
function sitek_set_sub(sub) {
SK_SUB = (sub % 3);
}
function sitek_tick() {
SK_TICK = ((SK_TICK + 1) & 0xFFFF);
if (SK_SCREEN == SCR_TERR) {
if ((SK_TICK & 1) == 0) tr_step();
}
}
function sitek_render() {
fb_clear();
if (SK_SCREEN == SCR_BOOT) {
render_boot();
return;
}
draw_status();
if (SK_SCREEN == SCR_GRID) render_grid();
else if (SK_SCREEN == SCR_KEYS) render_keys();
else if (SK_SCREEN == SCR_TERR) render_terr();
else render_info();
}

export { idiv, imod, iabs, imin, imax, iclamp, u32w, shr32, mul32, add32, ror32, rng_seed, rng_next, rng_range, sin_index, fsin, fcos, isqrt, log2_q8, fb_clear, fb_px, fb_get, fb_hline, fb_vline, fb_line, fb_rect, fb_box, font_index, fb_textm, fb_text, fb_text2, fb_text_w, str_copy, str_copy_at, num_to, sha_compress, sha256_hash, ks_seed, ks_ent_bits, ks_cs_bits, ks_words, ks_stream_bit, ks_gen, ks_set_entropy, ks_word, ks_gray, ks_gray_inv, ks_hilbert, ks_morton, ks_ones, ks_h8, grid_seed, grid_nodes, grid_node_xy, tr_w, tr_h, tr_gen, tr_init, tr_get, tr_step, dev_name, dev_cpu, dev_ram_k, scr_name, fmt_dims, fmt_ram, fmt_sec, fmt_q8, draw_status, draw_footer, render_boot, render_grid, keys_footer, render_keys, render_terr, render_info, sitek_init, grid_key, keys_key, sitek_key, sitek_set_screen, sitek_get_screen, sitek_set_cursor, sitek_set_sub, sitek_tick, sitek_render, SK_FB, SK_W, SK_H, SK_ROWB, SK_FBB, SK_DEV, SK_SCREEN, SK_CURSOR, SK_SUB, SK_SELWORD, SK_TICK, SK_QUIT, FB_MAX, DEV_TI83, DEV_TI85, DEV_TI89, DEV_TI90, DEV_TI92, DEV_HOST, SCR_BOOT, SCR_GRID, SCR_KEYS, SCR_TERR, SCR_INFO, SKK_NONE, SKK_LEFT, SKK_RIGHT, SKK_UP, SKK_DOWN, SKK_ENTER, SKK_EXIT, SKK_ACT, SKK_1, SKK_2, SKK_3, SKK_4, SKK_5, PX_CLEAR, PX_SET, PX_FLIP, FILL_CLEAR, FILL_SOLID, FILL_HALF, FILL_QUARTER, KS_MAX_WORDS, TR_MAXW, TR_MAXH };
