<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE eagle SYSTEM "eagle.dtd">
<!-- generated by tools/build-wallplug-eagle.mjs from tools/pi-socket-model.mjs — do not edit by hand -->
<eagle version="9.6.2">
<drawing>
<settings><setting alwaysvectorfont="no"/>
<setting verticaltext="up"/></settings>

<grid distance="2.54" unitdist="mm" unit="mm" style="lines" multiple="1" display="yes" altdistance="0.635" altunitdist="mm" altunit="mm"/>
<layers><layer number="90" name="Modules" color="5" fill="1" visible="yes" active="yes"/>
<layer number="91" name="Nets" color="2" fill="1" visible="yes" active="yes"/>
<layer number="92" name="Busses" color="1" fill="1" visible="yes" active="yes"/>
<layer number="93" name="Pins" color="2" fill="1" visible="yes" active="yes"/>
<layer number="94" name="Symbols" color="4" fill="1" visible="yes" active="yes"/>
<layer number="95" name="Names" color="7" fill="1" visible="yes" active="yes"/>
<layer number="96" name="Values" color="7" fill="1" visible="yes" active="yes"/>
<layer number="97" name="Info" color="7" fill="1" visible="yes" active="yes"/>
<layer number="98" name="Guide" color="6" fill="1" visible="yes" active="yes"/></layers>
<schematic xreflabel="%F%N/%S.%C%R" xrefpart="/%S.%C%R"><description>Pi Wall Socket: mains-powered Raspberry Pi Zero 2 W carrier for a wall-socket enclosure, with wired Ethernet (WIZ850io, SPI0) and Ethernet-over-powerline (PLC Stamp mini 2, SPI1)</description>
<libraries><library name="pi-wall-socket"><description>pi-wall-socket: Pi Wall Socket design library (generated by tools/build-wallplug-eagle.mjs from tools/pi-socket-model.mjs)</description>
<packages><package name="R-7.62"><description>Resistor, axial DIN0207 (6.3 x 2.5 mm), 7.62 mm pitch</description>
<wire x1="-3.15" y1="1.25" x2="3.15" y2="1.25" width="0.2032" layer="21"/>
<wire x1="3.15" y1="1.25" x2="3.15" y2="-1.25" width="0.2032" layer="21"/>
<wire x1="3.15" y1="-1.25" x2="-3.15" y2="-1.25" width="0.2032" layer="21"/>
<wire x1="-3.15" y1="-1.25" x2="-3.15" y2="1.25" width="0.2032" layer="21"/>
<wire x1="-3.81" y1="0" x2="-3.15" y2="0" width="0.2032" layer="51"/>
<wire x1="3.15" y1="0" x2="3.81" y2="0" width="0.2032" layer="51"/>
<text x="-3.15" y="1.75" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-3.81" y="0" drill="0.8" diameter="1.7" shape="square"/>
<pad name="2" x="3.81" y="0" drill="0.8" diameter="1.7"/></package>
<package name="C-5.08"><description>Ceramic / film disc capacitor, 5.0 x 2.5 mm, 5.08 mm pitch</description>
<wire x1="-2.5" y1="1.25" x2="2.5" y2="1.25" width="0.2032" layer="21"/>
<wire x1="2.5" y1="1.25" x2="2.5" y2="-1.25" width="0.2032" layer="21"/>
<wire x1="2.5" y1="-1.25" x2="-2.5" y2="-1.25" width="0.2032" layer="21"/>
<wire x1="-2.5" y1="-1.25" x2="-2.5" y2="1.25" width="0.2032" layer="21"/>
<wire x1="-2.54" y1="0" x2="-2.5" y2="0" width="0.2032" layer="51"/>
<wire x1="2.5" y1="0" x2="2.54" y2="0" width="0.2032" layer="51"/>
<text x="-2.5" y="1.75" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-2.54" y="0" drill="0.8" diameter="1.7" shape="square"/>
<pad name="2" x="2.54" y="0" drill="0.8" diameter="1.7"/></package>
<package name="CP-D10-P5"><description>Electrolytic, radial, 10 mm dia, 5.0 mm pitch</description>
<circle x="0" y="0" radius="5" width="0.2032" layer="21"/>
<text x="-4.4" y="-4.6" size="1.4" layer="21">+</text>
<text x="-5" y="5.4" size="1" layer="25">&gt;NAME</text>
<pad name="+" x="-2.5" y="0" drill="1" diameter="2" shape="square"/>
<pad name="-" x="2.5" y="0" drill="1" diameter="2"/></package>
<package name="CP-D6.3-P2.5"><description>Electrolytic, radial, 6.3 mm dia, 2.5 mm pitch</description>
<circle x="0" y="0" radius="3.15" width="0.2032" layer="21"/>
<text x="-2.55" y="-2.75" size="1.4" layer="21">+</text>
<text x="-3.15" y="3.55" size="1" layer="25">&gt;NAME</text>
<pad name="+" x="-1.25" y="0" drill="1" diameter="2" shape="square"/>
<pad name="-" x="1.25" y="0" drill="1" diameter="2"/></package>
<package name="FB-7.62"><description>Ferrite bead, axial 7.2 x 4.0 mm, 7.62 mm pitch</description>
<wire x1="-3.6" y1="2" x2="3.6" y2="2" width="0.2032" layer="21"/>
<wire x1="3.6" y1="2" x2="3.6" y2="-2" width="0.2032" layer="21"/>
<wire x1="3.6" y1="-2" x2="-3.6" y2="-2" width="0.2032" layer="21"/>
<wire x1="-3.6" y1="-2" x2="-3.6" y2="2" width="0.2032" layer="21"/>
<wire x1="-3.81" y1="0" x2="-3.6" y2="0" width="0.2032" layer="51"/>
<wire x1="3.6" y1="0" x2="3.81" y2="0" width="0.2032" layer="51"/>
<text x="-3.6" y="2.5" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-3.81" y="0" drill="0.8" diameter="1.7" shape="square"/>
<pad name="2" x="3.81" y="0" drill="0.8" diameter="1.7"/></package>
<package name="FUSE-RADIAL"><description>Radial fuse, TR5 / 372 series, 8.5 mm body, 5.08 mm pitch</description>
<circle x="0" y="0" radius="4.25" width="0.2032" layer="21"/>
<wire x1="-2.54" y1="0" x2="-4.25" y2="0" width="0.2032" layer="51"/>
<wire x1="4.25" y1="0" x2="2.54" y2="0" width="0.2032" layer="51"/>
<text x="-4.25" y="4.75" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-2.54" y="0" drill="1" diameter="2" shape="square"/>
<pad name="2" x="2.54" y="0" drill="1" diameter="2"/></package>
<package name="MOV07"><description>Metal-oxide varistor, 7 mm disc, 5.0 mm pitch</description>
<circle x="0" y="0" radius="3.5" width="0.2032" layer="21"/>
<wire x1="-2.5" y1="0" x2="-3.5" y2="0" width="0.2032" layer="51"/>
<wire x1="3.5" y1="0" x2="2.5" y2="0" width="0.2032" layer="51"/>
<text x="-3.5" y="4" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-2.5" y="0" drill="0.8" diameter="1.8" shape="square"/>
<pad name="2" x="2.5" y="0" drill="0.8" diameter="1.8"/></package>
<package name="LED-5MM"><description>LED 5 mm, 2.54 mm pitch</description>
<circle x="0" y="0" radius="2.5" width="0.2032" layer="21"/>
<wire x1="-1.27" y1="0" x2="-2.5" y2="0" width="0.2032" layer="51"/>
<wire x1="2.5" y1="0" x2="1.27" y2="0" width="0.2032" layer="51"/>
<text x="-2.5" y="3" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-1.27" y="0" drill="0.8" diameter="1.7" shape="square"/>
<pad name="2" x="1.27" y="0" drill="0.8" diameter="1.7"/></package>
<package name="SW-TACT-6MM"><description>Tactile pushbutton 6 x 6 mm, 2 poles (pins 1/1 and 2/2 internally common)</description>
<wire x1="-3" y1="-3" x2="3" y2="-3" width="0.2032" layer="21"/>
<wire x1="3" y1="-3" x2="3" y2="3" width="0.2032" layer="21"/>
<wire x1="3" y1="3" x2="-3" y2="3" width="0.2032" layer="21"/>
<wire x1="-3" y1="3" x2="-3" y2="-3" width="0.2032" layer="21"/>
<text x="-3" y="4.2" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-3.25" y="-2.25" drill="1.1" diameter="2" shape="square"/>
<pad name="1" x="3.25" y="-2.25" drill="1.1" diameter="2"/>
<pad name="2" x="-3.25" y="2.25" drill="1.1" diameter="2"/>
<pad name="2" x="3.25" y="2.25" drill="1.1" diameter="2"/></package>
<package name="TP"><description>Test point, 1.0 mm hole, 2.0 mm pad</description>
<text x="-1.2" y="1.6" size="0.9" layer="25">&gt;NAME</text>
<pad name="1" x="0" y="0" drill="1" diameter="2"/></package>
<package name="MOUNT-M3"><description>M3 mounting hole, 3.2 mm, non-plated, with keep-out ring</description>
<circle x="0" y="0" radius="2.4" width="0.2032" layer="41"/>
<circle x="0" y="0" radius="2.4" width="0.2032" layer="41"/>
<hole x="0" y="0" drill="3.2"/></package>
<package name="HDR-2X5"><description>2 x 5 pin header, 2.54 mm (TTL serial + CP + reset)</description>
<wire x1="-6.35" y1="2.54" x2="6.35" y2="2.54" width="0.2032" layer="21"/>
<wire x1="6.35" y1="2.54" x2="6.35" y2="-2.54" width="0.2032" layer="21"/>
<wire x1="6.35" y1="-2.54" x2="-6.35" y2="-2.54" width="0.2032" layer="21"/>
<wire x1="-6.35" y1="-2.54" x2="-6.35" y2="2.54" width="0.2032" layer="21"/>
<text x="-6.28" y="3.2" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-5.08" y="-1.27" drill="1" diameter="1.8" shape="square"/>
<pad name="2" x="-5.08" y="1.27" drill="1" diameter="1.8"/>
<pad name="3" x="-2.54" y="-1.27" drill="1" diameter="1.8"/>
<pad name="4" x="-2.54" y="1.27" drill="1" diameter="1.8"/>
<pad name="5" x="0" y="-1.27" drill="1" diameter="1.8"/>
<pad name="6" x="0" y="1.27" drill="1" diameter="1.8"/>
<pad name="7" x="2.54" y="-1.27" drill="1" diameter="1.8"/>
<pad name="8" x="2.54" y="1.27" drill="1" diameter="1.8"/>
<pad name="9" x="5.08" y="-1.27" drill="1" diameter="1.8"/>
<pad name="10" x="5.08" y="1.27" drill="1" diameter="1.8"/></package>
<package name="CUI_TB003"><description>CUI TB003-500-P03BE, 3-position 5.00 mm terminal block, drill 1.4 mm</description>

<pad name="1" x="-5" y="0" drill="1.4" diameter="2.1" shape="square"/>
<pad name="2" x="0" y="0" drill="1.4" diameter="2.1"/>
<pad name="3" x="5" y="0" drill="1.4" diameter="2.1"/></package>
<package name="MPM2012"><description>MEAN WELL MPM-20-12, 20 W encapsulated AC-DC, 12 V / 1.67 A out</description>

<pad name="1" x="22.733" y="9.906" drill="1.24" diameter="1.86"/>
<pad name="2" x="22.733" y="-10.894" drill="1.24" diameter="1.86"/>
<pad name="4" x="-22.267" y="9.906" drill="1.24" diameter="1.86"/>
<pad name="3" x="-22.267" y="1.906" drill="1.24" diameter="1.86"/></package>
<package name="LM2576S"><description>TO-263-5 (D2PAK) with tab tied to pin 3 — LM2576S-3.3 step-down regulator</description>

<smd name="1" x="-5.775" y="3.4" dx="4.6" dy="1.1" layer="1"/>
<smd name="2" x="-5.775" y="1.7" dx="4.6" dy="1.1" layer="1"/>
<smd name="3" x="-5.775" y="0" dx="4.6" dy="1.1" layer="1"/>
<smd name="4" x="-5.775" y="-1.7" dx="4.6" dy="1.1" layer="1"/>
<smd name="5" x="-5.775" y="-3.4" dx="4.6" dy="1.1" layer="1"/>
<smd name="3_2" x="3.375" y="0" dx="9.4" dy="10.8" layer="1"/>
<smd name="P7" x="5.8" y="-2.775" dx="4.55" dy="5.25" layer="1"/>
<smd name="P8" x="0.95" y="2.775" dx="4.55" dy="5.25" layer="1"/>
<smd name="P9" x="5.8" y="2.775" dx="4.55" dy="5.25" layer="1"/>
<smd name="P10" x="0.95" y="-2.775" dx="4.55" dy="5.25" layer="1"/></package>
<package name="LRAD12"><description>Radial power inductor, Ø12 mm body, 5.0 mm lead pitch — 100 µH for the LM2576</description>

<pad name="1" x="0" y="0" drill="1.3" diameter="2.6"/>
<pad name="2" x="5" y="0" drill="1.3" diameter="2.6"/></package>
<package name="DO41"><description>DO-41 axial diode, 7.62 mm lead pitch (1N5822 / SS34-class Schottky)</description>
<wire x1="-2.5" y1="1.3" x2="2.5" y2="1.3" width="0.2032" layer="21"/>
<wire x1="2.5" y1="1.3" x2="2.5" y2="-1.3" width="0.2032" layer="21"/>
<wire x1="2.5" y1="-1.3" x2="-2.5" y2="-1.3" width="0.2032" layer="21"/>
<wire x1="-2.5" y1="-1.3" x2="-2.5" y2="1.3" width="0.2032" layer="21"/>
<wire x1="1.6" y1="1.3" x2="1.6" y2="-1.3" width="0.2032" layer="21"/>
<text x="-2.4" y="1.9" size="1" layer="25">&gt;NAME</text>
<pad name="A" x="-3.81" y="0" drill="0.9" diameter="1.8"/>
<pad name="K" x="3.81" y="0" drill="0.9" diameter="1.8" shape="square"/></package>
<package name="R0603"><description>0603 (1608 metric) chip resistor</description>

<smd name="1" x="-0.825" y="0" dx="0.8" dy="0.95" layer="1"/>
<smd name="2" x="0.825" y="0" dx="0.8" dy="0.95" layer="1"/></package>
<package name="C0603"><description>0603 (1608 metric) chip capacitor</description>

<smd name="1" x="-0.775" y="0" dx="0.9" dy="0.95" layer="1"/>
<smd name="2" x="0.775" y="0" dx="0.9" dy="0.95" layer="1"/></package>
<package name="PIZERO"><description>Raspberry Pi Zero / Zero 2 W template: 2x20 header pads plus the four M2.5 corner holes at 58 x 23 mm, board outline 65 x 30 mm</description>

<pad name="1" x="8.4" y="25.25" drill="1" diameter="1.7" shape="square"/>
<pad name="2" x="8.4" y="27.79" drill="1" diameter="1.7" shape="square"/>
<pad name="3" x="10.94" y="25.25" drill="1" diameter="1.7" shape="square"/>
<pad name="4" x="10.94" y="27.79" drill="1" diameter="1.7" shape="square"/>
<pad name="5" x="13.48" y="25.25" drill="1" diameter="1.7" shape="square"/>
<pad name="6" x="13.48" y="27.79" drill="1" diameter="1.7" shape="square"/>
<pad name="7" x="16.02" y="25.25" drill="1" diameter="1.7" shape="square"/>
<pad name="8" x="16.02" y="27.79" drill="1" diameter="1.7" shape="square"/>
<pad name="9" x="18.56" y="25.25" drill="1" diameter="1.7" shape="square"/>
<pad name="10" x="18.56" y="27.79" drill="1" diameter="1.7" shape="square"/>
<pad name="11" x="21.1" y="25.25" drill="1" diameter="1.7" shape="square"/>
<pad name="12" x="21.1" y="27.79" drill="1" diameter="1.7" shape="square"/>
<pad name="13" x="23.64" y="25.25" drill="1" diameter="1.7" shape="square"/>
<pad name="14" x="23.64" y="27.79" drill="1" diameter="1.7" shape="square"/>
<pad name="15" x="26.18" y="25.25" drill="1" diameter="1.7" shape="square"/>
<pad name="16" x="26.18" y="27.79" drill="1" diameter="1.7" shape="square"/>
<pad name="17" x="28.72" y="25.25" drill="1" diameter="1.7" shape="square"/>
<pad name="18" x="28.72" y="27.79" drill="1" diameter="1.7" shape="square"/>
<pad name="19" x="31.26" y="25.25" drill="1" diameter="1.7" shape="square"/>
<pad name="20" x="31.26" y="27.79" drill="1" diameter="1.7" shape="square"/>
<pad name="21" x="33.8" y="25.25" drill="1" diameter="1.7" shape="square"/>
<pad name="22" x="33.8" y="27.79" drill="1" diameter="1.7" shape="square"/>
<pad name="23" x="36.34" y="25.25" drill="1" diameter="1.7" shape="square"/>
<pad name="24" x="36.34" y="27.79" drill="1" diameter="1.7" shape="square"/>
<pad name="25" x="38.88" y="25.25" drill="1" diameter="1.7" shape="square"/>
<pad name="26" x="38.88" y="27.79" drill="1" diameter="1.7" shape="square"/>
<pad name="27" x="41.42" y="25.25" drill="1" diameter="1.7" shape="square"/>
<pad name="28" x="41.42" y="27.79" drill="1" diameter="1.7" shape="square"/>
<pad name="29" x="43.96" y="25.25" drill="1" diameter="1.7" shape="square"/>
<pad name="30" x="43.96" y="27.79" drill="1" diameter="1.7" shape="square"/>
<pad name="31" x="46.5" y="25.25" drill="1" diameter="1.7" shape="square"/>
<pad name="32" x="46.5" y="27.79" drill="1" diameter="1.7" shape="square"/>
<pad name="33" x="49.04" y="25.25" drill="1" diameter="1.7" shape="square"/>
<pad name="34" x="49.04" y="27.79" drill="1" diameter="1.7" shape="square"/>
<pad name="35" x="51.58" y="25.25" drill="1" diameter="1.7" shape="square"/>
<pad name="36" x="51.58" y="27.79" drill="1" diameter="1.7" shape="square"/>
<pad name="37" x="54.12" y="25.25" drill="1" diameter="1.7" shape="square"/>
<pad name="38" x="54.12" y="27.79" drill="1" diameter="1.7" shape="square"/>
<pad name="39" x="56.66" y="25.25" drill="1" diameter="1.7" shape="square"/>
<pad name="40" x="56.66" y="27.79" drill="1" diameter="1.7" shape="square"/>
<hole x="61.5" y="3.5" drill="2.75"/>
<hole x="61.5" y="26.5" drill="2.75"/>
<hole x="3.5" y="26.5" drill="2.75"/>
<hole x="3.5" y="3.5" drill="2.75"/></package>
<package name="PLCSTAMP"><description>chargebyte (ex I2SE) PLC Stamp mini 2 — QCA7005 HomePlug Green PHY module, 43.5 x 22 x 6.5 mm, integrated mains coupling</description>

<smd name="1" x="20.48" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="2" x="19.21" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="3" x="17.94" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="4" x="16.67" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="5" x="15.4" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="6" x="14.13" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="7" x="12.86" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="8" x="11.59" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="9" x="10.32" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="10" x="9.05" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="11" x="7.78" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="12" x="6.51" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="13" x="5.24" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="15" x="-8.73" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="16" x="-18.89" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="17" x="-20.16" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="18" x="1.43" y="-10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="19" x="2.7" y="-10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="20" x="3.97" y="-10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="21" x="5.24" y="-10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="22" x="6.51" y="-10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="23" x="7.78" y="-10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="24" x="9.05" y="-10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="25" x="10.32" y="-10.235" dx="0.85" dy="0.85" layer="1"/></package>
<package name="WIZ850IO"><description>WIZnet WIZ850io plug-in Ethernet module: W5500 + magnetics + RJ45, two 1x6 headers 20.32 mm apart</description>

<pad name="1" x="-9.86" y="4.75" drill="1.12" diameter="1.68" shape="square"/>
<pad name="2" x="-9.86" y="2.21" drill="1.12" diameter="1.68"/>
<pad name="3" x="-9.86" y="-0.33" drill="1.12" diameter="1.68"/>
<pad name="4" x="-9.86" y="-2.87" drill="1.12" diameter="1.68"/>
<pad name="5" x="-9.86" y="-5.41" drill="1.12" diameter="1.68"/>
<pad name="6" x="-9.86" y="-7.95" drill="1.12" diameter="1.68"/>
<pad name="7" x="10.46" y="4.75" drill="1.12" diameter="1.68" shape="square"/>
<pad name="8" x="10.46" y="2.21" drill="1.12" diameter="1.68"/>
<pad name="9" x="10.46" y="-0.33" drill="1.12" diameter="1.68"/>
<pad name="10" x="10.46" y="-2.87" drill="1.12" diameter="1.68"/>
<pad name="11" x="10.46" y="-5.41" drill="1.12" diameter="1.68"/>
<pad name="12" x="10.46" y="-7.95" drill="1.12" diameter="1.68"/></package></packages>
<symbols><symbol name="R-EU"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="0" x2="-1.9" y2="1" width="0.2032" layer="94"/>
<wire x1="-1.9" y1="1" x2="-0.63" y2="-1" width="0.2032" layer="94"/>
<wire x1="-0.63" y1="-1" x2="0.63" y2="1" width="0.2032" layer="94"/>
<wire x1="0.63" y1="1" x2="1.9" y2="-1" width="0.2032" layer="94"/>
<wire x1="1.9" y1="-1" x2="2.54" y2="0" width="0.2032" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="C-EU"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="-1.27" y1="0.9" x2="1.27" y2="0.9" width="0.3" layer="94"/>
<wire x1="-1.27" y1="-0.9" x2="1.27" y2="-0.9" width="0.3" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="CPOL-EU"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="-1.27" y1="0.9" x2="1.27" y2="0.9" width="0.3" layer="94"/>
<wire x1="-1.27" y1="-0.9" x2="1.27" y2="-0.9" width="0.3" layer="94" style="shortdash"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<text x="-3.4" y="1.2" size="1.6" layer="94">+</text>
<pin name="+" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="-" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="FERRITE"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="FUSE"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="MOV"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="LED"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="1" y1="1.6" x2="2.2" y2="2.8" width="0.2032" layer="94"/>
<wire x1="1.8" y1="1.6" x2="3" y2="2.8" width="0.2032" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="A" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="K" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="SW-PUSH"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.2032" layer="94"/>
<wire x1="0" y1="1.27" x2="0" y2="2.54" width="0.2032" layer="94"/>
<wire x1="-2.54" y1="0" x2="-1.27" y2="0" width="0.2032" layer="94"/>
<wire x1="1.27" y1="0" x2="2.54" y2="0" width="0.2032" layer="94"/>
<text x="-3.81" y="3.54" size="1.778" layer="95">&gt;NAME</text>
<text x="-3.81" y="-5.14" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="TP"><circle x="0" y="0" radius="1.27" width="0.2032" layer="94"/>
<text x="-1.27" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-1.27" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="0" y="-3.81" visible="pin" length="short" direction="pas" rot="R90"/></symbol>
<symbol name="HDR-2X5"><wire x1="-6.35" y1="7.62" x2="6.35" y2="7.62" width="0.4064" layer="94"/>
<wire x1="6.35" y1="7.62" x2="6.35" y2="-7.62" width="0.4064" layer="94"/>
<wire x1="6.35" y1="-7.62" x2="-6.35" y2="-7.62" width="0.4064" layer="94"/>
<wire x1="-6.35" y1="-7.62" x2="-6.35" y2="7.62" width="0.4064" layer="94"/>
<text x="-6.35" y="8.62" size="1.778" layer="95">&gt;NAME</text>
<text x="-6.35" y="-10.22" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-11.43" y="5.08" visible="pin" length="middle" rot="R0"/>
<pin name="3" x="-11.43" y="2.54" visible="pin" length="middle" rot="R0"/>
<pin name="5" x="-11.43" y="0" visible="pin" length="middle" rot="R0"/>
<pin name="7" x="-11.43" y="-2.54" visible="pin" length="middle" rot="R0"/>
<pin name="9" x="-11.43" y="-5.08" visible="pin" length="middle" rot="R0"/>
<pin name="2" x="11.43" y="5.08" visible="pin" length="middle" rot="R180"/>
<pin name="4" x="11.43" y="2.54" visible="pin" length="middle" rot="R180"/>
<pin name="6" x="11.43" y="0" visible="pin" length="middle" rot="R180"/>
<pin name="8" x="11.43" y="-2.54" visible="pin" length="middle" rot="R180"/>
<pin name="10" x="11.43" y="-5.08" visible="pin" length="middle" rot="R180"/></symbol>
<symbol name="ACDC-4"><wire x1="-12.7" y1="3.81" x2="12.7" y2="3.81" width="0.4064" layer="94"/>
<wire x1="12.7" y1="3.81" x2="12.7" y2="-3.81" width="0.4064" layer="94"/>
<wire x1="12.7" y1="-3.81" x2="-12.7" y2="-3.81" width="0.4064" layer="94"/>
<wire x1="-12.7" y1="-3.81" x2="-12.7" y2="3.81" width="0.4064" layer="94"/>
<text x="-12.7" y="4.81" size="1.778" layer="95">&gt;NAME</text>
<text x="-12.7" y="-6.41" size="1.778" layer="96">&gt;VALUE</text>
<text x="-8" y="0" size="1.6" layer="94" ratio="10">AC / DC</text>
<text x="-8" y="-2.6" size="1.3" layer="94" ratio="10">isolated</text>
<pin name="AC-L" x="-12.7" y="1.27" visible="pin" length="middle" rot="R0"/>
<pin name="AC-N" x="-12.7" y="-1.27" visible="pin" length="middle" rot="R0"/>
<pin name="+VO" x="12.7" y="1.27" visible="pin" length="middle" rot="R180"/>
<pin name="-VO" x="12.7" y="-1.27" visible="pin" length="middle" rot="R180"/></symbol>
<symbol name="BUCK-3V3"><wire x1="-10.16" y1="3.81" x2="10.16" y2="3.81" width="0.4064" layer="94"/>
<wire x1="10.16" y1="3.81" x2="10.16" y2="-3.81" width="0.4064" layer="94"/>
<wire x1="10.16" y1="-3.81" x2="-10.16" y2="-3.81" width="0.4064" layer="94"/>
<wire x1="-10.16" y1="-3.81" x2="-10.16" y2="3.81" width="0.4064" layer="94"/>
<text x="-10.16" y="4.81" size="1.778" layer="95">&gt;NAME</text>
<text x="-10.16" y="-6.41" size="1.778" layer="96">&gt;VALUE</text>
<text x="-7.6" y="0" size="1.5" layer="94" ratio="10">LM2576</text>
<pin name="VIN" x="-10.16" y="1.27" visible="pin" length="middle" rot="R0"/>
<pin name="FB" x="-10.16" y="-1.27" visible="pin" length="middle" rot="R0"/>
<pin name="VOUT" x="10.16" y="1.27" visible="pin" length="middle" rot="R180"/>
<pin name="ONOFF" x="10.16" y="-1.27" visible="pin" length="middle" rot="R180"/>
<pin name="GND" x="0" y="-3.81" visible="pin" length="middle" rot="R90"/></symbol>
<symbol name="DIODE"><wire x1="-3.81" y1="2.54" x2="3.81" y2="2.54" width="0.254" layer="94"/>
<wire x1="3.81" y1="2.54" x2="3.81" y2="-2.54" width="0.254" layer="94"/>
<wire x1="3.81" y1="-2.54" x2="-3.81" y2="-2.54" width="0.254" layer="94"/>
<wire x1="-3.81" y1="-2.54" x2="-3.81" y2="2.54" width="0.254" layer="94"/>
<wire x1="-1.27" y1="1.27" x2="-1.27" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-1.27" y1="0" x2="1.27" y2="1.27" width="0.254" layer="94"/>
<wire x1="1.27" y1="1.27" x2="1.27" y2="-1.27" width="0.254" layer="94"/>
<wire x1="1.27" y1="-1.27" x2="-1.27" y2="0" width="0.254" layer="94"/>
<text x="-3.81" y="3.54" size="1.778" layer="95">&gt;NAME</text>
<text x="-3.81" y="-5.14" size="1.778" layer="96">&gt;VALUE</text>
<pin name="A" x="-7.62" y="0" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="K" x="7.62" y="0" visible="pin" length="middle" direction="pas" rot="R180"/></symbol>
<symbol name="INDUCTOR"><wire x1="-5.08" y1="2.54" x2="5.08" y2="2.54" width="0.254" layer="94"/>
<wire x1="5.08" y1="2.54" x2="5.08" y2="-2.54" width="0.254" layer="94"/>
<wire x1="5.08" y1="-2.54" x2="-5.08" y2="-2.54" width="0.254" layer="94"/>
<wire x1="-5.08" y1="-2.54" x2="-5.08" y2="2.54" width="0.254" layer="94"/>
<circle x="-2.54" y="0.9" radius="1.27" width="0.254" layer="94"/>
<circle x="0" y="0.9" radius="1.27" width="0.254" layer="94"/>
<circle x="2.54" y="0.9" radius="1.27" width="0.254" layer="94"/>
<text x="-5.08" y="3.54" size="1.778" layer="95">&gt;NAME</text>
<text x="-5.08" y="-5.14" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-10.16" y="0" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="2" x="10.16" y="0" visible="pin" length="middle" direction="pas" rot="R180"/></symbol>
<symbol name="TERM-3"><wire x1="-7.62" y1="8.89" x2="7.62" y2="8.89" width="0.4064" layer="94"/>
<wire x1="7.62" y1="8.89" x2="7.62" y2="-8.89" width="0.4064" layer="94"/>
<wire x1="7.62" y1="-8.89" x2="-7.62" y2="-8.89" width="0.4064" layer="94"/>
<wire x1="-7.62" y1="-8.89" x2="-7.62" y2="8.89" width="0.4064" layer="94"/>
<text x="-7.62" y="9.89" size="1.778" layer="95">&gt;NAME</text>
<text x="-7.62" y="-11.49" size="1.778" layer="96">&gt;VALUE</text>
<text x="-4.5" y="0" size="1.5" layer="94" ratio="10">TB3</text>
<pin name="1" x="-7.62" y="5.08" visible="pin" length="middle" rot="R0"/>
<pin name="2" x="-7.62" y="0" visible="pin" length="middle" rot="R0"/>
<pin name="3" x="-7.62" y="-5.08" visible="pin" length="middle" rot="R0"/></symbol>
<symbol name="PI40"><wire x1="-15.24" y1="26.67" x2="15.24" y2="26.67" width="0.4064" layer="94"/>
<wire x1="15.24" y1="26.67" x2="15.24" y2="-26.67" width="0.4064" layer="94"/>
<wire x1="15.24" y1="-26.67" x2="-15.24" y2="-26.67" width="0.4064" layer="94"/>
<wire x1="-15.24" y1="-26.67" x2="-15.24" y2="26.67" width="0.4064" layer="94"/>
<text x="-15.24" y="27.67" size="1.778" layer="95">&gt;NAME</text>
<text x="-15.24" y="-29.27" size="1.778" layer="96">&gt;VALUE</text>
<text x="-12" y="0" size="1.5" layer="94" ratio="10">Raspberry Pi</text>
<text x="-12" y="-2.6" size="1.2" layer="94" ratio="10">Zero 2 W GPIO</text>
<pin name="3V3" x="-15.24" y="24.13" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GPIO2" x="-15.24" y="21.59" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GPIO3" x="-15.24" y="19.05" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GPIO4" x="-15.24" y="16.51" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GND" x="-15.24" y="13.97" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GPIO17" x="-15.24" y="11.43" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GPIO27" x="-15.24" y="8.89" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GPIO22" x="-15.24" y="6.35" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="3V3_17" x="-15.24" y="3.81" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GPIO10" x="-15.24" y="1.27" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GPIO9" x="-15.24" y="-1.27" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GPIO11" x="-15.24" y="-3.81" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GND_25" x="-15.24" y="-6.35" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GPIO0" x="-15.24" y="-8.89" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GPIO5" x="-15.24" y="-11.43" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GPIO6" x="-15.24" y="-13.97" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GPIO13" x="-15.24" y="-16.51" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GPIO19" x="-15.24" y="-19.05" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GPIO26" x="-15.24" y="-21.59" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GND_39" x="-15.24" y="-24.13" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="5V" x="15.24" y="24.13" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="5V_4" x="15.24" y="21.59" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GND_6" x="15.24" y="19.05" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GPIO14" x="15.24" y="16.51" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GPIO15" x="15.24" y="13.97" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GPIO18" x="15.24" y="11.43" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GND_14" x="15.24" y="8.89" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GPIO23" x="15.24" y="6.35" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GPIO24" x="15.24" y="3.81" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GND_20" x="15.24" y="1.27" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GPIO25" x="15.24" y="-1.27" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GPIO8" x="15.24" y="-3.81" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GPIO7" x="15.24" y="-6.35" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GPIO1" x="15.24" y="-8.89" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GND_30" x="15.24" y="-11.43" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GPIO12" x="15.24" y="-13.97" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GND_34" x="15.24" y="-16.51" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GPIO16" x="15.24" y="-19.05" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GPIO20" x="15.24" y="-21.59" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GPIO21" x="15.24" y="-24.13" visible="pin" length="middle" direction="pas" rot="R180"/></symbol>
<symbol name="PLCSTAMP"><wire x1="-15.24" y1="15.24" x2="15.24" y2="15.24" width="0.4064" layer="94"/>
<wire x1="15.24" y1="15.24" x2="15.24" y2="-15.24" width="0.4064" layer="94"/>
<wire x1="15.24" y1="-15.24" x2="-15.24" y2="-15.24" width="0.4064" layer="94"/>
<wire x1="-15.24" y1="-15.24" x2="-15.24" y2="15.24" width="0.4064" layer="94"/>
<text x="-15.24" y="16.24" size="1.778" layer="95">&gt;NAME</text>
<text x="-15.24" y="-17.84" size="1.778" layer="96">&gt;VALUE</text>
<text x="-11.5" y="0" size="1.5" layer="94" ratio="10">PLC Stamp mini 2</text>
<text x="-11.5" y="-2.6" size="1.2" layer="94" ratio="10">QCA7005 Green PHY</text>
<pin name="GPIO_0" x="-15.24" y="12.7" visible="pin" length="middle" rot="R0"/>
<pin name="GPIO_1" x="-15.24" y="10.16" visible="pin" length="middle" rot="R0"/>
<pin name="GPIO_2" x="-15.24" y="7.62" visible="pin" length="middle" rot="R0"/>
<pin name="GPIO_3" x="-15.24" y="5.08" visible="pin" length="middle" rot="R0"/>
<pin name="RESET_L" x="-15.24" y="2.54" visible="pin" length="middle" rot="R0"/>
<pin name="SERIAL_4" x="-15.24" y="0" visible="pin" length="middle" rot="R0"/>
<pin name="SERIAL_3" x="-15.24" y="-2.54" visible="pin" length="middle" rot="R0"/>
<pin name="SERIAL_2" x="-15.24" y="-5.08" visible="pin" length="middle" rot="R0"/>
<pin name="SERIAL_1" x="-15.24" y="-7.62" visible="pin" length="middle" rot="R0"/>
<pin name="SERIAL_0" x="-15.24" y="-10.16" visible="pin" length="middle" rot="R0"/>
<pin name="ZC_IN" x="-15.24" y="-12.7" visible="pin" length="middle" rot="R0"/>
<pin name="VDD" x="15.24" y="12.7" visible="pin" length="middle" rot="R180"/>
<pin name="N" x="15.24" y="10.16" visible="pin" length="middle" rot="R180"/>
<pin name="L" x="15.24" y="7.62" visible="pin" length="middle" rot="R180"/>
<pin name="GND" x="0" y="-15.24" visible="pin" length="middle" rot="R90"/></symbol>
<symbol name="WIZ850IO"><wire x1="-11.43" y1="8.89" x2="11.43" y2="8.89" width="0.4064" layer="94"/>
<wire x1="11.43" y1="8.89" x2="11.43" y2="-8.89" width="0.4064" layer="94"/>
<wire x1="11.43" y1="-8.89" x2="-11.43" y2="-8.89" width="0.4064" layer="94"/>
<wire x1="-11.43" y1="-8.89" x2="-11.43" y2="8.89" width="0.4064" layer="94"/>
<text x="-11.43" y="9.89" size="1.778" layer="95">&gt;NAME</text>
<text x="-11.43" y="-11.49" size="1.778" layer="96">&gt;VALUE</text>
<text x="-8.5" y="0" size="1.5" layer="94" ratio="10">WIZ850io</text>
<text x="-8.5" y="-2.6" size="1.2" layer="94" ratio="10">W5500 + magjack</text>
<pin name="MOSI" x="-11.43" y="6.35" visible="pin" length="middle" rot="R0"/>
<pin name="SCLK" x="-11.43" y="3.81" visible="pin" length="middle" rot="R0"/>
<pin name="!SCS" x="-11.43" y="1.27" visible="pin" length="middle" rot="R0"/>
<pin name="!INT" x="-11.43" y="-1.27" visible="pin" length="middle" rot="R0"/>
<pin name="!RST" x="-11.43" y="-3.81" visible="pin" length="middle" rot="R0"/>
<pin name="MISO" x="-11.43" y="-6.35" visible="pin" length="middle" rot="R0"/>
<pin name="3V3" x="11.43" y="6.35" visible="pin" length="middle" rot="R180"/>
<pin name="NC" x="11.43" y="3.81" visible="pin" length="middle" rot="R180"/>
<pin name="GND" x="0" y="-8.89" visible="pin" length="middle" rot="R90"/></symbol></symbols>
<devicesets><deviceset name="R-EU" prefix="R"><gates><gate name="G$1" symbol="R-EU" x="0" y="0"/></gates>
<devices><device package="R-7.62"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="C-EU" prefix="C"><gates><gate name="G$1" symbol="C-EU" x="0" y="0"/></gates>
<devices><device package="C-5.08"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="CPOL-EU" prefix="C"><gates><gate name="G$1" symbol="CPOL-EU" x="0" y="0"/></gates>
<devices><device package="CP-D10-P5"><connects><connect gate="G$1" pin="+" pad="+"/>
<connect gate="G$1" pin="-" pad="-"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="CPOL-SMALL" prefix="C"><gates><gate name="G$1" symbol="CPOL-EU" x="0" y="0"/></gates>
<devices><device package="CP-D6.3-P2.5"><connects><connect gate="G$1" pin="+" pad="+"/>
<connect gate="G$1" pin="-" pad="-"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="FERRITE" prefix="FB"><gates><gate name="G$1" symbol="FERRITE" x="0" y="0"/></gates>
<devices><device package="FB-7.62"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="FUSE" prefix="F"><gates><gate name="G$1" symbol="FUSE" x="0" y="0"/></gates>
<devices><device package="FUSE-RADIAL"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="MOV" prefix="MOV"><gates><gate name="G$1" symbol="MOV" x="0" y="0"/></gates>
<devices><device package="MOV07"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="LED" prefix="LED"><gates><gate name="G$1" symbol="LED" x="0" y="0"/></gates>
<devices><device package="LED-5MM"><connects><connect gate="G$1" pin="A" pad="1"/>
<connect gate="G$1" pin="K" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="SW-PUSH" prefix="SW"><gates><gate name="G$1" symbol="SW-PUSH" x="0" y="0"/></gates>
<devices><device package="SW-TACT-6MM"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="TP" prefix="TP"><gates><gate name="G$1" symbol="TP" x="0" y="0"/></gates>
<devices><device package="TP"><connects><connect gate="G$1" pin="1" pad="1"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="MOUNT-M3" prefix="H"><gates></gates>
<devices><device package="MOUNT-M3"><connects></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="HDR-2X5" prefix="J"><gates><gate name="G$1" symbol="HDR-2X5" x="0" y="0"/></gates>
<devices><device package="HDR-2X5"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/>
<connect gate="G$1" pin="3" pad="3"/>
<connect gate="G$1" pin="4" pad="4"/>
<connect gate="G$1" pin="5" pad="5"/>
<connect gate="G$1" pin="6" pad="6"/>
<connect gate="G$1" pin="7" pad="7"/>
<connect gate="G$1" pin="8" pad="8"/>
<connect gate="G$1" pin="9" pad="9"/>
<connect gate="G$1" pin="10" pad="10"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="ACDC-12V" prefix="PS"><gates><gate name="G$1" symbol="ACDC-4" x="0" y="0"/></gates>
<devices><device package="MPM2012"><connects><connect gate="G$1" pin="AC-N" pad="1"/>
<connect gate="G$1" pin="AC-L" pad="2"/>
<connect gate="G$1" pin="+VO" pad="3"/>
<connect gate="G$1" pin="-VO" pad="4"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="BUCK-3V3" prefix="U"><gates><gate name="G$1" symbol="BUCK-3V3" x="0" y="0"/></gates>
<devices><device package="LM2576S"><connects><connect gate="G$1" pin="VIN" pad="1"/>
<connect gate="G$1" pin="VOUT" pad="2"/>
<connect gate="G$1" pin="GND" pad="3 3_2 P7 P8 P9 P10"/>
<connect gate="G$1" pin="FB" pad="4"/>
<connect gate="G$1" pin="ONOFF" pad="5"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="BUCK-5V" prefix="U"><gates><gate name="G$1" symbol="BUCK-3V3" x="0" y="0"/></gates>
<devices><device package="LM2576S"><connects><connect gate="G$1" pin="VIN" pad="1"/>
<connect gate="G$1" pin="VOUT" pad="2"/>
<connect gate="G$1" pin="GND" pad="3 3_2 P7 P8 P9 P10"/>
<connect gate="G$1" pin="FB" pad="4"/>
<connect gate="G$1" pin="ONOFF" pad="5"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="DIODE-SCH" prefix="D"><gates><gate name="G$1" symbol="DIODE" x="0" y="0"/></gates>
<devices><device package="DO41"><connects><connect gate="G$1" pin="A" pad="A"/>
<connect gate="G$1" pin="K" pad="K"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="L-RADIAL" prefix="L"><gates><gate name="G$1" symbol="INDUCTOR" x="0" y="0"/></gates>
<devices><device package="LRAD12"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="TERM-3" prefix="J"><gates><gate name="G$1" symbol="TERM-3" x="0" y="0"/></gates>
<devices><device package="CUI_TB003"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/>
<connect gate="G$1" pin="3" pad="3"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="R-0603" prefix="R"><gates><gate name="G$1" symbol="R-EU" x="0" y="0"/></gates>
<devices><device package="R0603"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="C-0603" prefix="C"><gates><gate name="G$1" symbol="C-EU" x="0" y="0"/></gates>
<devices><device package="C0603"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="PLC-STAMP-MINI-2" prefix="U"><gates><gate name="G$1" symbol="PLCSTAMP" x="0" y="0"/></gates>
<devices><device package="PLCSTAMP"><connects><connect gate="G$1" pin="GPIO_0" pad="1"/>
<connect gate="G$1" pin="GPIO_1" pad="2"/>
<connect gate="G$1" pin="GPIO_2" pad="3"/>
<connect gate="G$1" pin="GPIO_3" pad="4"/>
<connect gate="G$1" pin="RESET_L" pad="5"/>
<connect gate="G$1" pin="SERIAL_4" pad="6"/>
<connect gate="G$1" pin="SERIAL_3" pad="7"/>
<connect gate="G$1" pin="SERIAL_2" pad="8"/>
<connect gate="G$1" pin="SERIAL_1" pad="9"/>
<connect gate="G$1" pin="SERIAL_0" pad="10"/>
<connect gate="G$1" pin="GND" pad="11 18 19 20 21 22 23 24 25"/>
<connect gate="G$1" pin="VDD" pad="12"/>
<connect gate="G$1" pin="ZC_IN" pad="13"/>
<connect gate="G$1" pin="N" pad="15"/>
<connect gate="G$1" pin="L" pad="16 17"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="WIZ850IO" prefix="U"><gates><gate name="G$1" symbol="WIZ850IO" x="0" y="0"/></gates>
<devices><device package="WIZ850IO"><connects><connect gate="G$1" pin="GND" pad="1 2 7"/>
<connect gate="G$1" pin="MOSI" pad="3"/>
<connect gate="G$1" pin="SCLK" pad="4"/>
<connect gate="G$1" pin="!SCS" pad="5"/>
<connect gate="G$1" pin="!INT" pad="6"/>
<connect gate="G$1" pin="3V3" pad="8 9"/>
<connect gate="G$1" pin="NC" pad="10"/>
<connect gate="G$1" pin="!RST" pad="11"/>
<connect gate="G$1" pin="MISO" pad="12"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="PI-ZERO-SOCKET" prefix="J"><gates><gate name="G$1" symbol="PI40" x="0" y="0"/></gates>
<devices><device package="PIZERO"><connects><connect gate="G$1" pin="3V3" pad="1"/>
<connect gate="G$1" pin="5V" pad="2"/>
<connect gate="G$1" pin="GPIO2" pad="3"/>
<connect gate="G$1" pin="5V_4" pad="4"/>
<connect gate="G$1" pin="GPIO3" pad="5"/>
<connect gate="G$1" pin="GND_6" pad="6"/>
<connect gate="G$1" pin="GPIO4" pad="7"/>
<connect gate="G$1" pin="GPIO14" pad="8"/>
<connect gate="G$1" pin="GND" pad="9"/>
<connect gate="G$1" pin="GPIO15" pad="10"/>
<connect gate="G$1" pin="GPIO17" pad="11"/>
<connect gate="G$1" pin="GPIO18" pad="12"/>
<connect gate="G$1" pin="GPIO27" pad="13"/>
<connect gate="G$1" pin="GND_14" pad="14"/>
<connect gate="G$1" pin="GPIO22" pad="15"/>
<connect gate="G$1" pin="GPIO23" pad="16"/>
<connect gate="G$1" pin="3V3_17" pad="17"/>
<connect gate="G$1" pin="GPIO24" pad="18"/>
<connect gate="G$1" pin="GPIO10" pad="19"/>
<connect gate="G$1" pin="GND_20" pad="20"/>
<connect gate="G$1" pin="GPIO9" pad="21"/>
<connect gate="G$1" pin="GPIO25" pad="22"/>
<connect gate="G$1" pin="GPIO11" pad="23"/>
<connect gate="G$1" pin="GPIO8" pad="24"/>
<connect gate="G$1" pin="GND_25" pad="25"/>
<connect gate="G$1" pin="GPIO7" pad="26"/>
<connect gate="G$1" pin="GPIO0" pad="27"/>
<connect gate="G$1" pin="GPIO1" pad="28"/>
<connect gate="G$1" pin="GPIO5" pad="29"/>
<connect gate="G$1" pin="GND_30" pad="30"/>
<connect gate="G$1" pin="GPIO6" pad="31"/>
<connect gate="G$1" pin="GPIO12" pad="32"/>
<connect gate="G$1" pin="GPIO13" pad="33"/>
<connect gate="G$1" pin="GND_34" pad="34"/>
<connect gate="G$1" pin="GPIO19" pad="35"/>
<connect gate="G$1" pin="GPIO16" pad="36"/>
<connect gate="G$1" pin="GPIO26" pad="37"/>
<connect gate="G$1" pin="GPIO20" pad="38"/>
<connect gate="G$1" pin="GND_39" pad="39"/>
<connect gate="G$1" pin="GPIO21" pad="40"/></connects>
<technologies><technology/></technologies></device></devices></deviceset></devicesets></library></libraries>
<attributes/>
<variantdefs/>
<classes><class number="0" name="default" width="0.3048" drill="0"/>
<class number="1" name="mains" width="2.5" drill="0"><clearance class="0" value="8"/>
<clearance class="1" value="8"/>
<clearance class="2" value="8"/></class>
<class number="2" name="power" width="1" drill="0"><clearance class="0" value="0.5"/>
<clearance class="2" value="0.6"/></class></classes>
<parts><part name="J1" library="pi-wall-socket" deviceset="TERM-3" value="MAINS IN"/>
<part name="F1" library="pi-wall-socket" deviceset="FUSE" value="T1A/250V"/>
<part name="MOV1" library="pi-wall-socket" deviceset="MOV" value="S07K275"/>
<part name="PS1" library="pi-wall-socket" deviceset="ACDC-12V" value="MPM-20-12"/>
<part name="FB1" library="pi-wall-socket" deviceset="FERRITE" value="600R@100MHz"/>
<part name="C1" library="pi-wall-socket" deviceset="CPOL-EU" value="470uF/10V"/>
<part name="TP1" library="pi-wall-socket" deviceset="TP" value="+5V"/>
<part name="TP2" library="pi-wall-socket" deviceset="TP" value="GND"/>
<part name="TP3" library="pi-wall-socket" deviceset="TP" value="PE"/>
<part name="U1" library="pi-wall-socket" deviceset="BUCK-5V" value="LM2576S-5.0"/>
<part name="L1" library="pi-wall-socket" deviceset="L-RADIAL" value="47uH/3A"/>
<part name="D1" library="pi-wall-socket" deviceset="DIODE-SCH" value="SS34"/>
<part name="C2" library="pi-wall-socket" deviceset="CPOL-EU" value="470uF/25V"/>
<part name="C3" library="pi-wall-socket" deviceset="CPOL-EU" value="330uF/10V"/>
<part name="C4" library="pi-wall-socket" deviceset="C-0603" value="100nF"/>
<part name="TP4" library="pi-wall-socket" deviceset="TP" value="+5V"/>
<part name="U2" library="pi-wall-socket" deviceset="BUCK-3V3" value="LM2576S-3.3"/>
<part name="L2" library="pi-wall-socket" deviceset="L-RADIAL" value="100uH/3A"/>
<part name="D2" library="pi-wall-socket" deviceset="DIODE-SCH" value="SS34"/>
<part name="C5" library="pi-wall-socket" deviceset="CPOL-EU" value="470uF/25V"/>
<part name="C6" library="pi-wall-socket" deviceset="CPOL-EU" value="220uF/10V"/>
<part name="C7" library="pi-wall-socket" deviceset="C-0603" value="100nF"/>
<part name="TP5" library="pi-wall-socket" deviceset="TP" value="+3V3"/>
<part name="R1" library="pi-wall-socket" deviceset="R-EU" value="1k0"/>
<part name="LED1" library="pi-wall-socket" deviceset="LED" value="PWR green"/>
<part name="J2" library="pi-wall-socket" deviceset="PI-ZERO-SOCKET" value="Pi Zero 2 W"/>
<part name="U3" library="pi-wall-socket" deviceset="PLC-STAMP-MINI-2" value="I2PLCBMN-ISC-004-T"/>
<part name="R3" library="pi-wall-socket" deviceset="R-EU" value="3k3"/>
<part name="LED2" library="pi-wall-socket" deviceset="LED" value="PLC link"/>
<part name="R4" library="pi-wall-socket" deviceset="R-EU" value="3k3"/>
<part name="LED3" library="pi-wall-socket" deviceset="LED" value="PAIR amber"/>
<part name="R5" library="pi-wall-socket" deviceset="R-EU" value="10k"/>
<part name="R6" library="pi-wall-socket" deviceset="R-EU" value="100R"/>
<part name="C8" library="pi-wall-socket" deviceset="C-EU" value="100pF"/>
<part name="SW3" library="pi-wall-socket" deviceset="SW-PUSH" value="PAIR"/>
<part name="R7" library="pi-wall-socket" deviceset="R-EU" value="10k"/>
<part name="TP6" library="pi-wall-socket" deviceset="TP" value="PLC RESET"/>
<part name="U4" library="pi-wall-socket" deviceset="WIZ850IO" value="WIZ850io"/>
<part name="R8" library="pi-wall-socket" deviceset="R-EU" value="10k"/>
<part name="C9" library="pi-wall-socket" deviceset="C-0603" value="100nF"/>
<part name="J3" library="pi-wall-socket" deviceset="HDR-2X5" value="GPIO/UART"/></parts>
<sheets><sheet><plain><text x="20" y="492" size="3.4" layer="97" ratio="8">Pi Wall Socket — Raspberry Pi Zero 2 W carrier for a wall-socket enclosure: 12 V mains supply, wired Ethernet and Ethernet-over-powerline</text>
<text x="20" y="484" size="2.2" layer="97" ratio="8">MAINS (row A): L → F1 → PS1.2 (MPM-20-12 AC/L) and U3 pin 16/17 (L); N → PS1.1 (AC/N) and U3 pin 15 (N); MOV1 across L-N after the fuse.</text>
<text x="20" y="479" size="2.2" layer="97" ratio="8">PE lands on J1.3 and TP3 only — it is never bonded to SELV ground on this PCB.</text>
<text x="20" y="474" size="2.2" layer="97" ratio="8">POWER TREE: 12 V → U1 LM2576S-5.0 → Pi header pins 2/4 (the Zero 2 W takes ≈3 W max); 12 V → U2 LM2576S-3.3 → modem, WIZ850io, straps.</text>
<text x="20" y="469" size="2.2" layer="97" ratio="8">Header pins 1/17 are the Pi's own 3.3 V output (≈50 mA). They are left open, not paralleled with U2.</text>
<text x="20" y="300" size="2.2" layer="97" ratio="8">SPI1 → U3 (the Green PHY modem is a SPI slave: mode 3, burst CS, max 12 MHz). Raspberry Pi OS needs dtoverlay=spi1-3cs.</text>
<text x="20" y="295" size="2.2" layer="97" ratio="8">SPI0 → U4 (WIZ850io = W5500 + magnetics + RJ45, so no analogue design on this board).</text>
<text x="20" y="290" size="2.2" layer="97" ratio="8">U3 is the CE Class B / North America variant: transformer 1:4:5 and zero-cross detection on the module, pin 13 floating. Automotive variants are NOT for mains (datasheet §12.2).</text>
<text x="20" y="285" size="2.2" layer="97" ratio="8">Isolation is inside U3: 4000 Vac, 8 mm creepage / 6.5 mm clearance between L/N and everything else (§8.3). This board keeps 8.0 mm, checked by --check.</text>
<text x="20" y="190" size="2.2" layer="97" ratio="8">BOOTSTRAP (row F): GPIO_0 and GPIO_1 are read at boot, so their LEDs use the 3.3 kΩ series resistors of datasheet figure 3; GPIO_3 is the pushbutton input</text>
<text x="20" y="185" size="2.2" layer="97" ratio="8">with the 100 Ω / 10 kΩ / 100 pF network of figure 4. After boot GPIO_0 = PLC link, GPIO_1 = Simple Connect blink (1 Hz), GPIO_2 unused.</text>
<text x="20" y="110" size="2.2" layer="97" ratio="8">CONSOLE (row G / J3): UART0 on GPIO14/GPIO15 is how the board is provisioned; the Pi has no display connector in a socket box.</text>
<frame x1="0" y1="0" x2="520" y2="500" columns="8" rows="6" layer="91" border-left="yes" border-top="yes" border-right="yes" border-bottom="yes"/>
<text x="330" y="8" size="2.2" layer="97">Pi Wall Socket rev A · sheet 1/1 · generated from tools/pi-socket-model.mjs · see docs/wimax-pi-powerline-variants-2026-10-08.md</text></plain>
<instances><instance part="J1" gate="G$1" x="45" y="470" smashed="yes" rot="R0"><attribute name="NAME" x="37.38" y="481.16" size="1.778" layer="95"/>
<attribute name="VALUE" x="37.38" y="455.97" size="1.778" layer="96"/></instance>
<instance part="F1" gate="G$1" x="125" y="470" smashed="yes" rot="R0"><attribute name="NAME" x="119.92" y="473.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="119.92" y="463.59" size="1.778" layer="96"/></instance>
<instance part="MOV1" gate="G$1" x="205" y="470" smashed="yes" rot="R0"><attribute name="NAME" x="199.92" y="473.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="199.92" y="463.59" size="1.778" layer="96"/></instance>
<instance part="PS1" gate="G$1" x="285" y="470" smashed="yes" rot="R0"><attribute name="NAME" x="272.3" y="476.08" size="1.778" layer="95"/>
<attribute name="VALUE" x="272.3" y="461.05" size="1.778" layer="96"/></instance>
<instance part="FB1" gate="G$1" x="45" y="420" smashed="yes" rot="R0"><attribute name="NAME" x="39.92" y="423.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="39.92" y="413.59" size="1.778" layer="96"/></instance>
<instance part="C1" gate="G$1" x="105" y="420" smashed="yes" rot="R0"><attribute name="NAME" x="99.92" y="423.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="99.92" y="413.59" size="1.778" layer="96"/></instance>
<instance part="TP1" gate="G$1" x="165" y="420" smashed="yes" rot="R0"><attribute name="NAME" x="163.73" y="423.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="163.73" y="413.59" size="1.778" layer="96"/></instance>
<instance part="TP2" gate="G$1" x="215" y="420" smashed="yes" rot="R0"><attribute name="NAME" x="213.73" y="423.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="213.73" y="413.59" size="1.778" layer="96"/></instance>
<instance part="TP3" gate="G$1" x="365" y="470" smashed="yes" rot="R0"><attribute name="NAME" x="363.73" y="473.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="363.73" y="463.59" size="1.778" layer="96"/></instance>
<instance part="U1" gate="G$1" x="50" y="370" smashed="yes" rot="R0"><attribute name="NAME" x="39.84" y="376.08" size="1.778" layer="95"/>
<attribute name="VALUE" x="39.84" y="361.05" size="1.778" layer="96"/></instance>
<instance part="L1" gate="G$1" x="130" y="370" smashed="yes" rot="R0"><attribute name="NAME" x="119.84" y="374.81" size="1.778" layer="95"/>
<attribute name="VALUE" x="119.84" y="362.32" size="1.778" layer="96"/></instance>
<instance part="D1" gate="G$1" x="200" y="370" smashed="yes" rot="R0"><attribute name="NAME" x="192.38" y="374.81" size="1.778" layer="95"/>
<attribute name="VALUE" x="192.38" y="362.32" size="1.778" layer="96"/></instance>
<instance part="C2" gate="G$1" x="265" y="370" smashed="yes" rot="R0"><attribute name="NAME" x="259.92" y="373.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="259.92" y="363.59" size="1.778" layer="96"/></instance>
<instance part="C3" gate="G$1" x="325" y="370" smashed="yes" rot="R0"><attribute name="NAME" x="319.92" y="373.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="319.92" y="363.59" size="1.778" layer="96"/></instance>
<instance part="C4" gate="G$1" x="385" y="370" smashed="yes" rot="R0"><attribute name="NAME" x="379.92" y="373.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="379.92" y="363.59" size="1.778" layer="96"/></instance>
<instance part="TP4" gate="G$1" x="440" y="370" smashed="yes" rot="R0"><attribute name="NAME" x="438.73" y="373.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="438.73" y="363.59" size="1.778" layer="96"/></instance>
<instance part="U2" gate="G$1" x="50" y="320" smashed="yes" rot="R0"><attribute name="NAME" x="39.84" y="326.08" size="1.778" layer="95"/>
<attribute name="VALUE" x="39.84" y="311.05" size="1.778" layer="96"/></instance>
<instance part="L2" gate="G$1" x="130" y="320" smashed="yes" rot="R0"><attribute name="NAME" x="119.84" y="324.81" size="1.778" layer="95"/>
<attribute name="VALUE" x="119.84" y="312.32" size="1.778" layer="96"/></instance>
<instance part="D2" gate="G$1" x="200" y="320" smashed="yes" rot="R0"><attribute name="NAME" x="192.38" y="324.81" size="1.778" layer="95"/>
<attribute name="VALUE" x="192.38" y="312.32" size="1.778" layer="96"/></instance>
<instance part="C5" gate="G$1" x="265" y="320" smashed="yes" rot="R0"><attribute name="NAME" x="259.92" y="323.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="259.92" y="313.59" size="1.778" layer="96"/></instance>
<instance part="C6" gate="G$1" x="325" y="320" smashed="yes" rot="R0"><attribute name="NAME" x="319.92" y="323.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="319.92" y="313.59" size="1.778" layer="96"/></instance>
<instance part="C7" gate="G$1" x="385" y="320" smashed="yes" rot="R0"><attribute name="NAME" x="379.92" y="323.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="379.92" y="313.59" size="1.778" layer="96"/></instance>
<instance part="TP5" gate="G$1" x="440" y="320" smashed="yes" rot="R0"><attribute name="NAME" x="438.73" y="323.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="438.73" y="313.59" size="1.778" layer="96"/></instance>
<instance part="R1" gate="G$1" x="45" y="80" smashed="yes" rot="R0"><attribute name="NAME" x="39.92" y="83.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="39.92" y="73.59" size="1.778" layer="96"/></instance>
<instance part="LED1" gate="G$1" x="100" y="80" smashed="yes" rot="R0"><attribute name="NAME" x="94.92" y="84.07" size="1.778" layer="95"/>
<attribute name="VALUE" x="94.92" y="73.59" size="1.778" layer="96"/></instance>
<instance part="J2" gate="G$1" x="70" y="240" smashed="yes" rot="R0"><attribute name="NAME" x="54.76" y="268.94" size="1.778" layer="95"/>
<attribute name="VALUE" x="54.76" y="208.19" size="1.778" layer="96"/></instance>
<instance part="U3" gate="G$1" x="180" y="240" smashed="yes" rot="R0"><attribute name="NAME" x="164.76" y="257.51" size="1.778" layer="95"/>
<attribute name="VALUE" x="164.76" y="219.62" size="1.778" layer="96"/></instance>
<instance part="R3" gate="G$1" x="45" y="150" smashed="yes" rot="R0"><attribute name="NAME" x="39.92" y="153.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="39.92" y="143.59" size="1.778" layer="96"/></instance>
<instance part="LED2" gate="G$1" x="100" y="150" smashed="yes" rot="R0"><attribute name="NAME" x="94.92" y="154.07" size="1.778" layer="95"/>
<attribute name="VALUE" x="94.92" y="143.59" size="1.778" layer="96"/></instance>
<instance part="R4" gate="G$1" x="155" y="150" smashed="yes" rot="R0"><attribute name="NAME" x="149.92" y="153.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="149.92" y="143.59" size="1.778" layer="96"/></instance>
<instance part="LED3" gate="G$1" x="210" y="150" smashed="yes" rot="R0"><attribute name="NAME" x="204.92" y="154.07" size="1.778" layer="95"/>
<attribute name="VALUE" x="204.92" y="143.59" size="1.778" layer="96"/></instance>
<instance part="R5" gate="G$1" x="265" y="150" smashed="yes" rot="R0"><attribute name="NAME" x="259.92" y="153.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="259.92" y="143.59" size="1.778" layer="96"/></instance>
<instance part="R6" gate="G$1" x="320" y="150" smashed="yes" rot="R0"><attribute name="NAME" x="314.92" y="153.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="314.92" y="143.59" size="1.778" layer="96"/></instance>
<instance part="C8" gate="G$1" x="375" y="150" smashed="yes" rot="R0"><attribute name="NAME" x="369.92" y="153.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="369.92" y="143.59" size="1.778" layer="96"/></instance>
<instance part="SW3" gate="G$1" x="430" y="150" smashed="yes" rot="R0"><attribute name="NAME" x="424.92" y="154.81" size="1.778" layer="95"/>
<attribute name="VALUE" x="424.92" y="142.32" size="1.778" layer="96"/></instance>
<instance part="R7" gate="G$1" x="485" y="150" smashed="yes" rot="R0"><attribute name="NAME" x="479.92" y="153.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="479.92" y="143.59" size="1.778" layer="96"/></instance>
<instance part="TP6" gate="G$1" x="155" y="80" smashed="yes" rot="R0"><attribute name="NAME" x="153.73" y="83.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="153.73" y="73.59" size="1.778" layer="96"/></instance>
<instance part="U4" gate="G$1" x="290" y="240" smashed="yes" rot="R0"><attribute name="NAME" x="278.57" y="251.16" size="1.778" layer="95"/>
<attribute name="VALUE" x="278.57" y="225.97" size="1.778" layer="96"/></instance>
<instance part="R8" gate="G$1" x="440" y="240" smashed="yes" rot="R0"><attribute name="NAME" x="434.92" y="243.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="434.92" y="233.59" size="1.778" layer="96"/></instance>
<instance part="C9" gate="G$1" x="490" y="240" smashed="yes" rot="R0"><attribute name="NAME" x="484.92" y="243.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="484.92" y="233.59" size="1.778" layer="96"/></instance>
<instance part="J3" gate="G$1" x="380" y="240" smashed="yes" rot="R0"><attribute name="NAME" x="368.57" y="249.89" size="1.778" layer="95"/>
<attribute name="VALUE" x="368.57" y="227.24" size="1.778" layer="96"/></instance></instances>
<busses/>
<nets><net name="AC_L" class="1"><segment><pinref part="J1" gate="G$1" pin="1"/>
<wire x1="37.38" y1="475.08" x2="32.3" y2="475.08" width="0.1524" layer="91"/>
<label x="32.3" y="475.08" size="1.778" layer="95" rot="R0"/>
<pinref part="F1" gate="G$1" pin="1"/>
<wire x1="119.92" y1="470" x2="114.84" y2="470" width="0.1524" layer="91"/>
<label x="114.84" y="470" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="AC_L_F" class="1"><segment><pinref part="F1" gate="G$1" pin="2"/>
<wire x1="130.08" y1="470" x2="135.16" y2="470" width="0.1524" layer="91"/>
<label x="135.16" y="470" size="1.778" layer="95" rot="R0"/>
<pinref part="PS1" gate="G$1" pin="AC-L"/>
<wire x1="272.3" y1="471.27" x2="267.22" y2="471.27" width="0.1524" layer="91"/>
<label x="267.22" y="471.27" size="1.778" layer="95" rot="R0"/>
<pinref part="MOV1" gate="G$1" pin="1"/>
<wire x1="199.92" y1="470" x2="194.84" y2="470" width="0.1524" layer="91"/>
<label x="194.84" y="470" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="L"/>
<wire x1="195.24" y1="247.62" x2="200.32" y2="247.62" width="0.1524" layer="91"/>
<label x="200.32" y="247.62" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="AC_N" class="1"><segment><pinref part="J1" gate="G$1" pin="2"/>
<wire x1="37.38" y1="470" x2="32.3" y2="470" width="0.1524" layer="91"/>
<label x="32.3" y="470" size="1.778" layer="95" rot="R0"/>
<pinref part="PS1" gate="G$1" pin="AC-N"/>
<wire x1="272.3" y1="468.73" x2="267.22" y2="468.73" width="0.1524" layer="91"/>
<label x="267.22" y="468.73" size="1.778" layer="95" rot="R0"/>
<pinref part="MOV1" gate="G$1" pin="2"/>
<wire x1="210.08" y1="470" x2="215.16" y2="470" width="0.1524" layer="91"/>
<label x="215.16" y="470" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="N"/>
<wire x1="195.24" y1="250.16" x2="200.32" y2="250.16" width="0.1524" layer="91"/>
<label x="200.32" y="250.16" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="PE" class="1"><segment><pinref part="J1" gate="G$1" pin="3"/>
<wire x1="37.38" y1="464.92" x2="32.3" y2="464.92" width="0.1524" layer="91"/>
<label x="32.3" y="464.92" size="1.778" layer="95" rot="R0"/>
<pinref part="TP3" gate="G$1" pin="1"/>
<wire x1="365" y1="466.19" x2="365" y2="461.11" width="0.1524" layer="91"/>
<label x="365" y="461.11" size="1.778" layer="95" rot="R270"/></segment></net>
<net name="12V_P" class="2"><segment><pinref part="PS1" gate="G$1" pin="+VO"/>
<wire x1="297.7" y1="471.27" x2="302.78" y2="471.27" width="0.1524" layer="91"/>
<label x="302.78" y="471.27" size="1.778" layer="95" rot="R0"/>
<pinref part="FB1" gate="G$1" pin="1"/>
<wire x1="39.92" y1="420" x2="34.84" y2="420" width="0.1524" layer="91"/>
<label x="34.84" y="420" size="1.778" layer="95" rot="R0"/>
<pinref part="C1" gate="G$1" pin="+"/>
<wire x1="99.92" y1="420" x2="94.84" y2="420" width="0.1524" layer="91"/>
<label x="94.84" y="420" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="GND" class="2"><segment><pinref part="PS1" gate="G$1" pin="-VO"/>
<wire x1="297.7" y1="468.73" x2="302.78" y2="468.73" width="0.1524" layer="91"/>
<label x="302.78" y="468.73" size="1.778" layer="95" rot="R0"/>
<pinref part="C1" gate="G$1" pin="-"/>
<wire x1="110.08" y1="420" x2="115.16" y2="420" width="0.1524" layer="91"/>
<label x="115.16" y="420" size="1.778" layer="95" rot="R0"/>
<pinref part="TP2" gate="G$1" pin="1"/>
<wire x1="215" y1="416.19" x2="215" y2="411.11" width="0.1524" layer="91"/>
<label x="215" y="411.11" size="1.778" layer="95" rot="R270"/>
<pinref part="U1" gate="G$1" pin="GND"/>
<wire x1="50" y1="366.19" x2="50" y2="361.11" width="0.1524" layer="91"/>
<label x="50" y="361.11" size="1.778" layer="95" rot="R270"/>
<pinref part="U1" gate="G$1" pin="ONOFF"/>
<wire x1="60.16" y1="368.73" x2="65.24" y2="368.73" width="0.1524" layer="91"/>
<label x="65.24" y="368.73" size="1.778" layer="95" rot="R0"/>
<pinref part="C2" gate="G$1" pin="-"/>
<wire x1="270.08" y1="370" x2="275.16" y2="370" width="0.1524" layer="91"/>
<label x="275.16" y="370" size="1.778" layer="95" rot="R0"/>
<pinref part="C3" gate="G$1" pin="-"/>
<wire x1="330.08" y1="370" x2="335.16" y2="370" width="0.1524" layer="91"/>
<label x="335.16" y="370" size="1.778" layer="95" rot="R0"/>
<pinref part="C4" gate="G$1" pin="2"/>
<wire x1="390.08" y1="370" x2="395.16" y2="370" width="0.1524" layer="91"/>
<label x="395.16" y="370" size="1.778" layer="95" rot="R0"/>
<pinref part="D1" gate="G$1" pin="A"/>
<wire x1="192.38" y1="370" x2="187.3" y2="370" width="0.1524" layer="91"/>
<label x="187.3" y="370" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="GND"/>
<wire x1="50" y1="316.19" x2="50" y2="311.11" width="0.1524" layer="91"/>
<label x="50" y="311.11" size="1.778" layer="95" rot="R270"/>
<pinref part="U2" gate="G$1" pin="ONOFF"/>
<wire x1="60.16" y1="318.73" x2="65.24" y2="318.73" width="0.1524" layer="91"/>
<label x="65.24" y="318.73" size="1.778" layer="95" rot="R0"/>
<pinref part="C5" gate="G$1" pin="-"/>
<wire x1="270.08" y1="320" x2="275.16" y2="320" width="0.1524" layer="91"/>
<label x="275.16" y="320" size="1.778" layer="95" rot="R0"/>
<pinref part="C6" gate="G$1" pin="-"/>
<wire x1="330.08" y1="320" x2="335.16" y2="320" width="0.1524" layer="91"/>
<label x="335.16" y="320" size="1.778" layer="95" rot="R0"/>
<pinref part="C7" gate="G$1" pin="2"/>
<wire x1="390.08" y1="320" x2="395.16" y2="320" width="0.1524" layer="91"/>
<label x="395.16" y="320" size="1.778" layer="95" rot="R0"/>
<pinref part="D2" gate="G$1" pin="A"/>
<wire x1="192.38" y1="320" x2="187.3" y2="320" width="0.1524" layer="91"/>
<label x="187.3" y="320" size="1.778" layer="95" rot="R0"/>
<pinref part="LED1" gate="G$1" pin="K"/>
<wire x1="105.08" y1="80" x2="110.16" y2="80" width="0.1524" layer="91"/>
<label x="110.16" y="80" size="1.778" layer="95" rot="R0"/>
<pinref part="J2" gate="G$1" pin="GND_6"/>
<wire x1="85.24" y1="259.05" x2="90.32" y2="259.05" width="0.1524" layer="91"/>
<label x="90.32" y="259.05" size="1.778" layer="95" rot="R0"/>
<pinref part="J2" gate="G$1" pin="GND"/>
<wire x1="54.76" y1="253.97" x2="49.68" y2="253.97" width="0.1524" layer="91"/>
<label x="49.68" y="253.97" size="1.778" layer="95" rot="R0"/>
<pinref part="J2" gate="G$1" pin="GND_14"/>
<wire x1="85.24" y1="248.89" x2="90.32" y2="248.89" width="0.1524" layer="91"/>
<label x="90.32" y="248.89" size="1.778" layer="95" rot="R0"/>
<pinref part="J2" gate="G$1" pin="GND_20"/>
<wire x1="85.24" y1="241.27" x2="90.32" y2="241.27" width="0.1524" layer="91"/>
<label x="90.32" y="241.27" size="1.778" layer="95" rot="R0"/>
<pinref part="J2" gate="G$1" pin="GND_25"/>
<wire x1="54.76" y1="233.65" x2="49.68" y2="233.65" width="0.1524" layer="91"/>
<label x="49.68" y="233.65" size="1.778" layer="95" rot="R0"/>
<pinref part="J2" gate="G$1" pin="GND_30"/>
<wire x1="85.24" y1="228.57" x2="90.32" y2="228.57" width="0.1524" layer="91"/>
<label x="90.32" y="228.57" size="1.778" layer="95" rot="R0"/>
<pinref part="J2" gate="G$1" pin="GND_34"/>
<wire x1="85.24" y1="223.49" x2="90.32" y2="223.49" width="0.1524" layer="91"/>
<label x="90.32" y="223.49" size="1.778" layer="95" rot="R0"/>
<pinref part="J2" gate="G$1" pin="GND_39"/>
<wire x1="54.76" y1="215.87" x2="49.68" y2="215.87" width="0.1524" layer="91"/>
<label x="49.68" y="215.87" size="1.778" layer="95" rot="R0"/>
<pinref part="J3" gate="G$1" pin="2"/>
<wire x1="391.43" y1="245.08" x2="396.51" y2="245.08" width="0.1524" layer="91"/>
<label x="396.51" y="245.08" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="GND"/>
<wire x1="180" y1="224.76" x2="180" y2="219.68" width="0.1524" layer="91"/>
<label x="180" y="219.68" size="1.778" layer="95" rot="R270"/>
<pinref part="LED2" gate="G$1" pin="K"/>
<wire x1="105.08" y1="150" x2="110.16" y2="150" width="0.1524" layer="91"/>
<label x="110.16" y="150" size="1.778" layer="95" rot="R0"/>
<pinref part="LED3" gate="G$1" pin="K"/>
<wire x1="215.08" y1="150" x2="220.16" y2="150" width="0.1524" layer="91"/>
<label x="220.16" y="150" size="1.778" layer="95" rot="R0"/>
<pinref part="SW3" gate="G$1" pin="2"/>
<wire x1="435.08" y1="150" x2="440.16" y2="150" width="0.1524" layer="91"/>
<label x="440.16" y="150" size="1.778" layer="95" rot="R0"/>
<pinref part="C8" gate="G$1" pin="2"/>
<wire x1="380.08" y1="150" x2="385.16" y2="150" width="0.1524" layer="91"/>
<label x="385.16" y="150" size="1.778" layer="95" rot="R0"/>
<pinref part="R7" gate="G$1" pin="2"/>
<wire x1="490.08" y1="150" x2="495.16" y2="150" width="0.1524" layer="91"/>
<label x="495.16" y="150" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="GND"/>
<wire x1="290" y1="231.11" x2="290" y2="226.03" width="0.1524" layer="91"/>
<label x="290" y="226.03" size="1.778" layer="95" rot="R270"/>
<pinref part="C9" gate="G$1" pin="2"/>
<wire x1="495.08" y1="240" x2="500.16" y2="240" width="0.1524" layer="91"/>
<label x="500.16" y="240" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="12V" class="2"><segment><pinref part="FB1" gate="G$1" pin="2"/>
<wire x1="50.08" y1="420" x2="55.16" y2="420" width="0.1524" layer="91"/>
<label x="55.16" y="420" size="1.778" layer="95" rot="R0"/>
<pinref part="TP1" gate="G$1" pin="1"/>
<wire x1="165" y1="416.19" x2="165" y2="411.11" width="0.1524" layer="91"/>
<label x="165" y="411.11" size="1.778" layer="95" rot="R270"/>
<pinref part="U1" gate="G$1" pin="VIN"/>
<wire x1="39.84" y1="371.27" x2="34.76" y2="371.27" width="0.1524" layer="91"/>
<label x="34.76" y="371.27" size="1.778" layer="95" rot="R0"/>
<pinref part="C2" gate="G$1" pin="+"/>
<wire x1="259.92" y1="370" x2="254.84" y2="370" width="0.1524" layer="91"/>
<label x="254.84" y="370" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="VIN"/>
<wire x1="39.84" y1="321.27" x2="34.76" y2="321.27" width="0.1524" layer="91"/>
<label x="34.76" y="321.27" size="1.778" layer="95" rot="R0"/>
<pinref part="C5" gate="G$1" pin="+"/>
<wire x1="259.92" y1="320" x2="254.84" y2="320" width="0.1524" layer="91"/>
<label x="254.84" y="320" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="SW_5V" class="2"><segment><pinref part="U1" gate="G$1" pin="VOUT"/>
<wire x1="60.16" y1="371.27" x2="65.24" y2="371.27" width="0.1524" layer="91"/>
<label x="65.24" y="371.27" size="1.778" layer="95" rot="R0"/>
<pinref part="L1" gate="G$1" pin="1"/>
<wire x1="119.84" y1="370" x2="114.76" y2="370" width="0.1524" layer="91"/>
<label x="114.76" y="370" size="1.778" layer="95" rot="R0"/>
<pinref part="D1" gate="G$1" pin="K"/>
<wire x1="207.62" y1="370" x2="212.7" y2="370" width="0.1524" layer="91"/>
<label x="212.7" y="370" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="5V" class="2"><segment><pinref part="L1" gate="G$1" pin="2"/>
<wire x1="140.16" y1="370" x2="145.24" y2="370" width="0.1524" layer="91"/>
<label x="145.24" y="370" size="1.778" layer="95" rot="R0"/>
<pinref part="C3" gate="G$1" pin="+"/>
<wire x1="319.92" y1="370" x2="314.84" y2="370" width="0.1524" layer="91"/>
<label x="314.84" y="370" size="1.778" layer="95" rot="R0"/>
<pinref part="C4" gate="G$1" pin="1"/>
<wire x1="379.92" y1="370" x2="374.84" y2="370" width="0.1524" layer="91"/>
<label x="374.84" y="370" size="1.778" layer="95" rot="R0"/>
<pinref part="TP4" gate="G$1" pin="1"/>
<wire x1="440" y1="366.19" x2="440" y2="361.11" width="0.1524" layer="91"/>
<label x="440" y="361.11" size="1.778" layer="95" rot="R270"/>
<pinref part="J2" gate="G$1" pin="5V"/>
<wire x1="85.24" y1="264.13" x2="90.32" y2="264.13" width="0.1524" layer="91"/>
<label x="90.32" y="264.13" size="1.778" layer="95" rot="R0"/>
<pinref part="J2" gate="G$1" pin="5V_4"/>
<wire x1="85.24" y1="261.59" x2="90.32" y2="261.59" width="0.1524" layer="91"/>
<label x="90.32" y="261.59" size="1.778" layer="95" rot="R0"/>
<pinref part="J3" gate="G$1" pin="1"/>
<wire x1="368.57" y1="245.08" x2="363.49" y2="245.08" width="0.1524" layer="91"/>
<label x="363.49" y="245.08" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="SW_3V3" class="2"><segment><pinref part="U2" gate="G$1" pin="VOUT"/>
<wire x1="60.16" y1="321.27" x2="65.24" y2="321.27" width="0.1524" layer="91"/>
<label x="65.24" y="321.27" size="1.778" layer="95" rot="R0"/>
<pinref part="L2" gate="G$1" pin="1"/>
<wire x1="119.84" y1="320" x2="114.76" y2="320" width="0.1524" layer="91"/>
<label x="114.76" y="320" size="1.778" layer="95" rot="R0"/>
<pinref part="D2" gate="G$1" pin="K"/>
<wire x1="207.62" y1="320" x2="212.7" y2="320" width="0.1524" layer="91"/>
<label x="212.7" y="320" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="3V3" class="2"><segment><pinref part="L2" gate="G$1" pin="2"/>
<wire x1="140.16" y1="320" x2="145.24" y2="320" width="0.1524" layer="91"/>
<label x="145.24" y="320" size="1.778" layer="95" rot="R0"/>
<pinref part="C6" gate="G$1" pin="+"/>
<wire x1="319.92" y1="320" x2="314.84" y2="320" width="0.1524" layer="91"/>
<label x="314.84" y="320" size="1.778" layer="95" rot="R0"/>
<pinref part="C7" gate="G$1" pin="1"/>
<wire x1="379.92" y1="320" x2="374.84" y2="320" width="0.1524" layer="91"/>
<label x="374.84" y="320" size="1.778" layer="95" rot="R0"/>
<pinref part="TP5" gate="G$1" pin="1"/>
<wire x1="440" y1="316.19" x2="440" y2="311.11" width="0.1524" layer="91"/>
<label x="440" y="311.11" size="1.778" layer="95" rot="R270"/>
<pinref part="U3" gate="G$1" pin="VDD"/>
<wire x1="195.24" y1="252.7" x2="200.32" y2="252.7" width="0.1524" layer="91"/>
<label x="200.32" y="252.7" size="1.778" layer="95" rot="R0"/>
<pinref part="R5" gate="G$1" pin="1"/>
<wire x1="259.92" y1="150" x2="254.84" y2="150" width="0.1524" layer="91"/>
<label x="254.84" y="150" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="3V3"/>
<wire x1="301.43" y1="246.35" x2="306.51" y2="246.35" width="0.1524" layer="91"/>
<label x="306.51" y="246.35" size="1.778" layer="95" rot="R0"/>
<pinref part="R8" gate="G$1" pin="1"/>
<wire x1="434.92" y1="240" x2="429.84" y2="240" width="0.1524" layer="91"/>
<label x="429.84" y="240" size="1.778" layer="95" rot="R0"/>
<pinref part="C9" gate="G$1" pin="1"/>
<wire x1="484.92" y1="240" x2="479.84" y2="240" width="0.1524" layer="91"/>
<label x="479.84" y="240" size="1.778" layer="95" rot="R0"/>
<pinref part="R1" gate="G$1" pin="1"/>
<wire x1="39.92" y1="80" x2="34.84" y2="80" width="0.1524" layer="91"/>
<label x="34.84" y="80" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="LED_A" class="0"><segment><pinref part="R1" gate="G$1" pin="2"/>
<wire x1="50.08" y1="80" x2="55.16" y2="80" width="0.1524" layer="91"/>
<label x="55.16" y="80" size="1.778" layer="95" rot="R0"/>
<pinref part="LED1" gate="G$1" pin="A"/>
<wire x1="94.92" y1="80" x2="89.84" y2="80" width="0.1524" layer="91"/>
<label x="89.84" y="80" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="PLC_SCLK" class="0"><segment><pinref part="J2" gate="G$1" pin="GPIO21"/>
<wire x1="85.24" y1="215.87" x2="90.32" y2="215.87" width="0.1524" layer="91"/>
<label x="90.32" y="215.87" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="SERIAL_1"/>
<wire x1="164.76" y1="232.38" x2="159.68" y2="232.38" width="0.1524" layer="91"/>
<label x="159.68" y="232.38" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="PLC_MISO" class="0"><segment><pinref part="J2" gate="G$1" pin="GPIO19"/>
<wire x1="54.76" y1="220.95" x2="49.68" y2="220.95" width="0.1524" layer="91"/>
<label x="49.68" y="220.95" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="SERIAL_3"/>
<wire x1="164.76" y1="237.46" x2="159.68" y2="237.46" width="0.1524" layer="91"/>
<label x="159.68" y="237.46" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="PLC_MOSI" class="0"><segment><pinref part="J2" gate="G$1" pin="GPIO20"/>
<wire x1="85.24" y1="218.41" x2="90.32" y2="218.41" width="0.1524" layer="91"/>
<label x="90.32" y="218.41" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="SERIAL_4"/>
<wire x1="164.76" y1="240" x2="159.68" y2="240" width="0.1524" layer="91"/>
<label x="159.68" y="240" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="PLC_CS" class="0"><segment><pinref part="J2" gate="G$1" pin="GPIO16"/>
<wire x1="85.24" y1="220.95" x2="90.32" y2="220.95" width="0.1524" layer="91"/>
<label x="90.32" y="220.95" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="SERIAL_2"/>
<wire x1="164.76" y1="234.92" x2="159.68" y2="234.92" width="0.1524" layer="91"/>
<label x="159.68" y="234.92" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="PLC_INT" class="0"><segment><pinref part="J2" gate="G$1" pin="GPIO26"/>
<wire x1="54.76" y1="218.41" x2="49.68" y2="218.41" width="0.1524" layer="91"/>
<label x="49.68" y="218.41" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="SERIAL_0"/>
<wire x1="164.76" y1="229.84" x2="159.68" y2="229.84" width="0.1524" layer="91"/>
<label x="159.68" y="229.84" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="PLC_RESET" class="0"><segment><pinref part="J2" gate="G$1" pin="GPIO6"/>
<wire x1="54.76" y1="226.03" x2="49.68" y2="226.03" width="0.1524" layer="91"/>
<label x="49.68" y="226.03" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="RESET_L"/>
<wire x1="164.76" y1="242.54" x2="159.68" y2="242.54" width="0.1524" layer="91"/>
<label x="159.68" y="242.54" size="1.778" layer="95" rot="R0"/>
<pinref part="TP6" gate="G$1" pin="1"/>
<wire x1="155" y1="76.19" x2="155" y2="71.11" width="0.1524" layer="91"/>
<label x="155" y="71.11" size="1.778" layer="95" rot="R270"/></segment></net>
<net name="ETH_SCLK" class="0"><segment><pinref part="J2" gate="G$1" pin="GPIO11"/>
<wire x1="54.76" y1="236.19" x2="49.68" y2="236.19" width="0.1524" layer="91"/>
<label x="49.68" y="236.19" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="SCLK"/>
<wire x1="278.57" y1="243.81" x2="273.49" y2="243.81" width="0.1524" layer="91"/>
<label x="273.49" y="243.81" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="ETH_MISO" class="0"><segment><pinref part="J2" gate="G$1" pin="GPIO9"/>
<wire x1="54.76" y1="238.73" x2="49.68" y2="238.73" width="0.1524" layer="91"/>
<label x="49.68" y="238.73" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="MISO"/>
<wire x1="278.57" y1="233.65" x2="273.49" y2="233.65" width="0.1524" layer="91"/>
<label x="273.49" y="233.65" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="ETH_MOSI" class="0"><segment><pinref part="J2" gate="G$1" pin="GPIO10"/>
<wire x1="54.76" y1="241.27" x2="49.68" y2="241.27" width="0.1524" layer="91"/>
<label x="49.68" y="241.27" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="MOSI"/>
<wire x1="278.57" y1="246.35" x2="273.49" y2="246.35" width="0.1524" layer="91"/>
<label x="273.49" y="246.35" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="ETH_CS" class="0"><segment><pinref part="J2" gate="G$1" pin="GPIO8"/>
<wire x1="85.24" y1="236.19" x2="90.32" y2="236.19" width="0.1524" layer="91"/>
<label x="90.32" y="236.19" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="!SCS"/>
<wire x1="278.57" y1="241.27" x2="273.49" y2="241.27" width="0.1524" layer="91"/>
<label x="273.49" y="241.27" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="ETH_INT" class="0"><segment><pinref part="J2" gate="G$1" pin="GPIO25"/>
<wire x1="85.24" y1="238.73" x2="90.32" y2="238.73" width="0.1524" layer="91"/>
<label x="90.32" y="238.73" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="!INT"/>
<wire x1="278.57" y1="238.73" x2="273.49" y2="238.73" width="0.1524" layer="91"/>
<label x="273.49" y="238.73" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="ETH_RST" class="0"><segment><pinref part="J2" gate="G$1" pin="GPIO27"/>
<wire x1="54.76" y1="248.89" x2="49.68" y2="248.89" width="0.1524" layer="91"/>
<label x="49.68" y="248.89" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="!RST"/>
<wire x1="278.57" y1="236.19" x2="273.49" y2="236.19" width="0.1524" layer="91"/>
<label x="273.49" y="236.19" size="1.778" layer="95" rot="R0"/>
<pinref part="R8" gate="G$1" pin="2"/>
<wire x1="445.08" y1="240" x2="450.16" y2="240" width="0.1524" layer="91"/>
<label x="450.16" y="240" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="PLC_GPIO0" class="0"><segment><pinref part="U3" gate="G$1" pin="GPIO_0"/>
<wire x1="164.76" y1="252.7" x2="159.68" y2="252.7" width="0.1524" layer="91"/>
<label x="159.68" y="252.7" size="1.778" layer="95" rot="R0"/>
<pinref part="R3" gate="G$1" pin="1"/>
<wire x1="39.92" y1="150" x2="34.84" y2="150" width="0.1524" layer="91"/>
<label x="34.84" y="150" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="LED2_A" class="0"><segment><pinref part="R3" gate="G$1" pin="2"/>
<wire x1="50.08" y1="150" x2="55.16" y2="150" width="0.1524" layer="91"/>
<label x="55.16" y="150" size="1.778" layer="95" rot="R0"/>
<pinref part="LED2" gate="G$1" pin="A"/>
<wire x1="94.92" y1="150" x2="89.84" y2="150" width="0.1524" layer="91"/>
<label x="89.84" y="150" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="PLC_GPIO1" class="0"><segment><pinref part="U3" gate="G$1" pin="GPIO_1"/>
<wire x1="164.76" y1="250.16" x2="159.68" y2="250.16" width="0.1524" layer="91"/>
<label x="159.68" y="250.16" size="1.778" layer="95" rot="R0"/>
<pinref part="R4" gate="G$1" pin="1"/>
<wire x1="149.92" y1="150" x2="144.84" y2="150" width="0.1524" layer="91"/>
<label x="144.84" y="150" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="LED3_A" class="0"><segment><pinref part="R4" gate="G$1" pin="2"/>
<wire x1="160.08" y1="150" x2="165.16" y2="150" width="0.1524" layer="91"/>
<label x="165.16" y="150" size="1.778" layer="95" rot="R0"/>
<pinref part="LED3" gate="G$1" pin="A"/>
<wire x1="204.92" y1="150" x2="199.84" y2="150" width="0.1524" layer="91"/>
<label x="199.84" y="150" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="PLC_GPIO3" class="0"><segment><pinref part="U3" gate="G$1" pin="GPIO_3"/>
<wire x1="164.76" y1="245.08" x2="159.68" y2="245.08" width="0.1524" layer="91"/>
<label x="159.68" y="245.08" size="1.778" layer="95" rot="R0"/>
<pinref part="R5" gate="G$1" pin="2"/>
<wire x1="270.08" y1="150" x2="275.16" y2="150" width="0.1524" layer="91"/>
<label x="275.16" y="150" size="1.778" layer="95" rot="R0"/>
<pinref part="R6" gate="G$1" pin="2"/>
<wire x1="325.08" y1="150" x2="330.16" y2="150" width="0.1524" layer="91"/>
<label x="330.16" y="150" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="SW3_N" class="0"><segment><pinref part="R6" gate="G$1" pin="1"/>
<wire x1="314.92" y1="150" x2="309.84" y2="150" width="0.1524" layer="91"/>
<label x="309.84" y="150" size="1.778" layer="95" rot="R0"/>
<pinref part="SW3" gate="G$1" pin="1"/>
<wire x1="424.92" y1="150" x2="419.84" y2="150" width="0.1524" layer="91"/>
<label x="419.84" y="150" size="1.778" layer="95" rot="R0"/>
<pinref part="C8" gate="G$1" pin="1"/>
<wire x1="369.92" y1="150" x2="364.84" y2="150" width="0.1524" layer="91"/>
<label x="364.84" y="150" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="ZC_IN" class="0"><segment><pinref part="U3" gate="G$1" pin="ZC_IN"/>
<wire x1="164.76" y1="227.3" x2="159.68" y2="227.3" width="0.1524" layer="91"/>
<label x="159.68" y="227.3" size="1.778" layer="95" rot="R0"/>
<pinref part="R7" gate="G$1" pin="1"/>
<wire x1="479.92" y1="150" x2="474.84" y2="150" width="0.1524" layer="91"/>
<label x="474.84" y="150" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="BRK_TXD" class="0"><segment><pinref part="J2" gate="G$1" pin="GPIO14"/>
<wire x1="85.24" y1="256.51" x2="90.32" y2="256.51" width="0.1524" layer="91"/>
<label x="90.32" y="256.51" size="1.778" layer="95" rot="R0"/>
<pinref part="J3" gate="G$1" pin="3"/>
<wire x1="368.57" y1="242.54" x2="363.49" y2="242.54" width="0.1524" layer="91"/>
<label x="363.49" y="242.54" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="BRK_RXD" class="0"><segment><pinref part="J2" gate="G$1" pin="GPIO15"/>
<wire x1="85.24" y1="253.97" x2="90.32" y2="253.97" width="0.1524" layer="91"/>
<label x="90.32" y="253.97" size="1.778" layer="95" rot="R0"/>
<pinref part="J3" gate="G$1" pin="4"/>
<wire x1="391.43" y1="242.54" x2="396.51" y2="242.54" width="0.1524" layer="91"/>
<label x="396.51" y="242.54" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="BRK_GPIO4" class="0"><segment><pinref part="J2" gate="G$1" pin="GPIO4"/>
<wire x1="54.76" y1="256.51" x2="49.68" y2="256.51" width="0.1524" layer="91"/>
<label x="49.68" y="256.51" size="1.778" layer="95" rot="R0"/>
<pinref part="J3" gate="G$1" pin="5"/>
<wire x1="368.57" y1="240" x2="363.49" y2="240" width="0.1524" layer="91"/>
<label x="363.49" y="240" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="BRK_GPIO22" class="0"><segment><pinref part="J2" gate="G$1" pin="GPIO22"/>
<wire x1="54.76" y1="246.35" x2="49.68" y2="246.35" width="0.1524" layer="91"/>
<label x="49.68" y="246.35" size="1.778" layer="95" rot="R0"/>
<pinref part="J3" gate="G$1" pin="6"/>
<wire x1="391.43" y1="240" x2="396.51" y2="240" width="0.1524" layer="91"/>
<label x="396.51" y="240" size="1.778" layer="95" rot="R0"/></segment></net></nets></sheet></sheets></schematic>
</drawing>
</eagle>
