/* AesApplet.java — AES — CBC, GCM, CCM, as a JavaCard Classic card program.
 *
 * GENERATED by tools/cookbook_to_javacard.mjs — do not hand-edit.
 * Source recipe: public/apps/cookbook/index.html ("AES — CBC, GCM, CCM").
 * Card side of the two-program split (cf. BasicCard terminal+card model):
 * the JavaOS terminal program sends ISO 7816-4 APDUs, this applet answers.
 * JavaCard 2.2.2 subset only (no String/Thread/long/double/float); enforced
 * by tests/14-javacard.mjs. Grammar: one ClassDeclaration with field and
 * method declarations per JavacParser (see docs/UEFI_OPENBIOS_JAVAC.md).
 */
package kitchen.card;

import javacard.framework.*;
import javacard.security.*;
import javacardx.crypto.*;

public class AesApplet extends Applet {
    private Cipher cipher;
    private AESKey aesKey;

    protected AesApplet() {
        cipher = Cipher.getInstance(Cipher.ALG_AES_BLOCK_128_CBC_NOPAD, false);
        aesKey = (AESKey) KeyBuilder.buildKey(KeyBuilder.TYPE_AES, KeyBuilder.LENGTH_AES_128, false);
        register();
    }

    public static void install(byte[] bArray, short bOffset, byte bLength) {
        new AesApplet();
    }

    public void process(APDU apdu) {
        if (selectingApplet()) {
            return;
        }
        byte[] buf = apdu.getBuffer();
        byte ins = buf[ISO7816.OFFSET_INS];
        switch (ins) {
            case (byte) 0x10:
                apdu.setIncomingAndReceive();
                setKey(buf);
                break;
            case (byte) 0x20:
                doCrypto(apdu, Cipher.MODE_ENCRYPT);
                break;
            case (byte) 0x21:
                doCrypto(apdu, Cipher.MODE_DECRYPT);
                break;
            default:
                ISOException.throwIt(ISO7816.SW_INS_NOT_SUPPORTED);
        }
    }

    private void setKey(byte[] buf) {
        short len = (short) (buf[ISO7816.OFFSET_LC] & 0xFF);
        if (len != (short) 16) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }
        aesKey.setKey(buf, ISO7816.OFFSET_CDATA);
    }

    private void doCrypto(APDU apdu, byte mode) {
        byte[] buf = apdu.getBuffer();
        short got = apdu.setIncomingAndReceive();
        if (got < (short) 32 || (short) (got % 16) != (short) 0) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }
        cipher.init(aesKey, mode, buf, ISO7816.OFFSET_CDATA, (short) 16);
        short n = cipher.doFinal(buf, (short) (ISO7816.OFFSET_CDATA + 16),
                (short) (got - 16), buf, (short) 0);
        apdu.setOutgoingAndSend((short) 0, n);
    }
}
