/* DesApplet.java — DES + Triple DES (3DES / TDEA), as a JavaCard Classic card program.
 *
 * GENERATED by tools/cookbook_to_javacard.mjs — do not hand-edit.
 * Source recipe: public/apps/cookbook/index.html ("DES + Triple DES (3DES / TDEA)").
 * Card side of the two-program split (cf. BasicCard terminal+card model):
 * the JavaOS terminal program sends ISO 7816-4 APDUs, this applet answers.
 * JavaCard 2.2.2 subset only (no String/Thread/long/double/float); enforced
 * by tests/14-javacard.mjs. Grammar: one ClassDeclaration with field and
 * method declarations per JavacParser (see docs/UEFI_OPENBIOS_JAVAC.md).
 */
package kitchen.card;

import javacard.framework.*;
import javacard.security.*;
import javacardx.crypto.*;

public class DesApplet extends Applet {
    private Cipher cipher;
    private DESKey desKey;

    protected DesApplet() {
        cipher = Cipher.getInstance(Cipher.ALG_DES_CBC_NOPAD, false);
        desKey = (DESKey) KeyBuilder.buildKey(KeyBuilder.TYPE_DES, KeyBuilder.LENGTH_DES3_3KEY, false);
        register();
    }

    public static void install(byte[] bArray, short bOffset, byte bLength) {
        new DesApplet();
    }

    public void process(APDU apdu) {
        if (selectingApplet()) {
            return;
        }
        byte[] buf = apdu.getBuffer();
        byte ins = buf[ISO7816.OFFSET_INS];
        switch (ins) {
            case (byte) 0x10:
                apdu.setIncomingAndReceive();
                setKey(buf);
                break;
            case (byte) 0x20:
                doCrypto(apdu, Cipher.MODE_ENCRYPT);
                break;
            case (byte) 0x21:
                doCrypto(apdu, Cipher.MODE_DECRYPT);
                break;
            default:
                ISOException.throwIt(ISO7816.SW_INS_NOT_SUPPORTED);
        }
    }

    private void setKey(byte[] buf) {
        short len = (short) (buf[ISO7816.OFFSET_LC] & 0xFF);
        if (len != (short) 8 && len != (short) 16 && len != (short) 24) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }
        desKey.setKey(buf, ISO7816.OFFSET_CDATA);
    }

    private void doCrypto(APDU apdu, byte mode) {
        byte[] buf = apdu.getBuffer();
        short got = apdu.setIncomingAndReceive();
        if (got < (short) 16 || (short) (got % 8) != (short) 0) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }
        cipher.init(desKey, mode, buf, ISO7816.OFFSET_CDATA, (short) 8);
        short n = cipher.doFinal(buf, (short) (ISO7816.OFFSET_CDATA + 8),
                (short) (got - 8), buf, (short) 0);
        apdu.setOutgoingAndSend((short) 0, n);
    }
}
