/* EcApplet.java — ECC — SECP, Brainpool, Koblitz curves, as a JavaCard Classic card program.
 *
 * GENERATED by tools/cookbook_to_javacard.mjs — do not hand-edit.
 * Source recipe: public/apps/cookbook/index.html ("ECC — SECP, Brainpool, Koblitz curves").
 * Card side of the two-program split (cf. BasicCard terminal+card model):
 * the JavaOS terminal program sends ISO 7816-4 APDUs, this applet answers.
 * JavaCard 2.2.2 subset only (no String/Thread/long/double/float); enforced
 * by tests/14-javacard.mjs. Grammar: one ClassDeclaration with field and
 * method declarations per JavacParser (see docs/UEFI_OPENBIOS_JAVAC.md).
 */
package kitchen.card;

import javacard.framework.*;
import javacard.security.*;
import javacardx.crypto.*;

public class EcApplet extends Applet {
    private KeyPair keyPair;
    private Signature signer;
    private ECPublicKey pub;
    private ECPrivateKey prv;
    private byte[] domain;

    protected EcApplet() {
        keyPair = new KeyPair(KeyPair.ALG_EC_FP, KeyBuilder.LENGTH_EC_FP_256);
        pub = (ECPublicKey) keyPair.getPublic();
        prv = (ECPrivateKey) keyPair.getPrivate();
        setDomainParams();
        keyPair.genKeyPair();
        signer = Signature.getInstance(Signature.ALG_ECDSA_SHA_256, false);
        register();
    }

    public static void install(byte[] bArray, short bOffset, byte bLength) {
        new EcApplet();
    }

    public void process(APDU apdu) {
        if (selectingApplet()) {
            return;
        }
        byte[] buf = apdu.getBuffer();
        byte ins = buf[ISO7816.OFFSET_INS];
        switch (ins) {
            case (byte) 0x30:
                keyPair.genKeyPair();
                break;
            case (byte) 0x31:
                doSign(apdu);
                break;
            case (byte) 0x32:
                doVerify(apdu);
                break;
            default:
                ISOException.throwIt(ISO7816.SW_INS_NOT_SUPPORTED);
        }
    }

    private void setDomainParams() {
        domain = new byte[(short) 160];
        short o = (short) 0;
        // p = FFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFF
        byte[] p = new byte[] {
            (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x01,
            (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x00,
            (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF,
            (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF };
        // a = FFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFC
        byte[] a = new byte[] {
            (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x01,
            (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x00,
            (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF,
            (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0xFC };
        // b = 5AC635D8AA3A93E7B3EBBD55769886BC651D06B0CC53B0F63BCE3C3E27D2604B
        byte[] b = new byte[] {
            (byte) 0x5A, (byte) 0xC6, (byte) 0x35, (byte) 0xD8, (byte) 0xAA, (byte) 0x3A, (byte) 0x93, (byte) 0xE7,
            (byte) 0xB3, (byte) 0xEB, (byte) 0xBD, (byte) 0x55, (byte) 0x76, (byte) 0x98, (byte) 0x86, (byte) 0xBC,
            (byte) 0x65, (byte) 0x1D, (byte) 0x06, (byte) 0xB0, (byte) 0xCC, (byte) 0x53, (byte) 0xB0, (byte) 0xF6,
            (byte) 0x3B, (byte) 0xCE, (byte) 0x3C, (byte) 0x3E, (byte) 0x27, (byte) 0xD2, (byte) 0x60, (byte) 0x4B };
        // Gx = 6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296
        byte[] gx = new byte[] {
            (byte) 0x6B, (byte) 0x17, (byte) 0xD1, (byte) 0xF2, (byte) 0xE1, (byte) 0x2C, (byte) 0x42, (byte) 0x47,
            (byte) 0xF8, (byte) 0xBC, (byte) 0xE6, (byte) 0xE5, (byte) 0x63, (byte) 0xA4, (byte) 0x40, (byte) 0xF2,
            (byte) 0x77, (byte) 0x03, (byte) 0x7D, (byte) 0x81, (byte) 0x2D, (byte) 0xEB, (byte) 0x33, (byte) 0xA0,
            (byte) 0xF4, (byte) 0xA1, (byte) 0x39, (byte) 0x45, (byte) 0xD8, (byte) 0x98, (byte) 0xC2, (byte) 0x96 };
        // Gy = 4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5
        byte[] gy = new byte[] {
            (byte) 0x4F, (byte) 0xE3, (byte) 0x42, (byte) 0xE2, (byte) 0xFE, (byte) 0x1A, (byte) 0x7F, (byte) 0x9B,
            (byte) 0x8E, (byte) 0xE7, (byte) 0xEB, (byte) 0x4A, (byte) 0x7C, (byte) 0x0F, (byte) 0x9E, (byte) 0x16,
            (byte) 0x2B, (byte) 0xCE, (byte) 0x33, (byte) 0x57, (byte) 0x6B, (byte) 0x31, (byte) 0x5E, (byte) 0xCE,
            (byte) 0xCB, (byte) 0xB6, (byte) 0x40, (byte) 0x68, (byte) 0x37, (byte) 0xBF, (byte) 0x51, (byte) 0xF5 };
        // r = FFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551
        byte[] r = new byte[] {
            (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x00,
            (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF,
            (byte) 0xBC, (byte) 0xE6, (byte) 0xFA, (byte) 0xAD, (byte) 0xA7, (byte) 0x17, (byte) 0x9E, (byte) 0x84,
            (byte) 0xF3, (byte) 0xB9, (byte) 0xCA, (byte) 0xC2, (byte) 0xFC, (byte) 0x63, (byte) 0x25, (byte) 0x51 };
        pub.setFieldFP(p, (short) 0, (short) 32);
        pub.setA(a, (short) 0, (short) 32);
        pub.setB(b, (short) 0, (short) 32);
        pub.setG(gx, (short) 0, gy, (short) 0, (short) 32);
        pub.setR(r, (short) 0, (short) 32);
        pub.setK((short) 1);
        prv.setFieldFP(p, (short) 0, (short) 32);
        prv.setA(a, (short) 0, (short) 32);
        prv.setB(b, (short) 0, (short) 32);
        prv.setG(gx, (short) 0, gy, (short) 0, (short) 32);
        prv.setR(r, (short) 0, (short) 32);
        prv.setK((short) 1);
        o = (short) (o + 1);
        domain[o] = (byte) 0x01;
    }

    private void doSign(APDU apdu) {
        byte[] buf = apdu.getBuffer();
        short got = apdu.setIncomingAndReceive();
        signer.init(prv, Signature.MODE_SIGN);
        short n = signer.sign(buf, ISO7816.OFFSET_CDATA, got, buf, (short) 0);
        apdu.setOutgoingAndSend((short) 0, n);
    }

    private void doVerify(APDU apdu) {
        byte[] buf = apdu.getBuffer();
        short got = apdu.setIncomingAndReceive();
        signer.init(pub, Signature.MODE_VERIFY);
        short half = (short) (got / 2);
        boolean ok = signer.verify(buf, ISO7816.OFFSET_CDATA, half,
                buf, (short) (ISO7816.OFFSET_CDATA + half), half);
        if (!ok) {
            ISOException.throwIt(ISO7816.SW_SECURITY_STATUS_NOT_SATISFIED);
        }
    }
}
