/* HmacApplet.java — HMAC (+ TOTP/HOTP, OnlyKey challenge-response), as a JavaCard Classic card program.
 *
 * GENERATED by tools/cookbook_to_javacard.mjs — do not hand-edit.
 * Source recipe: public/apps/cookbook/index.html ("HMAC (+ TOTP/HOTP, OnlyKey challenge-response)").
 * Card side of the two-program split (cf. BasicCard terminal+card model):
 * the JavaOS terminal program sends ISO 7816-4 APDUs, this applet answers.
 * JavaCard 2.2.2 subset only (no String/Thread/long/double/float); enforced
 * by tests/14-javacard.mjs. Grammar: one ClassDeclaration with field and
 * method declarations per JavacParser (see docs/UEFI_OPENBIOS_JAVAC.md).
 */
package kitchen.card;

import javacard.framework.*;
import javacard.security.*;
import javacardx.crypto.*;

public class HmacApplet extends Applet {
    private Signature hmac;
    private HMACKey hmacKey;

    protected HmacApplet() {
        hmac = Signature.getInstance(Signature.ALG_HMAC_SHA_256, false);
        hmacKey = (HMACKey) KeyBuilder.buildKey(KeyBuilder.TYPE_HMAC, KeyBuilder.LENGTH_HMAC_SHA_256_BLOCK_64, false);
        register();
    }

    public static void install(byte[] bArray, short bOffset, byte bLength) {
        new HmacApplet();
    }

    public void process(APDU apdu) {
        if (selectingApplet()) {
            return;
        }
        byte[] buf = apdu.getBuffer();
        byte ins = buf[ISO7816.OFFSET_INS];
        switch (ins) {
            case (byte) 0x10:
                apdu.setIncomingAndReceive();
                setKey(buf);
                break;
            case (byte) 0x41:
                doMac(apdu);
                break;
            default:
                ISOException.throwIt(ISO7816.SW_INS_NOT_SUPPORTED);
        }
    }

    private void setKey(byte[] buf) {
        short len = (short) (buf[ISO7816.OFFSET_LC] & 0xFF);
        if (len == (short) 0 || len > (short) 64) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }
        hmacKey.setKey(buf, ISO7816.OFFSET_CDATA, len);
    }

    private void doMac(APDU apdu) {
        byte[] buf = apdu.getBuffer();
        short got = apdu.setIncomingAndReceive();
        hmac.init(hmacKey, Signature.MODE_SIGN);
        short n = hmac.sign(buf, ISO7816.OFFSET_CDATA, got, buf, (short) 0);
        apdu.setOutgoingAndSend((short) 0, n);
    }
}
