/* RsaApplet.java — RSA, as a JavaCard Classic card program.
 *
 * GENERATED by tools/cookbook_to_javacard.mjs — do not hand-edit.
 * Source recipe: public/apps/cookbook/index.html ("RSA").
 * Card side of the two-program split (cf. BasicCard terminal+card model):
 * the JavaOS terminal program sends ISO 7816-4 APDUs, this applet answers.
 * JavaCard 2.2.2 subset only (no String/Thread/long/double/float); enforced
 * by tests/14-javacard.mjs. Grammar: one ClassDeclaration with field and
 * method declarations per JavacParser (see docs/UEFI_OPENBIOS_JAVAC.md).
 */
package kitchen.card;

import javacard.framework.*;
import javacard.security.*;
import javacardx.crypto.*;

public class RsaApplet extends Applet {
    private KeyPair keyPair;
    private Signature signer;

    protected RsaApplet() {
        keyPair = new KeyPair(KeyPair.ALG_RSA, KeyBuilder.LENGTH_RSA_1024);
        signer = Signature.getInstance(Signature.ALG_RSA_SHA_PKCS1, false);
        register();
    }

    public void process(APDU apdu) {
        if (selectingApplet()) {
            return;
        }
        byte[] buf = apdu.getBuffer();
        byte ins = buf[ISO7816.OFFSET_INS];
        switch (ins) {
            case (byte) 0x30:
                keyPair.genKeyPair();
                break;
            case (byte) 0x31:
                doSign(apdu);
                break;
            case (byte) 0x32:
                doVerify(apdu);
                break;
            default:
                ISOException.throwIt(ISO7816.SW_INS_NOT_SUPPORTED);
        }
    }

    public static void install(byte[] bArray, short bOffset, byte bLength) {
        new RsaApplet();
    }

    private void doSign(APDU apdu) {
        byte[] buf = apdu.getBuffer();
        short got = apdu.setIncomingAndReceive();
        signer.init(keyPair.getPrivate(), Signature.MODE_SIGN);
        short n = signer.sign(buf, ISO7816.OFFSET_CDATA, got, buf, (short) 0);
        apdu.setOutgoingAndSend((short) 0, n);
    }

    private void doVerify(APDU apdu) {
        byte[] buf = apdu.getBuffer();
        short got = apdu.setIncomingAndReceive();
        if (got < (short) 128) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }
        signer.init(keyPair.getPublic(), Signature.MODE_VERIFY);
        short msgLen = (short) (got - 128);
        boolean ok = signer.verify(buf, ISO7816.OFFSET_CDATA, msgLen,
                buf, (short) (ISO7816.OFFSET_CDATA + msgLen), (short) 128);
        if (!ok) {
            ISOException.throwIt(ISO7816.SW_SECURITY_STATUS_NOT_SATISFIED);
        }
    }
}
