/* ShaApplet.java — SHA-256 · SHA-384 · SHA-512 · SHA-3, as a JavaCard Classic card program.
 *
 * GENERATED by tools/cookbook_to_javacard.mjs — do not hand-edit.
 * Source recipe: public/apps/cookbook/index.html ("SHA-256 · SHA-384 · SHA-512 · SHA-3").
 * Card side of the two-program split (cf. BasicCard terminal+card model):
 * the JavaOS terminal program sends ISO 7816-4 APDUs, this applet answers.
 * JavaCard 2.2.2 subset only (no String/Thread/long/double/float); enforced
 * by tests/14-javacard.mjs. Grammar: one ClassDeclaration with field and
 * method declarations per JavacParser (see docs/UEFI_OPENBIOS_JAVAC.md).
 */
package kitchen.card;

import javacard.framework.*;
import javacard.security.*;

public class ShaApplet extends Applet {
    private MessageDigest sha256;

    protected ShaApplet() {
        sha256 = MessageDigest.getInstance(MessageDigest.ALG_SHA_256, false);
        register();
    }

    public static void install(byte[] bArray, short bOffset, byte bLength) {
        new ShaApplet();
    }

    public void process(APDU apdu) {
        if (selectingApplet()) {
            return;
        }
        byte[] buf = apdu.getBuffer();
        byte ins = buf[ISO7816.OFFSET_INS];
        switch (ins) {
            case (byte) 0x40:
                doDigest(apdu);
                break;
            default:
                ISOException.throwIt(ISO7816.SW_INS_NOT_SUPPORTED);
        }
    }

    private void doDigest(APDU apdu) {
        byte[] buf = apdu.getBuffer();
        short got = apdu.setIncomingAndReceive();
        short n = sha256.doFinal(buf, ISO7816.OFFSET_CDATA, got, buf, (short) 0);
        apdu.setOutgoingAndSend((short) 0, n);
    }
}
