import { PLACES, SATELLITES, LAUNCHES, DEM_SAMPLES } from './four-corners-data.js';
const $ = (id) => document.getElementById(id);
const esc = (s) => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(q='') { const term=q.trim().toLowerCase(); const hits=PLACES.filter(p=>!term||`${p.name} ${p.kind} ${p.region}`.toLowerCase().includes(term)).slice(0,28); $('results').innerHTML=hits.length?hits.map(p=>`<div class="result"><b>${esc(p.name)}</b><span>${esc(p.kind)} · ${esc(p.region)} <em>${p.tier}</em></span></div>`).join(''):'<p class="note">No local match.</p>'; $('gazCount').textContent=`${hits.length} / ${PLACES.length}`; }
function renderDem(){ $('demSamples').innerHTML=DEM_SAMPLES.map(d=>`<div class="row"><strong>${esc(d.state)}</strong><span>${d.lat.toFixed(4)}, ${d.lon.toFixed(4)} · ${esc(d.place)}</span><small id="dem-${d.state}">${d.seedM===null?'not sampled offline':'seed '+d.seedM+' m · 3DEP control'}</small></div>`).join(''); }
const EPQS='https://epqs.nationalmap.gov/v1/json'; const LEGACY='https://nationalmap.gov/epqs/pqs.php'; const SAMPLES='https://elevation.nationalmap.gov/arcgis/rest/services/3DEPElevation/ImageServer/getSamples';
function proxyUrl(raw){const template=$('proxyUrl').value.trim(); if(!template) return raw; if(!template.includes('{url}')) throw new Error('proxy template must contain {url}'); return template.replace('{url}',encodeURIComponent(raw)); }
async function json(url){const r=await fetch(url,{mode:'cors'}); if(!r.ok) throw new Error(`HTTP ${r.status}`); return r.json();}
async function oneDem(d,useProxy=false){const urls=[`${EPQS}?x=${d.lon}&y=${d.lat}&wkid=4326&units=Meters&includeDate=false`,`${LEGACY}?x=${d.lon}&y=${d.lat}&output=json&units=Meters`,`${SAMPLES}?geometry=${encodeURIComponent(JSON.stringify({points:[{x:d.lon,y:d.lat,spatialReference:{wkid:4326}}]}))}&geometryType=esriGeometryMultipoint&returnFirstValueOnly=true&f=json`]; for(const raw of urls){try{const j=await json(useProxy?proxyUrl(raw):raw); const v=Number(j.value??j.USGS_Elevation_Point_Query_Service?.Elevation_Query?.Elevation??j.samples?.[0]?.value); if(Number.isFinite(v)&&v>-100000) return {value:v,source:raw.startsWith(EPQS)?'EPQS':raw.startsWith(LEGACY)?'legacy EPQS':'3DEP ImageServer getSamples'};}catch{} } return null; }
async function queryDem(useProxy=false){$('demStatus').textContent=useProxy?'querying through supplied proxy…':'querying direct USGS endpoints…'; const results=await Promise.all(DEM_SAMPLES.map(d=>oneDem(d,useProxy))); let ok=0; results.forEach((hit,i)=>{const el=$('dem-'+DEM_SAMPLES[i].state); if(hit){el.textContent=`USGS ${hit.source} ${hit.value.toFixed(1)} m`;ok++;}else el.textContent='unavailable · no offline raster';}); $('demStatus').textContent=`${ok}/${DEM_SAMPLES.length} samples returned; tried EPQS, legacy EPQS, and 3DEP getSamples${useProxy?' via proxy':''}. Point values are not a DEM tile.`; }
function boot(){ $('countAll').textContent=PLACES.length; $('countOfficial').textContent=PLACES.filter(p=>p.tier==='official').length; render(); renderDem(); $('search').addEventListener('input',e=>render(e.target.value)); $('satellites').innerHTML=SATELLITES.map(s=>`<div class="row"><strong>${esc(s.name)}</strong><span>${esc(s.platform)} · ${s.altitude} km · ${s.repeat} day repeat · ${esc(s.window)}</span><small>${esc(s.status)}</small></div>`).join(''); $('launches').innerHTML=LAUNCHES.map(l=>`<div class="row"><strong>${esc(l.name)}</strong><span>${esc(l.date)} · ${esc(l.site)}</span><small>${esc(l.window)} · ${esc(l.status)}</small></div>`).join(''); $('syncBtn').addEventListener('click',()=>{ $('syncState').textContent='SYNCED LOCALLY'; if(window.webxdc?.sendUpdate) window.webxdc.sendUpdate({status:'gazetteer-sync',summary:`${PLACES.length} merged records`}); }); $('demBtn').addEventListener('click',()=>queryDem(false)); $('proxyBtn').addEventListener('click',()=>queryDem(true)); }
boot();
