// GENERATED by tools/gen_vchip_vectors.mjs — do not edit by hand.
// Source: rtl/scenarios/vchip_scenarios.json + js/vchip-model.js
#pragma once
#include <stdint.h>

struct VMixVec { uint64_t acc; uint64_t dig; uint64_t mix; };

struct VStep {
  uint8_t rst_n, arm, recov, boot, mode, allow_destr, prov_latches;
  uint8_t prov_valid, prov_idx;
  uint64_t prov_vec;
  uint8_t meas_valid, meas_stage;
  uint64_t meas_digest;
  uint8_t cmd_valid, cmd, pwd_ok;
  const char *note;
};

struct VScenario { const char *name; const char *desc; const VStep *steps; int count; };

static const uint64_t VCHIP_SEED = 0x5a5a5a5a5a5a5a5aull;
static const uint64_t VCHIP_GOLDEN_MBR = 0x904e2f69eb77f634ull;
static const uint64_t VCHIP_GOLDEN_EFI = 0x3f4dab614c5f4080ull;
static const uint64_t VCHIP_GOLDEN_LOADER = 0x75c39f3296a3469eull;
static const int VCHIP_VEC_W = 64;
static const int VCHIP_LANES = 4;
static const int VCHIP_ROUNDS = 4;

static const VMixVec VCHIP_MIX_VECTORS[] = {
  { 0x0000000000000000ull, 0x0000000000000000ull, 0xc00bc00bc00bc00bull },
  { 0x0000000000000000ull, 0xffffffffffffffffull, 0x3791379137913791ull },
  { 0xffffffffffffffffull, 0x0000000000000000ull, 0x400b400b400b400bull },
  { 0xffffffffffffffffull, 0xffffffffffffffffull, 0xb790b790b790b790ull },
  { 0x5a5a5a5a5a5a5a5aull, 0x0000000000000000ull, 0x69b169b169b169b1ull },
  { 0x0000000000000000ull, 0x5a5a5a5a5a5a5a5aull, 0xd0e5d0e5d0e5d0e5ull },
  { 0x000000000000ffffull, 0xffff000000000000ull, 0x400a932a18e9bd50ull },
  { 0x00000000ffff0000ull, 0x0000ffff00000000ull, 0x3d50400a132b18e9ull },
  { 0x0123456789abcdefull, 0xfedcba9876543210ull, 0x840be36b0ed19ae0ull },
  { 0x8000000000000000ull, 0x0000000000000001ull, 0xc014c80bc04bc03cull },
  { 0x0000000000000001ull, 0x8000000000000000ull, 0x4013c00bc00bc03bull },
  { 0x856d9c28a9741a02ull, 0x86ad14d4430c32b6ull, 0x45dd9a6c56ab67b2ull },
  { 0xc366ae2c20764753ull, 0xce6336ec93771f1dull, 0x1c4495720de0c685ull },
  { 0x1a79312058b39663ull, 0x3ca10c145535098full, 0xa1c3f140d208e8c1ull },
  { 0x9e66e2665154e05cull, 0xba96d597e9fdde9cull, 0xc3913b9e1b5a8a79ull },
  { 0xa11665ed06c80221ull, 0x480c4fbc1a4b3a65ull, 0x000f282dae6ecf46ull },
  { 0xb6a11497bd5f9551ull, 0x9cefea2e8b1c5e3bull, 0x0f7f7e9ba3ccfabdull },
  { 0xbf1e5a8e8a548847ull, 0x5d0032063244d097ull, 0x50004e9ca9a3208eull },
  { 0xb0ba1fab0cea9cf6ull, 0x333d875f5b54b44full, 0xf361245894e3066aull },
  { 0x030a8c607b88eee7ull, 0x4e0d0726096ca6faull, 0x28e908b193797e4cull },
  { 0xc43b009688e68137ull, 0xa1331aca8f9be1f5ull, 0x7a08114536004a8eull },
  { 0xfcb19f2b96ae0b76ull, 0x468112fb3eaf4ae0ull, 0x0f0dfe6d29dfe917ull },
  { 0xf79edd7dd2b6ac75ull, 0x27a3a789a9ec7c6dull, 0x593bb49fc6046b03ull },
  { 0x3cd6abcb71871fd5ull, 0xdc9c50c2ec0d44aaull, 0x0d5ea5d67557a4c5ull },
  { 0x5c9a817bab5734a3ull, 0x335e4148cb4cd20aull, 0x200226d8dedc42aeull },
  { 0x97a391ce01f3892eull, 0x2ef6453c5b4fe5bcull, 0x6deded9878579713ull },
  { 0x3c0f74a626599577ull, 0xdd251ab0f9e49b9dull, 0xe96be70e9a460470ull },
  { 0xb9810703599615eaull, 0xc5805ed3fe9f0341ull, 0x3008858641bc546dull },
  { 0xe542a8d784c4cd07ull, 0x60c7ee4249e4e55dull, 0xcce24153e44718d9ull },
  { 0xec55e9fb9f4bdbd7ull, 0xcf85ccd472b959a0ull, 0xefb639af011ff3abull },
  { 0x8effc27ad9184313ull, 0x868b3ddacc72d755ull, 0xf7fa21f8b3860b84ull },
  { 0xe9ca7bf6b0c347bbull, 0x2e93cfbd9a6c4ff4ull, 0x0e0d61dc98ad0d97ull },
  { 0x3fd953622763ea6bull, 0xeedcf094e864d77full, 0xb1abf8013545456full },
  { 0x92a9759f004c2111ull, 0xfc19f2701340dd13ull, 0xd43f54697d8ff4d1ull },
  { 0x7c232e1ec8217869ull, 0x743a9330d35000d9ull, 0xbfdbd646c08d1301ull },
  { 0x4680fd930bddb698ull, 0xaa2221383b9eabf5ull, 0x7a381208431eecffull },
  { 0xb7d7de7ceef9cbe2ull, 0xaac9537191c080f5ull, 0x95d2c6de0c238778ull },
  { 0xdeb00a302bb59cb4ull, 0x18f9c97ea0095a8dull, 0xdfa9af9abd428285ull },
  { 0x431f59d9e2be4b78ull, 0xf3fe4248e45ae9eeull, 0xf02fc42c330d7bb5ull },
  { 0x5b3c4c55f16fe7bdull, 0xec2a649a13e77732ull, 0xbf3f3dcfc5618d20ull },
  { 0x08ae355d5a43355cull, 0xe5cbb80bdefd6436ull, 0x67c76e58b17c840cull },
  { 0x3f48e36d7c63537eull, 0x2f92ae39c0908a58ull, 0x154c6cdbfa19c33aull },
  { 0x00ae31f7fce03d4cull, 0x18f3b68970d32e36ull, 0x805b1b2d9ea63c48ull },
  { 0xd5babbddb8ebc5eaull, 0x9e760d75101428e1ull, 0x6069e265ce164f1eull },
  { 0x6335ea6d4bc218f0ull, 0xb8e2f608634fa0c1ull, 0xf2afe0699f6e3d9eull },
  { 0x9cc515670bf92fc0ull, 0x71f51b4a45632d9full, 0x1e1418031768f5a5ull },
  { 0x05bab26334996c04ull, 0x21e2cb0e4693dfdcull, 0xcbb087e09956004cull },
  { 0x73c50ffe9bd48f63ull, 0x81e4ad643f569ebdull, 0x7c925e42eef625cfull },
  { 0x61d7586b88d83cc0ull, 0xb18b419f172cbcb9ull, 0x205e4a51bc922c61ull },
  { 0x7c733949a2baeb80ull, 0x69653d6e3e9b7e57ull, 0xd76b546d6863f538ull },
  { 0x19c53cae51253d6bull, 0x11e391ad78c74dd1ull, 0xc915bb9b00b48189ull },
  { 0x46806677d44b970aull, 0x4954b6085eaf82a4ull, 0xe37171e77005505full },
  { 0xf366bdebfce4f4a1ull, 0xcf756c9be6a43508ull, 0x095dd2b91f98da03ull },
  { 0xdafc21e580013f62ull, 0x7ff1c983279aa59cull, 0x22c7faf669ce9f66ull },
  { 0x1a1909b47c6177d7ull, 0x89319d4963cea0f8ull, 0xabe449d0820c99aeull },
  { 0xbb482d2ed1cc03b9ull, 0xe662d2c9d4e455feull, 0x9f39a113dd58974bull },
  { 0x8248764bb14d22d5ull, 0x895da0198a9dadd0ull, 0x81806ee14c17a0c4ull },
  { 0x65f57adb6e4fe28bull, 0x5d422549c826bf8eull, 0xc98ac8200283a0a2ull },
  { 0x8d33c1a4270ad171ull, 0x6372a47286f8b893ull, 0x2fc38bc90cd542c5ull },
  { 0x2d1a98d6d08d0d22ull, 0xfa79bdd4c0bb1fb8ull, 0x3b6f31cca5ee12ddull },
  { 0x8b48eb9d2b048787ull, 0xe7d7b9675e138f48ull, 0x4779addb340864a0ull },
  { 0x58da6f4a91097a56ull, 0xa33b896f137b3d22ull, 0xc4c9b3609c9459d0ull },
  { 0x5c1eafbbf386c3d8ull, 0x8c2b793ccd14385full, 0xe4b9e8b0fc281e2bull },
  { 0x10741448b955e7efull, 0x61117a226e6357e0ull, 0x059b523eca0e51e7ull },
  { 0x75ca2cad0a08694full, 0x55d08ca84b95ca5dull, 0xc3dd470036635d18ull },
  { 0x596f80a6ea29d689ull, 0xfe9985ea19910764ull, 0xbcb8a4d9b3f29424ull },
  { 0xd1139d4b71db7c6aull, 0xaed27a43de4e9012ull, 0x5c693cf4fa5c81f3ull },
  { 0x8b4b05218b3049b2ull, 0x3e66f02b064005a1ull, 0xd72b3334be48f3abull },
  { 0x4e26d6315b2dcdeaull, 0xec95aa0512b7acf1ull, 0x8ddb102f36c7afc8ull },
  { 0x1de0238cff37dfe8ull, 0x27873e94446d4a57ull, 0x44511bf80fde4cddull },
  { 0xfb3ea08e14fbe503ull, 0x56dba9c32e993209ull, 0x8db47fa43aa875a1ull },
  { 0x34b45a1b6c93a22dull, 0x0d44cc2956b5ae29ull, 0x3b5c12c221954138ull },
  { 0x5f8c5c5ec2dc6f35ull, 0xc3b5004430f2baabull, 0xe75d6b863ef6da46ull },
  { 0x99d75b87f954951eull, 0xa58a89a54648bbb4ull, 0x57eb2f7812d5152bull },
  { 0x4f0a4e16061a47c3ull, 0x3954d7372367e38cull, 0x97138e3c23a05286ull },
  { 0x0c8f866df63e4f4bull, 0x840c6b8a69828115ull, 0x3e583290e577b593ull },
  { 0xb08147518f7d6157ull, 0xd9fd1e7103bb2e55ull, 0xddf26789b456f80full },
  { 0xca338d00b02f6d49ull, 0xc2821249d49b41d3ull, 0x12a1d0fdd045d01bull },
  { 0xfcdcad3bcef86390ull, 0x2f333553e5a17757ull, 0x591569e359262daaull },
  { 0xbfe272ce042f0079ull, 0x7a0622ffb39a6039ull, 0x7883dd33b52a616aull },
  { 0x716eabe113107ab9ull, 0xfc7a986fb267d40cull, 0x83e29e04d6af03bfull },
  { 0xafd79c103f3f98a4ull, 0x3d6d77a6be994e95ull, 0xbf9bbbb32c7f409bull },
  { 0xb4d46bff8ef57948ull, 0xa3f20a2ae0ebc1baull, 0xec838ca7bc0b723aull },
  { 0x9245d741869f38b9ull, 0x504636cb545b0888ull, 0x61c0340de3c0ec49ull },
  { 0x524308b98c129c99ull, 0x11a1c134d7febfe0ull, 0x5bc66442cf77a585ull },
  { 0x832d7979e33cba9full, 0xaf72d09b40d3842aull, 0xe5c03a74c33cf30aull },
  { 0x036b1f9ce17269a2ull, 0x0532208882fca5f1ull, 0x30d26c1e78c6bc61ull },
  { 0xaccc066ab99a00faull, 0x8bafc717de804a7bull, 0xca7c04a917125993ull },
  { 0x3ed7167f303eb42full, 0x5e90ef7452782287ull, 0x5593ba4fe2b1f35aull },
  { 0x701ad8f806809302ull, 0x8c635a0a618112a4ull, 0xb034f1c0d2d195ebull },
  { 0x42c03cb244503981ull, 0xf47cbf1d8082d9b2ull, 0x64eb3cdee75a135cull },
  { 0x017fb1142101f081ull, 0xe80f6101916ff320ull, 0x39125a7203937252ull },
  { 0x1f336221fe59e4c6ull, 0x15339dd85a5aa68full, 0x3e9438490290568dull },
  { 0x6939d69288925002ull, 0xf253d6a1ab533422ull, 0x427750624472d8a6ull },
  { 0x518e5895efd8dacaull, 0x22e18e751a9699ffull, 0xdfe5b536ef99f629ull },
  { 0xf5f27f09d0222b0cull, 0x7c687f55d6dd2c5aull, 0x9d8d75a4ce9c7b69ull },
  { 0xf36f1f64eeb4c082ull, 0x1bcca124814fc983ull, 0x701afb0b025d7cb4ull },
  { 0x4c292471cf2f56d0ull, 0xcf2848d27544bc7dull, 0xc7dcca858130efadull },
  { 0x03524c6b03848a45ull, 0x6ecdd990c1cbb211ull, 0xcae51e62b8ac28f1ull },
  { 0xa801f7e7e68c8135ull, 0x7590c5aef0a97577ull, 0xb8a26664a7f97fccull },
  { 0xcee602fb9d019a5dull, 0x09d631944544ae29ull, 0x100bcbd5d27c5f3eull },
  { 0x2ee6220fb34a8d35ull, 0xdceec59dc5f7f56full, 0xc5a829f4b7b9a187ull },
  { 0x8be73d803fa6a145ull, 0x448f90b238d71d47ull, 0x296d4a4648f7499full },
  { 0x7ffbf1958fb302bdull, 0xa40c8295ffcb6bf8ull, 0x3a8f0a92d58792f4ull },
  { 0x361a16344dcf032full, 0x39504b51db23b6e9ull, 0xef2c13199f60fcd3ull },
  { 0x39f1899f112d6bc4ull, 0xd6087d37490b4013ull, 0xb97725dca2c05488ull },
  { 0x4a61d3a869ed3253ull, 0x9ea53f58ddd61cf7ull, 0x6bd806bd844370e2ull }
};
static const int VCHIP_MIX_VECTOR_COUNT = (int)(sizeof(VCHIP_MIX_VECTORS) / sizeof(VMixVec));

static const VStep SC_HONEST_BOOT[] = {
  { 0, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "power-on reset" },
  { 0, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "reset held" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "reset released; lock idle, no golden vector yet" },
  { 1, 1, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "arming strap asserted" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 0, 0x904e2f69eb77f634ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "fixture writes golden for LBA0" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 1, 0x3f4dab614c5f4080ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "fixture writes golden for the ESP" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 2, 0x75c39f3296a3469eull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "fixture writes golden for the loader; fuse burnt" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 1, 0, 0x1122334455667788ull, 0, 0, 0, "measure LBA0 bootstrap" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 1, 1, 0x99aabbccddeeff00ull, 0, 0, 0, "measure EFI system partition" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 1, 2, 0x0123456789abcdefull, 0, 0, 0, "measure second-stage loader" },
  { 1, 0, 0, 2, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "platform presents a UEFI boot source" },
  { 1, 0, 0, 2, 0, 1, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 202, 0, "ATA WRITE DMA" },
  { 1, 0, 0, 2, 0, 1, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 241, 0, "hdparm: SECURITY SET PASSWORD" },
  { 1, 0, 0, 2, 0, 1, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 243, 1, "hdparm: SECURITY ERASE PREPARE" },
  { 1, 0, 0, 2, 0, 1, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 244, 1, "hdparm: SECURITY ERASE UNIT" },
  { 1, 0, 0, 2, 0, 1, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 245, 0, "hdparm: SECURITY FREEZE LOCK" },
  { 1, 0, 0, 2, 0, 1, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 242, 1, "hdparm: SECURITY UNLOCK after freeze -> refused" }
};

static const VStep SC_TAMPERED_MBR[] = {
  { 0, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "power-on reset" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 1, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 0, 0x904e2f69eb77f634ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 1, 0x3f4dab614c5f4080ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 2, 0x75c39f3296a3469eull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "fuse burnt" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 1, 0, 0xdeadbeefcafebabeull, 0, 0, 0, "modified bootstrap: digest mismatch" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 1, 1, 0x99aabbccddeeff00ull, 0, 0, 0, "attacker then presents a good ESP: refused, lock is closed" },
  { 1, 0, 0, 2, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "boot source presented to a locked chipset" },
  { 1, 0, 0, 2, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 202, 0, "ATA WRITE DMA" },
  { 1, 0, 0, 2, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 241, 0, "hdparm: SECURITY SET PASSWORD" },
  { 1, 0, 0, 2, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 243, 1, "hdparm: SECURITY ERASE PREPARE" },
  { 1, 0, 0, 2, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 244, 1, "hdparm: SECURITY ERASE UNIT -> denied by chipset policy" },
  { 1, 0, 0, 2, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 254, 0, "vendor reflash -> denied" },
  { 1, 0, 1, 2, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "recovery strap: re-provisioning only, not erasure" },
  { 1, 0, 1, 2, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 254, 0, "reflash while recovery strap is asserted -> still denied on a tampered box" }
};

static const VStep SC_STAGE_SKIP[] = {
  { 0, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 1, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 0, 0x904e2f69eb77f634ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 1, 0x3f4dab614c5f4080ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 2, 0x75c39f3296a3469eull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 1, 1, 0x99aabbccddeeff00ull, 0, 0, 0, "ESP measured before LBA0" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 1, 0, 0x1122334455667788ull, 0, 0, 0, "backfill attempt ignored" }
};

static const VStep SC_BOOT_MODE_POLICY[] = {
  { 0, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 1, 0, 0, 2, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "policy: UEFI only, CSM disabled" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 0, 0x904e2f69eb77f634ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 1, 0x3f4dab614c5f4080ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 2, 0x75c39f3296a3469eull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 1, 0, 0x1122334455667788ull, 0, 0, 0, "" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 1, 1, 0x99aabbccddeeff00ull, 0, 0, 0, "" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 1, 2, 0x0123456789abcdefull, 0, 0, 0, "chain complete and matched" },
  { 1, 0, 0, 1, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "legacy/CSM source presented under a UEFI-only policy" },
  { 1, 0, 0, 2, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "the UEFI source is accepted" }
};

static const VStep SC_PROVISION_ATTACK[] = {
  { 0, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 1, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 0, 0x904e2f69eb77f634ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 1, 0x3f4dab614c5f4080ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 2, 0x75c39f3296a3469eull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "fuse burnt" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 1, 0, 0x1122334455667788ull, 0, 0, 0, "first measurement closes provisioning" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 0, 0xdeadbeefcafebabeull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "rewrite the root of trust to match the attacker" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 1, 1, 0x99aabbccddeeff00ull, 0, 0, 0, "everything after the violation is inert" }
};

static const VStep SC_ATTEMPT_COUNTER[] = {
  { 0, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 1, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 0, 0x904e2f69eb77f634ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 1, 0x3f4dab614c5f4080ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 2, 0x75c39f3296a3469eull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 1, 0, 0x1122334455667788ull, 0, 0, 0, "" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 1, 1, 0x99aabbccddeeff00ull, 0, 0, 0, "" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 1, 2, 0x0123456789abcdefull, 0, 0, 0, "" },
  { 1, 0, 0, 2, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 241, 0, "hdparm: SECURITY SET PASSWORD" },
  { 1, 0, 0, 2, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 242, 0, "wrong password 1" },
  { 1, 0, 0, 2, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 242, 0, "wrong password 2" },
  { 1, 0, 0, 2, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 242, 0, "wrong password 3" },
  { 1, 0, 0, 2, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 242, 0, "wrong password 4" },
  { 1, 0, 0, 2, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 242, 0, "wrong password 5: counter spent" },
  { 1, 0, 0, 2, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 242, 1, "the correct password no longer unlocks" },
  { 1, 0, 0, 2, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 243, 1, "hdparm: SECURITY ERASE PREPARE" },
  { 1, 0, 0, 2, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 244, 1, "hdparm: SECURITY ERASE UNIT -> policy denies destructive history erasure" },
  { 1, 0, 0, 2, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 202, 0, "writes were already blocked by the locked drive" }
};

static const VStep SC_RECOVERY_STRAP[] = {
  { 0, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 1, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 0, 0x904e2f69eb77f634ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 1, 0x3f4dab614c5f4080ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 2, 0x75c39f3296a3469eull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 1, 0, 0xdeadbeefcafebabeull, 0, 0, 0, "tampered bootstrap latches the lock" },
  { 1, 0, 1, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "recovery strap asserted: no help, the latch is not pre-boot any more" },
  { 0, 0, 1, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "fixture cycle: power-on reset with the strap held" },
  { 1, 1, 1, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "pre-boot window: recovery is active" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 0, 0x904e2f69eb77f634ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "re-key the root of trust" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 1, 0x3f4dab614c5f4080ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 2, 0x75c39f3296a3469eull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 1, 254, 0, "vendor reflash during recovery: refused, chain not complete" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 1, 0, 0x1122334455667788ull, 0, 0, 0, "" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 1, 1, 0x99aabbccddeeff00ull, 0, 0, 0, "" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 1, 2, 0x0123456789abcdefull, 0, 0, 0, "" },
  { 1, 0, 0, 2, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "re-keyed device hands control to the measured stage" }
};

static const VStep SC_PROV_RACE[] = {
  { 0, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 1, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 0, 0x904e2f69eb77f634ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 1, 0x3f4dab614c5f4080ull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 1, 0, 0, 0, 1, 1, 2, 0x75c39f3296a3469eull, 0, 0, 0x0000000000000000ull, 0, 0, 0, "" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 1, 0, 0x1122334455667788ull, 0, 0, 0, "" },
  { 1, 0, 0, 0, 0, 0, 1, 1, 0, 0xdeadbeefcafebabeull, 1, 1, 0x99aabbccddeeff00ull, 0, 0, 0, "violation and measurement in the same cycle" },
  { 1, 0, 0, 0, 0, 0, 1, 0, 0, 0x0000000000000000ull, 1, 2, 0x0123456789abcdefull, 0, 0, 0, "the chain can never complete after this" }
};

static const VScenario VCHIP_SCENARIOS[] = {
  { "honest_boot", "Provision three stages, arm, measure MBR -> ESP -> loader in order with the right digests, then use the media and grant a password-authorized erase.", SC_HONEST_BOOT, (int)(sizeof(SC_HONEST_BOOT) / sizeof(VStep)) },
  { "tampered_mbr", "The bootstrap on the disk does not match the golden vector. Everything after that must be denied, and the destructive-command refusal is the point.", SC_TAMPERED_MBR, (int)(sizeof(SC_TAMPERED_MBR) / sizeof(VStep)) },
  { "stage_skip", "A loader that skips straight to the ESP, i.e. an attempt to reorder or omit a stage. Order violation latches immediately.", SC_STAGE_SKIP, (int)(sizeof(SC_STAGE_SKIP) / sizeof(VStep)) },
  { "boot_mode_policy", "UEFI-only policy. The legacy MBR path is refused even with a perfect chain, and vice versa.", SC_BOOT_MODE_POLICY, (int)(sizeof(SC_BOOT_MODE_POLICY) / sizeof(VStep)) },
  { "provision_attack", "After the first accepted measurement the reference vectors are frozen. A late provisioning attempt is refused and (by policy) is treated as tamper.", SC_PROVISION_ATTACK, (int)(sizeof(SC_PROVISION_ATTACK) / sizeof(VStep)) },
  { "attempt_counter", "Five wrong passwords exhaust the ATA attempt counter. With destructive operations denied by policy the device cannot be recovered in-band, which is the documented cost of refusing to erase.", SC_ATTEMPT_COUNTER, (int)(sizeof(SC_ATTEMPT_COUNTER) / sizeof(VStep)) },
  { "recovery_strap", "Physical presence before first handoff re-opens provisioning so a fixture can re-key the device. It never grants erasure and never reflashes a tampered box.", SC_RECOVERY_STRAP, (int)(sizeof(SC_RECOVERY_STRAP) / sizeof(VStep)) },
  { "prov_race", "A provisioning violation landing in the same cycle as a valid measurement. The attack must win: the measurement is refused and the lock latches, instead of leaving tampered-but-not-locked for a cycle. The SAT solver found this race, so it is pinned here.", SC_PROV_RACE, (int)(sizeof(SC_PROV_RACE) / sizeof(VStep)) }
};
static const int VCHIP_SCENARIO_COUNT = (int)(sizeof(VCHIP_SCENARIOS) / sizeof(VScenario));
