/* GENERATED by four-corners-calc/tools/xdc2c.py from four-corners.xdc — do not edit.
 *
 * Source of truth is the bundle, not this file. Regenerate with:
 *     make -C four-corners-calc data
 *
 * 8 layers  3 corridors (19 vertices)  24 sites + 47 register rows  31 control points
 * Positions are u16 in units of 1/2000 degree; worst-case quantisation
 * error 22.3 m, against curated point data and a context-tier relief.
 */

#ifndef FCDATA_H
#define FCDATA_H

#define FC_NLAYER          8   /* layers */
#define FC_NCOR            3   /* corridors: 2 state lines + the San Juan River */
#define FC_NNODE           71   /* point features: sites, then the gazetteer register */
#define FC_NSITE           24   /* dossier sites (necks, energy, uranium, ruins) */
#define FC_NREG            47   /* gazetteer register rows */
#define FC_NPT             19   /* corridor vertices */
#define FC_NTER            31   /* IDW terrain control points */
#define FC_STRB            4572   /* string pool bytes */
#define FC_Q               2000   /* quantisation units per degree */
#define FC_LON_BASE_M      -110600   /* lon origin, 1/1000 deg */
#define FC_LAT_BASE_M      35800   /* lat origin, 1/1000 deg */
#define FC_SPAN_LON        5600   /* frame width in quant units */
#define FC_SPAN_LAT        4200   /* frame height in quant units */
#define FC_CENTER_LON_M    -109045   /* projection centre, 1/1000 deg */
#define FC_CENTER_LAT_M    36999   /* projection centre, 1/1000 deg */
#define FC_COSLAT_Q12      3271   /* cos(centre latitude) in Q12 */
#define FC_KMDEG_Q4        1781   /* km per degree of latitude, Q4 */
#define FC_QUAD_LON_Q      3110   /* the SURVEYED quadripoint, qlon */
#define FC_QUAD_LAT_Q      2398   /* the SURVEYED quadripoint, qlat */
#define FC_TIER_OFFICIAL   0
#define FC_TIER_COMMUNITY  1
#define FC_TIER_CONTEXT    2
#define FC_KIND_TERRAIN    0
#define FC_KIND_LINE       1
#define FC_KIND_NODE       2

/* IDW relief field: power 2.4, snap inside 0.5 km, from four-corners-geo.js */
#define FC_ELEV_BASE       1500   /* metres returned when every weight underflows (unreachable) */
#define FC_KMQ_Q12         228   /* km per lat-quant unit, Q12 */
#define FC_SNAP_Q          81   /* 0.25 km2 snap radius in quant2 units */
#define FC_IDW_MUL         307   /* weight exponent 1.2 in Q8: t = (log2(d2)*FC_IDW_MUL)>>8 */
#define FC_WBIAS           14   /* w = (FC_EXP2_Q16[f] << FC_WBIAS) >> n, see core/geo.c */

/* the port's own log depth ramp for the section screen (the app has none) */
#define FC_DEPTH_A_Q8      90   /* mag = a + b*log10(1+|m|), Q8 */
#define FC_DEPTH_B_Q8      115

/* string-pool offsets for the UI chrome */
#define FL_TITLE           4146
#define FL_FOUR            4159
#define FL_CORNERS         4164
#define FL_SUB             4172
#define FL_PRESS           4189
#define FL_MAP             4203
#define FL_PROF            4207
#define FL_LAYERS          4215
#define FL_DOS             4222
#define FL_INFO            4230
#define FL_OFFICIAL        4237
#define FL_COMMUNITY       4246
#define FL_CONTEXT         4256
#define FL_TIER            4264
#define FL_LAYER           4270
#define FL_ELEV            4277
#define FL_MAX             4283
#define FL_DEPTH           4288
#define FL_LEN             4295
#define FL_KM              4300
#define FL_M               4304
#define FL_FT              4307
#define FL_LON             4311
#define FL_LAT             4316
#define FL_NOTDEM          4321
#define FL_SURVEY          4345
#define FL_REGNOTE         4371
#define FL_TRANSECT        4390
#define FL_ALONG           4403
#define FL_ON              4415
#define FL_OFF             4418
#define FL_VIS             4422
#define FL_SLASH           4427
#define FL_CORR            4429
#define FL_SITES           4440
#define FL_REG             4447
#define FL_VERTS           4457
#define FL_TER             4467
#define FL_LCD             4480
#define FL_RAM             4485
#define FL_XDC             4490
#define FL_QUANT           4507
#define FL_ZOOM            4523
#define FL_IDW             4525
#define FL_TI83            4529
#define FL_TI89            4535
#define FL_TI92            4541
#define FL_HOST            4547
#define FL_Z80             4552
#define FL_M68K            4556
#define FL_LAYERSON        4561

extern const u16 FC_PT[];
extern const u16 FC_COR_OFF[];
extern const u8 FC_COR_LAYER[];
extern const u8 FC_COR_TIER[];
extern const u16 FC_COR_KM[];
extern const u16 FC_COR_NAME[];
extern const u16 FC_COR_FACT[];
extern const u16 FC_NODE_Q[];
extern const u8 FC_NODE_LAYER[];
extern const u8 FC_NODE_TIER[];
extern const u8 FC_NODE_REG[];
extern const i16 FC_NODE_ELEV[];
extern const i16 FC_NODE_DEPTH[];
extern const u16 FC_NODE_NAME[];
extern const u16 FC_NODE_KIND[];
extern const u16 FC_NODE_FACT[];
extern const u16 FC_TER[];
extern const u16 FC_LAYER_NAME[];
extern const u8 FC_LAYER_KIND[];
extern const u8 FC_LAYER_ON[];
extern const u8 FC_STR[];

#endif
