/* FOUR CORNERS — portable core for the TI-92, TI-89 and TI-83.
 *
 * This is the calculator port of four-corners.xdc: the quadripoint-country
 * theater of the Navajo volcanic field necks, the San Juan energy basin, the
 * uranium legacy ring and the Ancestral Puebloan core, reduced to one 1-bit
 * framebuffer, integer arithmetic and a keypad.
 *
 * The 1-bit runtime underneath it — types, framebuffer, 3x5 font, integer
 * helpers, key codes — is NOT forked. It is SITE-K's, from calc/core, built
 * from the same files by the same compilers:
 *
 *     calc/core/sitek.h    types, FB_MAX, DEV_*, SKK_*, PX_*, FILL_*, fb_*
 *     calc/core/tables.c   3x5 font, 64-step sine, log2 mantissa
 *     calc/core/util.c     idiv/imod, u32w/mul32/shr32, log2_q8
 *     calc/core/fb.c       pixel/line/box/text into SK_FB
 *
 * What this port adds is in four-corners-calc/core:
 *
 *     fcdata.[ch]     GENERATED from the .xdc by tools/xdc2c.py
 *     fctables.c      GENERATED by tools/gen_tables.py (exp2 fraction)
 *     geo.c           integer projection, IDW terrain field, log depth ramp
 *     app.c           five screens and the key dispatch
 *
 * Same dialect as calc/core, enforced by calc/tools/c2js.py:
 *   integer only, no float, no libc, no malloc, no struct, no pointer
 *   arithmetic, no ternary, no switch, declarations at block top.
 */
#ifndef FOURCORNERS_H
#define FOURCORNERS_H

#include "sitek.h"
#include "fcdata.h"

/* ---------- screens ---------- */
#define FC_SCR_BOOT 0
#define FC_SCR_MAP 1
#define FC_SCR_PROF 2
#define FC_SCR_LAYERS 3
#define FC_SCR_DOS 4
#define FC_SCR_INFO 5
#define FC_NSCREEN 6

/* ---------- feature classes in the unified selection list ---------- */
#define FC_CLS_COR 0
#define FC_CLS_NODE 1

#define FC_NFEAT (FC_NCOR + FC_NNODE)

/* ---------- line styles, standing in for the web app's tier colours ------- */
#define FC_STY_SOLID 0
#define FC_STY_DASH 1
#define FC_STY_DOT 2

/* Longest profile the section screen will sample (TI-92 is 240 wide). */
#define FC_PROF_MAX 232

/* ---------- live state ---------- */
extern u8 FC_SCREEN;
extern u16 FC_SEL;      /* index into the unified feature list */
extern u8 FC_ZOOM;      /* 0..3 -> 1x, 2x, 4x, 8x on the selected feature */
extern u8 FC_DEPTHX;    /* depth exaggeration step for the hung reservoirs */
extern u8 FC_PROFMODE;  /* 0 = along the route, 1 = W-E transect */
extern u8 FC_LAYCUR;    /* cursor on the LAYERS screen */
extern u8 FC_LAYON[FC_NLAYER];

/* ---------- geo.c ---------- */
extern const u16 FC_EXP2_Q16[257];   /* 2^(-i/256) in Q16, from core/fctables.c */
i32 idiv32(i32 a, i32 b);
i32 fc_elev_q(i32 qlon, i32 qlat);
i32 fc_elev_deg(i32 lon_m, i32 lat_m);
u16 fc_depth_mag_q8(i32 metres);
u16 fc_isqrt32(u32 v);
u16 fc_km_span(i32 dqlon, i32 dqlat);
i32 fc_lon_mdeg(u16 q);
i32 fc_lat_mdeg(u16 q);

void fc_view(void);
int fc_px(u16 q);
int fc_py(u16 q);
extern u16 FC_MX;
extern u16 FC_MY;
extern u16 FC_MW;
extern u16 FC_MH;
extern i32 FC_VX;
extern i32 FC_VY;
extern i32 FC_VW;
extern i32 FC_VH;
extern i32 FC_KX;
extern i32 FC_KY;

/* ---------- app.c ---------- */
void fcorner_init(u8 dev, u16 w, u16 h);
void fcorner_key(u8 k);
void fcorner_tick(void);
void fcorner_render(void);
void fcorner_set_screen(u8 scr);
u8 fcorner_get_screen(void);
void fcorner_set_sel(u16 i);
u16 fcorner_get_sel(void);
void fcorner_toggle_layer(u8 i);
u8 fcorner_layer_on(u8 i);
u16 fcorner_feat_count(void);
u8 fcorner_feat_class(u16 f);
u16 fcorner_feat_sub(u16 f);
u8 fcorner_feat_layer(u16 f);
u8 fcorner_feat_tier(u16 f);
u16 fcorner_feat_name(u16 f);
u16 fcorner_feat_kind(u16 f);
u8 fcorner_feat_reg(u16 f);
u16 fcorner_visible(void);
u16 fcorner_layer_name(u8 i);
u8 fcorner_layer_kind(u8 i);
u16 fcorner_feat_qlon(u16 f);
u16 fcorner_feat_qlat(u16 f);
i32 fcorner_feat_elev(u16 f);
i32 fcorner_feat_depth(u16 f);
u16 fc_str(u8 *dst, u16 off);
u16 fc_str_at(u8 *dst, u16 at, u16 off);
u16 fc_num_at(u8 *dst, u16 at, i32 v);
u16 fc_deg_at(u8 *dst, u16 at, i32 mdeg);
u16 fc_dev_label(u8 dev);
u16 fc_dev_cpu(u8 dev);
u16 fc_dev_ram(u8 dev);
void fcorner_set_zoom(u8 z);
void fcorner_set_depthx(u8 d);
void fcorner_set_profmode(u8 m);
void fcorner_set_laycur(u8 i);
u16 fc_prof_km(void);
u16 fc_prof_n(void);
i32 fc_prof_elev(u16 i);

#endif
