#!/usr/bin/env python3
"""Generate the constant tables shared by every SITE-K calculator target.

Everything the core needs at link time is integer data, so the tables are
emitted as plain C arrays and consumed identically by:

    sdcc (Z80: TI-83 / TI-85 / TI-90),  gcc4ti (m68k: TI-89 / TI-92),
    gcc (host tests)                    and the C->JS transpiler (web).

Run:  python3 calc/tools/gen_tables.py > calc/core/tables.c
"""

import math

# 3x5 glyphs. Each row is 3 bits: bit2 = left pixel, bit1 = middle, bit0 = right.
GLYPHS = {
    "0": ["111", "101", "101", "101", "111"],
    "1": ["010", "110", "010", "010", "111"],
    "2": ["111", "001", "111", "100", "111"],
    "3": ["111", "001", "111", "001", "111"],
    "4": ["101", "101", "111", "001", "001"],
    "5": ["111", "100", "111", "001", "111"],
    "6": ["111", "100", "111", "101", "111"],
    "7": ["111", "001", "001", "001", "001"],
    "8": ["111", "101", "111", "101", "111"],
    "9": ["111", "101", "111", "001", "111"],
    " ": ["000", "000", "000", "000", "000"],
    ".": ["000", "000", "000", "000", "010"],
    "-": ["000", "000", "111", "000", "000"],
    ":": ["000", "010", "000", "010", "000"],
    "/": ["001", "001", "010", "100", "100"],
    "+": ["000", "010", "111", "010", "000"],
    "*": ["101", "010", "101", "000", "000"],
    "#": ["101", "111", "101", "111", "101"],
    "A": ["111", "101", "111", "101", "101"],
    "B": ["110", "101", "110", "101", "110"],
    "C": ["111", "100", "100", "100", "111"],
    "D": ["110", "101", "101", "101", "110"],
    "E": ["111", "100", "111", "100", "111"],
    "F": ["111", "100", "111", "100", "100"],
    "G": ["111", "100", "101", "101", "111"],
    "H": ["101", "101", "111", "101", "101"],
    "I": ["111", "010", "010", "010", "111"],
    "J": ["001", "001", "001", "101", "111"],
    "K": ["101", "101", "110", "101", "101"],
    "L": ["100", "100", "100", "100", "111"],
    "M": ["101", "111", "111", "101", "101"],
    "N": ["110", "101", "101", "101", "101"],
    "O": ["111", "101", "101", "101", "111"],
    "P": ["111", "101", "111", "100", "100"],
    "Q": ["111", "101", "101", "111", "001"],
    "R": ["111", "101", "111", "110", "101"],
    "S": ["111", "100", "111", "001", "111"],
    "T": ["111", "010", "010", "010", "010"],
    "U": ["101", "101", "101", "101", "111"],
    "V": ["101", "101", "101", "101", "010"],
    "W": ["101", "101", "111", "111", "101"],
    "X": ["101", "101", "010", "101", "101"],
    "Y": ["101", "101", "010", "010", "010"],
    "Z": ["111", "001", "010", "100", "111"],
}

# Index order in FONT3x5 — must match font_index() in core/fb.c
ORDER = "0123456789 .-:+/*#" + "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

SIN_STEPS = 64      # full circle, 5.625 degrees per step
SIN_SCALE = 4096    # Q12
LOG2_SCALE = 256    # Q8 mantissa table


def emit(name, values, ctype="const i16", per_line=12):
    out = ["%s %s[%d] = {" % (ctype, name, len(values))]
    for i in range(0, len(values), per_line):
        chunk = values[i : i + per_line]
        out.append("  " + ", ".join(str(v) for v in chunk) + ",")
    out.append("};")
    return "\n".join(out)


def main() -> None:
    font = []
    for ch in ORDER:
        for row in GLYPHS[ch]:
            font.append(int(row, 2))
    assert len(font) == len(ORDER) * 5

    sin = [int(round(math.sin(2 * math.pi * i / SIN_STEPS) * SIN_SCALE)) for i in range(SIN_STEPS)]

    # log2(1 + m/256) * 256, for the 8-bit mantissa of log2_q8()
    log2 = [int(round(math.log2(1.0 + m / 256.0) * LOG2_SCALE)) if m else 0 for m in range(256)]

    print("/* Generated by calc/tools/gen_tables.py — do not edit by hand. */")
    print("#include \"sitek.h\"")
    print()
    print("/* 3x5 bitmap font, 5 rows per glyph, 3 bits per row (bit2 = left). */")
    print("/* Glyph order: %s */" % ORDER.replace("/*", "/ *"))
    print(emit("FONT3x5", font, ctype="const u8", per_line=15))
    print()
    print("/* sin(2*pi*i/64) in Q12. */")
    print(emit("SIN_Q12", sin, ctype="const i16", per_line=8))
    print()
    print("/* 256 * log2(1 + m/256) for the 8-bit mantissa of log2_q8(). */")
    print(emit("LOG2_MANT", log2, ctype="const u8", per_line=16))


if __name__ == "__main__":
    main()
