<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE eagle SYSTEM "eagle.dtd">
<!-- generated by tools/build-wallplug-eagle.mjs from tools/wallplug-model.mjs — do not edit by hand -->
<eagle version="9.6.2">
<drawing>
<settings><setting alwaysvectorfont="no"/>
<setting verticaltext="up"/></settings>

<grid distance="2.54" unitdist="mm" unit="mm" style="lines" multiple="1" display="yes" altdistance="0.635" altunitdist="mm" altunit="mm"/>
<layers><layer number="90" name="Modules" color="5" fill="1" visible="yes" active="yes"/>
<layer number="91" name="Nets" color="2" fill="1" visible="yes" active="yes"/>
<layer number="92" name="Busses" color="1" fill="1" visible="yes" active="yes"/>
<layer number="93" name="Pins" color="2" fill="1" visible="yes" active="yes"/>
<layer number="94" name="Symbols" color="4" fill="1" visible="yes" active="yes"/>
<layer number="95" name="Names" color="7" fill="1" visible="yes" active="yes"/>
<layer number="96" name="Values" color="7" fill="1" visible="yes" active="yes"/>
<layer number="97" name="Info" color="7" fill="1" visible="yes" active="yes"/>
<layer number="98" name="Guide" color="6" fill="1" visible="yes" active="yes"/></layers>
<schematic xreflabel="%F%N/%S.%C%R" xrefpart="/%S.%C%R"><description>xPort Wallplug: mains-powered RS-232 ↔ Ethernet adapter around a Lantronix xPort Pro (16 MB flash)</description>
<libraries><library name="lantronix-wallplug"><description>lantronix-wallplug: xPort Wallplug design library (generated by tools/build-wallplug-eagle.mjs from tools/wallplug-model.mjs)</description>
<packages><package name="XPORTPRO"><description>Lantronix xPort Pro / xPort Pro Lx6 embedded device server, RJ45 at +X (front)</description>
<wire x1="-18.42" y1="8.5" x2="15.48" y2="8.5" width="0.2032" layer="21"/>
<wire x1="15.48" y1="8.5" x2="15.48" y2="-8.5" width="0.2032" layer="21"/>
<wire x1="15.48" y1="-8.5" x2="-18.42" y2="-8.5" width="0.2032" layer="21"/>
<wire x1="-18.42" y1="-8.5" x2="-18.42" y2="8.5" width="0.2032" layer="21"/>
<wire x1="2.38" y1="8.5" x2="6.13" y2="8.5" width="0.2032" layer="51" style="shortdash"/>
<wire x1="2.38" y1="-8.5" x2="6.13" y2="-8.5" width="0.2032" layer="51" style="shortdash"/>
<wire x1="12" y1="6" x2="12" y2="-6" width="0.2032" layer="51" style="shortdash"/>
<text x="-14" y="-0.6" size="1.27" layer="51" rot="R0">FRONT (RJ45)</text>
<text x="16.6" y="-8.2" size="1.27" layer="25" rot="R90">&gt;NAME</text>
<text x="10" y="-1" size="1" layer="27" rot="R90">&gt;VALUE</text>
<pad name="1" x="1.27" y="-3.58" drill="0.9" diameter="1.8" shape="square"/>
<pad name="2" x="-1.27" y="-2.31" drill="0.9" diameter="1.8"/>
<pad name="3" x="1.27" y="-1.04" drill="0.9" diameter="1.8"/>
<pad name="4" x="-1.27" y="0.23" drill="0.9" diameter="1.8"/>
<pad name="5" x="1.27" y="1.5" drill="0.9" diameter="1.8"/>
<pad name="6" x="-1.27" y="2.77" drill="0.9" diameter="1.8"/>
<pad name="7" x="1.27" y="4.04" drill="0.9" diameter="1.8"/>
<pad name="8" x="-1.27" y="5.31" drill="0.9" diameter="1.8"/>
<pad name="S1" x="4.28" y="8.025" drill="1.6764" diameter="3.175" shape="square"/>
<pad name="S2" x="4.28" y="-8.025" drill="1.6764" diameter="3.175" shape="square"/>
<hole x="-7.62" y="6.15" drill="3.5"/>
<hole x="-7.62" y="-6.15" drill="3.5"/></package>
<package name="HLKPM03"><description>Hi-Link HLK-PM03 3 W AC/DC module, 85-265 VAC in, 3.3 V / 1 A out, 3 kV isolation</description>
<wire x1="-17" y1="10.1" x2="17" y2="10.1" width="0.2032" layer="21"/>
<wire x1="17" y1="10.1" x2="17" y2="-10.1" width="0.2032" layer="21"/>
<wire x1="17" y1="-10.1" x2="-17" y2="-10.1" width="0.2032" layer="21"/>
<wire x1="-17" y1="-10.1" x2="-17" y2="10.1" width="0.2032" layer="21"/>
<wire x1="-3.2" y1="10.1" x2="-3.2" y2="-10.1" width="0.2032" layer="51" style="shortdash"/>
<wire x1="3.2" y1="10.1" x2="3.2" y2="-10.1" width="0.2032" layer="51" style="shortdash"/>
<text x="-16" y="5.5" size="1.27" layer="21">AC-L</text>
<text x="-16" y="-6.5" size="1.27" layer="21">AC-N</text>
<text x="8" y="6.5" size="1.27" layer="21">+Vo</text>
<text x="8" y="-9" size="1.27" layer="21">-Vo</text>
<text x="-6" y="-1" size="1.4" layer="21">HLK-PM03</text>
<text x="19" y="-10" size="1.27" layer="25" rot="R90">&gt;NAME</text>
<pad name="1" x="-14.605" y="2.54" drill="1" diameter="2.2" shape="square"/>
<pad name="2" x="-14.605" y="-2.54" drill="1" diameter="2.2"/>
<pad name="3" x="14.605" y="-7.62" drill="1" diameter="2.2"/>
<pad name="4" x="14.605" y="7.62" drill="1" diameter="2.2"/></package>
<package name="SO16"><description>SOIC-16 narrow, 3.9 x 9.9 mm, 1.27 mm pitch (MAX3232)</description>
<wire x1="-1.95" y1="4.95" x2="1.95" y2="4.95" width="0.2032" layer="21"/>
<wire x1="1.95" y1="4.95" x2="1.95" y2="-4.95" width="0.2032" layer="21"/>
<wire x1="1.95" y1="-4.95" x2="-1.95" y2="-4.95" width="0.2032" layer="21"/>
<wire x1="-1.95" y1="-4.95" x2="-1.95" y2="4.95" width="0.2032" layer="21"/>
<circle x="-1.2" y="4.2" radius="0.35" width="0.2032" layer="21"/>
<text x="-1.9" y="5.6" size="1" layer="25">&gt;NAME</text>
<text x="-1.9" y="-6.6" size="1" layer="27">&gt;VALUE</text>
<smd name="1" x="-2.475" y="4.445" dx="1.95" dy="0.6" layer="1"/>
<smd name="2" x="-2.475" y="3.175" dx="1.95" dy="0.6" layer="1"/>
<smd name="3" x="-2.475" y="1.905" dx="1.95" dy="0.6" layer="1"/>
<smd name="4" x="-2.475" y="0.635" dx="1.95" dy="0.6" layer="1"/>
<smd name="5" x="-2.475" y="-0.635" dx="1.95" dy="0.6" layer="1"/>
<smd name="6" x="-2.475" y="-1.905" dx="1.95" dy="0.6" layer="1"/>
<smd name="7" x="-2.475" y="-3.175" dx="1.95" dy="0.6" layer="1"/>
<smd name="8" x="-2.475" y="-4.445" dx="1.95" dy="0.6" layer="1"/>
<smd name="9" x="2.475" y="-4.445" dx="1.95" dy="0.6" layer="1"/>
<smd name="10" x="2.475" y="-3.175" dx="1.95" dy="0.6" layer="1"/>
<smd name="11" x="2.475" y="-1.905" dx="1.95" dy="0.6" layer="1"/>
<smd name="12" x="2.475" y="-0.635" dx="1.95" dy="0.6" layer="1"/>
<smd name="13" x="2.475" y="0.635" dx="1.95" dy="0.6" layer="1"/>
<smd name="14" x="2.475" y="1.905" dx="1.95" dy="0.6" layer="1"/>
<smd name="15" x="2.475" y="3.175" dx="1.95" dy="0.6" layer="1"/>
<smd name="16" x="2.475" y="4.445" dx="1.95" dy="0.6" layer="1"/></package>
<package name="SO8"><description>SOIC-8 narrow, 3.9 x 4.9 mm, 1.27 mm pitch (SP3485 / AD3485)</description>
<wire x1="-1.95" y1="2.45" x2="1.95" y2="2.45" width="0.2032" layer="21"/>
<wire x1="1.95" y1="2.45" x2="1.95" y2="-2.45" width="0.2032" layer="21"/>
<wire x1="1.95" y1="-2.45" x2="-1.95" y2="-2.45" width="0.2032" layer="21"/>
<wire x1="-1.95" y1="-2.45" x2="-1.95" y2="2.45" width="0.2032" layer="21"/>
<circle x="-1.2" y="1.8" radius="0.3" width="0.2032" layer="21"/>
<text x="-1.9" y="3.1" size="1" layer="25">&gt;NAME</text>
<smd name="1" x="-1.9" y="1.905" dx="1.6" dy="0.6" layer="1"/>
<smd name="2" x="-1.9" y="0.635" dx="1.6" dy="0.6" layer="1"/>
<smd name="3" x="-1.9" y="-0.635" dx="1.6" dy="0.6" layer="1"/>
<smd name="4" x="-1.9" y="-1.905" dx="1.6" dy="0.6" layer="1"/>
<smd name="5" x="1.9" y="-1.905" dx="1.6" dy="0.6" layer="1"/>
<smd name="6" x="1.9" y="-0.635" dx="1.6" dy="0.6" layer="1"/>
<smd name="7" x="1.9" y="0.635" dx="1.6" dy="0.6" layer="1"/>
<smd name="8" x="1.9" y="1.905" dx="1.6" dy="0.6" layer="1"/></package>
<package name="DB9MRA"><description>DE-9 (DB9) male, right angle, housed; board edge 7.70 mm from pin row 1</description>
<wire x1="-9.885" y1="-1.8" x2="20.965" y2="-1.8" width="0.2032" layer="21"/>
<wire x1="20.965" y1="-1.8" x2="20.965" y2="10.54" width="0.2032" layer="21"/>
<wire x1="20.965" y1="10.54" x2="-9.885" y2="10.54" width="0.2032" layer="21"/>
<wire x1="-9.885" y1="10.54" x2="-9.885" y2="-1.8" width="0.2032" layer="21"/>
<wire x1="-9.46" y1="10.94" x2="-9.46" y2="15.94" width="0.2032" layer="21"/>
<wire x1="-9.46" y1="15.94" x2="-4.46" y2="15.94" width="0.2032" layer="21"/>
<wire x1="-4.46" y1="15.94" x2="-4.46" y2="10.94" width="0.2032" layer="21"/>
<wire x1="15.54" y1="10.94" x2="15.54" y2="15.94" width="0.2032" layer="21"/>
<wire x1="15.54" y1="15.94" x2="20.54" y2="15.94" width="0.2032" layer="21"/>
<wire x1="20.54" y1="15.94" x2="20.54" y2="10.94" width="0.2032" layer="21"/>
<wire x1="-10.4" y1="-7.7" x2="21.5" y2="-7.7" width="0.2032" layer="51" style="shortdash"/>
<text x="-10" y="-10" size="1" layer="51">BOARD EDGE</text>
<text x="2" y="11.5" size="1.27" layer="25">&gt;NAME</text>
<text x="2" y="5" size="1" layer="27">&gt;VALUE</text>
<pad name="1" x="0" y="0" drill="1" diameter="1.8" shape="square"/>
<pad name="2" x="2.77" y="0" drill="1" diameter="1.8"/>
<pad name="3" x="5.54" y="0" drill="1" diameter="1.8"/>
<pad name="4" x="8.31" y="0" drill="1" diameter="1.8"/>
<pad name="5" x="11.08" y="0" drill="1" diameter="1.8"/>
<pad name="6" x="1.385" y="2.84" drill="1" diameter="1.8"/>
<pad name="7" x="4.155" y="2.84" drill="1" diameter="1.8"/>
<pad name="8" x="6.925" y="2.84" drill="1" diameter="1.8"/>
<pad name="9" x="9.695" y="2.84" drill="1" diameter="1.8"/>
<pad name="MH" x="-6.96" y="1.42" drill="3.2" diameter="4.4"/>
<pad name="MH" x="18.04" y="1.42" drill="3.2" diameter="4.4"/></package>
<package name="TERM2-5.08"><description>2-pin 5.08 mm screw terminal (mains input)</description>
<wire x1="-5.08" y1="4.75" x2="5.08" y2="4.75" width="0.2032" layer="21"/>
<wire x1="5.08" y1="4.75" x2="5.08" y2="-4.75" width="0.2032" layer="21"/>
<wire x1="5.08" y1="-4.75" x2="-5.08" y2="-4.75" width="0.2032" layer="21"/>
<wire x1="-5.08" y1="-4.75" x2="-5.08" y2="4.75" width="0.2032" layer="21"/>
<text x="-4.54" y="5.4" size="1.27" layer="25">&gt;NAME</text>
<pad name="1" x="-2.54" y="0" drill="1.52" diameter="3" shape="square"/>
<pad name="2" x="2.54" y="0" drill="1.52" diameter="3"/></package>
<package name="TERM5-5.08"><description>5-pin 5.08 mm screw terminal (RS-232 field wiring)</description>
<wire x1="-12.7" y1="4.75" x2="12.7" y2="4.75" width="0.2032" layer="21"/>
<wire x1="12.7" y1="4.75" x2="12.7" y2="-4.75" width="0.2032" layer="21"/>
<wire x1="12.7" y1="-4.75" x2="-12.7" y2="-4.75" width="0.2032" layer="21"/>
<wire x1="-12.7" y1="-4.75" x2="-12.7" y2="4.75" width="0.2032" layer="21"/>
<text x="-12.16" y="5.4" size="1.27" layer="25">&gt;NAME</text>
<pad name="1" x="-10.16" y="0" drill="1.52" diameter="3" shape="square"/>
<pad name="2" x="-5.08" y="0" drill="1.52" diameter="3"/>
<pad name="3" x="0" y="0" drill="1.52" diameter="3"/>
<pad name="4" x="5.08" y="0" drill="1.52" diameter="3"/>
<pad name="5" x="10.16" y="0" drill="1.52" diameter="3"/></package>
<package name="R-7.62"><description>Resistor, axial DIN0207 (6.3 x 2.5 mm), 7.62 mm pitch</description>
<wire x1="-3.15" y1="1.25" x2="3.15" y2="1.25" width="0.2032" layer="21"/>
<wire x1="3.15" y1="1.25" x2="3.15" y2="-1.25" width="0.2032" layer="21"/>
<wire x1="3.15" y1="-1.25" x2="-3.15" y2="-1.25" width="0.2032" layer="21"/>
<wire x1="-3.15" y1="-1.25" x2="-3.15" y2="1.25" width="0.2032" layer="21"/>
<wire x1="-3.81" y1="0" x2="-3.15" y2="0" width="0.2032" layer="51"/>
<wire x1="3.15" y1="0" x2="3.81" y2="0" width="0.2032" layer="51"/>
<text x="-3.15" y="1.75" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-3.81" y="0" drill="0.8" diameter="1.7" shape="square"/>
<pad name="2" x="3.81" y="0" drill="0.8" diameter="1.7"/></package>
<package name="FB-7.62"><description>Ferrite bead, axial 7.2 x 4.0 mm, 7.62 mm pitch</description>
<wire x1="-3.6" y1="2" x2="3.6" y2="2" width="0.2032" layer="21"/>
<wire x1="3.6" y1="2" x2="3.6" y2="-2" width="0.2032" layer="21"/>
<wire x1="3.6" y1="-2" x2="-3.6" y2="-2" width="0.2032" layer="21"/>
<wire x1="-3.6" y1="-2" x2="-3.6" y2="2" width="0.2032" layer="21"/>
<wire x1="-3.81" y1="0" x2="-3.6" y2="0" width="0.2032" layer="51"/>
<wire x1="3.6" y1="0" x2="3.81" y2="0" width="0.2032" layer="51"/>
<text x="-3.6" y="2.5" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-3.81" y="0" drill="0.8" diameter="1.7" shape="square"/>
<pad name="2" x="3.81" y="0" drill="0.8" diameter="1.7"/></package>
<package name="C-5.08"><description>Ceramic / film disc capacitor, 5.0 x 2.5 mm, 5.08 mm pitch</description>
<wire x1="-2.5" y1="1.25" x2="2.5" y2="1.25" width="0.2032" layer="21"/>
<wire x1="2.5" y1="1.25" x2="2.5" y2="-1.25" width="0.2032" layer="21"/>
<wire x1="2.5" y1="-1.25" x2="-2.5" y2="-1.25" width="0.2032" layer="21"/>
<wire x1="-2.5" y1="-1.25" x2="-2.5" y2="1.25" width="0.2032" layer="21"/>
<wire x1="-2.54" y1="0" x2="-2.5" y2="0" width="0.2032" layer="51"/>
<wire x1="2.5" y1="0" x2="2.54" y2="0" width="0.2032" layer="51"/>
<text x="-2.5" y="1.75" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-2.54" y="0" drill="0.8" diameter="1.7" shape="square"/>
<pad name="2" x="2.54" y="0" drill="0.8" diameter="1.7"/></package>
<package name="C-5.08-200V"><description>Ceramic disc capacitor, 200 V rated, 5.08 mm pitch</description>
<wire x1="-2.5" y1="1.5" x2="2.5" y2="1.5" width="0.2032" layer="21"/>
<wire x1="2.5" y1="1.5" x2="2.5" y2="-1.5" width="0.2032" layer="21"/>
<wire x1="2.5" y1="-1.5" x2="-2.5" y2="-1.5" width="0.2032" layer="21"/>
<wire x1="-2.5" y1="-1.5" x2="-2.5" y2="1.5" width="0.2032" layer="21"/>
<wire x1="-2.54" y1="0" x2="-2.5" y2="0" width="0.2032" layer="51"/>
<wire x1="2.5" y1="0" x2="2.54" y2="0" width="0.2032" layer="51"/>
<text x="-2.5" y="2" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-2.54" y="0" drill="0.8" diameter="1.7" shape="square"/>
<pad name="2" x="2.54" y="0" drill="0.8" diameter="1.7"/></package>
<package name="FUSE-RADIAL"><description>Radial fuse, TR5 / 372 series, 8.5 mm body, 5.08 mm pitch</description>
<circle x="0" y="0" radius="4.25" width="0.2032" layer="21"/>
<wire x1="-2.54" y1="0" x2="-4.25" y2="0" width="0.2032" layer="51"/>
<wire x1="4.25" y1="0" x2="2.54" y2="0" width="0.2032" layer="51"/>
<text x="-4.25" y="4.75" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-2.54" y="0" drill="1" diameter="2" shape="square"/>
<pad name="2" x="2.54" y="0" drill="1" diameter="2"/></package>
<package name="MOV07"><description>Metal-oxide varistor, 7 mm disc, 5.0 mm pitch</description>
<circle x="0" y="0" radius="3.5" width="0.2032" layer="21"/>
<wire x1="-2.5" y1="0" x2="-3.5" y2="0" width="0.2032" layer="51"/>
<wire x1="3.5" y1="0" x2="2.5" y2="0" width="0.2032" layer="51"/>
<text x="-3.5" y="4" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-2.5" y="0" drill="0.8" diameter="1.8" shape="square"/>
<pad name="2" x="2.5" y="0" drill="0.8" diameter="1.8"/></package>
<package name="LED-5MM"><description>LED 5 mm, 2.54 mm pitch</description>
<circle x="0" y="0" radius="2.5" width="0.2032" layer="21"/>
<wire x1="-1.27" y1="0" x2="-2.5" y2="0" width="0.2032" layer="51"/>
<wire x1="2.5" y1="0" x2="1.27" y2="0" width="0.2032" layer="51"/>
<text x="-2.5" y="3" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-1.27" y="0" drill="0.8" diameter="1.7" shape="square"/>
<pad name="2" x="1.27" y="0" drill="0.8" diameter="1.7"/></package>
<package name="CP-D10-P5"><description>Electrolytic, radial, 10 mm dia, 5.0 mm pitch</description>
<circle x="0" y="0" radius="5" width="0.2032" layer="21"/>
<text x="-4.4" y="-4.6" size="1.4" layer="21">+</text>
<text x="-5" y="5.4" size="1" layer="25">&gt;NAME</text>
<pad name="+" x="-2.5" y="0" drill="1" diameter="2" shape="square"/>
<pad name="-" x="2.5" y="0" drill="1" diameter="2"/></package>
<package name="CP-D6.3-P2.5"><description>Electrolytic, radial, 6.3 mm dia, 2.5 mm pitch</description>
<circle x="0" y="0" radius="3.15" width="0.2032" layer="21"/>
<text x="-2.55" y="-2.75" size="1.4" layer="21">+</text>
<text x="-3.15" y="3.55" size="1" layer="25">&gt;NAME</text>
<pad name="+" x="-1.25" y="0" drill="1" diameter="2" shape="square"/>
<pad name="-" x="1.25" y="0" drill="1" diameter="2"/></package>
<package name="SW-TACT-6MM"><description>Tactile pushbutton 6 x 6 mm, 2 poles (pins 1/1 and 2/2 internally common)</description>
<wire x1="-3" y1="-3" x2="3" y2="-3" width="0.2032" layer="21"/>
<wire x1="3" y1="-3" x2="3" y2="3" width="0.2032" layer="21"/>
<wire x1="3" y1="3" x2="-3" y2="3" width="0.2032" layer="21"/>
<wire x1="-3" y1="3" x2="-3" y2="-3" width="0.2032" layer="21"/>
<text x="-3" y="4.2" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-3.25" y="-2.25" drill="1.1" diameter="2" shape="square"/>
<pad name="1" x="3.25" y="-2.25" drill="1.1" diameter="2"/>
<pad name="2" x="-3.25" y="2.25" drill="1.1" diameter="2"/>
<pad name="2" x="3.25" y="2.25" drill="1.1" diameter="2"/></package>
<package name="SJ-3"><description>3-pad solder jumper strap, 1.27 mm pitch</description>
<wire x1="-2.1" y1="1.1" x2="2.1" y2="1.1" width="0.2032" layer="21"/>
<wire x1="2.1" y1="1.1" x2="2.1" y2="-1.1" width="0.2032" layer="21"/>
<wire x1="2.1" y1="-1.1" x2="-2.1" y2="-1.1" width="0.2032" layer="21"/>
<wire x1="-2.1" y1="-1.1" x2="-2.1" y2="1.1" width="0.2032" layer="21"/>
<text x="-2.1" y="1.5" size="0.9" layer="25">&gt;NAME</text>
<pad name="1" x="-1.27" y="0" drill="0.8" diameter="1.5" shape="square"/>
<pad name="2" x="0" y="0" drill="0.8" diameter="1.5"/>
<pad name="3" x="1.27" y="0" drill="0.8" diameter="1.5"/></package>
<package name="HDR-2X5"><description>2 x 5 pin header, 2.54 mm (TTL serial + CP + reset)</description>
<wire x1="-6.35" y1="2.54" x2="6.35" y2="2.54" width="0.2032" layer="21"/>
<wire x1="6.35" y1="2.54" x2="6.35" y2="-2.54" width="0.2032" layer="21"/>
<wire x1="6.35" y1="-2.54" x2="-6.35" y2="-2.54" width="0.2032" layer="21"/>
<wire x1="-6.35" y1="-2.54" x2="-6.35" y2="2.54" width="0.2032" layer="21"/>
<text x="-6.28" y="3.2" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-5.08" y="-1.27" drill="1" diameter="1.8" shape="square"/>
<pad name="2" x="-5.08" y="1.27" drill="1" diameter="1.8"/>
<pad name="3" x="-2.54" y="-1.27" drill="1" diameter="1.8"/>
<pad name="4" x="-2.54" y="1.27" drill="1" diameter="1.8"/>
<pad name="5" x="0" y="-1.27" drill="1" diameter="1.8"/>
<pad name="6" x="0" y="1.27" drill="1" diameter="1.8"/>
<pad name="7" x="2.54" y="-1.27" drill="1" diameter="1.8"/>
<pad name="8" x="2.54" y="1.27" drill="1" diameter="1.8"/>
<pad name="9" x="5.08" y="-1.27" drill="1" diameter="1.8"/>
<pad name="10" x="5.08" y="1.27" drill="1" diameter="1.8"/></package>
<package name="TP"><description>Test point, 1.0 mm hole, 2.0 mm pad</description>
<text x="-1.2" y="1.6" size="0.9" layer="25">&gt;NAME</text>
<pad name="1" x="0" y="0" drill="1" diameter="2"/></package>
<package name="MOUNT-M3"><description>M3 mounting hole, 3.2 mm, non-plated, with keep-out ring</description>
<circle x="0" y="0" radius="2.4" width="0.2032" layer="41"/>
<circle x="0" y="0" radius="2.4" width="0.2032" layer="41"/>
<hole x="0" y="0" drill="3.2"/></package></packages>
<symbols><symbol name="XPORTPRO"><wire x1="-10.16" y1="15.24" x2="10.16" y2="15.24" width="0.4064" layer="94"/>
<wire x1="10.16" y1="15.24" x2="10.16" y2="-15.24" width="0.4064" layer="94"/>
<wire x1="10.16" y1="-15.24" x2="-10.16" y2="-15.24" width="0.4064" layer="94"/>
<wire x1="-10.16" y1="-15.24" x2="-10.16" y2="15.24" width="0.4064" layer="94"/>
<text x="-10.16" y="16.24" size="1.778" layer="95">&gt;NAME</text>
<text x="-10.16" y="-17.84" size="1.778" layer="96">&gt;VALUE</text>
<text x="-6" y="-2" size="1.778" layer="94" ratio="10">xPort Pro</text>
<text x="-6" y="-4.6" size="1.4" layer="94" ratio="10">16 MB flash</text>
<text x="-6" y="12" size="1.4" layer="94" ratio="10">RJ45 10/100</text>
<pin name="GND" x="-15.24" y="-12.7" visible="pin" length="middle" direction="pwr" rot="R0"/>
<pin name="3V3" x="-15.24" y="-10.16" visible="pin" length="middle" direction="pwr" rot="R0"/>
<pin name="!RESET" x="-15.24" y="12.7" visible="pin" length="middle" direction="in" function="dot" rot="R0"/>
<pin name="DOUT" x="-15.24" y="7.62" visible="pin" length="middle" direction="out" rot="R0"/>
<pin name="DIN" x="-15.24" y="5.08" visible="pin" length="middle" direction="in" rot="R0"/>
<pin name="CP1" x="-15.24" y="0" visible="pin" length="middle" rot="R0"/>
<pin name="CP2" x="-15.24" y="-2.54" visible="pin" length="middle" rot="R0"/>
<pin name="CP3" x="-15.24" y="-5.08" visible="pin" length="middle" rot="R0"/>
<pin name="S1" x="15.24" y="-12.7" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="S2" x="15.24" y="-10.16" visible="pin" length="middle" direction="pas" rot="R180"/></symbol>
<symbol name="ACDC-3V3"><wire x1="-10.16" y1="7.62" x2="10.16" y2="7.62" width="0.4064" layer="94"/>
<wire x1="10.16" y1="7.62" x2="10.16" y2="-7.62" width="0.4064" layer="94"/>
<wire x1="10.16" y1="-7.62" x2="-10.16" y2="-7.62" width="0.4064" layer="94"/>
<wire x1="-10.16" y1="-7.62" x2="-10.16" y2="7.62" width="0.4064" layer="94"/>
<text x="-10.16" y="8.62" size="1.778" layer="95">&gt;NAME</text>
<text x="-10.16" y="-10.22" size="1.778" layer="96">&gt;VALUE</text>
<text x="-7.5" y="1" size="1.6" layer="94" ratio="10">AC/DC</text>
<text x="-7.5" y="-1.6" size="1.4" layer="94" ratio="10">3.3 V / 3 W</text>
<text x="-7.5" y="-4.2" size="1.2" layer="94" ratio="10">3 kV isol.</text>
<pin name="AC-L" x="-15.24" y="5.08" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="AC-N" x="-15.24" y="2.54" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="+VO" x="15.24" y="5.08" visible="pin" length="middle" direction="pwr" rot="R180"/>
<pin name="-VO" x="15.24" y="2.54" visible="pin" length="middle" direction="pwr" rot="R180"/></symbol>
<symbol name="MAX3232"><wire x1="-8.89" y1="12.7" x2="8.89" y2="12.7" width="0.4064" layer="94"/>
<wire x1="8.89" y1="12.7" x2="8.89" y2="-12.7" width="0.4064" layer="94"/>
<wire x1="8.89" y1="-12.7" x2="-8.89" y2="-12.7" width="0.4064" layer="94"/>
<wire x1="-8.89" y1="-12.7" x2="-8.89" y2="12.7" width="0.4064" layer="94"/>
<text x="-8.89" y="13.7" size="1.778" layer="95">&gt;NAME</text>
<text x="-8.89" y="-15.3" size="1.778" layer="96">&gt;VALUE</text>
<text x="-5.5" y="0" size="1.4" layer="94" ratio="10">RS-232</text>
<pin name="C1+" x="-13.97" y="10.16" visible="pin" length="middle" rot="R0"/>
<pin name="V+" x="-13.97" y="7.62" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="C1-" x="-13.97" y="5.08" visible="pin" length="middle" rot="R0"/>
<pin name="C2+" x="-13.97" y="2.54" visible="pin" length="middle" rot="R0"/>
<pin name="C2-" x="-13.97" y="0" visible="pin" length="middle" rot="R0"/>
<pin name="V-" x="-13.97" y="-2.54" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="T2OUT" x="-13.97" y="-5.08" visible="pin" length="middle" direction="out" rot="R0"/>
<pin name="R2IN" x="-13.97" y="-7.62" visible="pin" length="middle" direction="in" rot="R0"/>
<pin name="R2OUT" x="13.97" y="-7.62" visible="pin" length="middle" direction="out" rot="R180"/>
<pin name="T2IN" x="13.97" y="-5.08" visible="pin" length="middle" direction="in" rot="R180"/>
<pin name="T1IN" x="13.97" y="-2.54" visible="pin" length="middle" direction="in" rot="R180"/>
<pin name="R1OUT" x="13.97" y="0" visible="pin" length="middle" direction="out" rot="R180"/>
<pin name="R1IN" x="13.97" y="2.54" visible="pin" length="middle" direction="in" rot="R180"/>
<pin name="T1OUT" x="13.97" y="5.08" visible="pin" length="middle" direction="out" rot="R180"/>
<pin name="GND" x="13.97" y="-10.16" visible="pin" length="middle" direction="pwr" rot="R180"/>
<pin name="VCC" x="13.97" y="10.16" visible="pin" length="middle" direction="pwr" rot="R180"/></symbol>
<symbol name="SP3485"><wire x1="-7.62" y1="6.35" x2="7.62" y2="6.35" width="0.4064" layer="94"/>
<wire x1="7.62" y1="6.35" x2="7.62" y2="-6.35" width="0.4064" layer="94"/>
<wire x1="7.62" y1="-6.35" x2="-7.62" y2="-6.35" width="0.4064" layer="94"/>
<wire x1="-7.62" y1="-6.35" x2="-7.62" y2="6.35" width="0.4064" layer="94"/>
<text x="-7.62" y="7.35" size="1.778" layer="95">&gt;NAME</text>
<text x="-7.62" y="-8.95" size="1.778" layer="96">&gt;VALUE</text>
<text x="-5" y="0" size="1.4" layer="94" ratio="10">RS-485</text>
<pin name="RO" x="-12.7" y="5.08" visible="pin" length="middle" direction="out" rot="R0"/>
<pin name="!RE" x="-12.7" y="2.54" visible="pin" length="middle" direction="in" function="dot" rot="R0"/>
<pin name="DE" x="-12.7" y="0" visible="pin" length="middle" direction="in" rot="R0"/>
<pin name="DI" x="-12.7" y="-2.54" visible="pin" length="middle" direction="in" rot="R0"/>
<pin name="GND" x="-12.7" y="-5.08" visible="pin" length="middle" direction="pwr" rot="R0"/>
<pin name="A" x="12.7" y="5.08" visible="pin" length="middle" rot="R180"/>
<pin name="B" x="12.7" y="2.54" visible="pin" length="middle" rot="R180"/>
<pin name="VCC" x="12.7" y="-5.08" visible="pin" length="middle" direction="pwr" rot="R180"/></symbol>
<symbol name="DB9M"><wire x1="-8.89" y1="12.7" x2="8.89" y2="12.7" width="0.4064" layer="94"/>
<wire x1="8.89" y1="12.7" x2="8.89" y2="-12.7" width="0.4064" layer="94"/>
<wire x1="8.89" y1="-12.7" x2="-8.89" y2="-12.7" width="0.4064" layer="94"/>
<wire x1="-8.89" y1="-12.7" x2="-8.89" y2="12.7" width="0.4064" layer="94"/>
<text x="-8.89" y="13.7" size="1.778" layer="95">&gt;NAME</text>
<text x="-8.89" y="-15.3" size="1.778" layer="96">&gt;VALUE</text>
<text x="-6" y="0" size="1.4" layer="94" ratio="10">DE-9</text>
<pin name="DCD" x="-13.97" y="10.16" visible="pin" length="middle" direction="in" rot="R0"/>
<pin name="RXD" x="-13.97" y="7.62" visible="pin" length="middle" direction="in" rot="R0"/>
<pin name="TXD" x="-13.97" y="5.08" visible="pin" length="middle" direction="out" rot="R0"/>
<pin name="DTR" x="-13.97" y="2.54" visible="pin" length="middle" direction="out" rot="R0"/>
<pin name="GND" x="-13.97" y="0" visible="pin" length="middle" direction="pwr" rot="R0"/>
<pin name="DSR" x="-13.97" y="-2.54" visible="pin" length="middle" direction="in" rot="R0"/>
<pin name="RTS" x="-13.97" y="-5.08" visible="pin" length="middle" direction="out" rot="R0"/>
<pin name="CTS" x="-13.97" y="-7.62" visible="pin" length="middle" direction="in" rot="R0"/>
<pin name="RI" x="-13.97" y="-10.16" visible="pin" length="middle" direction="in" rot="R0"/>
<pin name="SH" x="13.97" y="-10.16" visible="pin" length="middle" direction="pas" rot="R180"/></symbol>
<symbol name="R-EU"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="0" x2="-1.9" y2="1" width="0.2032" layer="94"/>
<wire x1="-1.9" y1="1" x2="-0.63" y2="-1" width="0.2032" layer="94"/>
<wire x1="-0.63" y1="-1" x2="0.63" y2="1" width="0.2032" layer="94"/>
<wire x1="0.63" y1="1" x2="1.9" y2="-1" width="0.2032" layer="94"/>
<wire x1="1.9" y1="-1" x2="2.54" y2="0" width="0.2032" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="C-EU"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="-1.27" y1="0.9" x2="1.27" y2="0.9" width="0.3" layer="94"/>
<wire x1="-1.27" y1="-0.9" x2="1.27" y2="-0.9" width="0.3" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="CPOL-EU"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="-1.27" y1="0.9" x2="1.27" y2="0.9" width="0.3" layer="94"/>
<wire x1="-1.27" y1="-0.9" x2="1.27" y2="-0.9" width="0.3" layer="94" style="shortdash"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<text x="-3.4" y="1.2" size="1.6" layer="94">+</text>
<pin name="+" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="-" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="LED"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="1" y1="1.6" x2="2.2" y2="2.8" width="0.2032" layer="94"/>
<wire x1="1.8" y1="1.6" x2="3" y2="2.8" width="0.2032" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="A" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="K" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="FUSE"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="MOV"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="FERRITE"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="SW-PUSH"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.2032" layer="94"/>
<wire x1="0" y1="1.27" x2="0" y2="2.54" width="0.2032" layer="94"/>
<wire x1="-2.54" y1="0" x2="-1.27" y2="0" width="0.2032" layer="94"/>
<wire x1="1.27" y1="0" x2="2.54" y2="0" width="0.2032" layer="94"/>
<text x="-3.81" y="3.54" size="1.778" layer="95">&gt;NAME</text>
<text x="-3.81" y="-5.14" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="SJ-3"><wire x1="-5.08" y1="2.54" x2="5.08" y2="2.54" width="0.254" layer="94"/>
<wire x1="5.08" y1="2.54" x2="5.08" y2="-2.54" width="0.254" layer="94"/>
<wire x1="5.08" y1="-2.54" x2="-5.08" y2="-2.54" width="0.254" layer="94"/>
<wire x1="-5.08" y1="-2.54" x2="-5.08" y2="2.54" width="0.254" layer="94"/>
<text x="-5.08" y="3.54" size="1.778" layer="95">&gt;NAME</text>
<text x="-5.08" y="-5.14" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-2.54" y="-5.08" visible="pin" length="short" direction="pas" rot="R90"/>
<pin name="2" x="0" y="5.08" visible="pin" length="short" direction="pas" rot="R270"/>
<pin name="3" x="2.54" y="-5.08" visible="pin" length="short" direction="pas" rot="R90"/></symbol>
<symbol name="TERM-2"><wire x1="-5.08" y1="6.35" x2="5.08" y2="6.35" width="0.4064" layer="94"/>
<wire x1="5.08" y1="6.35" x2="5.08" y2="-6.35" width="0.4064" layer="94"/>
<wire x1="5.08" y1="-6.35" x2="-5.08" y2="-6.35" width="0.4064" layer="94"/>
<wire x1="-5.08" y1="-6.35" x2="-5.08" y2="6.35" width="0.4064" layer="94"/>
<text x="-5.08" y="7.35" size="1.778" layer="95">&gt;NAME</text>
<text x="-5.08" y="-8.95" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-10.16" y="3.81" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="2" x="-10.16" y="-1.27" visible="pin" length="middle" direction="pas" rot="R0"/></symbol>
<symbol name="TERM-5"><wire x1="-5.08" y1="13.97" x2="5.08" y2="13.97" width="0.4064" layer="94"/>
<wire x1="5.08" y1="13.97" x2="5.08" y2="-13.97" width="0.4064" layer="94"/>
<wire x1="5.08" y1="-13.97" x2="-5.08" y2="-13.97" width="0.4064" layer="94"/>
<wire x1="-5.08" y1="-13.97" x2="-5.08" y2="13.97" width="0.4064" layer="94"/>
<text x="-5.08" y="14.97" size="1.778" layer="95">&gt;NAME</text>
<text x="-5.08" y="-16.57" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-10.16" y="11.43" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="2" x="-10.16" y="6.35" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="3" x="-10.16" y="1.27" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="4" x="-10.16" y="-3.81" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="5" x="-10.16" y="-8.89" visible="pin" length="middle" direction="pas" rot="R0"/></symbol>
<symbol name="HDR-2X5"><wire x1="-6.35" y1="7.62" x2="6.35" y2="7.62" width="0.4064" layer="94"/>
<wire x1="6.35" y1="7.62" x2="6.35" y2="-7.62" width="0.4064" layer="94"/>
<wire x1="6.35" y1="-7.62" x2="-6.35" y2="-7.62" width="0.4064" layer="94"/>
<wire x1="-6.35" y1="-7.62" x2="-6.35" y2="7.62" width="0.4064" layer="94"/>
<text x="-6.35" y="8.62" size="1.778" layer="95">&gt;NAME</text>
<text x="-6.35" y="-10.22" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-11.43" y="5.08" visible="pin" length="middle" rot="R0"/>
<pin name="3" x="-11.43" y="2.54" visible="pin" length="middle" rot="R0"/>
<pin name="5" x="-11.43" y="0" visible="pin" length="middle" rot="R0"/>
<pin name="7" x="-11.43" y="-2.54" visible="pin" length="middle" rot="R0"/>
<pin name="9" x="-11.43" y="-5.08" visible="pin" length="middle" rot="R0"/>
<pin name="2" x="11.43" y="5.08" visible="pin" length="middle" rot="R180"/>
<pin name="4" x="11.43" y="2.54" visible="pin" length="middle" rot="R180"/>
<pin name="6" x="11.43" y="0" visible="pin" length="middle" rot="R180"/>
<pin name="8" x="11.43" y="-2.54" visible="pin" length="middle" rot="R180"/>
<pin name="10" x="11.43" y="-5.08" visible="pin" length="middle" rot="R180"/></symbol>
<symbol name="TP"><circle x="0" y="0" radius="1.27" width="0.2032" layer="94"/>
<text x="-1.27" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-1.27" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="0" y="-3.81" visible="pin" length="short" direction="pas" rot="R90"/></symbol>
<symbol name="GND"><wire x1="-1.905" y1="0" x2="1.905" y2="0" width="0.254" layer="94"/>
<text x="-1.27" y="-2.54" size="1.778" layer="96">&gt;VALUE</text>
<pin name="GND" x="0" y="2.54" visible="pin" length="short" direction="sup" rot="R270"/></symbol></symbols>
<devicesets><deviceset name="XPORT-PRO" prefix="X"><gates><gate name="G$1" symbol="XPORTPRO" x="0" y="0"/></gates>
<devices><device package="XPORTPRO"><connects><connect gate="G$1" pin="GND" pad="1"/>
<connect gate="G$1" pin="3V3" pad="2"/>
<connect gate="G$1" pin="!RESET" pad="3"/>
<connect gate="G$1" pin="DOUT" pad="4"/>
<connect gate="G$1" pin="DIN" pad="5"/>
<connect gate="G$1" pin="CP1" pad="6"/>
<connect gate="G$1" pin="CP2" pad="7"/>
<connect gate="G$1" pin="CP3" pad="8"/>
<connect gate="G$1" pin="S1" pad="S1"/>
<connect gate="G$1" pin="S2" pad="S2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="ACDC-3V3" prefix="PS"><gates><gate name="G$1" symbol="ACDC-3V3" x="0" y="0"/></gates>
<devices><device package="HLKPM03"><connects><connect gate="G$1" pin="AC-L" pad="1"/>
<connect gate="G$1" pin="AC-N" pad="2"/>
<connect gate="G$1" pin="-VO" pad="3"/>
<connect gate="G$1" pin="+VO" pad="4"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="MAX3232" prefix="U"><gates><gate name="G$1" symbol="MAX3232" x="0" y="0"/></gates>
<devices><device package="SO16"><connects><connect gate="G$1" pin="C1+" pad="1"/>
<connect gate="G$1" pin="V+" pad="2"/>
<connect gate="G$1" pin="C1-" pad="3"/>
<connect gate="G$1" pin="C2+" pad="4"/>
<connect gate="G$1" pin="C2-" pad="5"/>
<connect gate="G$1" pin="V-" pad="6"/>
<connect gate="G$1" pin="T2OUT" pad="7"/>
<connect gate="G$1" pin="R2IN" pad="8"/>
<connect gate="G$1" pin="R2OUT" pad="9"/>
<connect gate="G$1" pin="T2IN" pad="10"/>
<connect gate="G$1" pin="T1IN" pad="11"/>
<connect gate="G$1" pin="R1OUT" pad="12"/>
<connect gate="G$1" pin="R1IN" pad="13"/>
<connect gate="G$1" pin="T1OUT" pad="14"/>
<connect gate="G$1" pin="GND" pad="15"/>
<connect gate="G$1" pin="VCC" pad="16"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="SP3485" prefix="U"><gates><gate name="G$1" symbol="SP3485" x="0" y="0"/></gates>
<devices><device package="SO8"><connects><connect gate="G$1" pin="RO" pad="4"/>
<connect gate="G$1" pin="!RE" pad="2"/>
<connect gate="G$1" pin="DE" pad="3"/>
<connect gate="G$1" pin="DI" pad="1"/>
<connect gate="G$1" pin="GND" pad="5"/>
<connect gate="G$1" pin="A" pad="6"/>
<connect gate="G$1" pin="B" pad="7"/>
<connect gate="G$1" pin="VCC" pad="8"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="DB9M" prefix="J"><gates><gate name="G$1" symbol="DB9M" x="0" y="0"/></gates>
<devices><device package="DB9MRA"><connects><connect gate="G$1" pin="DCD" pad="1"/>
<connect gate="G$1" pin="RXD" pad="2"/>
<connect gate="G$1" pin="TXD" pad="3"/>
<connect gate="G$1" pin="DTR" pad="4"/>
<connect gate="G$1" pin="GND" pad="5"/>
<connect gate="G$1" pin="DSR" pad="6"/>
<connect gate="G$1" pin="RTS" pad="7"/>
<connect gate="G$1" pin="CTS" pad="8"/>
<connect gate="G$1" pin="RI" pad="9"/>
<connect gate="G$1" pin="SH" pad="MH"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="TERM-2" prefix="J"><gates><gate name="G$1" symbol="TERM-2" x="0" y="0"/></gates>
<devices><device package="TERM2-5.08"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="TERM-5" prefix="J"><gates><gate name="G$1" symbol="TERM-5" x="0" y="0"/></gates>
<devices><device package="TERM5-5.08"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/>
<connect gate="G$1" pin="3" pad="3"/>
<connect gate="G$1" pin="4" pad="4"/>
<connect gate="G$1" pin="5" pad="5"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="HDR-2X5" prefix="J"><gates><gate name="G$1" symbol="HDR-2X5" x="0" y="0"/></gates>
<devices><device package="HDR-2X5"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/>
<connect gate="G$1" pin="3" pad="3"/>
<connect gate="G$1" pin="4" pad="4"/>
<connect gate="G$1" pin="5" pad="5"/>
<connect gate="G$1" pin="6" pad="6"/>
<connect gate="G$1" pin="7" pad="7"/>
<connect gate="G$1" pin="8" pad="8"/>
<connect gate="G$1" pin="9" pad="9"/>
<connect gate="G$1" pin="10" pad="10"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="R-EU" prefix="R"><gates><gate name="G$1" symbol="R-EU" x="0" y="0"/></gates>
<devices><device package="R-7.62"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="C-EU" prefix="C"><gates><gate name="G$1" symbol="C-EU" x="0" y="0"/></gates>
<devices><device package="C-5.08"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="C-200V" prefix="C"><gates><gate name="G$1" symbol="C-EU" x="0" y="0"/></gates>
<devices><device package="C-5.08-200V"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="CPOL-EU" prefix="C"><gates><gate name="G$1" symbol="CPOL-EU" x="0" y="0"/></gates>
<devices><device package="CP-D10-P5"><connects><connect gate="G$1" pin="+" pad="+"/>
<connect gate="G$1" pin="-" pad="-"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="CPOL-SMALL" prefix="C"><gates><gate name="G$1" symbol="CPOL-EU" x="0" y="0"/></gates>
<devices><device package="CP-D6.3-P2.5"><connects><connect gate="G$1" pin="+" pad="+"/>
<connect gate="G$1" pin="-" pad="-"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="LED" prefix="LED"><gates><gate name="G$1" symbol="LED" x="0" y="0"/></gates>
<devices><device package="LED-5MM"><connects><connect gate="G$1" pin="A" pad="1"/>
<connect gate="G$1" pin="K" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="FUSE" prefix="F"><gates><gate name="G$1" symbol="FUSE" x="0" y="0"/></gates>
<devices><device package="FUSE-RADIAL"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="MOV" prefix="MOV"><gates><gate name="G$1" symbol="MOV" x="0" y="0"/></gates>
<devices><device package="MOV07"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="FERRITE" prefix="FB"><gates><gate name="G$1" symbol="FERRITE" x="0" y="0"/></gates>
<devices><device package="FB-7.62"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="SW-PUSH" prefix="SW"><gates><gate name="G$1" symbol="SW-PUSH" x="0" y="0"/></gates>
<devices><device package="SW-TACT-6MM"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="SJ-3" prefix="JP"><gates><gate name="G$1" symbol="SJ-3" x="0" y="0"/></gates>
<devices><device package="SJ-3"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/>
<connect gate="G$1" pin="3" pad="3"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="TP" prefix="TP"><gates><gate name="G$1" symbol="TP" x="0" y="0"/></gates>
<devices><device package="TP"><connects><connect gate="G$1" pin="1" pad="1"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="MOUNT-M3" prefix="H"><gates></gates>
<devices><device package="MOUNT-M3"><connects></connects>
<technologies><technology/></technologies></device></devices></deviceset></devicesets></library></libraries>
<attributes/>
<variantdefs/>
<classes><class number="0" name="default" width="0.3048" drill="0"/>
<class number="1" name="mains" width="2.5" drill="0"><clearance class="0" value="6.4"/>
<clearance class="1" value="6.4"/>
<clearance class="2" value="6.4"/></class>
<class number="2" name="power" width="1" drill="0"><clearance class="0" value="0.5"/>
<clearance class="2" value="0.6"/></class></classes>
<parts><part name="J1" library="lantronix-wallplug" deviceset="TERM-2" value="MAINS IN"/>
<part name="F1" library="lantronix-wallplug" deviceset="FUSE" value="T500mA/250V"/>
<part name="MOV1" library="lantronix-wallplug" deviceset="MOV" value="S07K275"/>
<part name="PS1" library="lantronix-wallplug" deviceset="ACDC-3V3" value="HLK-PM03"/>
<part name="FB1" library="lantronix-wallplug" deviceset="FERRITE" value="600R@100MHz"/>
<part name="C1" library="lantronix-wallplug" deviceset="CPOL-EU" value="1000uF/10V"/>
<part name="C2" library="lantronix-wallplug" deviceset="CPOL-SMALL" value="100uF/10V"/>
<part name="R4" library="lantronix-wallplug" deviceset="R-EU" value="1k0"/>
<part name="LED1" library="lantronix-wallplug" deviceset="LED" value="PWR green"/>
<part name="TP1" library="lantronix-wallplug" deviceset="TP" value="+3V3"/>
<part name="TP2" library="lantronix-wallplug" deviceset="TP" value="GND"/>
<part name="X1" library="lantronix-wallplug" deviceset="XPORT-PRO" value="XPP100300S-04R"/>
<part name="C3" library="lantronix-wallplug" deviceset="C-EU" value="100nF"/>
<part name="C4" library="lantronix-wallplug" deviceset="C-EU" value="100nF"/>
<part name="R1" library="lantronix-wallplug" deviceset="R-EU" value="10k"/>
<part name="R7" library="lantronix-wallplug" deviceset="R-EU" value="10k"/>
<part name="SW1" library="lantronix-wallplug" deviceset="SW-PUSH" value="RESET"/>
<part name="C9" library="lantronix-wallplug" deviceset="C-200V" value="10nF/200V"/>
<part name="C10" library="lantronix-wallplug" deviceset="C-200V" value="10nF/200V"/>
<part name="TP5" library="lantronix-wallplug" deviceset="TP" value="CHASSIS"/>
<part name="U2" library="lantronix-wallplug" deviceset="MAX3232" value="MAX3232CSE"/>
<part name="C5" library="lantronix-wallplug" deviceset="C-EU" value="100nF"/>
<part name="C6" library="lantronix-wallplug" deviceset="C-EU" value="100nF"/>
<part name="C7" library="lantronix-wallplug" deviceset="C-EU" value="100nF"/>
<part name="C8" library="lantronix-wallplug" deviceset="C-EU" value="100nF"/>
<part name="JP1" library="lantronix-wallplug" deviceset="SJ-3" value="TXD strap"/>
<part name="JP2" library="lantronix-wallplug" deviceset="SJ-3" value="RXD strap"/>
<part name="J2" library="lantronix-wallplug" deviceset="DB9M" value="DB9M DTE"/>
<part name="J3" library="lantronix-wallplug" deviceset="TERM-5" value="RS232 ALT"/>
<part name="U3" library="lantronix-wallplug" deviceset="MAX3232" value="MAX3232CSE"/>
<part name="C11" library="lantronix-wallplug" deviceset="C-EU" value="100nF"/>
<part name="C12" library="lantronix-wallplug" deviceset="C-EU" value="100nF"/>
<part name="C13" library="lantronix-wallplug" deviceset="C-EU" value="100nF"/>
<part name="C14" library="lantronix-wallplug" deviceset="C-EU" value="100nF"/>
<part name="U4" library="lantronix-wallplug" deviceset="SP3485" value="SP3485EN"/>
<part name="R8" library="lantronix-wallplug" deviceset="R-EU" value="0R"/>
<part name="R9" library="lantronix-wallplug" deviceset="R-EU" value="0R"/>
<part name="R10" library="lantronix-wallplug" deviceset="R-EU" value="0R"/>
<part name="J5" library="lantronix-wallplug" deviceset="TERM-2" value="RS485 A/B"/>
<part name="J4" library="lantronix-wallplug" deviceset="HDR-2X5" value="TTL/CP"/>
<part name="TP3" library="lantronix-wallplug" deviceset="TP" value="TXD TTL"/>
<part name="TP4" library="lantronix-wallplug" deviceset="TP" value="RXD TTL"/></parts>
<sheets><sheet><plain><text x="20" y="292" size="3.4" layer="97" ratio="8">xPort Wallplug — mains-powered RS-232 ↔ Ethernet adapter around a Lantronix xPort Pro (16 MB flash)</text>
<text x="20" y="284" size="2.2" layer="97" ratio="8">MAINS (row A): L → F1 → PS1 pin 1, N → PS1 pin 2, MOV1 across L-N after the fuse. Isolation is inside PS1 (3 kV reinforced).</text>
<text x="20" y="279" size="2.2" layer="97" ratio="8">Keep 6.4 mm creepage / 4.0 mm clearance between mains and SELV copper — enforced by tools/build-wallplug-eagle.mjs --check.</text>
<text x="20" y="274" size="2.2" layer="97" ratio="8">MODULE (row C): xPort Pro pinout per Integration Guide 900-557 rev K Table 2-2 — 1 GND, 2 +3V3, 3 RESET, 4 Data Out, 5 Data In,</text>
<text x="20" y="269" size="2.2" layer="97" ratio="8">6 CP1/RTS, 7 CP2/DTR, 8 CP3/CTS-DCD. Serial I/O is 3.3 V CMOS, so a transceiver (U2) is mandatory for RS-232 levels.</text>
<text x="20" y="264" size="2.2" layer="97" ratio="8">JP1/JP2 strapped 1-2 = DTE (default, EDS2100 style), 2-3 = DCE (UDS1100 style). U3/U4/C11-C14/R8-R10/J5 are DNP options.</text>
<frame x1="0" y1="0" x2="480" y2="300" columns="8" rows="6" layer="91" border-left="yes" border-top="yes" border-right="yes" border-bottom="yes"/>
<text x="290" y="8" size="2.2" layer="97">xPort Wallplug rev A · sheet 1/1 · generated from tools/wallplug-model.mjs · see docs/lantronix-uclinux-deep-dive-2026-10-08.md</text></plain>
<instances><instance part="J1" gate="G$1" x="35" y="240" smashed="yes" rot="R0"><attribute name="NAME" x="24.84" y="248.62" size="1.778" layer="95"/>
<attribute name="VALUE" x="24.84" y="228.51" size="1.778" layer="96"/></instance>
<instance part="F1" gate="G$1" x="90" y="240" smashed="yes" rot="R0"><attribute name="NAME" x="84.92" y="243.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="84.92" y="233.59" size="1.778" layer="96"/></instance>
<instance part="MOV1" gate="G$1" x="145" y="240" smashed="yes" rot="R0"><attribute name="NAME" x="139.92" y="243.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="139.92" y="233.59" size="1.778" layer="96"/></instance>
<instance part="PS1" gate="G$1" x="215" y="240" smashed="yes" rot="R0"><attribute name="NAME" x="199.76" y="249.89" size="1.778" layer="95"/>
<attribute name="VALUE" x="199.76" y="227.24" size="1.778" layer="96"/></instance>
<instance part="FB1" gate="G$1" x="35" y="205" smashed="yes" rot="R0"><attribute name="NAME" x="29.92" y="208.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="29.92" y="198.59" size="1.778" layer="96"/></instance>
<instance part="C1" gate="G$1" x="90" y="205" smashed="yes" rot="R0"><attribute name="NAME" x="84.92" y="208.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="84.92" y="198.59" size="1.778" layer="96"/></instance>
<instance part="C2" gate="G$1" x="145" y="205" smashed="yes" rot="R0"><attribute name="NAME" x="139.92" y="208.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="139.92" y="198.59" size="1.778" layer="96"/></instance>
<instance part="R4" gate="G$1" x="200" y="205" smashed="yes" rot="R0"><attribute name="NAME" x="194.92" y="208.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="194.92" y="198.59" size="1.778" layer="96"/></instance>
<instance part="LED1" gate="G$1" x="255" y="205" smashed="yes" rot="R0"><attribute name="NAME" x="249.92" y="209.07" size="1.778" layer="95"/>
<attribute name="VALUE" x="249.92" y="198.59" size="1.778" layer="96"/></instance>
<instance part="TP1" gate="G$1" x="310" y="205" smashed="yes" rot="R0"><attribute name="NAME" x="308.73" y="208.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="308.73" y="198.59" size="1.778" layer="96"/></instance>
<instance part="TP2" gate="G$1" x="345" y="205" smashed="yes" rot="R0"><attribute name="NAME" x="343.73" y="208.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="343.73" y="198.59" size="1.778" layer="96"/></instance>
<instance part="X1" gate="G$1" x="60" y="165" smashed="yes" rot="R0"><attribute name="NAME" x="44.76" y="182.51" size="1.778" layer="95"/>
<attribute name="VALUE" x="44.76" y="144.62" size="1.778" layer="96"/></instance>
<instance part="C3" gate="G$1" x="120" y="165" smashed="yes" rot="R0"><attribute name="NAME" x="114.92" y="168.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="114.92" y="158.59" size="1.778" layer="96"/></instance>
<instance part="C4" gate="G$1" x="175" y="165" smashed="yes" rot="R0"><attribute name="NAME" x="169.92" y="168.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="169.92" y="158.59" size="1.778" layer="96"/></instance>
<instance part="R1" gate="G$1" x="340" y="165" smashed="yes" rot="R0"><attribute name="NAME" x="334.92" y="168.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="334.92" y="158.59" size="1.778" layer="96"/></instance>
<instance part="R7" gate="G$1" x="285" y="165" smashed="yes" rot="R0"><attribute name="NAME" x="279.92" y="168.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="279.92" y="158.59" size="1.778" layer="96"/></instance>
<instance part="SW1" gate="G$1" x="230" y="165" smashed="yes" rot="R0"><attribute name="NAME" x="224.92" y="169.81" size="1.778" layer="95"/>
<attribute name="VALUE" x="224.92" y="157.32" size="1.778" layer="96"/></instance>
<instance part="C9" gate="G$1" x="395" y="205" smashed="yes" rot="R0"><attribute name="NAME" x="389.92" y="208.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="389.92" y="198.59" size="1.778" layer="96"/></instance>
<instance part="C10" gate="G$1" x="445" y="205" smashed="yes" rot="R0"><attribute name="NAME" x="439.92" y="208.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="439.92" y="198.59" size="1.778" layer="96"/></instance>
<instance part="TP5" gate="G$1" x="445" y="165" smashed="yes" rot="R0"><attribute name="NAME" x="443.73" y="168.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="443.73" y="158.59" size="1.778" layer="96"/></instance>
<instance part="U2" gate="G$1" x="60" y="120" smashed="yes" rot="R0"><attribute name="NAME" x="46.03" y="134.97" size="1.778" layer="95"/>
<attribute name="VALUE" x="46.03" y="102.16" size="1.778" layer="96"/></instance>
<instance part="C5" gate="G$1" x="120" y="120" smashed="yes" rot="R0"><attribute name="NAME" x="114.92" y="123.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="114.92" y="113.59" size="1.778" layer="96"/></instance>
<instance part="C6" gate="G$1" x="175" y="120" smashed="yes" rot="R0"><attribute name="NAME" x="169.92" y="123.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="169.92" y="113.59" size="1.778" layer="96"/></instance>
<instance part="C7" gate="G$1" x="230" y="120" smashed="yes" rot="R0"><attribute name="NAME" x="224.92" y="123.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="224.92" y="113.59" size="1.778" layer="96"/></instance>
<instance part="C8" gate="G$1" x="285" y="120" smashed="yes" rot="R0"><attribute name="NAME" x="279.92" y="123.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="279.92" y="113.59" size="1.778" layer="96"/></instance>
<instance part="JP1" gate="G$1" x="340" y="120" smashed="yes" rot="R0"><attribute name="NAME" x="334.92" y="126.35" size="1.778" layer="95"/>
<attribute name="VALUE" x="334.92" y="112.32" size="1.778" layer="96"/></instance>
<instance part="JP2" gate="G$1" x="370" y="120" smashed="yes" rot="R0"><attribute name="NAME" x="364.92" y="126.35" size="1.778" layer="95"/>
<attribute name="VALUE" x="364.92" y="112.32" size="1.778" layer="96"/></instance>
<instance part="J2" gate="G$1" x="60" y="75" smashed="yes" rot="R0"><attribute name="NAME" x="46.03" y="89.97" size="1.778" layer="95"/>
<attribute name="VALUE" x="46.03" y="57.16" size="1.778" layer="96"/></instance>
<instance part="J3" gate="G$1" x="130" y="75" smashed="yes" rot="R0"><attribute name="NAME" x="119.84" y="91.24" size="1.778" layer="95"/>
<attribute name="VALUE" x="119.84" y="55.89" size="1.778" layer="96"/></instance>
<instance part="U3" gate="G$1" x="280" y="75" smashed="yes" rot="R0"><attribute name="NAME" x="266.03" y="89.97" size="1.778" layer="95"/>
<attribute name="VALUE" x="266.03" y="57.16" size="1.778" layer="96"/></instance>
<instance part="C11" gate="G$1" x="340" y="75" smashed="yes" rot="R0"><attribute name="NAME" x="334.92" y="78.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="334.92" y="68.59" size="1.778" layer="96"/></instance>
<instance part="C12" gate="G$1" x="395" y="75" smashed="yes" rot="R0"><attribute name="NAME" x="389.92" y="78.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="389.92" y="68.59" size="1.778" layer="96"/></instance>
<instance part="C13" gate="G$1" x="350" y="30" smashed="yes" rot="R0"><attribute name="NAME" x="344.92" y="33.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="344.92" y="23.59" size="1.778" layer="96"/></instance>
<instance part="C14" gate="G$1" x="405" y="30" smashed="yes" rot="R0"><attribute name="NAME" x="399.92" y="33.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="399.92" y="23.59" size="1.778" layer="96"/></instance>
<instance part="U4" gate="G$1" x="60" y="30" smashed="yes" rot="R0"><attribute name="NAME" x="47.3" y="38.62" size="1.778" layer="95"/>
<attribute name="VALUE" x="47.3" y="18.51" size="1.778" layer="96"/></instance>
<instance part="R8" gate="G$1" x="125" y="30" smashed="yes" rot="R0"><attribute name="NAME" x="119.92" y="33.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="119.92" y="23.59" size="1.778" layer="96"/></instance>
<instance part="R9" gate="G$1" x="180" y="30" smashed="yes" rot="R0"><attribute name="NAME" x="174.92" y="33.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="174.92" y="23.59" size="1.778" layer="96"/></instance>
<instance part="R10" gate="G$1" x="235" y="30" smashed="yes" rot="R0"><attribute name="NAME" x="229.92" y="33.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="229.92" y="23.59" size="1.778" layer="96"/></instance>
<instance part="J5" gate="G$1" x="290" y="30" smashed="yes" rot="R0"><attribute name="NAME" x="279.84" y="38.62" size="1.778" layer="95"/>
<attribute name="VALUE" x="279.84" y="18.51" size="1.778" layer="96"/></instance>
<instance part="J4" gate="G$1" x="200" y="75" smashed="yes" rot="R0"><attribute name="NAME" x="188.57" y="84.89" size="1.778" layer="95"/>
<attribute name="VALUE" x="188.57" y="62.24" size="1.778" layer="96"/></instance>
<instance part="TP3" gate="G$1" x="390" y="165" smashed="yes" rot="R0"><attribute name="NAME" x="388.73" y="168.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="388.73" y="158.59" size="1.778" layer="96"/></instance>
<instance part="TP4" gate="G$1" x="415" y="165" smashed="yes" rot="R0"><attribute name="NAME" x="413.73" y="168.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="413.73" y="158.59" size="1.778" layer="96"/></instance></instances>
<busses/>
<nets><net name="AC_L" class="1"><segment><pinref part="J1" gate="G$1" pin="1"/>
<wire x1="24.84" y1="243.81" x2="19.76" y2="243.81" width="0.1524" layer="91"/>
<label x="19.76" y="243.81" size="1.778" layer="95" rot="R0"/>
<pinref part="F1" gate="G$1" pin="1"/>
<wire x1="84.92" y1="240" x2="79.84" y2="240" width="0.1524" layer="91"/>
<label x="79.84" y="240" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="AC_L_F" class="1"><segment><pinref part="F1" gate="G$1" pin="2"/>
<wire x1="95.08" y1="240" x2="100.16" y2="240" width="0.1524" layer="91"/>
<label x="100.16" y="240" size="1.778" layer="95" rot="R0"/>
<pinref part="PS1" gate="G$1" pin="AC-L"/>
<wire x1="199.76" y1="245.08" x2="194.68" y2="245.08" width="0.1524" layer="91"/>
<label x="194.68" y="245.08" size="1.778" layer="95" rot="R0"/>
<pinref part="MOV1" gate="G$1" pin="1"/>
<wire x1="139.92" y1="240" x2="134.84" y2="240" width="0.1524" layer="91"/>
<label x="134.84" y="240" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="AC_N" class="1"><segment><pinref part="J1" gate="G$1" pin="2"/>
<wire x1="24.84" y1="238.73" x2="19.76" y2="238.73" width="0.1524" layer="91"/>
<label x="19.76" y="238.73" size="1.778" layer="95" rot="R0"/>
<pinref part="PS1" gate="G$1" pin="AC-N"/>
<wire x1="199.76" y1="242.54" x2="194.68" y2="242.54" width="0.1524" layer="91"/>
<label x="194.68" y="242.54" size="1.778" layer="95" rot="R0"/>
<pinref part="MOV1" gate="G$1" pin="2"/>
<wire x1="150.08" y1="240" x2="155.16" y2="240" width="0.1524" layer="91"/>
<label x="155.16" y="240" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="3V3_P" class="2"><segment><pinref part="PS1" gate="G$1" pin="+VO"/>
<wire x1="230.24" y1="245.08" x2="235.32" y2="245.08" width="0.1524" layer="91"/>
<label x="235.32" y="245.08" size="1.778" layer="95" rot="R0"/>
<pinref part="FB1" gate="G$1" pin="1"/>
<wire x1="29.92" y1="205" x2="24.84" y2="205" width="0.1524" layer="91"/>
<label x="24.84" y="205" size="1.778" layer="95" rot="R0"/>
<pinref part="C1" gate="G$1" pin="+"/>
<wire x1="84.92" y1="205" x2="79.84" y2="205" width="0.1524" layer="91"/>
<label x="79.84" y="205" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="3V3" class="2"><segment><pinref part="FB1" gate="G$1" pin="2"/>
<wire x1="40.08" y1="205" x2="45.16" y2="205" width="0.1524" layer="91"/>
<label x="45.16" y="205" size="1.778" layer="95" rot="R0"/>
<pinref part="C1" gate="G$1" pin="-"/>
<wire x1="95.08" y1="205" x2="100.16" y2="205" width="0.1524" layer="91"/>
<label x="100.16" y="205" size="1.778" layer="95" rot="R0"/>
<pinref part="C2" gate="G$1" pin="+"/>
<wire x1="139.92" y1="205" x2="134.84" y2="205" width="0.1524" layer="91"/>
<label x="134.84" y="205" size="1.778" layer="95" rot="R0"/>
<pinref part="X1" gate="G$1" pin="3V3"/>
<wire x1="44.76" y1="154.84" x2="39.68" y2="154.84" width="0.1524" layer="91"/>
<label x="39.68" y="154.84" size="1.778" layer="95" rot="R0"/>
<pinref part="C3" gate="G$1" pin="1"/>
<wire x1="114.92" y1="165" x2="109.84" y2="165" width="0.1524" layer="91"/>
<label x="109.84" y="165" size="1.778" layer="95" rot="R0"/>
<pinref part="C4" gate="G$1" pin="1"/>
<wire x1="169.92" y1="165" x2="164.84" y2="165" width="0.1524" layer="91"/>
<label x="164.84" y="165" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="VCC"/>
<wire x1="73.97" y1="130.16" x2="79.05" y2="130.16" width="0.1524" layer="91"/>
<label x="79.05" y="130.16" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="VCC"/>
<wire x1="293.97" y1="85.16" x2="299.05" y2="85.16" width="0.1524" layer="91"/>
<label x="299.05" y="85.16" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="VCC"/>
<wire x1="72.7" y1="24.92" x2="77.78" y2="24.92" width="0.1524" layer="91"/>
<label x="77.78" y="24.92" size="1.778" layer="95" rot="R0"/>
<pinref part="R1" gate="G$1" pin="2"/>
<wire x1="345.08" y1="165" x2="350.16" y2="165" width="0.1524" layer="91"/>
<label x="350.16" y="165" size="1.778" layer="95" rot="R0"/>
<pinref part="R7" gate="G$1" pin="2"/>
<wire x1="290.08" y1="165" x2="295.16" y2="165" width="0.1524" layer="91"/>
<label x="295.16" y="165" size="1.778" layer="95" rot="R0"/>
<pinref part="R4" gate="G$1" pin="1"/>
<wire x1="194.92" y1="205" x2="189.84" y2="205" width="0.1524" layer="91"/>
<label x="189.84" y="205" size="1.778" layer="95" rot="R0"/>
<pinref part="C10" gate="G$1" pin="2"/>
<wire x1="450.08" y1="205" x2="455.16" y2="205" width="0.1524" layer="91"/>
<label x="455.16" y="205" size="1.778" layer="95" rot="R0"/>
<pinref part="J4" gate="G$1" pin="1"/>
<wire x1="188.57" y1="80.08" x2="183.49" y2="80.08" width="0.1524" layer="91"/>
<label x="183.49" y="80.08" size="1.778" layer="95" rot="R0"/>
<pinref part="TP1" gate="G$1" pin="1"/>
<wire x1="310" y1="201.19" x2="310" y2="196.11" width="0.1524" layer="91"/>
<label x="310" y="196.11" size="1.778" layer="95" rot="R270"/></segment></net>
<net name="GND" class="2"><segment><pinref part="PS1" gate="G$1" pin="-VO"/>
<wire x1="230.24" y1="242.54" x2="235.32" y2="242.54" width="0.1524" layer="91"/>
<label x="235.32" y="242.54" size="1.778" layer="95" rot="R0"/>
<pinref part="C2" gate="G$1" pin="-"/>
<wire x1="150.08" y1="205" x2="155.16" y2="205" width="0.1524" layer="91"/>
<label x="155.16" y="205" size="1.778" layer="95" rot="R0"/>
<pinref part="X1" gate="G$1" pin="GND"/>
<wire x1="44.76" y1="152.3" x2="39.68" y2="152.3" width="0.1524" layer="91"/>
<label x="39.68" y="152.3" size="1.778" layer="95" rot="R0"/>
<pinref part="C3" gate="G$1" pin="2"/>
<wire x1="125.08" y1="165" x2="130.16" y2="165" width="0.1524" layer="91"/>
<label x="130.16" y="165" size="1.778" layer="95" rot="R0"/>
<pinref part="C4" gate="G$1" pin="2"/>
<wire x1="180.08" y1="165" x2="185.16" y2="165" width="0.1524" layer="91"/>
<label x="185.16" y="165" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="GND"/>
<wire x1="73.97" y1="109.84" x2="79.05" y2="109.84" width="0.1524" layer="91"/>
<label x="79.05" y="109.84" size="1.778" layer="95" rot="R0"/>
<pinref part="C7" gate="G$1" pin="2"/>
<wire x1="235.08" y1="120" x2="240.16" y2="120" width="0.1524" layer="91"/>
<label x="240.16" y="120" size="1.778" layer="95" rot="R0"/>
<pinref part="C8" gate="G$1" pin="2"/>
<wire x1="290.08" y1="120" x2="295.16" y2="120" width="0.1524" layer="91"/>
<label x="295.16" y="120" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="GND"/>
<wire x1="293.97" y1="64.84" x2="299.05" y2="64.84" width="0.1524" layer="91"/>
<label x="299.05" y="64.84" size="1.778" layer="95" rot="R0"/>
<pinref part="C13" gate="G$1" pin="2"/>
<wire x1="355.08" y1="30" x2="360.16" y2="30" width="0.1524" layer="91"/>
<label x="360.16" y="30" size="1.778" layer="95" rot="R0"/>
<pinref part="C14" gate="G$1" pin="2"/>
<wire x1="410.08" y1="30" x2="415.16" y2="30" width="0.1524" layer="91"/>
<label x="415.16" y="30" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="GND"/>
<wire x1="47.3" y1="24.92" x2="42.22" y2="24.92" width="0.1524" layer="91"/>
<label x="42.22" y="24.92" size="1.778" layer="95" rot="R0"/>
<pinref part="SW1" gate="G$1" pin="2"/>
<wire x1="235.08" y1="165" x2="240.16" y2="165" width="0.1524" layer="91"/>
<label x="240.16" y="165" size="1.778" layer="95" rot="R0"/>
<pinref part="J2" gate="G$1" pin="GND"/>
<wire x1="46.03" y1="75" x2="40.95" y2="75" width="0.1524" layer="91"/>
<label x="40.95" y="75" size="1.778" layer="95" rot="R0"/>
<pinref part="J3" gate="G$1" pin="5"/>
<wire x1="119.84" y1="66.11" x2="114.76" y2="66.11" width="0.1524" layer="91"/>
<label x="114.76" y="66.11" size="1.778" layer="95" rot="R0"/>
<pinref part="J4" gate="G$1" pin="2"/>
<wire x1="211.43" y1="80.08" x2="216.51" y2="80.08" width="0.1524" layer="91"/>
<label x="216.51" y="80.08" size="1.778" layer="95" rot="R0"/>
<pinref part="J4" gate="G$1" pin="10"/>
<wire x1="211.43" y1="69.92" x2="216.51" y2="69.92" width="0.1524" layer="91"/>
<label x="216.51" y="69.92" size="1.778" layer="95" rot="R0"/>
<pinref part="LED1" gate="G$1" pin="K"/>
<wire x1="260.08" y1="205" x2="265.16" y2="205" width="0.1524" layer="91"/>
<label x="265.16" y="205" size="1.778" layer="95" rot="R0"/>
<pinref part="C9" gate="G$1" pin="2"/>
<wire x1="400.08" y1="205" x2="405.16" y2="205" width="0.1524" layer="91"/>
<label x="405.16" y="205" size="1.778" layer="95" rot="R0"/>
<pinref part="TP2" gate="G$1" pin="1"/>
<wire x1="345" y1="201.19" x2="345" y2="196.11" width="0.1524" layer="91"/>
<label x="345" y="196.11" size="1.778" layer="95" rot="R270"/></segment></net>
<net name="CHASSIS" class="2"><segment><pinref part="X1" gate="G$1" pin="S1"/>
<wire x1="75.24" y1="152.3" x2="80.32" y2="152.3" width="0.1524" layer="91"/>
<label x="80.32" y="152.3" size="1.778" layer="95" rot="R0"/>
<pinref part="X1" gate="G$1" pin="S2"/>
<wire x1="75.24" y1="154.84" x2="80.32" y2="154.84" width="0.1524" layer="91"/>
<label x="80.32" y="154.84" size="1.778" layer="95" rot="R0"/>
<pinref part="J2" gate="G$1" pin="SH"/>
<wire x1="73.97" y1="64.84" x2="79.05" y2="64.84" width="0.1524" layer="91"/>
<label x="79.05" y="64.84" size="1.778" layer="95" rot="R0"/>
<pinref part="C9" gate="G$1" pin="1"/>
<wire x1="389.92" y1="205" x2="384.84" y2="205" width="0.1524" layer="91"/>
<label x="384.84" y="205" size="1.778" layer="95" rot="R0"/>
<pinref part="C10" gate="G$1" pin="1"/>
<wire x1="439.92" y1="205" x2="434.84" y2="205" width="0.1524" layer="91"/>
<label x="434.84" y="205" size="1.778" layer="95" rot="R0"/>
<pinref part="TP5" gate="G$1" pin="1"/>
<wire x1="445" y1="161.19" x2="445" y2="156.11" width="0.1524" layer="91"/>
<label x="445" y="156.11" size="1.778" layer="95" rot="R270"/></segment></net>
<net name="TXD_TTL" class="0"><segment><pinref part="X1" gate="G$1" pin="DOUT"/>
<wire x1="44.76" y1="172.62" x2="39.68" y2="172.62" width="0.1524" layer="91"/>
<label x="39.68" y="172.62" size="1.778" layer="95" rot="R0"/>
<pinref part="R1" gate="G$1" pin="1"/>
<wire x1="334.92" y1="165" x2="329.84" y2="165" width="0.1524" layer="91"/>
<label x="329.84" y="165" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="T1IN"/>
<wire x1="73.97" y1="117.46" x2="79.05" y2="117.46" width="0.1524" layer="91"/>
<label x="79.05" y="117.46" size="1.778" layer="95" rot="R0"/>
<pinref part="J4" gate="G$1" pin="3"/>
<wire x1="188.57" y1="77.54" x2="183.49" y2="77.54" width="0.1524" layer="91"/>
<label x="183.49" y="77.54" size="1.778" layer="95" rot="R0"/>
<pinref part="R8" gate="G$1" pin="1"/>
<wire x1="119.92" y1="30" x2="114.84" y2="30" width="0.1524" layer="91"/>
<label x="114.84" y="30" size="1.778" layer="95" rot="R0"/>
<pinref part="TP3" gate="G$1" pin="1"/>
<wire x1="390" y1="161.19" x2="390" y2="156.11" width="0.1524" layer="91"/>
<label x="390" y="156.11" size="1.778" layer="95" rot="R270"/></segment></net>
<net name="RXD_TTL" class="0"><segment><pinref part="X1" gate="G$1" pin="DIN"/>
<wire x1="44.76" y1="170.08" x2="39.68" y2="170.08" width="0.1524" layer="91"/>
<label x="39.68" y="170.08" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="R1OUT"/>
<wire x1="73.97" y1="120" x2="79.05" y2="120" width="0.1524" layer="91"/>
<label x="79.05" y="120" size="1.778" layer="95" rot="R0"/>
<pinref part="J4" gate="G$1" pin="4"/>
<wire x1="211.43" y1="77.54" x2="216.51" y2="77.54" width="0.1524" layer="91"/>
<label x="216.51" y="77.54" size="1.778" layer="95" rot="R0"/>
<pinref part="R9" gate="G$1" pin="1"/>
<wire x1="174.92" y1="30" x2="169.84" y2="30" width="0.1524" layer="91"/>
<label x="169.84" y="30" size="1.778" layer="95" rot="R0"/>
<pinref part="TP4" gate="G$1" pin="1"/>
<wire x1="415" y1="161.19" x2="415" y2="156.11" width="0.1524" layer="91"/>
<label x="415" y="156.11" size="1.778" layer="95" rot="R270"/></segment></net>
<net name="RESET_N" class="0"><segment><pinref part="X1" gate="G$1" pin="!RESET"/>
<wire x1="44.76" y1="177.7" x2="39.68" y2="177.7" width="0.1524" layer="91"/>
<label x="39.68" y="177.7" size="1.778" layer="95" rot="R0"/>
<pinref part="SW1" gate="G$1" pin="1"/>
<wire x1="224.92" y1="165" x2="219.84" y2="165" width="0.1524" layer="91"/>
<label x="219.84" y="165" size="1.778" layer="95" rot="R0"/>
<pinref part="R7" gate="G$1" pin="1"/>
<wire x1="279.92" y1="165" x2="274.84" y2="165" width="0.1524" layer="91"/>
<label x="274.84" y="165" size="1.778" layer="95" rot="R0"/>
<pinref part="J4" gate="G$1" pin="8"/>
<wire x1="211.43" y1="72.46" x2="216.51" y2="72.46" width="0.1524" layer="91"/>
<label x="216.51" y="72.46" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="CP1" class="0"><segment><pinref part="X1" gate="G$1" pin="CP1"/>
<wire x1="44.76" y1="165" x2="39.68" y2="165" width="0.1524" layer="91"/>
<label x="39.68" y="165" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="T1IN"/>
<wire x1="293.97" y1="72.46" x2="299.05" y2="72.46" width="0.1524" layer="91"/>
<label x="299.05" y="72.46" size="1.778" layer="95" rot="R0"/>
<pinref part="J4" gate="G$1" pin="5"/>
<wire x1="188.57" y1="75" x2="183.49" y2="75" width="0.1524" layer="91"/>
<label x="183.49" y="75" size="1.778" layer="95" rot="R0"/>
<pinref part="R10" gate="G$1" pin="1"/>
<wire x1="229.92" y1="30" x2="224.84" y2="30" width="0.1524" layer="91"/>
<label x="224.84" y="30" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="CP2" class="0"><segment><pinref part="X1" gate="G$1" pin="CP2"/>
<wire x1="44.76" y1="162.46" x2="39.68" y2="162.46" width="0.1524" layer="91"/>
<label x="39.68" y="162.46" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="T2IN"/>
<wire x1="293.97" y1="69.92" x2="299.05" y2="69.92" width="0.1524" layer="91"/>
<label x="299.05" y="69.92" size="1.778" layer="95" rot="R0"/>
<pinref part="J4" gate="G$1" pin="6"/>
<wire x1="211.43" y1="75" x2="216.51" y2="75" width="0.1524" layer="91"/>
<label x="216.51" y="75" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="CP3" class="0"><segment><pinref part="X1" gate="G$1" pin="CP3"/>
<wire x1="44.76" y1="159.92" x2="39.68" y2="159.92" width="0.1524" layer="91"/>
<label x="39.68" y="159.92" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="R2OUT"/>
<wire x1="293.97" y1="67.38" x2="299.05" y2="67.38" width="0.1524" layer="91"/>
<label x="299.05" y="67.38" size="1.778" layer="95" rot="R0"/>
<pinref part="J4" gate="G$1" pin="7"/>
<wire x1="188.57" y1="72.46" x2="183.49" y2="72.46" width="0.1524" layer="91"/>
<label x="183.49" y="72.46" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="T1OUT_2" class="0"><segment><pinref part="U2" gate="G$1" pin="T1OUT"/>
<wire x1="73.97" y1="125.08" x2="79.05" y2="125.08" width="0.1524" layer="91"/>
<label x="79.05" y="125.08" size="1.778" layer="95" rot="R0"/>
<pinref part="JP1" gate="G$1" pin="1"/>
<wire x1="337.46" y1="114.92" x2="337.46" y2="109.84" width="0.1524" layer="91"/>
<label x="337.46" y="109.84" size="1.778" layer="95" rot="R270"/></segment></net>
<net name="R1IN_2" class="0"><segment><pinref part="U2" gate="G$1" pin="R1IN"/>
<wire x1="73.97" y1="122.54" x2="79.05" y2="122.54" width="0.1524" layer="91"/>
<label x="79.05" y="122.54" size="1.778" layer="95" rot="R0"/>
<pinref part="JP2" gate="G$1" pin="1"/>
<wire x1="367.46" y1="114.92" x2="367.46" y2="109.84" width="0.1524" layer="91"/>
<label x="367.46" y="109.84" size="1.778" layer="95" rot="R270"/></segment></net>
<net name="DB9_2" class="0"><segment><pinref part="J2" gate="G$1" pin="RXD"/>
<wire x1="46.03" y1="82.62" x2="40.95" y2="82.62" width="0.1524" layer="91"/>
<label x="40.95" y="82.62" size="1.778" layer="95" rot="R0"/>
<pinref part="J3" gate="G$1" pin="2"/>
<wire x1="119.84" y1="81.35" x2="114.76" y2="81.35" width="0.1524" layer="91"/>
<label x="114.76" y="81.35" size="1.778" layer="95" rot="R0"/>
<pinref part="JP1" gate="G$1" pin="3"/>
<wire x1="342.54" y1="114.92" x2="342.54" y2="109.84" width="0.1524" layer="91"/>
<label x="342.54" y="109.84" size="1.778" layer="95" rot="R270"/>
<pinref part="JP2" gate="G$1" pin="2"/>
<wire x1="370" y1="125.08" x2="370" y2="130.16" width="0.1524" layer="91"/>
<label x="370" y="130.16" size="1.778" layer="95" rot="R270"/></segment></net>
<net name="DB9_3" class="0"><segment><pinref part="J2" gate="G$1" pin="TXD"/>
<wire x1="46.03" y1="80.08" x2="40.95" y2="80.08" width="0.1524" layer="91"/>
<label x="40.95" y="80.08" size="1.778" layer="95" rot="R0"/>
<pinref part="J3" gate="G$1" pin="1"/>
<wire x1="119.84" y1="86.43" x2="114.76" y2="86.43" width="0.1524" layer="91"/>
<label x="114.76" y="86.43" size="1.778" layer="95" rot="R0"/>
<pinref part="JP1" gate="G$1" pin="2"/>
<wire x1="340" y1="125.08" x2="340" y2="130.16" width="0.1524" layer="91"/>
<label x="340" y="130.16" size="1.778" layer="95" rot="R270"/>
<pinref part="JP2" gate="G$1" pin="3"/>
<wire x1="372.54" y1="114.92" x2="372.54" y2="109.84" width="0.1524" layer="91"/>
<label x="372.54" y="109.84" size="1.778" layer="95" rot="R270"/></segment></net>
<net name="CTS_232" class="0"><segment><pinref part="U3" gate="G$1" pin="R1OUT"/>
<wire x1="293.97" y1="75" x2="299.05" y2="75" width="0.1524" layer="91"/>
<label x="299.05" y="75" size="1.778" layer="95" rot="R0"/>
<pinref part="J3" gate="G$1" pin="4"/>
<wire x1="119.84" y1="71.19" x2="114.76" y2="71.19" width="0.1524" layer="91"/>
<label x="114.76" y="71.19" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="DB9_7" class="0"><segment><pinref part="J2" gate="G$1" pin="RTS"/>
<wire x1="46.03" y1="69.92" x2="40.95" y2="69.92" width="0.1524" layer="91"/>
<label x="40.95" y="69.92" size="1.778" layer="95" rot="R0"/>
<pinref part="J3" gate="G$1" pin="3"/>
<wire x1="119.84" y1="76.27" x2="114.76" y2="76.27" width="0.1524" layer="91"/>
<label x="114.76" y="76.27" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="T1OUT"/>
<wire x1="293.97" y1="80.08" x2="299.05" y2="80.08" width="0.1524" layer="91"/>
<label x="299.05" y="80.08" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="DB9_8" class="0"><segment><pinref part="J2" gate="G$1" pin="CTS"/>
<wire x1="46.03" y1="67.38" x2="40.95" y2="67.38" width="0.1524" layer="91"/>
<label x="40.95" y="67.38" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="R1IN"/>
<wire x1="293.97" y1="77.54" x2="299.05" y2="77.54" width="0.1524" layer="91"/>
<label x="299.05" y="77.54" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="DB9_4" class="0"><segment><pinref part="J2" gate="G$1" pin="DTR"/>
<wire x1="46.03" y1="77.54" x2="40.95" y2="77.54" width="0.1524" layer="91"/>
<label x="40.95" y="77.54" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="T2OUT"/>
<wire x1="266.03" y1="69.92" x2="260.95" y2="69.92" width="0.1524" layer="91"/>
<label x="260.95" y="69.92" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="DB9_1" class="0"><segment><pinref part="J2" gate="G$1" pin="DCD"/>
<wire x1="46.03" y1="85.16" x2="40.95" y2="85.16" width="0.1524" layer="91"/>
<label x="40.95" y="85.16" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="R2IN"/>
<wire x1="266.03" y1="67.38" x2="260.95" y2="67.38" width="0.1524" layer="91"/>
<label x="260.95" y="67.38" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="DSR_TTL" class="0"><segment><pinref part="J2" gate="G$1" pin="DSR"/>
<wire x1="46.03" y1="72.46" x2="40.95" y2="72.46" width="0.1524" layer="91"/>
<label x="40.95" y="72.46" size="1.778" layer="95" rot="R0"/>
<pinref part="J4" gate="G$1" pin="9"/>
<wire x1="188.57" y1="69.92" x2="183.49" y2="69.92" width="0.1524" layer="91"/>
<label x="183.49" y="69.92" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="VPLUS2" class="0"><segment><pinref part="U2" gate="G$1" pin="V+"/>
<wire x1="46.03" y1="127.62" x2="40.95" y2="127.62" width="0.1524" layer="91"/>
<label x="40.95" y="127.62" size="1.778" layer="95" rot="R0"/>
<pinref part="C7" gate="G$1" pin="1"/>
<wire x1="224.92" y1="120" x2="219.84" y2="120" width="0.1524" layer="91"/>
<label x="219.84" y="120" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="VMINUS2" class="0"><segment><pinref part="U2" gate="G$1" pin="V-"/>
<wire x1="46.03" y1="117.46" x2="40.95" y2="117.46" width="0.1524" layer="91"/>
<label x="40.95" y="117.46" size="1.778" layer="95" rot="R0"/>
<pinref part="C8" gate="G$1" pin="1"/>
<wire x1="279.92" y1="120" x2="274.84" y2="120" width="0.1524" layer="91"/>
<label x="274.84" y="120" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="C1P2" class="0"><segment><pinref part="U2" gate="G$1" pin="C1+"/>
<wire x1="46.03" y1="130.16" x2="40.95" y2="130.16" width="0.1524" layer="91"/>
<label x="40.95" y="130.16" size="1.778" layer="95" rot="R0"/>
<pinref part="C5" gate="G$1" pin="1"/>
<wire x1="114.92" y1="120" x2="109.84" y2="120" width="0.1524" layer="91"/>
<label x="109.84" y="120" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="C1N2" class="0"><segment><pinref part="U2" gate="G$1" pin="C1-"/>
<wire x1="46.03" y1="125.08" x2="40.95" y2="125.08" width="0.1524" layer="91"/>
<label x="40.95" y="125.08" size="1.778" layer="95" rot="R0"/>
<pinref part="C5" gate="G$1" pin="2"/>
<wire x1="125.08" y1="120" x2="130.16" y2="120" width="0.1524" layer="91"/>
<label x="130.16" y="120" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="C2P2" class="0"><segment><pinref part="U2" gate="G$1" pin="C2+"/>
<wire x1="46.03" y1="122.54" x2="40.95" y2="122.54" width="0.1524" layer="91"/>
<label x="40.95" y="122.54" size="1.778" layer="95" rot="R0"/>
<pinref part="C6" gate="G$1" pin="1"/>
<wire x1="169.92" y1="120" x2="164.84" y2="120" width="0.1524" layer="91"/>
<label x="164.84" y="120" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="C2N2" class="0"><segment><pinref part="U2" gate="G$1" pin="C2-"/>
<wire x1="46.03" y1="120" x2="40.95" y2="120" width="0.1524" layer="91"/>
<label x="40.95" y="120" size="1.778" layer="95" rot="R0"/>
<pinref part="C6" gate="G$1" pin="2"/>
<wire x1="180.08" y1="120" x2="185.16" y2="120" width="0.1524" layer="91"/>
<label x="185.16" y="120" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="VPLUS3" class="0"><segment><pinref part="U3" gate="G$1" pin="V+"/>
<wire x1="266.03" y1="82.62" x2="260.95" y2="82.62" width="0.1524" layer="91"/>
<label x="260.95" y="82.62" size="1.778" layer="95" rot="R0"/>
<pinref part="C13" gate="G$1" pin="1"/>
<wire x1="344.92" y1="30" x2="339.84" y2="30" width="0.1524" layer="91"/>
<label x="339.84" y="30" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="VMINUS3" class="0"><segment><pinref part="U3" gate="G$1" pin="V-"/>
<wire x1="266.03" y1="72.46" x2="260.95" y2="72.46" width="0.1524" layer="91"/>
<label x="260.95" y="72.46" size="1.778" layer="95" rot="R0"/>
<pinref part="C14" gate="G$1" pin="1"/>
<wire x1="399.92" y1="30" x2="394.84" y2="30" width="0.1524" layer="91"/>
<label x="394.84" y="30" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="C1P3" class="0"><segment><pinref part="U3" gate="G$1" pin="C1+"/>
<wire x1="266.03" y1="85.16" x2="260.95" y2="85.16" width="0.1524" layer="91"/>
<label x="260.95" y="85.16" size="1.778" layer="95" rot="R0"/>
<pinref part="C11" gate="G$1" pin="1"/>
<wire x1="334.92" y1="75" x2="329.84" y2="75" width="0.1524" layer="91"/>
<label x="329.84" y="75" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="C1N3" class="0"><segment><pinref part="U3" gate="G$1" pin="C1-"/>
<wire x1="266.03" y1="80.08" x2="260.95" y2="80.08" width="0.1524" layer="91"/>
<label x="260.95" y="80.08" size="1.778" layer="95" rot="R0"/>
<pinref part="C11" gate="G$1" pin="2"/>
<wire x1="345.08" y1="75" x2="350.16" y2="75" width="0.1524" layer="91"/>
<label x="350.16" y="75" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="C2P3" class="0"><segment><pinref part="U3" gate="G$1" pin="C2+"/>
<wire x1="266.03" y1="77.54" x2="260.95" y2="77.54" width="0.1524" layer="91"/>
<label x="260.95" y="77.54" size="1.778" layer="95" rot="R0"/>
<pinref part="C12" gate="G$1" pin="1"/>
<wire x1="389.92" y1="75" x2="384.84" y2="75" width="0.1524" layer="91"/>
<label x="384.84" y="75" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="C2N3" class="0"><segment><pinref part="U3" gate="G$1" pin="C2-"/>
<wire x1="266.03" y1="75" x2="260.95" y2="75" width="0.1524" layer="91"/>
<label x="260.95" y="75" size="1.778" layer="95" rot="R0"/>
<pinref part="C12" gate="G$1" pin="2"/>
<wire x1="400.08" y1="75" x2="405.16" y2="75" width="0.1524" layer="91"/>
<label x="405.16" y="75" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="RS485_DI" class="0"><segment><pinref part="R8" gate="G$1" pin="2"/>
<wire x1="130.08" y1="30" x2="135.16" y2="30" width="0.1524" layer="91"/>
<label x="135.16" y="30" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="DI"/>
<wire x1="47.3" y1="27.46" x2="42.22" y2="27.46" width="0.1524" layer="91"/>
<label x="42.22" y="27.46" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="RS485_RO" class="0"><segment><pinref part="R9" gate="G$1" pin="2"/>
<wire x1="185.08" y1="30" x2="190.16" y2="30" width="0.1524" layer="91"/>
<label x="190.16" y="30" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="RO"/>
<wire x1="47.3" y1="35.08" x2="42.22" y2="35.08" width="0.1524" layer="91"/>
<label x="42.22" y="35.08" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="RS485_DE" class="0"><segment><pinref part="R10" gate="G$1" pin="2"/>
<wire x1="240.08" y1="30" x2="245.16" y2="30" width="0.1524" layer="91"/>
<label x="245.16" y="30" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="DE"/>
<wire x1="47.3" y1="30" x2="42.22" y2="30" width="0.1524" layer="91"/>
<label x="42.22" y="30" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="!RE"/>
<wire x1="47.3" y1="32.54" x2="42.22" y2="32.54" width="0.1524" layer="91"/>
<label x="42.22" y="32.54" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="RS485_A" class="0"><segment><pinref part="U4" gate="G$1" pin="A"/>
<wire x1="72.7" y1="35.08" x2="77.78" y2="35.08" width="0.1524" layer="91"/>
<label x="77.78" y="35.08" size="1.778" layer="95" rot="R0"/>
<pinref part="J5" gate="G$1" pin="1"/>
<wire x1="279.84" y1="33.81" x2="274.76" y2="33.81" width="0.1524" layer="91"/>
<label x="274.76" y="33.81" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="RS485_B" class="0"><segment><pinref part="U4" gate="G$1" pin="B"/>
<wire x1="72.7" y1="32.54" x2="77.78" y2="32.54" width="0.1524" layer="91"/>
<label x="77.78" y="32.54" size="1.778" layer="95" rot="R0"/>
<pinref part="J5" gate="G$1" pin="2"/>
<wire x1="279.84" y1="28.73" x2="274.76" y2="28.73" width="0.1524" layer="91"/>
<label x="274.76" y="28.73" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="LED_A" class="0"><segment><pinref part="R4" gate="G$1" pin="2"/>
<wire x1="205.08" y1="205" x2="210.16" y2="205" width="0.1524" layer="91"/>
<label x="210.16" y="205" size="1.778" layer="95" rot="R0"/>
<pinref part="LED1" gate="G$1" pin="A"/>
<wire x1="249.92" y1="205" x2="244.84" y2="205" width="0.1524" layer="91"/>
<label x="244.84" y="205" size="1.778" layer="95" rot="R0"/></segment></net></nets></sheet></sheets></schematic>
</drawing>
</eagle>
