#!/usr/bin/env python3
"""Generate core/sctables.c — the two lookup tables the terrain field needs.

calc/core/tables.c already supplies the 3x5 font, a 64-step sine and a log2
mantissa, and this port links against it unchanged. What it does not supply is
enough angular resolution for socal-geo.js's fractal texture term (its argument
is lon*21.3 + lat*13.7 radians, so a 5.6-degree sine step is useless) or a
gaussian falloff. Both are added here.

    python3 socal-calc/tools/gen_tables.py > socal-calc/core/sctables.c
"""
import math

SIN_N = 256         # samples per turn; linear interpolation between them
SIN_SCALE = 4096    # Q12
EXP_N = 130         # exp(-i/16), i = 0..129 (128 usable + 1 for interpolation)
EXP_SCALE = 256     # Q8


def emit(name, values, ctype, per_line=12):
    out = ["%s %s[%d] = {" % (ctype, name, len(values))]
    for i in range(0, len(values), per_line):
        out.append("  " + ", ".join(str(v) for v in values[i:i + per_line]) + ",")
    out.append("};")
    return "\n".join(out)


def main():
    # One full turn plus a wrap sample, so sc_sin_turn() can interpolate
    # between SC_SIN_Q12[255] and SC_SIN_Q12[256] without a modulo.
    sin = [int(round(math.sin(2 * math.pi * i / SIN_N) * SIN_SCALE)) for i in range(SIN_N + 1)]
    exp = [int(round(math.exp(-i / 16.0) * EXP_SCALE)) for i in range(EXP_N)]

    print("/* Generated by socal-calc/tools/gen_tables.py — do not edit by hand. */")
    print('#include "socal.h"')
    print()
    print("/* sin(2*pi*i/%d) in Q12, one turn plus a wrap sample. */" % SIN_N)
    print(emit("SC_SIN_Q12", sin, "const i16", per_line=10))
    print()
    print("/* exp(-i/16) in Q8 — the gaussian falloff of the relief features. */")
    print(emit("SC_EXP_Q8", exp, "const u16", per_line=12))


if __name__ == "__main__":
    main()
