#!/usr/bin/env python3
"""Generate core/fctables.c — the one lookup table the IDW field needs.

calc/core/tables.c already supplies the 3x5 font, a 64-step sine and a log2
mantissa, and this port links against it unchanged. The inverse-distance
weight needs 2^(-f/256) for the fractional part of a Q8 exponent: the integer
part is a shift, the fraction is this table. Unlike the SOCAL port there is no
sine and no gaussian here — the field is a weighted average, not a sum of
bumps.

    python3 four-corners-calc/tools/gen_tables.py > four-corners-calc/core/fctables.c
"""
import math

EXP2_N = 256         # fraction of the exponent, in 1/256
EXP2_SCALE = 65536   # Q16


def emit(name, values, ctype, per_line=12):
    out = ["%s %s[%d] = {" % (ctype, name, len(values))]
    for i in range(0, len(values), per_line):
        out.append("  " + ", ".join(str(v) for v in values[i:i + per_line]) + ",")
    out.append("};")
    return "\n".join(out)


def main():
    # 2^(-i/256) in Q16, clamped to u16. Index 256 would be exactly 0.5 but is
    # never read: f = t & 255, so 256 entries suffice. One extra wrap entry is
    # emitted anyway to keep the array a power-of-two size and the C honest.
    exp2 = [min(65535, int(round(math.pow(2.0, -i / EXP2_N) * EXP2_SCALE)))
            for i in range(EXP2_N + 1)]

    print("/* Generated by four-corners-calc/tools/gen_tables.py — do not edit by hand. */")
    print('#include "fourcorners.h"')
    print()
    print("/* 2^(-i/256) in Q16 — the fractional half of the IDW weight in core/geo.c. */")
    print(emit("FC_EXP2_Q16", exp2, "const u16", per_line=10))


if __name__ == "__main__":
    main()
