<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE eagle SYSTEM "eagle.dtd">
<!-- generated by tools/build-wallplug-eagle.mjs from tools/wimax-cpe-model.mjs — do not edit by hand -->
<eagle version="9.6.2">
<drawing>
<settings><setting alwaysvectorfont="no"/>
<setting verticaltext="up"/></settings>

<grid distance="2.54" unitdist="mm" unit="mm" style="lines" multiple="1" display="yes" altdistance="0.635" altunitdist="mm" altunit="mm"/>
<layers><layer number="90" name="Modules" color="5" fill="1" visible="yes" active="yes"/>
<layer number="91" name="Nets" color="2" fill="1" visible="yes" active="yes"/>
<layer number="92" name="Busses" color="1" fill="1" visible="yes" active="yes"/>
<layer number="93" name="Pins" color="2" fill="1" visible="yes" active="yes"/>
<layer number="94" name="Symbols" color="4" fill="1" visible="yes" active="yes"/>
<layer number="95" name="Names" color="7" fill="1" visible="yes" active="yes"/>
<layer number="96" name="Values" color="7" fill="1" visible="yes" active="yes"/>
<layer number="97" name="Info" color="7" fill="1" visible="yes" active="yes"/>
<layer number="98" name="Guide" color="6" fill="1" visible="yes" active="yes"/></layers>
<schematic xreflabel="%F%N/%S.%C%R" xrefpart="/%S.%C%R"><description>WiMAX CPE Wallplug: mains-powered PCI Express Mini Card carrier for an IEEE 802.16e WiMAX modem (Intel Centrino Advanced-N + WiMAX 6250), USB 2.0 to the host</description>
<libraries><library name="wimax-cpe"><description>wimax-cpe: WiMAX CPE Wallplug design library (generated by tools/build-wallplug-eagle.mjs from tools/wimax-cpe-model.mjs)</description>
<packages><package name="R-7.62"><description>Resistor, axial DIN0207 (6.3 x 2.5 mm), 7.62 mm pitch</description>
<wire x1="-3.15" y1="1.25" x2="3.15" y2="1.25" width="0.2032" layer="21"/>
<wire x1="3.15" y1="1.25" x2="3.15" y2="-1.25" width="0.2032" layer="21"/>
<wire x1="3.15" y1="-1.25" x2="-3.15" y2="-1.25" width="0.2032" layer="21"/>
<wire x1="-3.15" y1="-1.25" x2="-3.15" y2="1.25" width="0.2032" layer="21"/>
<wire x1="-3.81" y1="0" x2="-3.15" y2="0" width="0.2032" layer="51"/>
<wire x1="3.15" y1="0" x2="3.81" y2="0" width="0.2032" layer="51"/>
<text x="-3.15" y="1.75" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-3.81" y="0" drill="0.8" diameter="1.7" shape="square"/>
<pad name="2" x="3.81" y="0" drill="0.8" diameter="1.7"/></package>
<package name="C-5.08"><description>Ceramic / film disc capacitor, 5.0 x 2.5 mm, 5.08 mm pitch</description>
<wire x1="-2.5" y1="1.25" x2="2.5" y2="1.25" width="0.2032" layer="21"/>
<wire x1="2.5" y1="1.25" x2="2.5" y2="-1.25" width="0.2032" layer="21"/>
<wire x1="2.5" y1="-1.25" x2="-2.5" y2="-1.25" width="0.2032" layer="21"/>
<wire x1="-2.5" y1="-1.25" x2="-2.5" y2="1.25" width="0.2032" layer="21"/>
<wire x1="-2.54" y1="0" x2="-2.5" y2="0" width="0.2032" layer="51"/>
<wire x1="2.5" y1="0" x2="2.54" y2="0" width="0.2032" layer="51"/>
<text x="-2.5" y="1.75" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-2.54" y="0" drill="0.8" diameter="1.7" shape="square"/>
<pad name="2" x="2.54" y="0" drill="0.8" diameter="1.7"/></package>
<package name="CP-D10-P5"><description>Electrolytic, radial, 10 mm dia, 5.0 mm pitch</description>
<circle x="0" y="0" radius="5" width="0.2032" layer="21"/>
<text x="-4.4" y="-4.6" size="1.4" layer="21">+</text>
<text x="-5" y="5.4" size="1" layer="25">&gt;NAME</text>
<pad name="+" x="-2.5" y="0" drill="1" diameter="2" shape="square"/>
<pad name="-" x="2.5" y="0" drill="1" diameter="2"/></package>
<package name="CP-D6.3-P2.5"><description>Electrolytic, radial, 6.3 mm dia, 2.5 mm pitch</description>
<circle x="0" y="0" radius="3.15" width="0.2032" layer="21"/>
<text x="-2.55" y="-2.75" size="1.4" layer="21">+</text>
<text x="-3.15" y="3.55" size="1" layer="25">&gt;NAME</text>
<pad name="+" x="-1.25" y="0" drill="1" diameter="2" shape="square"/>
<pad name="-" x="1.25" y="0" drill="1" diameter="2"/></package>
<package name="FB-7.62"><description>Ferrite bead, axial 7.2 x 4.0 mm, 7.62 mm pitch</description>
<wire x1="-3.6" y1="2" x2="3.6" y2="2" width="0.2032" layer="21"/>
<wire x1="3.6" y1="2" x2="3.6" y2="-2" width="0.2032" layer="21"/>
<wire x1="3.6" y1="-2" x2="-3.6" y2="-2" width="0.2032" layer="21"/>
<wire x1="-3.6" y1="-2" x2="-3.6" y2="2" width="0.2032" layer="21"/>
<wire x1="-3.81" y1="0" x2="-3.6" y2="0" width="0.2032" layer="51"/>
<wire x1="3.6" y1="0" x2="3.81" y2="0" width="0.2032" layer="51"/>
<text x="-3.6" y="2.5" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-3.81" y="0" drill="0.8" diameter="1.7" shape="square"/>
<pad name="2" x="3.81" y="0" drill="0.8" diameter="1.7"/></package>
<package name="FUSE-RADIAL"><description>Radial fuse, TR5 / 372 series, 8.5 mm body, 5.08 mm pitch</description>
<circle x="0" y="0" radius="4.25" width="0.2032" layer="21"/>
<wire x1="-2.54" y1="0" x2="-4.25" y2="0" width="0.2032" layer="51"/>
<wire x1="4.25" y1="0" x2="2.54" y2="0" width="0.2032" layer="51"/>
<text x="-4.25" y="4.75" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-2.54" y="0" drill="1" diameter="2" shape="square"/>
<pad name="2" x="2.54" y="0" drill="1" diameter="2"/></package>
<package name="MOV07"><description>Metal-oxide varistor, 7 mm disc, 5.0 mm pitch</description>
<circle x="0" y="0" radius="3.5" width="0.2032" layer="21"/>
<wire x1="-2.5" y1="0" x2="-3.5" y2="0" width="0.2032" layer="51"/>
<wire x1="3.5" y1="0" x2="2.5" y2="0" width="0.2032" layer="51"/>
<text x="-3.5" y="4" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-2.5" y="0" drill="0.8" diameter="1.8" shape="square"/>
<pad name="2" x="2.5" y="0" drill="0.8" diameter="1.8"/></package>
<package name="LED-5MM"><description>LED 5 mm, 2.54 mm pitch</description>
<circle x="0" y="0" radius="2.5" width="0.2032" layer="21"/>
<wire x1="-1.27" y1="0" x2="-2.5" y2="0" width="0.2032" layer="51"/>
<wire x1="2.5" y1="0" x2="1.27" y2="0" width="0.2032" layer="51"/>
<text x="-2.5" y="3" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-1.27" y="0" drill="0.8" diameter="1.7" shape="square"/>
<pad name="2" x="1.27" y="0" drill="0.8" diameter="1.7"/></package>
<package name="SW-TACT-6MM"><description>Tactile pushbutton 6 x 6 mm, 2 poles (pins 1/1 and 2/2 internally common)</description>
<wire x1="-3" y1="-3" x2="3" y2="-3" width="0.2032" layer="21"/>
<wire x1="3" y1="-3" x2="3" y2="3" width="0.2032" layer="21"/>
<wire x1="3" y1="3" x2="-3" y2="3" width="0.2032" layer="21"/>
<wire x1="-3" y1="3" x2="-3" y2="-3" width="0.2032" layer="21"/>
<text x="-3" y="4.2" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-3.25" y="-2.25" drill="1.1" diameter="2" shape="square"/>
<pad name="1" x="3.25" y="-2.25" drill="1.1" diameter="2"/>
<pad name="2" x="-3.25" y="2.25" drill="1.1" diameter="2"/>
<pad name="2" x="3.25" y="2.25" drill="1.1" diameter="2"/></package>
<package name="TP"><description>Test point, 1.0 mm hole, 2.0 mm pad</description>
<text x="-1.2" y="1.6" size="0.9" layer="25">&gt;NAME</text>
<pad name="1" x="0" y="0" drill="1" diameter="2"/></package>
<package name="MOUNT-M3"><description>M3 mounting hole, 3.2 mm, non-plated, with keep-out ring</description>
<circle x="0" y="0" radius="2.4" width="0.2032" layer="41"/>
<circle x="0" y="0" radius="2.4" width="0.2032" layer="41"/>
<hole x="0" y="0" drill="3.2"/></package>
<package name="CUI_TB003"><description>CUI TB003-500-P03BE, 3-position 5.00 mm terminal block, drill 1.4 mm</description>

<pad name="1" x="-5" y="0" drill="1.4" diameter="2.1" shape="square"/>
<pad name="2" x="0" y="0" drill="1.4" diameter="2.1"/>
<pad name="3" x="5" y="0" drill="1.4" diameter="2.1"/></package>
<package name="MPM2012"><description>MEAN WELL MPM-20-12, 20 W encapsulated AC-DC, 12 V / 1.67 A out</description>

<pad name="1" x="22.733" y="9.906" drill="1.24" diameter="1.86"/>
<pad name="2" x="22.733" y="-10.894" drill="1.24" diameter="1.86"/>
<pad name="4" x="-22.267" y="9.906" drill="1.24" diameter="1.86"/>
<pad name="3" x="-22.267" y="1.906" drill="1.24" diameter="1.86"/></package>
<package name="LM2576S"><description>TO-263-5 (D2PAK) with tab tied to pin 3 — LM2576S-3.3 step-down regulator</description>

<smd name="1" x="-5.775" y="3.4" dx="4.6" dy="1.1" layer="1"/>
<smd name="2" x="-5.775" y="1.7" dx="4.6" dy="1.1" layer="1"/>
<smd name="3" x="-5.775" y="0" dx="4.6" dy="1.1" layer="1"/>
<smd name="4" x="-5.775" y="-1.7" dx="4.6" dy="1.1" layer="1"/>
<smd name="5" x="-5.775" y="-3.4" dx="4.6" dy="1.1" layer="1"/>
<smd name="3_2" x="3.375" y="0" dx="9.4" dy="10.8" layer="1"/>
<smd name="P7" x="5.8" y="-2.775" dx="4.55" dy="5.25" layer="1"/>
<smd name="P8" x="0.95" y="2.775" dx="4.55" dy="5.25" layer="1"/>
<smd name="P9" x="5.8" y="2.775" dx="4.55" dy="5.25" layer="1"/>
<smd name="P10" x="0.95" y="-2.775" dx="4.55" dy="5.25" layer="1"/></package>
<package name="LRAD12"><description>Radial power inductor, Ø12 mm body, 5.0 mm lead pitch — 100 µH for the LM2576</description>

<pad name="1" x="0" y="0" drill="1.3" diameter="2.6"/>
<pad name="2" x="5" y="0" drill="1.3" diameter="2.6"/></package>
<package name="MPCIE"><description>PCI Express Mini Card socket, 52 positions at 0.8 mm, two staggered rows, half-size card (30 x 26.8 mm), Ø2.6 mounting holes</description>

<smd name="15" x="-2.35" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="19" x="2.45" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="21" x="3.25" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="23" x="4.05" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="25" x="4.85" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="27" x="5.65" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="29" x="6.45" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="31" x="7.25" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="33" x="8.05" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="35" x="8.85" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="37" x="9.65" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="39" x="10.45" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="41" x="11.25" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="43" x="12.05" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="45" x="12.85" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="47" x="13.65" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="49" x="14.45" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="51" x="15.25" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="13" x="-3.15" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="11" x="-3.95" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="9" x="-4.75" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="7" x="-5.55" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="5" x="-6.35" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="3" x="-7.15" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="1" x="-7.95" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="17" x="1.65" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="18" x="2.05" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="20" x="2.85" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="22" x="3.65" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="24" x="4.45" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="26" x="5.25" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="28" x="6.05" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="30" x="6.85" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="32" x="7.65" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="34" x="8.45" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="36" x="9.25" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="38" x="10.05" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="40" x="10.85" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="42" x="11.65" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="44" x="12.45" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="46" x="13.25" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="48" x="14.05" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="50" x="14.85" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="52" x="15.65" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="16" x="-1.95" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="14" x="-2.75" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="12" x="-3.55" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="10" x="-4.35" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="8" x="-5.15" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="6" x="-5.95" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="4" x="-6.75" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<smd name="2" x="-7.55" y="1.375" dx="0.6" dy="2.35" layer="1"/>
<hole x="-8.25" y="23.9" drill="2.6"/>
<hole x="15.95" y="23.9" drill="2.6"/></package>
<package name="USBMB"><description>Molex 105017-0001 USB Micro-B receptacle — upstream host connection</description>

<smd name="6" x="1" y="-1.2375" dx="1.5" dy="1.9" layer="1"/>
<pad name="6_2" x="-2.5" y="1.4625" drill="0.85" diameter="1.45"/>
<smd name="2" x="-0.65" y="1.4625" dx="0.4" dy="1.35" layer="1"/>
<smd name="1" x="-1.3" y="1.4625" dx="0.4" dy="1.35" layer="1"/>
<smd name="5" x="1.3" y="1.4625" dx="0.4" dy="1.35" layer="1"/>
<smd name="4" x="0.65" y="1.4625" dx="0.4" dy="1.35" layer="1"/>
<smd name="3" x="0" y="1.4625" dx="0.4" dy="1.35" layer="1"/>
<pad name="6_3" x="2.5" y="1.4625" drill="0.85" diameter="1.45"/>
<smd name="6_4" x="-1" y="-1.2375" dx="1.5" dy="1.9" layer="1"/>
<pad name="6_5" x="-3.5" y="-1.2375" drill="0.6" diameter="1.2" shape="square"/>
<pad name="6_6" x="3.5" y="-1.2375" drill="0.6" diameter="1.2" shape="square"/>
<smd name="6_7" x="2.9" y="-1.2375" dx="1.2" dy="1.9" layer="1"/>
<smd name="6_8" x="-2.9" y="-1.2375" dx="1.2" dy="1.9" layer="1"/></package>
<package name="MICROSIM"><description>JAE SF53S006VCBR2000 micro-SIM holder — for the UIM pins of a mini-PCIe modem card</description>

<smd name="SH" x="-6.105" y="-7.11" dx="1.4" dy="1.7" layer="1"/>
<smd name="SH_2" x="6.105" y="-7.11" dx="1.4" dy="1.7" layer="1"/>
<smd name="SH_3" x="-6.27" y="2.45" dx="0.45" dy="1.3" layer="1"/>
<smd name="SH_4" x="-6.27" y="4.45" dx="0.45" dy="1.3" layer="1"/>
<smd name="SH_5" x="6.27" y="2.45" dx="0.45" dy="1.3" layer="1"/>
<smd name="SH_6" x="6.27" y="4.45" dx="0.45" dy="1.3" layer="1"/>
<smd name="SH_7" x="-2.535" y="-6.53" dx="0.54" dy="0.8" layer="1"/>
<smd name="SH_8" x="2.545" y="-6.53" dx="0.54" dy="0.8" layer="1"/>
<smd name="1" x="2.755" y="6.62" dx="0.65" dy="1.15" layer="1"/>
<smd name="2" x="0.215" y="6.62" dx="0.65" dy="1.15" layer="1"/>
<smd name="3" x="-2.325" y="6.62" dx="0.65" dy="1.15" layer="1"/>
<smd name="5" x="4.025" y="6.62" dx="0.65" dy="1.15" layer="1"/>
<smd name="6" x="1.485" y="6.62" dx="0.65" dy="1.15" layer="1"/>
<smd name="7" x="-1.055" y="6.62" dx="0.65" dy="1.15" layer="1"/></package>
<package name="AMS1117"><description>SOT-223 with tab tied to pin 2 (VOUT) — AMS1117-3.3 / LD1117S33 linear regulator</description>

<smd name="2" x="3.15" y="0" dx="2" dy="3.8" layer="1"/>
<smd name="2_2" x="-3.15" y="0" dx="2" dy="1.5" layer="1"/>
<smd name="3" x="-3.15" y="-2.3" dx="2" dy="1.5" layer="1"/>
<smd name="1" x="-3.15" y="2.3" dx="2" dy="1.5" layer="1"/></package>
<package name="R0603"><description>0603 (1608 metric) chip resistor</description>

<smd name="1" x="-0.825" y="0" dx="0.8" dy="0.95" layer="1"/>
<smd name="2" x="0.825" y="0" dx="0.8" dy="0.95" layer="1"/></package>
<package name="C0603"><description>0603 (1608 metric) chip capacitor</description>

<smd name="1" x="-0.775" y="0" dx="0.9" dy="0.95" layer="1"/>
<smd name="2" x="0.775" y="0" dx="0.9" dy="0.95" layer="1"/></package>
<package name="DO41"><description>DO-41 axial diode, 7.62 mm lead pitch (1N5822 / SS34-class Schottky)</description>
<wire x1="-2.5" y1="1.3" x2="2.5" y2="1.3" width="0.2032" layer="21"/>
<wire x1="2.5" y1="1.3" x2="2.5" y2="-1.3" width="0.2032" layer="21"/>
<wire x1="2.5" y1="-1.3" x2="-2.5" y2="-1.3" width="0.2032" layer="21"/>
<wire x1="-2.5" y1="-1.3" x2="-2.5" y2="1.3" width="0.2032" layer="21"/>
<wire x1="1.6" y1="1.3" x2="1.6" y2="-1.3" width="0.2032" layer="21"/>
<text x="-2.4" y="1.9" size="1" layer="25">&gt;NAME</text>
<pad name="A" x="-3.81" y="0" drill="0.9" diameter="1.8"/>
<pad name="K" x="3.81" y="0" drill="0.9" diameter="1.8" shape="square"/></package></packages>
<symbols><symbol name="R-EU"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="0" x2="-1.9" y2="1" width="0.2032" layer="94"/>
<wire x1="-1.9" y1="1" x2="-0.63" y2="-1" width="0.2032" layer="94"/>
<wire x1="-0.63" y1="-1" x2="0.63" y2="1" width="0.2032" layer="94"/>
<wire x1="0.63" y1="1" x2="1.9" y2="-1" width="0.2032" layer="94"/>
<wire x1="1.9" y1="-1" x2="2.54" y2="0" width="0.2032" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="C-EU"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="-1.27" y1="0.9" x2="1.27" y2="0.9" width="0.3" layer="94"/>
<wire x1="-1.27" y1="-0.9" x2="1.27" y2="-0.9" width="0.3" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="CPOL-EU"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="-1.27" y1="0.9" x2="1.27" y2="0.9" width="0.3" layer="94"/>
<wire x1="-1.27" y1="-0.9" x2="1.27" y2="-0.9" width="0.3" layer="94" style="shortdash"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<text x="-3.4" y="1.2" size="1.6" layer="94">+</text>
<pin name="+" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="-" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="FERRITE"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="FUSE"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="MOV"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="LED"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="1" y1="1.6" x2="2.2" y2="2.8" width="0.2032" layer="94"/>
<wire x1="1.8" y1="1.6" x2="3" y2="2.8" width="0.2032" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="A" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="K" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="SW-PUSH"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.2032" layer="94"/>
<wire x1="0" y1="1.27" x2="0" y2="2.54" width="0.2032" layer="94"/>
<wire x1="-2.54" y1="0" x2="-1.27" y2="0" width="0.2032" layer="94"/>
<wire x1="1.27" y1="0" x2="2.54" y2="0" width="0.2032" layer="94"/>
<text x="-3.81" y="3.54" size="1.778" layer="95">&gt;NAME</text>
<text x="-3.81" y="-5.14" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="TP"><circle x="0" y="0" radius="1.27" width="0.2032" layer="94"/>
<text x="-1.27" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-1.27" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="0" y="-3.81" visible="pin" length="short" direction="pas" rot="R90"/></symbol>
<symbol name="ACDC-4"><wire x1="-12.7" y1="3.81" x2="12.7" y2="3.81" width="0.4064" layer="94"/>
<wire x1="12.7" y1="3.81" x2="12.7" y2="-3.81" width="0.4064" layer="94"/>
<wire x1="12.7" y1="-3.81" x2="-12.7" y2="-3.81" width="0.4064" layer="94"/>
<wire x1="-12.7" y1="-3.81" x2="-12.7" y2="3.81" width="0.4064" layer="94"/>
<text x="-12.7" y="4.81" size="1.778" layer="95">&gt;NAME</text>
<text x="-12.7" y="-6.41" size="1.778" layer="96">&gt;VALUE</text>
<text x="-8" y="0" size="1.6" layer="94" ratio="10">AC / DC</text>
<text x="-8" y="-2.6" size="1.3" layer="94" ratio="10">isolated</text>
<pin name="AC-L" x="-12.7" y="1.27" visible="pin" length="middle" rot="R0"/>
<pin name="AC-N" x="-12.7" y="-1.27" visible="pin" length="middle" rot="R0"/>
<pin name="+VO" x="12.7" y="1.27" visible="pin" length="middle" rot="R180"/>
<pin name="-VO" x="12.7" y="-1.27" visible="pin" length="middle" rot="R180"/></symbol>
<symbol name="BUCK-3V3"><wire x1="-10.16" y1="3.81" x2="10.16" y2="3.81" width="0.4064" layer="94"/>
<wire x1="10.16" y1="3.81" x2="10.16" y2="-3.81" width="0.4064" layer="94"/>
<wire x1="10.16" y1="-3.81" x2="-10.16" y2="-3.81" width="0.4064" layer="94"/>
<wire x1="-10.16" y1="-3.81" x2="-10.16" y2="3.81" width="0.4064" layer="94"/>
<text x="-10.16" y="4.81" size="1.778" layer="95">&gt;NAME</text>
<text x="-10.16" y="-6.41" size="1.778" layer="96">&gt;VALUE</text>
<text x="-7.6" y="0" size="1.5" layer="94" ratio="10">LM2576</text>
<pin name="VIN" x="-10.16" y="1.27" visible="pin" length="middle" rot="R0"/>
<pin name="FB" x="-10.16" y="-1.27" visible="pin" length="middle" rot="R0"/>
<pin name="VOUT" x="10.16" y="1.27" visible="pin" length="middle" rot="R180"/>
<pin name="ONOFF" x="10.16" y="-1.27" visible="pin" length="middle" rot="R180"/>
<pin name="GND" x="0" y="-3.81" visible="pin" length="middle" rot="R90"/></symbol>
<symbol name="DIODE"><wire x1="-3.81" y1="2.54" x2="3.81" y2="2.54" width="0.254" layer="94"/>
<wire x1="3.81" y1="2.54" x2="3.81" y2="-2.54" width="0.254" layer="94"/>
<wire x1="3.81" y1="-2.54" x2="-3.81" y2="-2.54" width="0.254" layer="94"/>
<wire x1="-3.81" y1="-2.54" x2="-3.81" y2="2.54" width="0.254" layer="94"/>
<wire x1="-1.27" y1="1.27" x2="-1.27" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-1.27" y1="0" x2="1.27" y2="1.27" width="0.254" layer="94"/>
<wire x1="1.27" y1="1.27" x2="1.27" y2="-1.27" width="0.254" layer="94"/>
<wire x1="1.27" y1="-1.27" x2="-1.27" y2="0" width="0.254" layer="94"/>
<text x="-3.81" y="3.54" size="1.778" layer="95">&gt;NAME</text>
<text x="-3.81" y="-5.14" size="1.778" layer="96">&gt;VALUE</text>
<pin name="A" x="-7.62" y="0" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="K" x="7.62" y="0" visible="pin" length="middle" direction="pas" rot="R180"/></symbol>
<symbol name="INDUCTOR"><wire x1="-5.08" y1="2.54" x2="5.08" y2="2.54" width="0.254" layer="94"/>
<wire x1="5.08" y1="2.54" x2="5.08" y2="-2.54" width="0.254" layer="94"/>
<wire x1="5.08" y1="-2.54" x2="-5.08" y2="-2.54" width="0.254" layer="94"/>
<wire x1="-5.08" y1="-2.54" x2="-5.08" y2="2.54" width="0.254" layer="94"/>
<circle x="-2.54" y="0.9" radius="1.27" width="0.254" layer="94"/>
<circle x="0" y="0.9" radius="1.27" width="0.254" layer="94"/>
<circle x="2.54" y="0.9" radius="1.27" width="0.254" layer="94"/>
<text x="-5.08" y="3.54" size="1.778" layer="95">&gt;NAME</text>
<text x="-5.08" y="-5.14" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-10.16" y="0" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="2" x="10.16" y="0" visible="pin" length="middle" direction="pas" rot="R180"/></symbol>
<symbol name="TERM-3"><wire x1="-7.62" y1="8.89" x2="7.62" y2="8.89" width="0.4064" layer="94"/>
<wire x1="7.62" y1="8.89" x2="7.62" y2="-8.89" width="0.4064" layer="94"/>
<wire x1="7.62" y1="-8.89" x2="-7.62" y2="-8.89" width="0.4064" layer="94"/>
<wire x1="-7.62" y1="-8.89" x2="-7.62" y2="8.89" width="0.4064" layer="94"/>
<text x="-7.62" y="9.89" size="1.778" layer="95">&gt;NAME</text>
<text x="-7.62" y="-11.49" size="1.778" layer="96">&gt;VALUE</text>
<text x="-4.5" y="0" size="1.5" layer="94" ratio="10">TB3</text>
<pin name="1" x="-7.62" y="5.08" visible="pin" length="middle" rot="R0"/>
<pin name="2" x="-7.62" y="0" visible="pin" length="middle" rot="R0"/>
<pin name="3" x="-7.62" y="-5.08" visible="pin" length="middle" rot="R0"/></symbol>
<symbol name="MPCIE"><wire x1="-16.51" y1="34.29" x2="16.51" y2="34.29" width="0.4064" layer="94"/>
<wire x1="16.51" y1="34.29" x2="16.51" y2="-34.29" width="0.4064" layer="94"/>
<wire x1="16.51" y1="-34.29" x2="-16.51" y2="-34.29" width="0.4064" layer="94"/>
<wire x1="-16.51" y1="-34.29" x2="-16.51" y2="34.29" width="0.4064" layer="94"/>
<text x="-16.51" y="35.29" size="1.778" layer="95">&gt;NAME</text>
<text x="-16.51" y="-36.89" size="1.778" layer="96">&gt;VALUE</text>
<text x="-13" y="0" size="1.5" layer="94" ratio="10">Mini Card socket</text>
<text x="-13" y="-2.6" size="1.2" layer="94" ratio="10">52 pos / 0.8 mm</text>
<pin name="!WAKE" x="-16.51" y="31.75" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="3V3AUX" x="-16.51" y="29.21" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="COEX1" x="-16.51" y="26.67" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GND" x="-16.51" y="24.13" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="COEX2" x="-16.51" y="21.59" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="1V5" x="-16.51" y="19.05" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="!CLKREQ" x="-16.51" y="16.51" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="UIM_PWR" x="-16.51" y="13.97" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GND_9" x="-16.51" y="11.43" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="UIM_DATA" x="-16.51" y="8.89" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="REFCLK_N" x="-16.51" y="6.35" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="UIM_CLK" x="-16.51" y="3.81" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="REFCLK_P" x="-16.51" y="1.27" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="UIM_RESET" x="-16.51" y="-1.27" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GND_15" x="-16.51" y="-3.81" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="UIM_VPP" x="-16.51" y="-6.35" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="RSVD_UIM_C8" x="-16.51" y="-8.89" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GND_18" x="-16.51" y="-11.43" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="UIM_IC_DP" x="-16.51" y="-13.97" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="!W_DISABLE" x="-16.51" y="-16.51" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GND_21" x="-16.51" y="-19.05" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="!PERST" x="-16.51" y="-21.59" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="PERn0" x="-16.51" y="-24.13" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="3V3AUX_24" x="-16.51" y="-26.67" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="PERp0" x="-16.51" y="-29.21" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GND_26" x="-16.51" y="-31.75" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="GND_27" x="16.51" y="31.75" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="1V5_28" x="16.51" y="29.21" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GND_29" x="16.51" y="26.67" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="SMB_CLK" x="16.51" y="24.13" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GND_31" x="16.51" y="21.59" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="SMB_DATA" x="16.51" y="19.05" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="PETp0" x="16.51" y="16.51" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GND_34" x="16.51" y="13.97" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GND_35" x="16.51" y="11.43" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="USB_D_N" x="16.51" y="8.89" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GND_37" x="16.51" y="6.35" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="USB_D_P" x="16.51" y="3.81" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="3V3AUX_39" x="16.51" y="1.27" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GND_40" x="16.51" y="-1.27" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="3V3AUX_41" x="16.51" y="-3.81" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="!LED_WWAN" x="16.51" y="-6.35" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="!LED_WLAN" x="16.51" y="-8.89" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="!LED_WPAN" x="16.51" y="-11.43" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="RSVD_45" x="16.51" y="-13.97" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="RSVD_46" x="16.51" y="-16.51" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="RSVD_47" x="16.51" y="-19.05" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="1V5_48" x="16.51" y="-21.59" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="RSVD_49" x="16.51" y="-24.13" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="GND_50" x="16.51" y="-26.67" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="!W_DISABLE2" x="16.51" y="-29.21" visible="pin" length="middle" direction="pas" rot="R180"/>
<pin name="3V3AUX_52" x="16.51" y="-31.75" visible="pin" length="middle" direction="pas" rot="R180"/></symbol>
<symbol name="USB-MICRO-B"><wire x1="-10.16" y1="5.08" x2="10.16" y2="5.08" width="0.4064" layer="94"/>
<wire x1="10.16" y1="5.08" x2="10.16" y2="-5.08" width="0.4064" layer="94"/>
<wire x1="10.16" y1="-5.08" x2="-10.16" y2="-5.08" width="0.4064" layer="94"/>
<wire x1="-10.16" y1="-5.08" x2="-10.16" y2="5.08" width="0.4064" layer="94"/>
<text x="-10.16" y="6.08" size="1.778" layer="95">&gt;NAME</text>
<text x="-10.16" y="-7.68" size="1.778" layer="96">&gt;VALUE</text>
<pin name="VBUS" x="-10.16" y="2.54" visible="pin" length="middle" rot="R0"/>
<pin name="DM" x="-10.16" y="0" visible="pin" length="middle" rot="R0"/>
<pin name="DP" x="-10.16" y="-2.54" visible="pin" length="middle" rot="R0"/>
<pin name="ID" x="10.16" y="2.54" visible="pin" length="middle" rot="R180"/>
<pin name="GND" x="10.16" y="0" visible="pin" length="middle" rot="R180"/>
<pin name="SH" x="0" y="-5.08" visible="pin" length="middle" rot="R90"/></symbol>
<symbol name="MICRO-SIM"><wire x1="-11.43" y1="5.08" x2="11.43" y2="5.08" width="0.4064" layer="94"/>
<wire x1="11.43" y1="5.08" x2="11.43" y2="-5.08" width="0.4064" layer="94"/>
<wire x1="11.43" y1="-5.08" x2="-11.43" y2="-5.08" width="0.4064" layer="94"/>
<wire x1="-11.43" y1="-5.08" x2="-11.43" y2="5.08" width="0.4064" layer="94"/>
<text x="-11.43" y="6.08" size="1.778" layer="95">&gt;NAME</text>
<text x="-11.43" y="-7.68" size="1.778" layer="96">&gt;VALUE</text>
<pin name="VCC" x="-11.43" y="2.54" visible="pin" length="middle" rot="R0"/>
<pin name="RST" x="-11.43" y="0" visible="pin" length="middle" rot="R0"/>
<pin name="CLK" x="-11.43" y="-2.54" visible="pin" length="middle" rot="R0"/>
<pin name="IO" x="11.43" y="2.54" visible="pin" length="middle" rot="R180"/>
<pin name="GND" x="11.43" y="0" visible="pin" length="middle" rot="R180"/>
<pin name="DET" x="11.43" y="-2.54" visible="pin" length="middle" rot="R180"/>
<pin name="SH" x="0" y="-5.08" visible="pin" length="middle" rot="R90"/></symbol>
<symbol name="LDO-3V3"><wire x1="-7.62" y1="3.81" x2="7.62" y2="3.81" width="0.4064" layer="94"/>
<wire x1="7.62" y1="3.81" x2="7.62" y2="-3.81" width="0.4064" layer="94"/>
<wire x1="7.62" y1="-3.81" x2="-7.62" y2="-3.81" width="0.4064" layer="94"/>
<wire x1="-7.62" y1="-3.81" x2="-7.62" y2="3.81" width="0.4064" layer="94"/>
<text x="-7.62" y="4.81" size="1.778" layer="95">&gt;NAME</text>
<text x="-7.62" y="-6.41" size="1.778" layer="96">&gt;VALUE</text>
<text x="-5" y="0" size="1.5" layer="94" ratio="10">1117</text>
<pin name="VI" x="-7.62" y="0" visible="pin" length="middle" rot="R0"/>
<pin name="VO" x="7.62" y="0" visible="pin" length="middle" rot="R180"/>
<pin name="GND" x="0" y="-3.81" visible="pin" length="middle" rot="R90"/></symbol></symbols>
<devicesets><deviceset name="R-EU" prefix="R"><gates><gate name="G$1" symbol="R-EU" x="0" y="0"/></gates>
<devices><device package="R-7.62"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="C-EU" prefix="C"><gates><gate name="G$1" symbol="C-EU" x="0" y="0"/></gates>
<devices><device package="C-5.08"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="CPOL-EU" prefix="C"><gates><gate name="G$1" symbol="CPOL-EU" x="0" y="0"/></gates>
<devices><device package="CP-D10-P5"><connects><connect gate="G$1" pin="+" pad="+"/>
<connect gate="G$1" pin="-" pad="-"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="CPOL-SMALL" prefix="C"><gates><gate name="G$1" symbol="CPOL-EU" x="0" y="0"/></gates>
<devices><device package="CP-D6.3-P2.5"><connects><connect gate="G$1" pin="+" pad="+"/>
<connect gate="G$1" pin="-" pad="-"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="FERRITE" prefix="FB"><gates><gate name="G$1" symbol="FERRITE" x="0" y="0"/></gates>
<devices><device package="FB-7.62"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="FUSE" prefix="F"><gates><gate name="G$1" symbol="FUSE" x="0" y="0"/></gates>
<devices><device package="FUSE-RADIAL"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="MOV" prefix="MOV"><gates><gate name="G$1" symbol="MOV" x="0" y="0"/></gates>
<devices><device package="MOV07"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="LED" prefix="LED"><gates><gate name="G$1" symbol="LED" x="0" y="0"/></gates>
<devices><device package="LED-5MM"><connects><connect gate="G$1" pin="A" pad="1"/>
<connect gate="G$1" pin="K" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="SW-PUSH" prefix="SW"><gates><gate name="G$1" symbol="SW-PUSH" x="0" y="0"/></gates>
<devices><device package="SW-TACT-6MM"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="TP" prefix="TP"><gates><gate name="G$1" symbol="TP" x="0" y="0"/></gates>
<devices><device package="TP"><connects><connect gate="G$1" pin="1" pad="1"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="MOUNT-M3" prefix="H"><gates></gates>
<devices><device package="MOUNT-M3"><connects></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="ACDC-12V" prefix="PS"><gates><gate name="G$1" symbol="ACDC-4" x="0" y="0"/></gates>
<devices><device package="MPM2012"><connects><connect gate="G$1" pin="AC-N" pad="1"/>
<connect gate="G$1" pin="AC-L" pad="2"/>
<connect gate="G$1" pin="+VO" pad="3"/>
<connect gate="G$1" pin="-VO" pad="4"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="BUCK-3V3" prefix="U"><gates><gate name="G$1" symbol="BUCK-3V3" x="0" y="0"/></gates>
<devices><device package="LM2576S"><connects><connect gate="G$1" pin="VIN" pad="1"/>
<connect gate="G$1" pin="VOUT" pad="2"/>
<connect gate="G$1" pin="GND" pad="3 3_2 P7 P8 P9 P10"/>
<connect gate="G$1" pin="FB" pad="4"/>
<connect gate="G$1" pin="ONOFF" pad="5"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="DIODE-SCH" prefix="D"><gates><gate name="G$1" symbol="DIODE" x="0" y="0"/></gates>
<devices><device package="DO41"><connects><connect gate="G$1" pin="A" pad="A"/>
<connect gate="G$1" pin="K" pad="K"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="L-RADIAL" prefix="L"><gates><gate name="G$1" symbol="INDUCTOR" x="0" y="0"/></gates>
<devices><device package="LRAD12"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="TERM-3" prefix="J"><gates><gate name="G$1" symbol="TERM-3" x="0" y="0"/></gates>
<devices><device package="CUI_TB003"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/>
<connect gate="G$1" pin="3" pad="3"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="R-0603" prefix="R"><gates><gate name="G$1" symbol="R-EU" x="0" y="0"/></gates>
<devices><device package="R0603"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="C-0603" prefix="C"><gates><gate name="G$1" symbol="C-EU" x="0" y="0"/></gates>
<devices><device package="C0603"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="LDO-3V3" prefix="U"><gates><gate name="G$1" symbol="LDO-3V3" x="0" y="0"/></gates>
<devices><device package="AMS1117"><connects><connect gate="G$1" pin="GND" pad="1"/>
<connect gate="G$1" pin="VO" pad="2 2_2"/>
<connect gate="G$1" pin="VI" pad="3"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="USB-MICRO-B" prefix="J"><gates><gate name="G$1" symbol="USB-MICRO-B" x="0" y="0"/></gates>
<devices><device package="USBMB"><connects><connect gate="G$1" pin="VBUS" pad="1"/>
<connect gate="G$1" pin="DM" pad="2"/>
<connect gate="G$1" pin="DP" pad="3"/>
<connect gate="G$1" pin="ID" pad="4"/>
<connect gate="G$1" pin="GND" pad="5"/>
<connect gate="G$1" pin="SH" pad="6 6_2 6_3 6_4 6_5 6_6 6_7 6_8"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="MICRO-SIM" prefix="J"><gates><gate name="G$1" symbol="MICRO-SIM" x="0" y="0"/></gates>
<devices><device package="MICROSIM"><connects><connect gate="G$1" pin="VCC" pad="1"/>
<connect gate="G$1" pin="RST" pad="2"/>
<connect gate="G$1" pin="CLK" pad="3"/>
<connect gate="G$1" pin="GND" pad="5"/>
<connect gate="G$1" pin="DET" pad="6"/>
<connect gate="G$1" pin="IO" pad="7"/>
<connect gate="G$1" pin="SH" pad="SH SH_2 SH_3 SH_4 SH_5 SH_6 SH_7 SH_8"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="MPCIE-SOCKET" prefix="X"><gates><gate name="G$1" symbol="MPCIE" x="0" y="0"/></gates>
<devices><device package="MPCIE"><connects><connect gate="G$1" pin="!WAKE" pad="1"/>
<connect gate="G$1" pin="3V3AUX" pad="2"/>
<connect gate="G$1" pin="COEX1" pad="3"/>
<connect gate="G$1" pin="GND" pad="4"/>
<connect gate="G$1" pin="COEX2" pad="5"/>
<connect gate="G$1" pin="1V5" pad="6"/>
<connect gate="G$1" pin="!CLKREQ" pad="7"/>
<connect gate="G$1" pin="UIM_PWR" pad="8"/>
<connect gate="G$1" pin="GND_9" pad="9"/>
<connect gate="G$1" pin="UIM_DATA" pad="10"/>
<connect gate="G$1" pin="REFCLK_N" pad="11"/>
<connect gate="G$1" pin="UIM_CLK" pad="12"/>
<connect gate="G$1" pin="REFCLK_P" pad="13"/>
<connect gate="G$1" pin="UIM_RESET" pad="14"/>
<connect gate="G$1" pin="GND_15" pad="15"/>
<connect gate="G$1" pin="UIM_VPP" pad="16"/>
<connect gate="G$1" pin="RSVD_UIM_C8" pad="17"/>
<connect gate="G$1" pin="GND_18" pad="18"/>
<connect gate="G$1" pin="UIM_IC_DP" pad="19"/>
<connect gate="G$1" pin="!W_DISABLE" pad="20"/>
<connect gate="G$1" pin="GND_21" pad="21"/>
<connect gate="G$1" pin="!PERST" pad="22"/>
<connect gate="G$1" pin="PERn0" pad="23"/>
<connect gate="G$1" pin="3V3AUX_24" pad="24"/>
<connect gate="G$1" pin="PERp0" pad="25"/>
<connect gate="G$1" pin="GND_26" pad="26"/>
<connect gate="G$1" pin="GND_27" pad="27"/>
<connect gate="G$1" pin="1V5_28" pad="28"/>
<connect gate="G$1" pin="GND_29" pad="29"/>
<connect gate="G$1" pin="SMB_CLK" pad="30"/>
<connect gate="G$1" pin="GND_31" pad="31"/>
<connect gate="G$1" pin="SMB_DATA" pad="32"/>
<connect gate="G$1" pin="PETp0" pad="33"/>
<connect gate="G$1" pin="GND_34" pad="34"/>
<connect gate="G$1" pin="GND_35" pad="35"/>
<connect gate="G$1" pin="USB_D_N" pad="36"/>
<connect gate="G$1" pin="GND_37" pad="37"/>
<connect gate="G$1" pin="USB_D_P" pad="38"/>
<connect gate="G$1" pin="3V3AUX_39" pad="39"/>
<connect gate="G$1" pin="GND_40" pad="40"/>
<connect gate="G$1" pin="3V3AUX_41" pad="41"/>
<connect gate="G$1" pin="!LED_WWAN" pad="42"/>
<connect gate="G$1" pin="!LED_WLAN" pad="43"/>
<connect gate="G$1" pin="!LED_WPAN" pad="44"/>
<connect gate="G$1" pin="RSVD_45" pad="45"/>
<connect gate="G$1" pin="RSVD_46" pad="46"/>
<connect gate="G$1" pin="RSVD_47" pad="47"/>
<connect gate="G$1" pin="1V5_48" pad="48"/>
<connect gate="G$1" pin="RSVD_49" pad="49"/>
<connect gate="G$1" pin="GND_50" pad="50"/>
<connect gate="G$1" pin="!W_DISABLE2" pad="51"/>
<connect gate="G$1" pin="3V3AUX_52" pad="52"/></connects>
<technologies><technology/></technologies></device></devices></deviceset></devicesets></library></libraries>
<attributes/>
<variantdefs/>
<classes><class number="0" name="default" width="0.3048" drill="0"/>
<class number="1" name="mains" width="2.5" drill="0"><clearance class="0" value="6.4"/>
<clearance class="1" value="6.4"/>
<clearance class="2" value="6.4"/></class>
<class number="2" name="power" width="1" drill="0"><clearance class="0" value="0.5"/>
<clearance class="2" value="0.6"/></class></classes>
<parts><part name="J1" library="wimax-cpe" deviceset="TERM-3" value="MAINS IN"/>
<part name="F1" library="wimax-cpe" deviceset="FUSE" value="T630mA/250V"/>
<part name="MOV1" library="wimax-cpe" deviceset="MOV" value="S07K275"/>
<part name="PS1" library="wimax-cpe" deviceset="ACDC-12V" value="MPM-20-12"/>
<part name="FB1" library="wimax-cpe" deviceset="FERRITE" value="600R@100MHz"/>
<part name="C1" library="wimax-cpe" deviceset="CPOL-EU" value="470uF/10V"/>
<part name="TP1" library="wimax-cpe" deviceset="TP" value="+5V"/>
<part name="TP2" library="wimax-cpe" deviceset="TP" value="GND"/>
<part name="TP3" library="wimax-cpe" deviceset="TP" value="PE"/>
<part name="U1" library="wimax-cpe" deviceset="BUCK-3V3" value="LM2576S-3.3"/>
<part name="L1" library="wimax-cpe" deviceset="L-RADIAL" value="100uH/3A"/>
<part name="D1" library="wimax-cpe" deviceset="DIODE-SCH" value="SS34"/>
<part name="C2" library="wimax-cpe" deviceset="CPOL-EU" value="470uF/25V"/>
<part name="C3" library="wimax-cpe" deviceset="CPOL-EU" value="220uF/10V"/>
<part name="C4" library="wimax-cpe" deviceset="C-0603" value="100nF"/>
<part name="TP4" library="wimax-cpe" deviceset="TP" value="+3V3"/>
<part name="R1" library="wimax-cpe" deviceset="R-EU" value="1k0"/>
<part name="LED1" library="wimax-cpe" deviceset="LED" value="PWR green"/>
<part name="U2" library="wimax-cpe" deviceset="MPCIE-SOCKET" value="mini-PCIe 52p"/>
<part name="C5" library="wimax-cpe" deviceset="C-0603" value="100nF"/>
<part name="C6" library="wimax-cpe" deviceset="C-0603" value="100nF"/>
<part name="C7" library="wimax-cpe" deviceset="CPOL-SMALL" value="10uF/10V"/>
<part name="R2" library="wimax-cpe" deviceset="R-EU" value="10k"/>
<part name="R3" library="wimax-cpe" deviceset="R-EU" value="10k"/>
<part name="SW4" library="wimax-cpe" deviceset="SW-PUSH" value="RADIO OFF"/>
<part name="R4" library="wimax-cpe" deviceset="R-EU" value="2k2"/>
<part name="R5" library="wimax-cpe" deviceset="R-EU" value="2k2"/>
<part name="R6" library="wimax-cpe" deviceset="R-EU" value="3k3"/>
<part name="LED2" library="wimax-cpe" deviceset="LED" value="WWAN"/>
<part name="R7" library="wimax-cpe" deviceset="R-EU" value="3k3"/>
<part name="LED3" library="wimax-cpe" deviceset="LED" value="WLAN"/>
<part name="J3" library="wimax-cpe" deviceset="USB-MICRO-B" value="USB UP"/>
<part name="J4" library="wimax-cpe" deviceset="MICRO-SIM" value="UIM (DNP)"/>
<part name="U3" library="wimax-cpe" deviceset="LDO-3V3" value="AMS1117-1.5"/>
<part name="C8" library="wimax-cpe" deviceset="CPOL-SMALL" value="10uF/10V"/>
<part name="C9" library="wimax-cpe" deviceset="CPOL-SMALL" value="10uF/10V"/>
<part name="TP5" library="wimax-cpe" deviceset="TP" value="3V3AUX"/>
<part name="TP6" library="wimax-cpe" deviceset="TP" value="1V5"/>
<part name="TP7" library="wimax-cpe" deviceset="TP" value="USB_D+"/>
<part name="TP8" library="wimax-cpe" deviceset="TP" value="USB_D-"/></parts>
<sheets><sheet><plain><text x="20" y="452" size="3.4" layer="97" ratio="8">WiMAX CPE Wallplug — mains-powered Mini Card carrier for an IEEE 802.16e modem, USB 2.0 to the host</text>
<text x="20" y="444" size="2.2" layer="97" ratio="8">MAINS (row A): L → F1 → PS1.2 (MPM-20-12 AC/L), N → PS1.1 (AC/N), MOV1 across L-N after the fuse. PE is not bonded to SELV ground.</text>
<text x="20" y="439" size="2.2" layer="97" ratio="8">12 V → U1 LM2576S-3.3 → 3.3 V. The card may take 1100 mA at 3.3 V (PEAK Systems adapter rating); the EM spec allows 0.50 A per power contact and there are five of them.</text>
<text x="20" y="296" size="2.2" layer="97" ratio="8">CARD (row D): Intel Centrino Advanced-N + WiMAX 6250, half Mini Card, 3.3 V, 802.16e-2005 Wave 2 on 2.3/2.5/3.5 GHz.</text>
<text x="20" y="291" size="2.2" layer="97" ratio="8">Its WiMAX side is USB 2.0 (pins 36/38) and its Wi-Fi side is PCI Express. This carrier has no PCIe root complex, so REFCLK±, PERp0/PERn0, PETp0 and CLKREQ# stay open</text>
<text x="20" y="286" size="2.2" layer="97" ratio="8">and only the WiMAX radio runs. That is a property of the card, not a layout mistake — a PCIe host would be needed for the 802.11 half.</text>
<text x="20" y="281" size="2.2" layer="97" ratio="8">W_DISABLE# / W_DISABLE2# are pulled up and switched by SW4: the EM spec makes the radio-disable signal mandatory for RF cards and asks for a pull-up.</text>
<text x="20" y="176" size="2.2" layer="97" ratio="8">USB (row E): J3 is the upstream port. VBUS is deliberately not connected — the board is mains-powered and tying host VBUS to a rail would back-feed the host.</text>
<text x="20" y="171" size="2.2" layer="97" ratio="8">Antennas: the card has its own Hirose U.FL-R-SMT jacks (U.FL-LP-066 cables). Two SMA bulkhead pigtails are enclosure items; keep the card's antenna end clear of copper.</text>
<text x="20" y="100" size="2.2" layer="97" ratio="8">OPTIONS (row F): J4 micro-SIM on the UIM pins and U3 AMS1117-1.5 for the +1.5 V rail are both DNP — an LTE mini-PCIe card swap-in needs the SIM, the Intel 6250 needs neither.</text>
<frame x1="0" y1="0" x2="480" y2="460" columns="8" rows="6" layer="91" border-left="yes" border-top="yes" border-right="yes" border-bottom="yes"/>
<text x="290" y="8" size="2.2" layer="97">WiMAX CPE Wallplug rev A · sheet 1/1 · generated from tools/wimax-cpe-model.mjs · see docs/wimax-pi-powerline-variants-2026-10-08.md</text></plain>
<instances><instance part="J1" gate="G$1" x="40" y="430" smashed="yes" rot="R0"><attribute name="NAME" x="32.38" y="441.16" size="1.778" layer="95"/>
<attribute name="VALUE" x="32.38" y="415.97" size="1.778" layer="96"/></instance>
<instance part="F1" gate="G$1" x="110" y="430" smashed="yes" rot="R0"><attribute name="NAME" x="104.92" y="433.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="104.92" y="423.59" size="1.778" layer="96"/></instance>
<instance part="MOV1" gate="G$1" x="180" y="430" smashed="yes" rot="R0"><attribute name="NAME" x="174.92" y="433.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="174.92" y="423.59" size="1.778" layer="96"/></instance>
<instance part="PS1" gate="G$1" x="260" y="430" smashed="yes" rot="R0"><attribute name="NAME" x="247.3" y="436.08" size="1.778" layer="95"/>
<attribute name="VALUE" x="247.3" y="421.05" size="1.778" layer="96"/></instance>
<instance part="FB1" gate="G$1" x="40" y="380" smashed="yes" rot="R0"><attribute name="NAME" x="34.92" y="383.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="34.92" y="373.59" size="1.778" layer="96"/></instance>
<instance part="C1" gate="G$1" x="100" y="380" smashed="yes" rot="R0"><attribute name="NAME" x="94.92" y="383.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="94.92" y="373.59" size="1.778" layer="96"/></instance>
<instance part="TP1" gate="G$1" x="160" y="380" smashed="yes" rot="R0"><attribute name="NAME" x="158.73" y="383.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="158.73" y="373.59" size="1.778" layer="96"/></instance>
<instance part="TP2" gate="G$1" x="210" y="380" smashed="yes" rot="R0"><attribute name="NAME" x="208.73" y="383.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="208.73" y="373.59" size="1.778" layer="96"/></instance>
<instance part="TP3" gate="G$1" x="350" y="430" smashed="yes" rot="R0"><attribute name="NAME" x="348.73" y="433.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="348.73" y="423.59" size="1.778" layer="96"/></instance>
<instance part="U1" gate="G$1" x="50" y="330" smashed="yes" rot="R0"><attribute name="NAME" x="39.84" y="336.08" size="1.778" layer="95"/>
<attribute name="VALUE" x="39.84" y="321.05" size="1.778" layer="96"/></instance>
<instance part="L1" gate="G$1" x="130" y="330" smashed="yes" rot="R0"><attribute name="NAME" x="119.84" y="334.81" size="1.778" layer="95"/>
<attribute name="VALUE" x="119.84" y="322.32" size="1.778" layer="96"/></instance>
<instance part="D1" gate="G$1" x="200" y="330" smashed="yes" rot="R0"><attribute name="NAME" x="192.38" y="334.81" size="1.778" layer="95"/>
<attribute name="VALUE" x="192.38" y="322.32" size="1.778" layer="96"/></instance>
<instance part="C2" gate="G$1" x="265" y="330" smashed="yes" rot="R0"><attribute name="NAME" x="259.92" y="333.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="259.92" y="323.59" size="1.778" layer="96"/></instance>
<instance part="C3" gate="G$1" x="325" y="330" smashed="yes" rot="R0"><attribute name="NAME" x="319.92" y="333.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="319.92" y="323.59" size="1.778" layer="96"/></instance>
<instance part="C4" gate="G$1" x="385" y="330" smashed="yes" rot="R0"><attribute name="NAME" x="379.92" y="333.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="379.92" y="323.59" size="1.778" layer="96"/></instance>
<instance part="TP4" gate="G$1" x="435" y="330" smashed="yes" rot="R0"><attribute name="NAME" x="433.73" y="333.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="433.73" y="323.59" size="1.778" layer="96"/></instance>
<instance part="R1" gate="G$1" x="100" y="25" smashed="yes" rot="R0"><attribute name="NAME" x="94.92" y="28.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="94.92" y="18.59" size="1.778" layer="96"/></instance>
<instance part="LED1" gate="G$1" x="155" y="25" smashed="yes" rot="R0"><attribute name="NAME" x="149.92" y="29.07" size="1.778" layer="95"/>
<attribute name="VALUE" x="149.92" y="18.59" size="1.778" layer="96"/></instance>
<instance part="U2" gate="G$1" x="70" y="250" smashed="yes" rot="R0"><attribute name="NAME" x="53.49" y="286.56" size="1.778" layer="95"/>
<attribute name="VALUE" x="53.49" y="210.57" size="1.778" layer="96"/></instance>
<instance part="C5" gate="G$1" x="225" y="140" smashed="yes" rot="R0"><attribute name="NAME" x="219.92" y="143.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="219.92" y="133.59" size="1.778" layer="96"/></instance>
<instance part="C6" gate="G$1" x="280" y="140" smashed="yes" rot="R0"><attribute name="NAME" x="274.92" y="143.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="274.92" y="133.59" size="1.778" layer="96"/></instance>
<instance part="C7" gate="G$1" x="335" y="140" smashed="yes" rot="R0"><attribute name="NAME" x="329.92" y="143.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="329.92" y="133.59" size="1.778" layer="96"/></instance>
<instance part="R2" gate="G$1" x="140" y="250" smashed="yes" rot="R0"><attribute name="NAME" x="134.92" y="253.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="134.92" y="243.59" size="1.778" layer="96"/></instance>
<instance part="R3" gate="G$1" x="195" y="250" smashed="yes" rot="R0"><attribute name="NAME" x="189.92" y="253.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="189.92" y="243.59" size="1.778" layer="96"/></instance>
<instance part="SW4" gate="G$1" x="250" y="250" smashed="yes" rot="R0"><attribute name="NAME" x="244.92" y="254.81" size="1.778" layer="95"/>
<attribute name="VALUE" x="244.92" y="242.32" size="1.778" layer="96"/></instance>
<instance part="R4" gate="G$1" x="305" y="250" smashed="yes" rot="R0"><attribute name="NAME" x="299.92" y="253.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="299.92" y="243.59" size="1.778" layer="96"/></instance>
<instance part="R5" gate="G$1" x="360" y="250" smashed="yes" rot="R0"><attribute name="NAME" x="354.92" y="253.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="354.92" y="243.59" size="1.778" layer="96"/></instance>
<instance part="R6" gate="G$1" x="415" y="250" smashed="yes" rot="R0"><attribute name="NAME" x="409.92" y="253.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="409.92" y="243.59" size="1.778" layer="96"/></instance>
<instance part="LED2" gate="G$1" x="60" y="140" smashed="yes" rot="R0"><attribute name="NAME" x="54.92" y="144.07" size="1.778" layer="95"/>
<attribute name="VALUE" x="54.92" y="133.59" size="1.778" layer="96"/></instance>
<instance part="R7" gate="G$1" x="170" y="140" smashed="yes" rot="R0"><attribute name="NAME" x="164.92" y="143.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="164.92" y="133.59" size="1.778" layer="96"/></instance>
<instance part="LED3" gate="G$1" x="115" y="140" smashed="yes" rot="R0"><attribute name="NAME" x="109.92" y="144.07" size="1.778" layer="95"/>
<attribute name="VALUE" x="109.92" y="133.59" size="1.778" layer="96"/></instance>
<instance part="J3" gate="G$1" x="400" y="140" smashed="yes" rot="R0"><attribute name="NAME" x="389.84" y="147.35" size="1.778" layer="95"/>
<attribute name="VALUE" x="389.84" y="129.78" size="1.778" layer="96"/></instance>
<instance part="J4" gate="G$1" x="60" y="70" smashed="yes" rot="R0"><attribute name="NAME" x="48.57" y="77.35" size="1.778" layer="95"/>
<attribute name="VALUE" x="48.57" y="59.78" size="1.778" layer="96"/></instance>
<instance part="U3" gate="G$1" x="150" y="70" smashed="yes" rot="R0"><attribute name="NAME" x="142.38" y="76.08" size="1.778" layer="95"/>
<attribute name="VALUE" x="142.38" y="61.05" size="1.778" layer="96"/></instance>
<instance part="C8" gate="G$1" x="215" y="70" smashed="yes" rot="R0"><attribute name="NAME" x="209.92" y="73.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="209.92" y="63.59" size="1.778" layer="96"/></instance>
<instance part="C9" gate="G$1" x="270" y="70" smashed="yes" rot="R0"><attribute name="NAME" x="264.92" y="73.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="264.92" y="63.59" size="1.778" layer="96"/></instance>
<instance part="TP5" gate="G$1" x="325" y="70" smashed="yes" rot="R0"><attribute name="NAME" x="323.73" y="73.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="323.73" y="63.59" size="1.778" layer="96"/></instance>
<instance part="TP6" gate="G$1" x="375" y="70" smashed="yes" rot="R0"><attribute name="NAME" x="373.73" y="73.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="373.73" y="63.59" size="1.778" layer="96"/></instance>
<instance part="TP7" gate="G$1" x="425" y="70" smashed="yes" rot="R0"><attribute name="NAME" x="423.73" y="73.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="423.73" y="63.59" size="1.778" layer="96"/></instance>
<instance part="TP8" gate="G$1" x="40" y="25" smashed="yes" rot="R0"><attribute name="NAME" x="38.73" y="28.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="38.73" y="18.59" size="1.778" layer="96"/></instance></instances>
<busses/>
<nets><net name="AC_L" class="1"><segment><pinref part="J1" gate="G$1" pin="1"/>
<wire x1="32.38" y1="435.08" x2="27.3" y2="435.08" width="0.1524" layer="91"/>
<label x="27.3" y="435.08" size="1.778" layer="95" rot="R0"/>
<pinref part="F1" gate="G$1" pin="1"/>
<wire x1="104.92" y1="430" x2="99.84" y2="430" width="0.1524" layer="91"/>
<label x="99.84" y="430" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="AC_L_F" class="1"><segment><pinref part="F1" gate="G$1" pin="2"/>
<wire x1="115.08" y1="430" x2="120.16" y2="430" width="0.1524" layer="91"/>
<label x="120.16" y="430" size="1.778" layer="95" rot="R0"/>
<pinref part="PS1" gate="G$1" pin="AC-L"/>
<wire x1="247.3" y1="431.27" x2="242.22" y2="431.27" width="0.1524" layer="91"/>
<label x="242.22" y="431.27" size="1.778" layer="95" rot="R0"/>
<pinref part="MOV1" gate="G$1" pin="1"/>
<wire x1="174.92" y1="430" x2="169.84" y2="430" width="0.1524" layer="91"/>
<label x="169.84" y="430" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="AC_N" class="1"><segment><pinref part="J1" gate="G$1" pin="2"/>
<wire x1="32.38" y1="430" x2="27.3" y2="430" width="0.1524" layer="91"/>
<label x="27.3" y="430" size="1.778" layer="95" rot="R0"/>
<pinref part="PS1" gate="G$1" pin="AC-N"/>
<wire x1="247.3" y1="428.73" x2="242.22" y2="428.73" width="0.1524" layer="91"/>
<label x="242.22" y="428.73" size="1.778" layer="95" rot="R0"/>
<pinref part="MOV1" gate="G$1" pin="2"/>
<wire x1="185.08" y1="430" x2="190.16" y2="430" width="0.1524" layer="91"/>
<label x="190.16" y="430" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="PE" class="1"><segment><pinref part="J1" gate="G$1" pin="3"/>
<wire x1="32.38" y1="424.92" x2="27.3" y2="424.92" width="0.1524" layer="91"/>
<label x="27.3" y="424.92" size="1.778" layer="95" rot="R0"/>
<pinref part="TP3" gate="G$1" pin="1"/>
<wire x1="350" y1="426.19" x2="350" y2="421.11" width="0.1524" layer="91"/>
<label x="350" y="421.11" size="1.778" layer="95" rot="R270"/></segment></net>
<net name="12V_P" class="2"><segment><pinref part="PS1" gate="G$1" pin="+VO"/>
<wire x1="272.7" y1="431.27" x2="277.78" y2="431.27" width="0.1524" layer="91"/>
<label x="277.78" y="431.27" size="1.778" layer="95" rot="R0"/>
<pinref part="FB1" gate="G$1" pin="1"/>
<wire x1="34.92" y1="380" x2="29.84" y2="380" width="0.1524" layer="91"/>
<label x="29.84" y="380" size="1.778" layer="95" rot="R0"/>
<pinref part="C1" gate="G$1" pin="+"/>
<wire x1="94.92" y1="380" x2="89.84" y2="380" width="0.1524" layer="91"/>
<label x="89.84" y="380" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="GND" class="2"><segment><pinref part="PS1" gate="G$1" pin="-VO"/>
<wire x1="272.7" y1="428.73" x2="277.78" y2="428.73" width="0.1524" layer="91"/>
<label x="277.78" y="428.73" size="1.778" layer="95" rot="R0"/>
<pinref part="C1" gate="G$1" pin="-"/>
<wire x1="105.08" y1="380" x2="110.16" y2="380" width="0.1524" layer="91"/>
<label x="110.16" y="380" size="1.778" layer="95" rot="R0"/>
<pinref part="TP2" gate="G$1" pin="1"/>
<wire x1="210" y1="376.19" x2="210" y2="371.11" width="0.1524" layer="91"/>
<label x="210" y="371.11" size="1.778" layer="95" rot="R270"/>
<pinref part="U1" gate="G$1" pin="GND"/>
<wire x1="50" y1="326.19" x2="50" y2="321.11" width="0.1524" layer="91"/>
<label x="50" y="321.11" size="1.778" layer="95" rot="R270"/>
<pinref part="U1" gate="G$1" pin="ONOFF"/>
<wire x1="60.16" y1="328.73" x2="65.24" y2="328.73" width="0.1524" layer="91"/>
<label x="65.24" y="328.73" size="1.778" layer="95" rot="R0"/>
<pinref part="C2" gate="G$1" pin="-"/>
<wire x1="270.08" y1="330" x2="275.16" y2="330" width="0.1524" layer="91"/>
<label x="275.16" y="330" size="1.778" layer="95" rot="R0"/>
<pinref part="C3" gate="G$1" pin="-"/>
<wire x1="330.08" y1="330" x2="335.16" y2="330" width="0.1524" layer="91"/>
<label x="335.16" y="330" size="1.778" layer="95" rot="R0"/>
<pinref part="C4" gate="G$1" pin="2"/>
<wire x1="390.08" y1="330" x2="395.16" y2="330" width="0.1524" layer="91"/>
<label x="395.16" y="330" size="1.778" layer="95" rot="R0"/>
<pinref part="D1" gate="G$1" pin="A"/>
<wire x1="192.38" y1="330" x2="187.3" y2="330" width="0.1524" layer="91"/>
<label x="187.3" y="330" size="1.778" layer="95" rot="R0"/>
<pinref part="LED1" gate="G$1" pin="K"/>
<wire x1="160.08" y1="25" x2="165.16" y2="25" width="0.1524" layer="91"/>
<label x="165.16" y="25" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="GND"/>
<wire x1="53.49" y1="274.13" x2="48.41" y2="274.13" width="0.1524" layer="91"/>
<label x="48.41" y="274.13" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="GND_9"/>
<wire x1="53.49" y1="261.43" x2="48.41" y2="261.43" width="0.1524" layer="91"/>
<label x="48.41" y="261.43" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="GND_15"/>
<wire x1="53.49" y1="246.19" x2="48.41" y2="246.19" width="0.1524" layer="91"/>
<label x="48.41" y="246.19" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="GND_18"/>
<wire x1="53.49" y1="238.57" x2="48.41" y2="238.57" width="0.1524" layer="91"/>
<label x="48.41" y="238.57" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="GND_21"/>
<wire x1="53.49" y1="230.95" x2="48.41" y2="230.95" width="0.1524" layer="91"/>
<label x="48.41" y="230.95" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="GND_26"/>
<wire x1="53.49" y1="218.25" x2="48.41" y2="218.25" width="0.1524" layer="91"/>
<label x="48.41" y="218.25" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="GND_27"/>
<wire x1="86.51" y1="281.75" x2="91.59" y2="281.75" width="0.1524" layer="91"/>
<label x="91.59" y="281.75" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="GND_29"/>
<wire x1="86.51" y1="276.67" x2="91.59" y2="276.67" width="0.1524" layer="91"/>
<label x="91.59" y="276.67" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="GND_31"/>
<wire x1="86.51" y1="271.59" x2="91.59" y2="271.59" width="0.1524" layer="91"/>
<label x="91.59" y="271.59" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="GND_34"/>
<wire x1="86.51" y1="263.97" x2="91.59" y2="263.97" width="0.1524" layer="91"/>
<label x="91.59" y="263.97" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="GND_35"/>
<wire x1="86.51" y1="261.43" x2="91.59" y2="261.43" width="0.1524" layer="91"/>
<label x="91.59" y="261.43" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="GND_37"/>
<wire x1="86.51" y1="256.35" x2="91.59" y2="256.35" width="0.1524" layer="91"/>
<label x="91.59" y="256.35" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="GND_40"/>
<wire x1="86.51" y1="248.73" x2="91.59" y2="248.73" width="0.1524" layer="91"/>
<label x="91.59" y="248.73" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="GND_50"/>
<wire x1="86.51" y1="223.33" x2="91.59" y2="223.33" width="0.1524" layer="91"/>
<label x="91.59" y="223.33" size="1.778" layer="95" rot="R0"/>
<pinref part="C5" gate="G$1" pin="2"/>
<wire x1="230.08" y1="140" x2="235.16" y2="140" width="0.1524" layer="91"/>
<label x="235.16" y="140" size="1.778" layer="95" rot="R0"/>
<pinref part="C6" gate="G$1" pin="2"/>
<wire x1="285.08" y1="140" x2="290.16" y2="140" width="0.1524" layer="91"/>
<label x="290.16" y="140" size="1.778" layer="95" rot="R0"/>
<pinref part="C7" gate="G$1" pin="-"/>
<wire x1="340.08" y1="140" x2="345.16" y2="140" width="0.1524" layer="91"/>
<label x="345.16" y="140" size="1.778" layer="95" rot="R0"/>
<pinref part="SW4" gate="G$1" pin="2"/>
<wire x1="255.08" y1="250" x2="260.16" y2="250" width="0.1524" layer="91"/>
<label x="260.16" y="250" size="1.778" layer="95" rot="R0"/>
<pinref part="LED2" gate="G$1" pin="K"/>
<wire x1="65.08" y1="140" x2="70.16" y2="140" width="0.1524" layer="91"/>
<label x="70.16" y="140" size="1.778" layer="95" rot="R0"/>
<pinref part="LED3" gate="G$1" pin="K"/>
<wire x1="120.08" y1="140" x2="125.16" y2="140" width="0.1524" layer="91"/>
<label x="125.16" y="140" size="1.778" layer="95" rot="R0"/>
<pinref part="J3" gate="G$1" pin="GND"/>
<wire x1="410.16" y1="140" x2="415.24" y2="140" width="0.1524" layer="91"/>
<label x="415.24" y="140" size="1.778" layer="95" rot="R0"/>
<pinref part="J3" gate="G$1" pin="SH"/>
<wire x1="400" y1="134.92" x2="400" y2="129.84" width="0.1524" layer="91"/>
<label x="400" y="129.84" size="1.778" layer="95" rot="R270"/>
<pinref part="J4" gate="G$1" pin="GND"/>
<wire x1="71.43" y1="70" x2="76.51" y2="70" width="0.1524" layer="91"/>
<label x="76.51" y="70" size="1.778" layer="95" rot="R0"/>
<pinref part="J4" gate="G$1" pin="SH"/>
<wire x1="60" y1="64.92" x2="60" y2="59.84" width="0.1524" layer="91"/>
<label x="60" y="59.84" size="1.778" layer="95" rot="R270"/>
<pinref part="U3" gate="G$1" pin="GND"/>
<wire x1="150" y1="66.19" x2="150" y2="61.11" width="0.1524" layer="91"/>
<label x="150" y="61.11" size="1.778" layer="95" rot="R270"/>
<pinref part="C8" gate="G$1" pin="-"/>
<wire x1="220.08" y1="70" x2="225.16" y2="70" width="0.1524" layer="91"/>
<label x="225.16" y="70" size="1.778" layer="95" rot="R0"/>
<pinref part="C9" gate="G$1" pin="-"/>
<wire x1="275.08" y1="70" x2="280.16" y2="70" width="0.1524" layer="91"/>
<label x="280.16" y="70" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="12V" class="2"><segment><pinref part="FB1" gate="G$1" pin="2"/>
<wire x1="45.08" y1="380" x2="50.16" y2="380" width="0.1524" layer="91"/>
<label x="50.16" y="380" size="1.778" layer="95" rot="R0"/>
<pinref part="TP1" gate="G$1" pin="1"/>
<wire x1="160" y1="376.19" x2="160" y2="371.11" width="0.1524" layer="91"/>
<label x="160" y="371.11" size="1.778" layer="95" rot="R270"/>
<pinref part="U1" gate="G$1" pin="VIN"/>
<wire x1="39.84" y1="331.27" x2="34.76" y2="331.27" width="0.1524" layer="91"/>
<label x="34.76" y="331.27" size="1.778" layer="95" rot="R0"/>
<pinref part="C2" gate="G$1" pin="+"/>
<wire x1="259.92" y1="330" x2="254.84" y2="330" width="0.1524" layer="91"/>
<label x="254.84" y="330" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="SW_3V3" class="2"><segment><pinref part="U1" gate="G$1" pin="VOUT"/>
<wire x1="60.16" y1="331.27" x2="65.24" y2="331.27" width="0.1524" layer="91"/>
<label x="65.24" y="331.27" size="1.778" layer="95" rot="R0"/>
<pinref part="L1" gate="G$1" pin="1"/>
<wire x1="119.84" y1="330" x2="114.76" y2="330" width="0.1524" layer="91"/>
<label x="114.76" y="330" size="1.778" layer="95" rot="R0"/>
<pinref part="D1" gate="G$1" pin="K"/>
<wire x1="207.62" y1="330" x2="212.7" y2="330" width="0.1524" layer="91"/>
<label x="212.7" y="330" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="3V3" class="2"><segment><pinref part="L1" gate="G$1" pin="2"/>
<wire x1="140.16" y1="330" x2="145.24" y2="330" width="0.1524" layer="91"/>
<label x="145.24" y="330" size="1.778" layer="95" rot="R0"/>
<pinref part="C3" gate="G$1" pin="+"/>
<wire x1="319.92" y1="330" x2="314.84" y2="330" width="0.1524" layer="91"/>
<label x="314.84" y="330" size="1.778" layer="95" rot="R0"/>
<pinref part="C4" gate="G$1" pin="1"/>
<wire x1="379.92" y1="330" x2="374.84" y2="330" width="0.1524" layer="91"/>
<label x="374.84" y="330" size="1.778" layer="95" rot="R0"/>
<pinref part="TP4" gate="G$1" pin="1"/>
<wire x1="435" y1="326.19" x2="435" y2="321.11" width="0.1524" layer="91"/>
<label x="435" y="321.11" size="1.778" layer="95" rot="R270"/>
<pinref part="U2" gate="G$1" pin="3V3AUX"/>
<wire x1="53.49" y1="279.21" x2="48.41" y2="279.21" width="0.1524" layer="91"/>
<label x="48.41" y="279.21" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="3V3AUX_24"/>
<wire x1="53.49" y1="223.33" x2="48.41" y2="223.33" width="0.1524" layer="91"/>
<label x="48.41" y="223.33" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="3V3AUX_39"/>
<wire x1="86.51" y1="251.27" x2="91.59" y2="251.27" width="0.1524" layer="91"/>
<label x="91.59" y="251.27" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="3V3AUX_41"/>
<wire x1="86.51" y1="246.19" x2="91.59" y2="246.19" width="0.1524" layer="91"/>
<label x="91.59" y="246.19" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="3V3AUX_52"/>
<wire x1="86.51" y1="218.25" x2="91.59" y2="218.25" width="0.1524" layer="91"/>
<label x="91.59" y="218.25" size="1.778" layer="95" rot="R0"/>
<pinref part="C5" gate="G$1" pin="1"/>
<wire x1="219.92" y1="140" x2="214.84" y2="140" width="0.1524" layer="91"/>
<label x="214.84" y="140" size="1.778" layer="95" rot="R0"/>
<pinref part="C6" gate="G$1" pin="1"/>
<wire x1="274.92" y1="140" x2="269.84" y2="140" width="0.1524" layer="91"/>
<label x="269.84" y="140" size="1.778" layer="95" rot="R0"/>
<pinref part="C7" gate="G$1" pin="+"/>
<wire x1="329.92" y1="140" x2="324.84" y2="140" width="0.1524" layer="91"/>
<label x="324.84" y="140" size="1.778" layer="95" rot="R0"/>
<pinref part="R1" gate="G$1" pin="1"/>
<wire x1="94.92" y1="25" x2="89.84" y2="25" width="0.1524" layer="91"/>
<label x="89.84" y="25" size="1.778" layer="95" rot="R0"/>
<pinref part="R2" gate="G$1" pin="1"/>
<wire x1="134.92" y1="250" x2="129.84" y2="250" width="0.1524" layer="91"/>
<label x="129.84" y="250" size="1.778" layer="95" rot="R0"/>
<pinref part="R3" gate="G$1" pin="1"/>
<wire x1="189.92" y1="250" x2="184.84" y2="250" width="0.1524" layer="91"/>
<label x="184.84" y="250" size="1.778" layer="95" rot="R0"/>
<pinref part="R4" gate="G$1" pin="1"/>
<wire x1="299.92" y1="250" x2="294.84" y2="250" width="0.1524" layer="91"/>
<label x="294.84" y="250" size="1.778" layer="95" rot="R0"/>
<pinref part="R5" gate="G$1" pin="1"/>
<wire x1="354.92" y1="250" x2="349.84" y2="250" width="0.1524" layer="91"/>
<label x="349.84" y="250" size="1.778" layer="95" rot="R0"/>
<pinref part="TP5" gate="G$1" pin="1"/>
<wire x1="325" y1="66.19" x2="325" y2="61.11" width="0.1524" layer="91"/>
<label x="325" y="61.11" size="1.778" layer="95" rot="R270"/>
<pinref part="U3" gate="G$1" pin="VI"/>
<wire x1="142.38" y1="70" x2="137.3" y2="70" width="0.1524" layer="91"/>
<label x="137.3" y="70" size="1.778" layer="95" rot="R0"/>
<pinref part="C8" gate="G$1" pin="+"/>
<wire x1="209.92" y1="70" x2="204.84" y2="70" width="0.1524" layer="91"/>
<label x="204.84" y="70" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="LED_A" class="0"><segment><pinref part="R1" gate="G$1" pin="2"/>
<wire x1="105.08" y1="25" x2="110.16" y2="25" width="0.1524" layer="91"/>
<label x="110.16" y="25" size="1.778" layer="95" rot="R0"/>
<pinref part="LED1" gate="G$1" pin="A"/>
<wire x1="149.92" y1="25" x2="144.84" y2="25" width="0.1524" layer="91"/>
<label x="144.84" y="25" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="1V5" class="2"><segment><pinref part="U2" gate="G$1" pin="1V5"/>
<wire x1="53.49" y1="269.05" x2="48.41" y2="269.05" width="0.1524" layer="91"/>
<label x="48.41" y="269.05" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="1V5_28"/>
<wire x1="86.51" y1="279.21" x2="91.59" y2="279.21" width="0.1524" layer="91"/>
<label x="91.59" y="279.21" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="1V5_48"/>
<wire x1="86.51" y1="228.41" x2="91.59" y2="228.41" width="0.1524" layer="91"/>
<label x="91.59" y="228.41" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="VO"/>
<wire x1="157.62" y1="70" x2="162.7" y2="70" width="0.1524" layer="91"/>
<label x="162.7" y="70" size="1.778" layer="95" rot="R0"/>
<pinref part="C9" gate="G$1" pin="+"/>
<wire x1="264.92" y1="70" x2="259.84" y2="70" width="0.1524" layer="91"/>
<label x="259.84" y="70" size="1.778" layer="95" rot="R0"/>
<pinref part="TP6" gate="G$1" pin="1"/>
<wire x1="375" y1="66.19" x2="375" y2="61.11" width="0.1524" layer="91"/>
<label x="375" y="61.11" size="1.778" layer="95" rot="R270"/></segment></net>
<net name="USB_DP" class="0"><segment><pinref part="U2" gate="G$1" pin="USB_D_P"/>
<wire x1="86.51" y1="253.81" x2="91.59" y2="253.81" width="0.1524" layer="91"/>
<label x="91.59" y="253.81" size="1.778" layer="95" rot="R0"/>
<pinref part="J3" gate="G$1" pin="DP"/>
<wire x1="389.84" y1="137.46" x2="384.76" y2="137.46" width="0.1524" layer="91"/>
<label x="384.76" y="137.46" size="1.778" layer="95" rot="R0"/>
<pinref part="TP7" gate="G$1" pin="1"/>
<wire x1="425" y1="66.19" x2="425" y2="61.11" width="0.1524" layer="91"/>
<label x="425" y="61.11" size="1.778" layer="95" rot="R270"/></segment></net>
<net name="USB_DM" class="0"><segment><pinref part="U2" gate="G$1" pin="USB_D_N"/>
<wire x1="86.51" y1="258.89" x2="91.59" y2="258.89" width="0.1524" layer="91"/>
<label x="91.59" y="258.89" size="1.778" layer="95" rot="R0"/>
<pinref part="J3" gate="G$1" pin="DM"/>
<wire x1="389.84" y1="140" x2="384.76" y2="140" width="0.1524" layer="91"/>
<label x="384.76" y="140" size="1.778" layer="95" rot="R0"/>
<pinref part="TP8" gate="G$1" pin="1"/>
<wire x1="40" y1="21.19" x2="40" y2="16.11" width="0.1524" layer="91"/>
<label x="40" y="16.11" size="1.778" layer="95" rot="R270"/></segment></net>
<net name="MPCIE_PERST" class="0"><segment><pinref part="U2" gate="G$1" pin="!PERST"/>
<wire x1="53.49" y1="228.41" x2="48.41" y2="228.41" width="0.1524" layer="91"/>
<label x="48.41" y="228.41" size="1.778" layer="95" rot="R0"/>
<pinref part="R2" gate="G$1" pin="2"/>
<wire x1="145.08" y1="250" x2="150.16" y2="250" width="0.1524" layer="91"/>
<label x="150.16" y="250" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="MPCIE_WDISABLE" class="0"><segment><pinref part="U2" gate="G$1" pin="!W_DISABLE"/>
<wire x1="53.49" y1="233.49" x2="48.41" y2="233.49" width="0.1524" layer="91"/>
<label x="48.41" y="233.49" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="!W_DISABLE2"/>
<wire x1="86.51" y1="220.79" x2="91.59" y2="220.79" width="0.1524" layer="91"/>
<label x="91.59" y="220.79" size="1.778" layer="95" rot="R0"/>
<pinref part="R3" gate="G$1" pin="2"/>
<wire x1="200.08" y1="250" x2="205.16" y2="250" width="0.1524" layer="91"/>
<label x="205.16" y="250" size="1.778" layer="95" rot="R0"/>
<pinref part="SW4" gate="G$1" pin="1"/>
<wire x1="244.92" y1="250" x2="239.84" y2="250" width="0.1524" layer="91"/>
<label x="239.84" y="250" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="SMB_CLK" class="0"><segment><pinref part="U2" gate="G$1" pin="SMB_CLK"/>
<wire x1="86.51" y1="274.13" x2="91.59" y2="274.13" width="0.1524" layer="91"/>
<label x="91.59" y="274.13" size="1.778" layer="95" rot="R0"/>
<pinref part="R4" gate="G$1" pin="2"/>
<wire x1="310.08" y1="250" x2="315.16" y2="250" width="0.1524" layer="91"/>
<label x="315.16" y="250" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="SMB_DATA" class="0"><segment><pinref part="U2" gate="G$1" pin="SMB_DATA"/>
<wire x1="86.51" y1="269.05" x2="91.59" y2="269.05" width="0.1524" layer="91"/>
<label x="91.59" y="269.05" size="1.778" layer="95" rot="R0"/>
<pinref part="R5" gate="G$1" pin="2"/>
<wire x1="365.08" y1="250" x2="370.16" y2="250" width="0.1524" layer="91"/>
<label x="370.16" y="250" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="LED_WWAN" class="0"><segment><pinref part="U2" gate="G$1" pin="!LED_WWAN"/>
<wire x1="86.51" y1="243.65" x2="91.59" y2="243.65" width="0.1524" layer="91"/>
<label x="91.59" y="243.65" size="1.778" layer="95" rot="R0"/>
<pinref part="R6" gate="G$1" pin="1"/>
<wire x1="409.92" y1="250" x2="404.84" y2="250" width="0.1524" layer="91"/>
<label x="404.84" y="250" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="LED2_A" class="0"><segment><pinref part="R6" gate="G$1" pin="2"/>
<wire x1="420.08" y1="250" x2="425.16" y2="250" width="0.1524" layer="91"/>
<label x="425.16" y="250" size="1.778" layer="95" rot="R0"/>
<pinref part="LED2" gate="G$1" pin="A"/>
<wire x1="54.92" y1="140" x2="49.84" y2="140" width="0.1524" layer="91"/>
<label x="49.84" y="140" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="LED_WLAN" class="0"><segment><pinref part="U2" gate="G$1" pin="!LED_WLAN"/>
<wire x1="86.51" y1="241.11" x2="91.59" y2="241.11" width="0.1524" layer="91"/>
<label x="91.59" y="241.11" size="1.778" layer="95" rot="R0"/>
<pinref part="R7" gate="G$1" pin="1"/>
<wire x1="164.92" y1="140" x2="159.84" y2="140" width="0.1524" layer="91"/>
<label x="159.84" y="140" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="LED3_A" class="0"><segment><pinref part="R7" gate="G$1" pin="2"/>
<wire x1="175.08" y1="140" x2="180.16" y2="140" width="0.1524" layer="91"/>
<label x="180.16" y="140" size="1.778" layer="95" rot="R0"/>
<pinref part="LED3" gate="G$1" pin="A"/>
<wire x1="109.92" y1="140" x2="104.84" y2="140" width="0.1524" layer="91"/>
<label x="104.84" y="140" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="UIM_PWR" class="0"><segment><pinref part="U2" gate="G$1" pin="UIM_PWR"/>
<wire x1="53.49" y1="263.97" x2="48.41" y2="263.97" width="0.1524" layer="91"/>
<label x="48.41" y="263.97" size="1.778" layer="95" rot="R0"/>
<pinref part="J4" gate="G$1" pin="VCC"/>
<wire x1="48.57" y1="72.54" x2="43.49" y2="72.54" width="0.1524" layer="91"/>
<label x="43.49" y="72.54" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="UIM_DATA" class="0"><segment><pinref part="U2" gate="G$1" pin="UIM_DATA"/>
<wire x1="53.49" y1="258.89" x2="48.41" y2="258.89" width="0.1524" layer="91"/>
<label x="48.41" y="258.89" size="1.778" layer="95" rot="R0"/>
<pinref part="J4" gate="G$1" pin="IO"/>
<wire x1="71.43" y1="72.54" x2="76.51" y2="72.54" width="0.1524" layer="91"/>
<label x="76.51" y="72.54" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="UIM_CLK" class="0"><segment><pinref part="U2" gate="G$1" pin="UIM_CLK"/>
<wire x1="53.49" y1="253.81" x2="48.41" y2="253.81" width="0.1524" layer="91"/>
<label x="48.41" y="253.81" size="1.778" layer="95" rot="R0"/>
<pinref part="J4" gate="G$1" pin="CLK"/>
<wire x1="48.57" y1="67.46" x2="43.49" y2="67.46" width="0.1524" layer="91"/>
<label x="43.49" y="67.46" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="UIM_RESET" class="0"><segment><pinref part="U2" gate="G$1" pin="UIM_RESET"/>
<wire x1="53.49" y1="248.73" x2="48.41" y2="248.73" width="0.1524" layer="91"/>
<label x="48.41" y="248.73" size="1.778" layer="95" rot="R0"/>
<pinref part="J4" gate="G$1" pin="RST"/>
<wire x1="48.57" y1="70" x2="43.49" y2="70" width="0.1524" layer="91"/>
<label x="43.49" y="70" size="1.778" layer="95" rot="R0"/></segment></net></nets></sheet></sheets></schematic>
</drawing>
</eagle>
