<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE eagle SYSTEM "eagle.dtd">
<!-- generated by tools/build-wallplug-eagle.mjs from tools/plc-bridge-model.mjs — do not edit by hand -->
<eagle version="9.6.2">
<drawing>
<settings><setting alwaysvectorfont="no"/>
<setting verticaltext="up"/></settings>

<grid distance="2.54" unitdist="mm" unit="mm" style="lines" multiple="1" display="yes" altdistance="0.635" altunitdist="mm" altunit="mm"/>
<layers><layer number="90" name="Modules" color="5" fill="1" visible="yes" active="yes"/>
<layer number="91" name="Nets" color="2" fill="1" visible="yes" active="yes"/>
<layer number="92" name="Busses" color="1" fill="1" visible="yes" active="yes"/>
<layer number="93" name="Pins" color="2" fill="1" visible="yes" active="yes"/>
<layer number="94" name="Symbols" color="4" fill="1" visible="yes" active="yes"/>
<layer number="95" name="Names" color="7" fill="1" visible="yes" active="yes"/>
<layer number="96" name="Values" color="7" fill="1" visible="yes" active="yes"/>
<layer number="97" name="Info" color="7" fill="1" visible="yes" active="yes"/>
<layer number="98" name="Guide" color="6" fill="1" visible="yes" active="yes"/></layers>
<schematic xreflabel="%F%N/%S.%C%R" xrefpart="/%S.%C%R"><description>Powerline Bridge: mains-powered HomePlug Green PHY (QCA7005) ↔ 10/100 Ethernet bridge: PLC Stamp mini 2 + ESP32 SPI host + WIZ850io</description>
<libraries><library name="plc-bridge"><description>plc-bridge: Powerline Bridge design library (generated by tools/build-wallplug-eagle.mjs from tools/plc-bridge-model.mjs)</description>
<packages><package name="R-7.62"><description>Resistor, axial DIN0207 (6.3 x 2.5 mm), 7.62 mm pitch</description>
<wire x1="-3.15" y1="1.25" x2="3.15" y2="1.25" width="0.2032" layer="21"/>
<wire x1="3.15" y1="1.25" x2="3.15" y2="-1.25" width="0.2032" layer="21"/>
<wire x1="3.15" y1="-1.25" x2="-3.15" y2="-1.25" width="0.2032" layer="21"/>
<wire x1="-3.15" y1="-1.25" x2="-3.15" y2="1.25" width="0.2032" layer="21"/>
<wire x1="-3.81" y1="0" x2="-3.15" y2="0" width="0.2032" layer="51"/>
<wire x1="3.15" y1="0" x2="3.81" y2="0" width="0.2032" layer="51"/>
<text x="-3.15" y="1.75" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-3.81" y="0" drill="0.8" diameter="1.7" shape="square"/>
<pad name="2" x="3.81" y="0" drill="0.8" diameter="1.7"/></package>
<package name="C-5.08"><description>Ceramic / film disc capacitor, 5.0 x 2.5 mm, 5.08 mm pitch</description>
<wire x1="-2.5" y1="1.25" x2="2.5" y2="1.25" width="0.2032" layer="21"/>
<wire x1="2.5" y1="1.25" x2="2.5" y2="-1.25" width="0.2032" layer="21"/>
<wire x1="2.5" y1="-1.25" x2="-2.5" y2="-1.25" width="0.2032" layer="21"/>
<wire x1="-2.5" y1="-1.25" x2="-2.5" y2="1.25" width="0.2032" layer="21"/>
<wire x1="-2.54" y1="0" x2="-2.5" y2="0" width="0.2032" layer="51"/>
<wire x1="2.5" y1="0" x2="2.54" y2="0" width="0.2032" layer="51"/>
<text x="-2.5" y="1.75" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-2.54" y="0" drill="0.8" diameter="1.7" shape="square"/>
<pad name="2" x="2.54" y="0" drill="0.8" diameter="1.7"/></package>
<package name="CP-D10-P5"><description>Electrolytic, radial, 10 mm dia, 5.0 mm pitch</description>
<circle x="0" y="0" radius="5" width="0.2032" layer="21"/>
<text x="-4.4" y="-4.6" size="1.4" layer="21">+</text>
<text x="-5" y="5.4" size="1" layer="25">&gt;NAME</text>
<pad name="+" x="-2.5" y="0" drill="1" diameter="2" shape="square"/>
<pad name="-" x="2.5" y="0" drill="1" diameter="2"/></package>
<package name="CP-D6.3-P2.5"><description>Electrolytic, radial, 6.3 mm dia, 2.5 mm pitch</description>
<circle x="0" y="0" radius="3.15" width="0.2032" layer="21"/>
<text x="-2.55" y="-2.75" size="1.4" layer="21">+</text>
<text x="-3.15" y="3.55" size="1" layer="25">&gt;NAME</text>
<pad name="+" x="-1.25" y="0" drill="1" diameter="2" shape="square"/>
<pad name="-" x="1.25" y="0" drill="1" diameter="2"/></package>
<package name="FB-7.62"><description>Ferrite bead, axial 7.2 x 4.0 mm, 7.62 mm pitch</description>
<wire x1="-3.6" y1="2" x2="3.6" y2="2" width="0.2032" layer="21"/>
<wire x1="3.6" y1="2" x2="3.6" y2="-2" width="0.2032" layer="21"/>
<wire x1="3.6" y1="-2" x2="-3.6" y2="-2" width="0.2032" layer="21"/>
<wire x1="-3.6" y1="-2" x2="-3.6" y2="2" width="0.2032" layer="21"/>
<wire x1="-3.81" y1="0" x2="-3.6" y2="0" width="0.2032" layer="51"/>
<wire x1="3.6" y1="0" x2="3.81" y2="0" width="0.2032" layer="51"/>
<text x="-3.6" y="2.5" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-3.81" y="0" drill="0.8" diameter="1.7" shape="square"/>
<pad name="2" x="3.81" y="0" drill="0.8" diameter="1.7"/></package>
<package name="FUSE-RADIAL"><description>Radial fuse, TR5 / 372 series, 8.5 mm body, 5.08 mm pitch</description>
<circle x="0" y="0" radius="4.25" width="0.2032" layer="21"/>
<wire x1="-2.54" y1="0" x2="-4.25" y2="0" width="0.2032" layer="51"/>
<wire x1="4.25" y1="0" x2="2.54" y2="0" width="0.2032" layer="51"/>
<text x="-4.25" y="4.75" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-2.54" y="0" drill="1" diameter="2" shape="square"/>
<pad name="2" x="2.54" y="0" drill="1" diameter="2"/></package>
<package name="MOV07"><description>Metal-oxide varistor, 7 mm disc, 5.0 mm pitch</description>
<circle x="0" y="0" radius="3.5" width="0.2032" layer="21"/>
<wire x1="-2.5" y1="0" x2="-3.5" y2="0" width="0.2032" layer="51"/>
<wire x1="3.5" y1="0" x2="2.5" y2="0" width="0.2032" layer="51"/>
<text x="-3.5" y="4" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-2.5" y="0" drill="0.8" diameter="1.8" shape="square"/>
<pad name="2" x="2.5" y="0" drill="0.8" diameter="1.8"/></package>
<package name="LED-5MM"><description>LED 5 mm, 2.54 mm pitch</description>
<circle x="0" y="0" radius="2.5" width="0.2032" layer="21"/>
<wire x1="-1.27" y1="0" x2="-2.5" y2="0" width="0.2032" layer="51"/>
<wire x1="2.5" y1="0" x2="1.27" y2="0" width="0.2032" layer="51"/>
<text x="-2.5" y="3" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-1.27" y="0" drill="0.8" diameter="1.7" shape="square"/>
<pad name="2" x="1.27" y="0" drill="0.8" diameter="1.7"/></package>
<package name="SW-TACT-6MM"><description>Tactile pushbutton 6 x 6 mm, 2 poles (pins 1/1 and 2/2 internally common)</description>
<wire x1="-3" y1="-3" x2="3" y2="-3" width="0.2032" layer="21"/>
<wire x1="3" y1="-3" x2="3" y2="3" width="0.2032" layer="21"/>
<wire x1="3" y1="3" x2="-3" y2="3" width="0.2032" layer="21"/>
<wire x1="-3" y1="3" x2="-3" y2="-3" width="0.2032" layer="21"/>
<text x="-3" y="4.2" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-3.25" y="-2.25" drill="1.1" diameter="2" shape="square"/>
<pad name="1" x="3.25" y="-2.25" drill="1.1" diameter="2"/>
<pad name="2" x="-3.25" y="2.25" drill="1.1" diameter="2"/>
<pad name="2" x="3.25" y="2.25" drill="1.1" diameter="2"/></package>
<package name="TP"><description>Test point, 1.0 mm hole, 2.0 mm pad</description>
<text x="-1.2" y="1.6" size="0.9" layer="25">&gt;NAME</text>
<pad name="1" x="0" y="0" drill="1" diameter="2"/></package>
<package name="MOUNT-M3"><description>M3 mounting hole, 3.2 mm, non-plated, with keep-out ring</description>
<circle x="0" y="0" radius="2.4" width="0.2032" layer="41"/>
<circle x="0" y="0" radius="2.4" width="0.2032" layer="41"/>
<hole x="0" y="0" drill="3.2"/></package>
<package name="HDR-2X5"><description>2 x 5 pin header, 2.54 mm (TTL serial + CP + reset)</description>
<wire x1="-6.35" y1="2.54" x2="6.35" y2="2.54" width="0.2032" layer="21"/>
<wire x1="6.35" y1="2.54" x2="6.35" y2="-2.54" width="0.2032" layer="21"/>
<wire x1="6.35" y1="-2.54" x2="-6.35" y2="-2.54" width="0.2032" layer="21"/>
<wire x1="-6.35" y1="-2.54" x2="-6.35" y2="2.54" width="0.2032" layer="21"/>
<text x="-6.28" y="3.2" size="1" layer="25">&gt;NAME</text>
<pad name="1" x="-5.08" y="-1.27" drill="1" diameter="1.8" shape="square"/>
<pad name="2" x="-5.08" y="1.27" drill="1" diameter="1.8"/>
<pad name="3" x="-2.54" y="-1.27" drill="1" diameter="1.8"/>
<pad name="4" x="-2.54" y="1.27" drill="1" diameter="1.8"/>
<pad name="5" x="0" y="-1.27" drill="1" diameter="1.8"/>
<pad name="6" x="0" y="1.27" drill="1" diameter="1.8"/>
<pad name="7" x="2.54" y="-1.27" drill="1" diameter="1.8"/>
<pad name="8" x="2.54" y="1.27" drill="1" diameter="1.8"/>
<pad name="9" x="5.08" y="-1.27" drill="1" diameter="1.8"/>
<pad name="10" x="5.08" y="1.27" drill="1" diameter="1.8"/></package>
<package name="CUI_TB003"><description>CUI TB003-500-P03BE, 3-position 5.00 mm terminal block, drill 1.4 mm</description>

<pad name="1" x="-5" y="0" drill="1.4" diameter="2.1" shape="square"/>
<pad name="2" x="0" y="0" drill="1.4" diameter="2.1"/>
<pad name="3" x="5" y="0" drill="1.4" diameter="2.1"/></package>
<package name="IRM055"><description>MEAN WELL IRM-05-5, 5 W encapsulated AC-DC, 85-305 VAC in, 5 V / 1 A out, 45.7 x 25.4 x 21.5 mm</description>

<pad name="1" x="-19.25" y="-9.25" drill="1.24" diameter="1.86"/>
<pad name="2" x="-19.25" y="1.5" drill="1.24" diameter="1.86"/>
<pad name="3" x="19.25" y="-9.25" drill="1.24" diameter="1.86"/>
<pad name="4" x="19.25" y="-1.25" drill="1.24" diameter="1.86"/></package>
<package name="LM2576S"><description>TO-263-5 (D2PAK) with tab tied to pin 3 — LM2576S-3.3 step-down regulator</description>

<smd name="1" x="-5.775" y="3.4" dx="4.6" dy="1.1" layer="1"/>
<smd name="2" x="-5.775" y="1.7" dx="4.6" dy="1.1" layer="1"/>
<smd name="3" x="-5.775" y="0" dx="4.6" dy="1.1" layer="1"/>
<smd name="4" x="-5.775" y="-1.7" dx="4.6" dy="1.1" layer="1"/>
<smd name="5" x="-5.775" y="-3.4" dx="4.6" dy="1.1" layer="1"/>
<smd name="3_2" x="3.375" y="0" dx="9.4" dy="10.8" layer="1"/>
<smd name="P7" x="5.8" y="-2.775" dx="4.55" dy="5.25" layer="1"/>
<smd name="P8" x="0.95" y="2.775" dx="4.55" dy="5.25" layer="1"/>
<smd name="P9" x="5.8" y="2.775" dx="4.55" dy="5.25" layer="1"/>
<smd name="P10" x="0.95" y="-2.775" dx="4.55" dy="5.25" layer="1"/></package>
<package name="LRAD12"><description>Radial power inductor, Ø12 mm body, 5.0 mm lead pitch — 100 µH for the LM2576</description>

<pad name="1" x="0" y="0" drill="1.3" diameter="2.6"/>
<pad name="2" x="5" y="0" drill="1.3" diameter="2.6"/></package>
<package name="PLCSTAMP"><description>chargebyte (ex I2SE) PLC Stamp mini 2 — QCA7005 HomePlug Green PHY module, 43.5 x 22 x 6.5 mm, integrated mains coupling</description>

<smd name="1" x="20.48" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="2" x="19.21" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="3" x="17.94" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="4" x="16.67" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="5" x="15.4" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="6" x="14.13" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="7" x="12.86" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="8" x="11.59" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="9" x="10.32" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="10" x="9.05" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="11" x="7.78" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="12" x="6.51" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="13" x="5.24" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="15" x="-8.73" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="16" x="-18.89" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="17" x="-20.16" y="10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="18" x="1.43" y="-10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="19" x="2.7" y="-10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="20" x="3.97" y="-10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="21" x="5.24" y="-10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="22" x="6.51" y="-10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="23" x="7.78" y="-10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="24" x="9.05" y="-10.235" dx="0.85" dy="0.85" layer="1"/>
<smd name="25" x="10.32" y="-10.235" dx="0.85" dy="0.85" layer="1"/></package>
<package name="ESP32WROOM"><description>Espressif ESP32-WROOM-32 / -32E module, 18 x 25.5 mm, 38 castellated pads + ground pad</description>

<smd name="39" x="-1" y="0.755" dx="5" dy="5" layer="1"/>
<smd name="1" x="-8.5" y="8.255" dx="2" dy="0.9" layer="1"/>
<smd name="2" x="-8.5" y="6.985" dx="2" dy="0.9" layer="1"/>
<smd name="3" x="-8.5" y="5.715" dx="2" dy="0.9" layer="1"/>
<smd name="4" x="-8.5" y="4.445" dx="2" dy="0.9" layer="1"/>
<smd name="5" x="-8.5" y="3.175" dx="2" dy="0.9" layer="1"/>
<smd name="6" x="-8.5" y="1.905" dx="2" dy="0.9" layer="1"/>
<smd name="7" x="-8.5" y="0.635" dx="2" dy="0.9" layer="1"/>
<smd name="8" x="-8.5" y="-0.635" dx="2" dy="0.9" layer="1"/>
<smd name="9" x="-8.5" y="-1.905" dx="2" dy="0.9" layer="1"/>
<smd name="10" x="-8.5" y="-3.175" dx="2" dy="0.9" layer="1"/>
<smd name="11" x="-8.5" y="-4.445" dx="2" dy="0.9" layer="1"/>
<smd name="12" x="-8.5" y="-5.715" dx="2" dy="0.9" layer="1"/>
<smd name="13" x="-8.5" y="-6.985" dx="2" dy="0.9" layer="1"/>
<smd name="14" x="-8.5" y="-8.255" dx="2" dy="0.9" layer="1"/>
<smd name="15" x="-5.715" y="-9.255" dx="0.9" dy="2" layer="1"/>
<smd name="16" x="-4.445" y="-9.255" dx="0.9" dy="2" layer="1"/>
<smd name="17" x="-3.175" y="-9.255" dx="0.9" dy="2" layer="1"/>
<smd name="18" x="-1.905" y="-9.255" dx="0.9" dy="2" layer="1"/>
<smd name="19" x="-0.635" y="-9.255" dx="0.9" dy="2" layer="1"/>
<smd name="20" x="0.635" y="-9.255" dx="0.9" dy="2" layer="1"/>
<smd name="21" x="1.905" y="-9.255" dx="0.9" dy="2" layer="1"/>
<smd name="22" x="3.175" y="-9.255" dx="0.9" dy="2" layer="1"/>
<smd name="23" x="4.445" y="-9.255" dx="0.9" dy="2" layer="1"/>
<smd name="24" x="5.715" y="-9.255" dx="0.9" dy="2" layer="1"/>
<smd name="25" x="8.5" y="-8.255" dx="2" dy="0.9" layer="1"/>
<smd name="26" x="8.5" y="-6.985" dx="2" dy="0.9" layer="1"/>
<smd name="27" x="8.5" y="-5.715" dx="2" dy="0.9" layer="1"/>
<smd name="28" x="8.5" y="-4.445" dx="2" dy="0.9" layer="1"/>
<smd name="29" x="8.5" y="-3.175" dx="2" dy="0.9" layer="1"/>
<smd name="30" x="8.5" y="-1.905" dx="2" dy="0.9" layer="1"/>
<smd name="31" x="8.5" y="-0.635" dx="2" dy="0.9" layer="1"/>
<smd name="32" x="8.5" y="0.635" dx="2" dy="0.9" layer="1"/>
<smd name="33" x="8.5" y="1.905" dx="2" dy="0.9" layer="1"/>
<smd name="34" x="8.5" y="3.175" dx="2" dy="0.9" layer="1"/>
<smd name="35" x="8.5" y="4.445" dx="2" dy="0.9" layer="1"/>
<smd name="36" x="8.5" y="5.715" dx="2" dy="0.9" layer="1"/>
<smd name="37" x="8.5" y="6.985" dx="2" dy="0.9" layer="1"/>
<smd name="38" x="8.5" y="8.255" dx="2" dy="0.9" layer="1"/></package>
<package name="WIZ850IO"><description>WIZnet WIZ850io plug-in Ethernet module: W5500 + magnetics + RJ45, two 1x6 headers 20.32 mm apart</description>

<pad name="1" x="-9.86" y="4.75" drill="1.12" diameter="1.68" shape="square"/>
<pad name="2" x="-9.86" y="2.21" drill="1.12" diameter="1.68"/>
<pad name="3" x="-9.86" y="-0.33" drill="1.12" diameter="1.68"/>
<pad name="4" x="-9.86" y="-2.87" drill="1.12" diameter="1.68"/>
<pad name="5" x="-9.86" y="-5.41" drill="1.12" diameter="1.68"/>
<pad name="6" x="-9.86" y="-7.95" drill="1.12" diameter="1.68"/>
<pad name="7" x="10.46" y="4.75" drill="1.12" diameter="1.68" shape="square"/>
<pad name="8" x="10.46" y="2.21" drill="1.12" diameter="1.68"/>
<pad name="9" x="10.46" y="-0.33" drill="1.12" diameter="1.68"/>
<pad name="10" x="10.46" y="-2.87" drill="1.12" diameter="1.68"/>
<pad name="11" x="10.46" y="-5.41" drill="1.12" diameter="1.68"/>
<pad name="12" x="10.46" y="-7.95" drill="1.12" diameter="1.68"/></package>
<package name="R0603"><description>0603 (1608 metric) chip resistor</description>

<smd name="1" x="-0.825" y="0" dx="0.8" dy="0.95" layer="1"/>
<smd name="2" x="0.825" y="0" dx="0.8" dy="0.95" layer="1"/></package>
<package name="C0603"><description>0603 (1608 metric) chip capacitor</description>

<smd name="1" x="-0.775" y="0" dx="0.9" dy="0.95" layer="1"/>
<smd name="2" x="0.775" y="0" dx="0.9" dy="0.95" layer="1"/></package>
<package name="DO41"><description>DO-41 axial diode, 7.62 mm lead pitch (1N5822 / SS34-class Schottky)</description>
<wire x1="-2.5" y1="1.3" x2="2.5" y2="1.3" width="0.2032" layer="21"/>
<wire x1="2.5" y1="1.3" x2="2.5" y2="-1.3" width="0.2032" layer="21"/>
<wire x1="2.5" y1="-1.3" x2="-2.5" y2="-1.3" width="0.2032" layer="21"/>
<wire x1="-2.5" y1="-1.3" x2="-2.5" y2="1.3" width="0.2032" layer="21"/>
<wire x1="1.6" y1="1.3" x2="1.6" y2="-1.3" width="0.2032" layer="21"/>
<text x="-2.4" y="1.9" size="1" layer="25">&gt;NAME</text>
<pad name="A" x="-3.81" y="0" drill="0.9" diameter="1.8"/>
<pad name="K" x="3.81" y="0" drill="0.9" diameter="1.8" shape="square"/></package></packages>
<symbols><symbol name="R-EU"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="0" x2="-1.9" y2="1" width="0.2032" layer="94"/>
<wire x1="-1.9" y1="1" x2="-0.63" y2="-1" width="0.2032" layer="94"/>
<wire x1="-0.63" y1="-1" x2="0.63" y2="1" width="0.2032" layer="94"/>
<wire x1="0.63" y1="1" x2="1.9" y2="-1" width="0.2032" layer="94"/>
<wire x1="1.9" y1="-1" x2="2.54" y2="0" width="0.2032" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="C-EU"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="-1.27" y1="0.9" x2="1.27" y2="0.9" width="0.3" layer="94"/>
<wire x1="-1.27" y1="-0.9" x2="1.27" y2="-0.9" width="0.3" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="CPOL-EU"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="-1.27" y1="0.9" x2="1.27" y2="0.9" width="0.3" layer="94"/>
<wire x1="-1.27" y1="-0.9" x2="1.27" y2="-0.9" width="0.3" layer="94" style="shortdash"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<text x="-3.4" y="1.2" size="1.6" layer="94">+</text>
<pin name="+" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="-" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="FERRITE"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="FUSE"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="MOV"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="LED"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="1.27" x2="2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="2.54" y1="-1.27" x2="-2.54" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-2.54" y1="-1.27" x2="-2.54" y2="1.27" width="0.254" layer="94"/>
<wire x1="1" y1="1.6" x2="2.2" y2="2.8" width="0.2032" layer="94"/>
<wire x1="1.8" y1="1.6" x2="3" y2="2.8" width="0.2032" layer="94"/>
<text x="-2.54" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-2.54" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="A" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="K" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="SW-PUSH"><wire x1="-2.54" y1="1.27" x2="2.54" y2="1.27" width="0.2032" layer="94"/>
<wire x1="0" y1="1.27" x2="0" y2="2.54" width="0.2032" layer="94"/>
<wire x1="-2.54" y1="0" x2="-1.27" y2="0" width="0.2032" layer="94"/>
<wire x1="1.27" y1="0" x2="2.54" y2="0" width="0.2032" layer="94"/>
<text x="-3.81" y="3.54" size="1.778" layer="95">&gt;NAME</text>
<text x="-3.81" y="-5.14" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-5.08" y="0" visible="pin" length="short" direction="pas" rot="R0"/>
<pin name="2" x="5.08" y="0" visible="pin" length="short" direction="pas" rot="R180"/></symbol>
<symbol name="TP"><circle x="0" y="0" radius="1.27" width="0.2032" layer="94"/>
<text x="-1.27" y="2.27" size="1.778" layer="95">&gt;NAME</text>
<text x="-1.27" y="-3.87" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="0" y="-3.81" visible="pin" length="short" direction="pas" rot="R90"/></symbol>
<symbol name="HDR-2X5"><wire x1="-6.35" y1="7.62" x2="6.35" y2="7.62" width="0.4064" layer="94"/>
<wire x1="6.35" y1="7.62" x2="6.35" y2="-7.62" width="0.4064" layer="94"/>
<wire x1="6.35" y1="-7.62" x2="-6.35" y2="-7.62" width="0.4064" layer="94"/>
<wire x1="-6.35" y1="-7.62" x2="-6.35" y2="7.62" width="0.4064" layer="94"/>
<text x="-6.35" y="8.62" size="1.778" layer="95">&gt;NAME</text>
<text x="-6.35" y="-10.22" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-11.43" y="5.08" visible="pin" length="middle" rot="R0"/>
<pin name="3" x="-11.43" y="2.54" visible="pin" length="middle" rot="R0"/>
<pin name="5" x="-11.43" y="0" visible="pin" length="middle" rot="R0"/>
<pin name="7" x="-11.43" y="-2.54" visible="pin" length="middle" rot="R0"/>
<pin name="9" x="-11.43" y="-5.08" visible="pin" length="middle" rot="R0"/>
<pin name="2" x="11.43" y="5.08" visible="pin" length="middle" rot="R180"/>
<pin name="4" x="11.43" y="2.54" visible="pin" length="middle" rot="R180"/>
<pin name="6" x="11.43" y="0" visible="pin" length="middle" rot="R180"/>
<pin name="8" x="11.43" y="-2.54" visible="pin" length="middle" rot="R180"/>
<pin name="10" x="11.43" y="-5.08" visible="pin" length="middle" rot="R180"/></symbol>
<symbol name="ACDC-4"><wire x1="-12.7" y1="3.81" x2="12.7" y2="3.81" width="0.4064" layer="94"/>
<wire x1="12.7" y1="3.81" x2="12.7" y2="-3.81" width="0.4064" layer="94"/>
<wire x1="12.7" y1="-3.81" x2="-12.7" y2="-3.81" width="0.4064" layer="94"/>
<wire x1="-12.7" y1="-3.81" x2="-12.7" y2="3.81" width="0.4064" layer="94"/>
<text x="-12.7" y="4.81" size="1.778" layer="95">&gt;NAME</text>
<text x="-12.7" y="-6.41" size="1.778" layer="96">&gt;VALUE</text>
<text x="-8" y="0" size="1.6" layer="94" ratio="10">AC / DC</text>
<text x="-8" y="-2.6" size="1.3" layer="94" ratio="10">isolated</text>
<pin name="AC-L" x="-12.7" y="1.27" visible="pin" length="middle" rot="R0"/>
<pin name="AC-N" x="-12.7" y="-1.27" visible="pin" length="middle" rot="R0"/>
<pin name="+VO" x="12.7" y="1.27" visible="pin" length="middle" rot="R180"/>
<pin name="-VO" x="12.7" y="-1.27" visible="pin" length="middle" rot="R180"/></symbol>
<symbol name="BUCK-3V3"><wire x1="-10.16" y1="3.81" x2="10.16" y2="3.81" width="0.4064" layer="94"/>
<wire x1="10.16" y1="3.81" x2="10.16" y2="-3.81" width="0.4064" layer="94"/>
<wire x1="10.16" y1="-3.81" x2="-10.16" y2="-3.81" width="0.4064" layer="94"/>
<wire x1="-10.16" y1="-3.81" x2="-10.16" y2="3.81" width="0.4064" layer="94"/>
<text x="-10.16" y="4.81" size="1.778" layer="95">&gt;NAME</text>
<text x="-10.16" y="-6.41" size="1.778" layer="96">&gt;VALUE</text>
<text x="-7.6" y="0" size="1.5" layer="94" ratio="10">LM2576</text>
<pin name="VIN" x="-10.16" y="1.27" visible="pin" length="middle" rot="R0"/>
<pin name="FB" x="-10.16" y="-1.27" visible="pin" length="middle" rot="R0"/>
<pin name="VOUT" x="10.16" y="1.27" visible="pin" length="middle" rot="R180"/>
<pin name="ONOFF" x="10.16" y="-1.27" visible="pin" length="middle" rot="R180"/>
<pin name="GND" x="0" y="-3.81" visible="pin" length="middle" rot="R90"/></symbol>
<symbol name="DIODE"><wire x1="-3.81" y1="2.54" x2="3.81" y2="2.54" width="0.254" layer="94"/>
<wire x1="3.81" y1="2.54" x2="3.81" y2="-2.54" width="0.254" layer="94"/>
<wire x1="3.81" y1="-2.54" x2="-3.81" y2="-2.54" width="0.254" layer="94"/>
<wire x1="-3.81" y1="-2.54" x2="-3.81" y2="2.54" width="0.254" layer="94"/>
<wire x1="-1.27" y1="1.27" x2="-1.27" y2="-1.27" width="0.254" layer="94"/>
<wire x1="-1.27" y1="0" x2="1.27" y2="1.27" width="0.254" layer="94"/>
<wire x1="1.27" y1="1.27" x2="1.27" y2="-1.27" width="0.254" layer="94"/>
<wire x1="1.27" y1="-1.27" x2="-1.27" y2="0" width="0.254" layer="94"/>
<text x="-3.81" y="3.54" size="1.778" layer="95">&gt;NAME</text>
<text x="-3.81" y="-5.14" size="1.778" layer="96">&gt;VALUE</text>
<pin name="A" x="-7.62" y="0" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="K" x="7.62" y="0" visible="pin" length="middle" direction="pas" rot="R180"/></symbol>
<symbol name="INDUCTOR"><wire x1="-5.08" y1="2.54" x2="5.08" y2="2.54" width="0.254" layer="94"/>
<wire x1="5.08" y1="2.54" x2="5.08" y2="-2.54" width="0.254" layer="94"/>
<wire x1="5.08" y1="-2.54" x2="-5.08" y2="-2.54" width="0.254" layer="94"/>
<wire x1="-5.08" y1="-2.54" x2="-5.08" y2="2.54" width="0.254" layer="94"/>
<circle x="-2.54" y="0.9" radius="1.27" width="0.254" layer="94"/>
<circle x="0" y="0.9" radius="1.27" width="0.254" layer="94"/>
<circle x="2.54" y="0.9" radius="1.27" width="0.254" layer="94"/>
<text x="-5.08" y="3.54" size="1.778" layer="95">&gt;NAME</text>
<text x="-5.08" y="-5.14" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-10.16" y="0" visible="pin" length="middle" direction="pas" rot="R0"/>
<pin name="2" x="10.16" y="0" visible="pin" length="middle" direction="pas" rot="R180"/></symbol>
<symbol name="TERM-3"><wire x1="-7.62" y1="8.89" x2="7.62" y2="8.89" width="0.4064" layer="94"/>
<wire x1="7.62" y1="8.89" x2="7.62" y2="-8.89" width="0.4064" layer="94"/>
<wire x1="7.62" y1="-8.89" x2="-7.62" y2="-8.89" width="0.4064" layer="94"/>
<wire x1="-7.62" y1="-8.89" x2="-7.62" y2="8.89" width="0.4064" layer="94"/>
<text x="-7.62" y="9.89" size="1.778" layer="95">&gt;NAME</text>
<text x="-7.62" y="-11.49" size="1.778" layer="96">&gt;VALUE</text>
<text x="-4.5" y="0" size="1.5" layer="94" ratio="10">TB3</text>
<pin name="1" x="-7.62" y="5.08" visible="pin" length="middle" rot="R0"/>
<pin name="2" x="-7.62" y="0" visible="pin" length="middle" rot="R0"/>
<pin name="3" x="-7.62" y="-5.08" visible="pin" length="middle" rot="R0"/></symbol>
<symbol name="PLCSTAMP"><wire x1="-15.24" y1="15.24" x2="15.24" y2="15.24" width="0.4064" layer="94"/>
<wire x1="15.24" y1="15.24" x2="15.24" y2="-15.24" width="0.4064" layer="94"/>
<wire x1="15.24" y1="-15.24" x2="-15.24" y2="-15.24" width="0.4064" layer="94"/>
<wire x1="-15.24" y1="-15.24" x2="-15.24" y2="15.24" width="0.4064" layer="94"/>
<text x="-15.24" y="16.24" size="1.778" layer="95">&gt;NAME</text>
<text x="-15.24" y="-17.84" size="1.778" layer="96">&gt;VALUE</text>
<text x="-11.5" y="0" size="1.5" layer="94" ratio="10">PLC Stamp mini 2</text>
<text x="-11.5" y="-2.6" size="1.2" layer="94" ratio="10">QCA7005 Green PHY</text>
<pin name="GPIO_0" x="-15.24" y="12.7" visible="pin" length="middle" rot="R0"/>
<pin name="GPIO_1" x="-15.24" y="10.16" visible="pin" length="middle" rot="R0"/>
<pin name="GPIO_2" x="-15.24" y="7.62" visible="pin" length="middle" rot="R0"/>
<pin name="GPIO_3" x="-15.24" y="5.08" visible="pin" length="middle" rot="R0"/>
<pin name="RESET_L" x="-15.24" y="2.54" visible="pin" length="middle" rot="R0"/>
<pin name="SERIAL_4" x="-15.24" y="0" visible="pin" length="middle" rot="R0"/>
<pin name="SERIAL_3" x="-15.24" y="-2.54" visible="pin" length="middle" rot="R0"/>
<pin name="SERIAL_2" x="-15.24" y="-5.08" visible="pin" length="middle" rot="R0"/>
<pin name="SERIAL_1" x="-15.24" y="-7.62" visible="pin" length="middle" rot="R0"/>
<pin name="SERIAL_0" x="-15.24" y="-10.16" visible="pin" length="middle" rot="R0"/>
<pin name="ZC_IN" x="-15.24" y="-12.7" visible="pin" length="middle" rot="R0"/>
<pin name="VDD" x="15.24" y="12.7" visible="pin" length="middle" rot="R180"/>
<pin name="N" x="15.24" y="10.16" visible="pin" length="middle" rot="R180"/>
<pin name="L" x="15.24" y="7.62" visible="pin" length="middle" rot="R180"/>
<pin name="GND" x="0" y="-15.24" visible="pin" length="middle" rot="R90"/></symbol>
<symbol name="ESP32-WROOM"><wire x1="-17.78" y1="27.94" x2="17.78" y2="27.94" width="0.4064" layer="94"/>
<wire x1="17.78" y1="27.94" x2="17.78" y2="-27.94" width="0.4064" layer="94"/>
<wire x1="17.78" y1="-27.94" x2="-17.78" y2="-27.94" width="0.4064" layer="94"/>
<wire x1="-17.78" y1="-27.94" x2="-17.78" y2="27.94" width="0.4064" layer="94"/>
<text x="-17.78" y="28.94" size="1.778" layer="95">&gt;NAME</text>
<text x="-17.78" y="-30.54" size="1.778" layer="96">&gt;VALUE</text>
<text x="-14" y="0" size="1.5" layer="94" ratio="10">ESP32-WROOM-32E</text>
<text x="-14" y="-2.6" size="1.2" layer="94" ratio="10">SPI host</text>
<pin name="VDD" x="-17.78" y="25.4" visible="pin" length="middle" rot="R0"/>
<pin name="EN" x="-17.78" y="22.86" visible="pin" length="middle" rot="R0"/>
<pin name="SENSOR_VP" x="-17.78" y="20.32" visible="pin" length="middle" rot="R0"/>
<pin name="SENSOR_VN" x="-17.78" y="17.78" visible="pin" length="middle" rot="R0"/>
<pin name="IO34" x="-17.78" y="15.24" visible="pin" length="middle" rot="R0"/>
<pin name="IO35" x="-17.78" y="12.7" visible="pin" length="middle" rot="R0"/>
<pin name="IO32" x="-17.78" y="10.16" visible="pin" length="middle" rot="R0"/>
<pin name="IO33" x="-17.78" y="7.62" visible="pin" length="middle" rot="R0"/>
<pin name="IO25" x="-17.78" y="5.08" visible="pin" length="middle" rot="R0"/>
<pin name="IO26" x="-17.78" y="2.54" visible="pin" length="middle" rot="R0"/>
<pin name="IO27" x="-17.78" y="0" visible="pin" length="middle" rot="R0"/>
<pin name="IO14" x="-17.78" y="-2.54" visible="pin" length="middle" rot="R0"/>
<pin name="IO12" x="-17.78" y="-5.08" visible="pin" length="middle" rot="R0"/>
<pin name="GND_15" x="-17.78" y="-7.62" visible="pin" length="middle" rot="R0"/>
<pin name="IO13" x="-17.78" y="-10.16" visible="pin" length="middle" rot="R0"/>
<pin name="NC_17" x="-17.78" y="-12.7" visible="pin" length="middle" rot="R0"/>
<pin name="NC_18" x="-17.78" y="-15.24" visible="pin" length="middle" rot="R0"/>
<pin name="NC_19" x="-17.78" y="-17.78" visible="pin" length="middle" rot="R0"/>
<pin name="NC_20" x="-17.78" y="-20.32" visible="pin" length="middle" rot="R0"/>
<pin name="NC_21" x="-17.78" y="-22.86" visible="pin" length="middle" rot="R0"/>
<pin name="NC_22" x="-17.78" y="-25.4" visible="pin" length="middle" rot="R0"/>
<pin name="IO21" x="17.78" y="25.4" visible="pin" length="middle" rot="R180"/>
<pin name="RXD0" x="17.78" y="22.86" visible="pin" length="middle" rot="R180"/>
<pin name="TXD0" x="17.78" y="20.32" visible="pin" length="middle" rot="R180"/>
<pin name="IO22" x="17.78" y="17.78" visible="pin" length="middle" rot="R180"/>
<pin name="IO23" x="17.78" y="15.24" visible="pin" length="middle" rot="R180"/>
<pin name="GND_38" x="17.78" y="12.7" visible="pin" length="middle" rot="R180"/>
<pin name="GND_39" x="17.78" y="10.16" visible="pin" length="middle" rot="R180"/>
<pin name="NC_32" x="17.78" y="7.62" visible="pin" length="middle" rot="R180"/>
<pin name="IO5" x="17.78" y="5.08" visible="pin" length="middle" rot="R180"/>
<pin name="IO18" x="17.78" y="2.54" visible="pin" length="middle" rot="R180"/>
<pin name="IO19" x="17.78" y="0" visible="pin" length="middle" rot="R180"/>
<pin name="IO16" x="17.78" y="-2.54" visible="pin" length="middle" rot="R180"/>
<pin name="IO17" x="17.78" y="-5.08" visible="pin" length="middle" rot="R180"/>
<pin name="IO4" x="17.78" y="-7.62" visible="pin" length="middle" rot="R180"/>
<pin name="IO0" x="17.78" y="-10.16" visible="pin" length="middle" rot="R180"/>
<pin name="IO2" x="17.78" y="-12.7" visible="pin" length="middle" rot="R180"/>
<pin name="IO15" x="17.78" y="-15.24" visible="pin" length="middle" rot="R180"/>
<pin name="GND_1" x="17.78" y="-17.78" visible="pin" length="middle" rot="R180"/></symbol>
<symbol name="WIZ850IO"><wire x1="-11.43" y1="8.89" x2="11.43" y2="8.89" width="0.4064" layer="94"/>
<wire x1="11.43" y1="8.89" x2="11.43" y2="-8.89" width="0.4064" layer="94"/>
<wire x1="11.43" y1="-8.89" x2="-11.43" y2="-8.89" width="0.4064" layer="94"/>
<wire x1="-11.43" y1="-8.89" x2="-11.43" y2="8.89" width="0.4064" layer="94"/>
<text x="-11.43" y="9.89" size="1.778" layer="95">&gt;NAME</text>
<text x="-11.43" y="-11.49" size="1.778" layer="96">&gt;VALUE</text>
<text x="-8.5" y="0" size="1.5" layer="94" ratio="10">WIZ850io</text>
<text x="-8.5" y="-2.6" size="1.2" layer="94" ratio="10">W5500 + magjack</text>
<pin name="MOSI" x="-11.43" y="6.35" visible="pin" length="middle" rot="R0"/>
<pin name="SCLK" x="-11.43" y="3.81" visible="pin" length="middle" rot="R0"/>
<pin name="!SCS" x="-11.43" y="1.27" visible="pin" length="middle" rot="R0"/>
<pin name="!INT" x="-11.43" y="-1.27" visible="pin" length="middle" rot="R0"/>
<pin name="!RST" x="-11.43" y="-3.81" visible="pin" length="middle" rot="R0"/>
<pin name="MISO" x="-11.43" y="-6.35" visible="pin" length="middle" rot="R0"/>
<pin name="3V3" x="11.43" y="6.35" visible="pin" length="middle" rot="R180"/>
<pin name="NC" x="11.43" y="3.81" visible="pin" length="middle" rot="R180"/>
<pin name="GND" x="0" y="-8.89" visible="pin" length="middle" rot="R90"/></symbol></symbols>
<devicesets><deviceset name="R-EU" prefix="R"><gates><gate name="G$1" symbol="R-EU" x="0" y="0"/></gates>
<devices><device package="R-7.62"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="C-EU" prefix="C"><gates><gate name="G$1" symbol="C-EU" x="0" y="0"/></gates>
<devices><device package="C-5.08"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="CPOL-EU" prefix="C"><gates><gate name="G$1" symbol="CPOL-EU" x="0" y="0"/></gates>
<devices><device package="CP-D10-P5"><connects><connect gate="G$1" pin="+" pad="+"/>
<connect gate="G$1" pin="-" pad="-"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="FERRITE" prefix="FB"><gates><gate name="G$1" symbol="FERRITE" x="0" y="0"/></gates>
<devices><device package="FB-7.62"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="FUSE" prefix="F"><gates><gate name="G$1" symbol="FUSE" x="0" y="0"/></gates>
<devices><device package="FUSE-RADIAL"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="MOV" prefix="MOV"><gates><gate name="G$1" symbol="MOV" x="0" y="0"/></gates>
<devices><device package="MOV07"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="LED" prefix="LED"><gates><gate name="G$1" symbol="LED" x="0" y="0"/></gates>
<devices><device package="LED-5MM"><connects><connect gate="G$1" pin="A" pad="1"/>
<connect gate="G$1" pin="K" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="SW-PUSH" prefix="SW"><gates><gate name="G$1" symbol="SW-PUSH" x="0" y="0"/></gates>
<devices><device package="SW-TACT-6MM"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="TP" prefix="TP"><gates><gate name="G$1" symbol="TP" x="0" y="0"/></gates>
<devices><device package="TP"><connects><connect gate="G$1" pin="1" pad="1"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="HDR-2X5" prefix="J"><gates><gate name="G$1" symbol="HDR-2X5" x="0" y="0"/></gates>
<devices><device package="HDR-2X5"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/>
<connect gate="G$1" pin="3" pad="3"/>
<connect gate="G$1" pin="4" pad="4"/>
<connect gate="G$1" pin="5" pad="5"/>
<connect gate="G$1" pin="6" pad="6"/>
<connect gate="G$1" pin="7" pad="7"/>
<connect gate="G$1" pin="8" pad="8"/>
<connect gate="G$1" pin="9" pad="9"/>
<connect gate="G$1" pin="10" pad="10"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="MOUNT-M3" prefix="H"><gates></gates>
<devices><device package="MOUNT-M3"><connects></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="ACDC-5V" prefix="PS"><gates><gate name="G$1" symbol="ACDC-4" x="0" y="0"/></gates>
<devices><device package="IRM055"><connects><connect gate="G$1" pin="AC-L" pad="1"/>
<connect gate="G$1" pin="AC-N" pad="2"/>
<connect gate="G$1" pin="-VO" pad="3"/>
<connect gate="G$1" pin="+VO" pad="4"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="BUCK-3V3" prefix="U"><gates><gate name="G$1" symbol="BUCK-3V3" x="0" y="0"/></gates>
<devices><device package="LM2576S"><connects><connect gate="G$1" pin="VIN" pad="1"/>
<connect gate="G$1" pin="VOUT" pad="2"/>
<connect gate="G$1" pin="GND" pad="3 3_2 P7 P8 P9 P10"/>
<connect gate="G$1" pin="FB" pad="4"/>
<connect gate="G$1" pin="ONOFF" pad="5"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="DIODE-SCH" prefix="D"><gates><gate name="G$1" symbol="DIODE" x="0" y="0"/></gates>
<devices><device package="DO41"><connects><connect gate="G$1" pin="A" pad="A"/>
<connect gate="G$1" pin="K" pad="K"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="L-RADIAL" prefix="L"><gates><gate name="G$1" symbol="INDUCTOR" x="0" y="0"/></gates>
<devices><device package="LRAD12"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="TERM-3" prefix="J"><gates><gate name="G$1" symbol="TERM-3" x="0" y="0"/></gates>
<devices><device package="CUI_TB003"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/>
<connect gate="G$1" pin="3" pad="3"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="R-0603" prefix="R"><gates><gate name="G$1" symbol="R-EU" x="0" y="0"/></gates>
<devices><device package="R0603"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="C-0603" prefix="C"><gates><gate name="G$1" symbol="C-EU" x="0" y="0"/></gates>
<devices><device package="C0603"><connects><connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="2" pad="2"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="PLC-STAMP-MINI-2" prefix="U"><gates><gate name="G$1" symbol="PLCSTAMP" x="0" y="0"/></gates>
<devices><device package="PLCSTAMP"><connects><connect gate="G$1" pin="GPIO_0" pad="1"/>
<connect gate="G$1" pin="GPIO_1" pad="2"/>
<connect gate="G$1" pin="GPIO_2" pad="3"/>
<connect gate="G$1" pin="GPIO_3" pad="4"/>
<connect gate="G$1" pin="RESET_L" pad="5"/>
<connect gate="G$1" pin="SERIAL_4" pad="6"/>
<connect gate="G$1" pin="SERIAL_3" pad="7"/>
<connect gate="G$1" pin="SERIAL_2" pad="8"/>
<connect gate="G$1" pin="SERIAL_1" pad="9"/>
<connect gate="G$1" pin="SERIAL_0" pad="10"/>
<connect gate="G$1" pin="GND" pad="11 18 19 20 21 22 23 24 25"/>
<connect gate="G$1" pin="VDD" pad="12"/>
<connect gate="G$1" pin="ZC_IN" pad="13"/>
<connect gate="G$1" pin="N" pad="15"/>
<connect gate="G$1" pin="L" pad="16 17"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="ESP32-WROOM-32E" prefix="U"><gates><gate name="G$1" symbol="ESP32-WROOM" x="0" y="0"/></gates>
<devices><device package="ESP32WROOM"><connects><connect gate="G$1" pin="GND_1" pad="1"/>
<connect gate="G$1" pin="VDD" pad="2"/>
<connect gate="G$1" pin="EN" pad="3"/>
<connect gate="G$1" pin="SENSOR_VP" pad="4"/>
<connect gate="G$1" pin="SENSOR_VN" pad="5"/>
<connect gate="G$1" pin="IO34" pad="6"/>
<connect gate="G$1" pin="IO35" pad="7"/>
<connect gate="G$1" pin="IO32" pad="8"/>
<connect gate="G$1" pin="IO33" pad="9"/>
<connect gate="G$1" pin="IO25" pad="10"/>
<connect gate="G$1" pin="IO26" pad="11"/>
<connect gate="G$1" pin="IO27" pad="12"/>
<connect gate="G$1" pin="IO14" pad="13"/>
<connect gate="G$1" pin="IO12" pad="14"/>
<connect gate="G$1" pin="GND_15" pad="15"/>
<connect gate="G$1" pin="IO13" pad="16"/>
<connect gate="G$1" pin="NC_17" pad="17"/>
<connect gate="G$1" pin="NC_18" pad="18"/>
<connect gate="G$1" pin="NC_19" pad="19"/>
<connect gate="G$1" pin="NC_20" pad="20"/>
<connect gate="G$1" pin="NC_21" pad="21"/>
<connect gate="G$1" pin="NC_22" pad="22"/>
<connect gate="G$1" pin="IO15" pad="23"/>
<connect gate="G$1" pin="IO2" pad="24"/>
<connect gate="G$1" pin="IO0" pad="25"/>
<connect gate="G$1" pin="IO4" pad="26"/>
<connect gate="G$1" pin="IO16" pad="27"/>
<connect gate="G$1" pin="IO17" pad="28"/>
<connect gate="G$1" pin="IO5" pad="29"/>
<connect gate="G$1" pin="IO18" pad="30"/>
<connect gate="G$1" pin="IO19" pad="31"/>
<connect gate="G$1" pin="NC_32" pad="32"/>
<connect gate="G$1" pin="IO21" pad="33"/>
<connect gate="G$1" pin="RXD0" pad="34"/>
<connect gate="G$1" pin="TXD0" pad="35"/>
<connect gate="G$1" pin="IO22" pad="36"/>
<connect gate="G$1" pin="IO23" pad="37"/>
<connect gate="G$1" pin="GND_38" pad="38"/>
<connect gate="G$1" pin="GND_39" pad="39"/></connects>
<technologies><technology/></technologies></device></devices></deviceset>
<deviceset name="WIZ850IO" prefix="U"><gates><gate name="G$1" symbol="WIZ850IO" x="0" y="0"/></gates>
<devices><device package="WIZ850IO"><connects><connect gate="G$1" pin="GND" pad="1 2 7"/>
<connect gate="G$1" pin="MOSI" pad="3"/>
<connect gate="G$1" pin="SCLK" pad="4"/>
<connect gate="G$1" pin="!SCS" pad="5"/>
<connect gate="G$1" pin="!INT" pad="6"/>
<connect gate="G$1" pin="3V3" pad="8 9"/>
<connect gate="G$1" pin="NC" pad="10"/>
<connect gate="G$1" pin="!RST" pad="11"/>
<connect gate="G$1" pin="MISO" pad="12"/></connects>
<technologies><technology/></technologies></device></devices></deviceset></devicesets></library></libraries>
<attributes/>
<variantdefs/>
<classes><class number="0" name="default" width="0.3048" drill="0"/>
<class number="1" name="mains" width="2.5" drill="0"><clearance class="0" value="8"/>
<clearance class="1" value="8"/>
<clearance class="2" value="8"/></class>
<class number="2" name="power" width="1" drill="0"><clearance class="0" value="0.5"/>
<clearance class="2" value="0.6"/></class></classes>
<parts><part name="J1" library="plc-bridge" deviceset="TERM-3" value="MAINS IN"/>
<part name="F1" library="plc-bridge" deviceset="FUSE" value="T630mA/250V"/>
<part name="MOV1" library="plc-bridge" deviceset="MOV" value="S07K275"/>
<part name="PS1" library="plc-bridge" deviceset="ACDC-5V" value="IRM-05-5"/>
<part name="FB1" library="plc-bridge" deviceset="FERRITE" value="600R@100MHz"/>
<part name="C1" library="plc-bridge" deviceset="CPOL-EU" value="470uF/10V"/>
<part name="TP1" library="plc-bridge" deviceset="TP" value="+5V"/>
<part name="TP2" library="plc-bridge" deviceset="TP" value="GND"/>
<part name="TP3" library="plc-bridge" deviceset="TP" value="PE"/>
<part name="U1" library="plc-bridge" deviceset="BUCK-3V3" value="LM2576S-3.3"/>
<part name="L1" library="plc-bridge" deviceset="L-RADIAL" value="100uH/3A"/>
<part name="D1" library="plc-bridge" deviceset="DIODE-SCH" value="SS34"/>
<part name="C2" library="plc-bridge" deviceset="CPOL-EU" value="470uF/10V"/>
<part name="C3" library="plc-bridge" deviceset="CPOL-EU" value="220uF/10V"/>
<part name="C4" library="plc-bridge" deviceset="C-0603" value="100nF"/>
<part name="TP4" library="plc-bridge" deviceset="TP" value="+3V3"/>
<part name="R1" library="plc-bridge" deviceset="R-EU" value="1k0"/>
<part name="LED1" library="plc-bridge" deviceset="LED" value="PWR green"/>
<part name="U2" library="plc-bridge" deviceset="PLC-STAMP-MINI-2" value="I2PLCBMN-ISC-004-T"/>
<part name="R2" library="plc-bridge" deviceset="R-EU" value="10k"/>
<part name="R5" library="plc-bridge" deviceset="R-EU" value="3k3"/>
<part name="LED2" library="plc-bridge" deviceset="LED" value="PLC link"/>
<part name="R6" library="plc-bridge" deviceset="R-EU" value="3k3"/>
<part name="LED3" library="plc-bridge" deviceset="LED" value="PAIR amber"/>
<part name="R4" library="plc-bridge" deviceset="R-EU" value="10k"/>
<part name="R3" library="plc-bridge" deviceset="R-EU" value="100R"/>
<part name="C5" library="plc-bridge" deviceset="C-EU" value="100pF"/>
<part name="SW3" library="plc-bridge" deviceset="SW-PUSH" value="PAIR"/>
<part name="U3" library="plc-bridge" deviceset="ESP32-WROOM-32E" value="ESP32-WROOM-32E"/>
<part name="C6" library="plc-bridge" deviceset="C-0603" value="100nF"/>
<part name="C7" library="plc-bridge" deviceset="C-0603" value="100nF"/>
<part name="R7" library="plc-bridge" deviceset="R-EU" value="10k"/>
<part name="R8" library="plc-bridge" deviceset="R-EU" value="10k"/>
<part name="R10" library="plc-bridge" deviceset="R-EU" value="10k"/>
<part name="SW1" library="plc-bridge" deviceset="SW-PUSH" value="RESET"/>
<part name="SW2" library="plc-bridge" deviceset="SW-PUSH" value="BOOT"/>
<part name="J2" library="plc-bridge" deviceset="HDR-2X5" value="PROG"/>
<part name="U4" library="plc-bridge" deviceset="WIZ850IO" value="WIZ850io"/>
<part name="R9" library="plc-bridge" deviceset="R-EU" value="10k"/>
<part name="C8" library="plc-bridge" deviceset="C-0603" value="100nF"/>
<part name="TP5" library="plc-bridge" deviceset="TP" value="PLC RESET"/></parts>
<sheets><sheet><plain><text x="20" y="452" size="3.4" layer="97" ratio="8">Powerline Bridge — HomePlug Green PHY (QCA7005) on the mains wiring, bridged to 10/100 Ethernet by an ESP32</text>
<text x="20" y="444" size="2.2" layer="97" ratio="8">MAINS (row A): L → F1 → PS1.1 and → U2 pin 16/17 (L); N → PS1.2 and U2 pin 15 (N). MOV1 across L-N after the fuse. PE is not bonded to SELV ground.</text>
<text x="20" y="439" size="2.2" layer="97" ratio="8">U2 is a chargebyte PLC Stamp mini 2, order code I2PLCBMN-ISC-004-T: QCA7005, SPI, transformer 1:4:5 and zero-cross on the module (§12.1).</text>
<text x="20" y="434" size="2.2" layer="97" ratio="8">Isolation is inside U2 — 4000 Vac, 8 mm creepage / 6.5 mm clearance between L/N and everything else (§8.3). This board keeps 8.0 mm, checked by --check.</text>
<text x="20" y="429" size="2.2" layer="97" ratio="8">AUTOMOTIVE VARIANTS (I2PLCBMN-ISE/ISP-*) ARE NOT FOR MAINS (§12.2): they tie pins 16/17 to GND and couple through pin 15 only. Do not fit one here.</text>
<text x="20" y="296" size="2.2" layer="97" ratio="8">SERIAL_x roles (§10.2 table 6): 0 INT, 1 CLK, 2 CS, 3 MISO, 4 MOSI. SPI Motorola mode 3 (CPOL=1, CPHA=1), CS held low for the whole message, max 12 MHz.</text>
<text x="20" y="291" size="2.2" layer="97" ratio="8">GPIO boot straps (§10.1 table 4): GPIO_0 boot source, GPIO_1 host interface (10 kΩ pull-down preloaded on the module), GPIO_2 SPI burst/legacy, GPIO_3 none.</text>
<text x="20" y="286" size="2.2" layer="97" ratio="8">After boot (§10.1 table 5): GPIO_0 = PLC link LED, GPIO_1 = Simple Connect blink, GPIO_3 = pushbutton (0.5-3 s pair, 5-8 s NMK, 10-15 s factory defaults).</text>
<text x="20" y="281" size="2.2" layer="97" ratio="8">LED bootstrap is 3.3 kΩ in series (figure 3); switch bootstrap is 100 Ω series + 10 kΩ pull-up + 100 pF across the switch (figure 4).</text>
<text x="20" y="176" size="2.2" layer="97" ratio="8">U3 is the SPI master on two buses: HSPI → U2 (the modem is a SPI slave), VSPI → U4 (WIZ850io). IO15 carries a 10 kΩ pull-down because it is a strapping pin.</text>
<text x="20" y="171" size="2.2" layer="97" ratio="8">Firmware precedent: qca/open-plc-utils (plctool/slac) and uhi22/wt32eth01-ethernet-to-qca7000-bridge, which bridges a QCA7000 SPI slave to Ethernet frames.</text>
<text x="20" y="100" size="2.2" layer="97" ratio="8">Green PHY is 10 Mbit/s and shares the medium with HomePlug AV/AV2; it does NOT interoperate with ITU-T G.hn (different FEC: turbo coding vs LDPC).</text>
<frame x1="0" y1="0" x2="480" y2="460" columns="8" rows="6" layer="91" border-left="yes" border-top="yes" border-right="yes" border-bottom="yes"/>
<text x="290" y="8" size="2.2" layer="97">Powerline Bridge rev A · sheet 1/1 · generated from tools/plc-bridge-model.mjs · see docs/wimax-pi-powerline-variants-2026-10-08.md</text></plain>
<instances><instance part="J1" gate="G$1" x="40" y="430" smashed="yes" rot="R0"><attribute name="NAME" x="32.38" y="441.16" size="1.778" layer="95"/>
<attribute name="VALUE" x="32.38" y="415.97" size="1.778" layer="96"/></instance>
<instance part="F1" gate="G$1" x="110" y="430" smashed="yes" rot="R0"><attribute name="NAME" x="104.92" y="433.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="104.92" y="423.59" size="1.778" layer="96"/></instance>
<instance part="MOV1" gate="G$1" x="180" y="430" smashed="yes" rot="R0"><attribute name="NAME" x="174.92" y="433.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="174.92" y="423.59" size="1.778" layer="96"/></instance>
<instance part="PS1" gate="G$1" x="260" y="430" smashed="yes" rot="R0"><attribute name="NAME" x="247.3" y="436.08" size="1.778" layer="95"/>
<attribute name="VALUE" x="247.3" y="421.05" size="1.778" layer="96"/></instance>
<instance part="FB1" gate="G$1" x="40" y="380" smashed="yes" rot="R0"><attribute name="NAME" x="34.92" y="383.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="34.92" y="373.59" size="1.778" layer="96"/></instance>
<instance part="C1" gate="G$1" x="100" y="380" smashed="yes" rot="R0"><attribute name="NAME" x="94.92" y="383.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="94.92" y="373.59" size="1.778" layer="96"/></instance>
<instance part="TP1" gate="G$1" x="160" y="380" smashed="yes" rot="R0"><attribute name="NAME" x="158.73" y="383.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="158.73" y="373.59" size="1.778" layer="96"/></instance>
<instance part="TP2" gate="G$1" x="210" y="380" smashed="yes" rot="R0"><attribute name="NAME" x="208.73" y="383.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="208.73" y="373.59" size="1.778" layer="96"/></instance>
<instance part="TP3" gate="G$1" x="350" y="430" smashed="yes" rot="R0"><attribute name="NAME" x="348.73" y="433.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="348.73" y="423.59" size="1.778" layer="96"/></instance>
<instance part="U1" gate="G$1" x="50" y="330" smashed="yes" rot="R0"><attribute name="NAME" x="39.84" y="336.08" size="1.778" layer="95"/>
<attribute name="VALUE" x="39.84" y="321.05" size="1.778" layer="96"/></instance>
<instance part="L1" gate="G$1" x="130" y="330" smashed="yes" rot="R0"><attribute name="NAME" x="119.84" y="334.81" size="1.778" layer="95"/>
<attribute name="VALUE" x="119.84" y="322.32" size="1.778" layer="96"/></instance>
<instance part="D1" gate="G$1" x="200" y="330" smashed="yes" rot="R0"><attribute name="NAME" x="192.38" y="334.81" size="1.778" layer="95"/>
<attribute name="VALUE" x="192.38" y="322.32" size="1.778" layer="96"/></instance>
<instance part="C2" gate="G$1" x="265" y="330" smashed="yes" rot="R0"><attribute name="NAME" x="259.92" y="333.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="259.92" y="323.59" size="1.778" layer="96"/></instance>
<instance part="C3" gate="G$1" x="325" y="330" smashed="yes" rot="R0"><attribute name="NAME" x="319.92" y="333.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="319.92" y="323.59" size="1.778" layer="96"/></instance>
<instance part="C4" gate="G$1" x="385" y="330" smashed="yes" rot="R0"><attribute name="NAME" x="379.92" y="333.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="379.92" y="323.59" size="1.778" layer="96"/></instance>
<instance part="TP4" gate="G$1" x="435" y="330" smashed="yes" rot="R0"><attribute name="NAME" x="433.73" y="333.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="433.73" y="323.59" size="1.778" layer="96"/></instance>
<instance part="R1" gate="G$1" x="200" y="25" smashed="yes" rot="R0"><attribute name="NAME" x="194.92" y="28.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="194.92" y="18.59" size="1.778" layer="96"/></instance>
<instance part="LED1" gate="G$1" x="255" y="25" smashed="yes" rot="R0"><attribute name="NAME" x="249.92" y="29.07" size="1.778" layer="95"/>
<attribute name="VALUE" x="249.92" y="18.59" size="1.778" layer="96"/></instance>
<instance part="U2" gate="G$1" x="70" y="255" smashed="yes" rot="R0"><attribute name="NAME" x="54.76" y="272.51" size="1.778" layer="95"/>
<attribute name="VALUE" x="54.76" y="234.62" size="1.778" layer="96"/></instance>
<instance part="R2" gate="G$1" x="160" y="255" smashed="yes" rot="R0"><attribute name="NAME" x="154.92" y="258.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="154.92" y="248.59" size="1.778" layer="96"/></instance>
<instance part="R5" gate="G$1" x="215" y="255" smashed="yes" rot="R0"><attribute name="NAME" x="209.92" y="258.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="209.92" y="248.59" size="1.778" layer="96"/></instance>
<instance part="LED2" gate="G$1" x="270" y="255" smashed="yes" rot="R0"><attribute name="NAME" x="264.92" y="259.07" size="1.778" layer="95"/>
<attribute name="VALUE" x="264.92" y="248.59" size="1.778" layer="96"/></instance>
<instance part="R6" gate="G$1" x="325" y="255" smashed="yes" rot="R0"><attribute name="NAME" x="319.92" y="258.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="319.92" y="248.59" size="1.778" layer="96"/></instance>
<instance part="LED3" gate="G$1" x="380" y="255" smashed="yes" rot="R0"><attribute name="NAME" x="374.92" y="259.07" size="1.778" layer="95"/>
<attribute name="VALUE" x="374.92" y="248.59" size="1.778" layer="96"/></instance>
<instance part="R4" gate="G$1" x="435" y="255" smashed="yes" rot="R0"><attribute name="NAME" x="429.92" y="258.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="429.92" y="248.59" size="1.778" layer="96"/></instance>
<instance part="R3" gate="G$1" x="160" y="215" smashed="yes" rot="R0"><attribute name="NAME" x="154.92" y="218.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="154.92" y="208.59" size="1.778" layer="96"/></instance>
<instance part="C5" gate="G$1" x="215" y="215" smashed="yes" rot="R0"><attribute name="NAME" x="209.92" y="218.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="209.92" y="208.59" size="1.778" layer="96"/></instance>
<instance part="SW3" gate="G$1" x="270" y="215" smashed="yes" rot="R0"><attribute name="NAME" x="264.92" y="219.81" size="1.778" layer="95"/>
<attribute name="VALUE" x="264.92" y="207.32" size="1.778" layer="96"/></instance>
<instance part="U3" gate="G$1" x="70" y="140" smashed="yes" rot="R0"><attribute name="NAME" x="52.22" y="170.21" size="1.778" layer="95"/>
<attribute name="VALUE" x="52.22" y="106.92" size="1.778" layer="96"/></instance>
<instance part="C6" gate="G$1" x="40" y="70" smashed="yes" rot="R0"><attribute name="NAME" x="34.92" y="73.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="34.92" y="63.59" size="1.778" layer="96"/></instance>
<instance part="C7" gate="G$1" x="95" y="70" smashed="yes" rot="R0"><attribute name="NAME" x="89.92" y="73.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="89.92" y="63.59" size="1.778" layer="96"/></instance>
<instance part="R7" gate="G$1" x="150" y="70" smashed="yes" rot="R0"><attribute name="NAME" x="144.92" y="73.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="144.92" y="63.59" size="1.778" layer="96"/></instance>
<instance part="R8" gate="G$1" x="205" y="70" smashed="yes" rot="R0"><attribute name="NAME" x="199.92" y="73.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="199.92" y="63.59" size="1.778" layer="96"/></instance>
<instance part="R10" gate="G$1" x="260" y="70" smashed="yes" rot="R0"><attribute name="NAME" x="254.92" y="73.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="254.92" y="63.59" size="1.778" layer="96"/></instance>
<instance part="SW1" gate="G$1" x="315" y="70" smashed="yes" rot="R0"><attribute name="NAME" x="309.92" y="74.81" size="1.778" layer="95"/>
<attribute name="VALUE" x="309.92" y="62.32" size="1.778" layer="96"/></instance>
<instance part="SW2" gate="G$1" x="370" y="70" smashed="yes" rot="R0"><attribute name="NAME" x="364.92" y="74.81" size="1.778" layer="95"/>
<attribute name="VALUE" x="364.92" y="62.32" size="1.778" layer="96"/></instance>
<instance part="J2" gate="G$1" x="50" y="25" smashed="yes" rot="R0"><attribute name="NAME" x="38.57" y="34.89" size="1.778" layer="95"/>
<attribute name="VALUE" x="38.57" y="12.24" size="1.778" layer="96"/></instance>
<instance part="U4" gate="G$1" x="250" y="140" smashed="yes" rot="R0"><attribute name="NAME" x="238.57" y="151.16" size="1.778" layer="95"/>
<attribute name="VALUE" x="238.57" y="125.97" size="1.778" layer="96"/></instance>
<instance part="R9" gate="G$1" x="130" y="25" smashed="yes" rot="R0"><attribute name="NAME" x="124.92" y="28.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="124.92" y="18.59" size="1.778" layer="96"/></instance>
<instance part="C8" gate="G$1" x="425" y="70" smashed="yes" rot="R0"><attribute name="NAME" x="419.92" y="73.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="419.92" y="63.59" size="1.778" layer="96"/></instance>
<instance part="TP5" gate="G$1" x="330" y="215" smashed="yes" rot="R0"><attribute name="NAME" x="328.73" y="218.54" size="1.778" layer="95"/>
<attribute name="VALUE" x="328.73" y="208.59" size="1.778" layer="96"/></instance></instances>
<busses/>
<nets><net name="AC_L" class="1"><segment><pinref part="J1" gate="G$1" pin="1"/>
<wire x1="32.38" y1="435.08" x2="27.3" y2="435.08" width="0.1524" layer="91"/>
<label x="27.3" y="435.08" size="1.778" layer="95" rot="R0"/>
<pinref part="F1" gate="G$1" pin="1"/>
<wire x1="104.92" y1="430" x2="99.84" y2="430" width="0.1524" layer="91"/>
<label x="99.84" y="430" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="AC_L_F" class="1"><segment><pinref part="F1" gate="G$1" pin="2"/>
<wire x1="115.08" y1="430" x2="120.16" y2="430" width="0.1524" layer="91"/>
<label x="120.16" y="430" size="1.778" layer="95" rot="R0"/>
<pinref part="PS1" gate="G$1" pin="AC-L"/>
<wire x1="247.3" y1="431.27" x2="242.22" y2="431.27" width="0.1524" layer="91"/>
<label x="242.22" y="431.27" size="1.778" layer="95" rot="R0"/>
<pinref part="MOV1" gate="G$1" pin="1"/>
<wire x1="174.92" y1="430" x2="169.84" y2="430" width="0.1524" layer="91"/>
<label x="169.84" y="430" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="L"/>
<wire x1="85.24" y1="262.62" x2="90.32" y2="262.62" width="0.1524" layer="91"/>
<label x="90.32" y="262.62" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="AC_N" class="1"><segment><pinref part="J1" gate="G$1" pin="2"/>
<wire x1="32.38" y1="430" x2="27.3" y2="430" width="0.1524" layer="91"/>
<label x="27.3" y="430" size="1.778" layer="95" rot="R0"/>
<pinref part="PS1" gate="G$1" pin="AC-N"/>
<wire x1="247.3" y1="428.73" x2="242.22" y2="428.73" width="0.1524" layer="91"/>
<label x="242.22" y="428.73" size="1.778" layer="95" rot="R0"/>
<pinref part="MOV1" gate="G$1" pin="2"/>
<wire x1="185.08" y1="430" x2="190.16" y2="430" width="0.1524" layer="91"/>
<label x="190.16" y="430" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="N"/>
<wire x1="85.24" y1="265.16" x2="90.32" y2="265.16" width="0.1524" layer="91"/>
<label x="90.32" y="265.16" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="PE" class="1"><segment><pinref part="J1" gate="G$1" pin="3"/>
<wire x1="32.38" y1="424.92" x2="27.3" y2="424.92" width="0.1524" layer="91"/>
<label x="27.3" y="424.92" size="1.778" layer="95" rot="R0"/>
<pinref part="TP3" gate="G$1" pin="1"/>
<wire x1="350" y1="426.19" x2="350" y2="421.11" width="0.1524" layer="91"/>
<label x="350" y="421.11" size="1.778" layer="95" rot="R270"/></segment></net>
<net name="5V_P" class="2"><segment><pinref part="PS1" gate="G$1" pin="+VO"/>
<wire x1="272.7" y1="431.27" x2="277.78" y2="431.27" width="0.1524" layer="91"/>
<label x="277.78" y="431.27" size="1.778" layer="95" rot="R0"/>
<pinref part="FB1" gate="G$1" pin="1"/>
<wire x1="34.92" y1="380" x2="29.84" y2="380" width="0.1524" layer="91"/>
<label x="29.84" y="380" size="1.778" layer="95" rot="R0"/>
<pinref part="C1" gate="G$1" pin="+"/>
<wire x1="94.92" y1="380" x2="89.84" y2="380" width="0.1524" layer="91"/>
<label x="89.84" y="380" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="GND" class="2"><segment><pinref part="PS1" gate="G$1" pin="-VO"/>
<wire x1="272.7" y1="428.73" x2="277.78" y2="428.73" width="0.1524" layer="91"/>
<label x="277.78" y="428.73" size="1.778" layer="95" rot="R0"/>
<pinref part="C1" gate="G$1" pin="-"/>
<wire x1="105.08" y1="380" x2="110.16" y2="380" width="0.1524" layer="91"/>
<label x="110.16" y="380" size="1.778" layer="95" rot="R0"/>
<pinref part="TP2" gate="G$1" pin="1"/>
<wire x1="210" y1="376.19" x2="210" y2="371.11" width="0.1524" layer="91"/>
<label x="210" y="371.11" size="1.778" layer="95" rot="R270"/>
<pinref part="U1" gate="G$1" pin="GND"/>
<wire x1="50" y1="326.19" x2="50" y2="321.11" width="0.1524" layer="91"/>
<label x="50" y="321.11" size="1.778" layer="95" rot="R270"/>
<pinref part="U1" gate="G$1" pin="ONOFF"/>
<wire x1="60.16" y1="328.73" x2="65.24" y2="328.73" width="0.1524" layer="91"/>
<label x="65.24" y="328.73" size="1.778" layer="95" rot="R0"/>
<pinref part="C2" gate="G$1" pin="-"/>
<wire x1="270.08" y1="330" x2="275.16" y2="330" width="0.1524" layer="91"/>
<label x="275.16" y="330" size="1.778" layer="95" rot="R0"/>
<pinref part="C3" gate="G$1" pin="-"/>
<wire x1="330.08" y1="330" x2="335.16" y2="330" width="0.1524" layer="91"/>
<label x="335.16" y="330" size="1.778" layer="95" rot="R0"/>
<pinref part="C4" gate="G$1" pin="2"/>
<wire x1="390.08" y1="330" x2="395.16" y2="330" width="0.1524" layer="91"/>
<label x="395.16" y="330" size="1.778" layer="95" rot="R0"/>
<pinref part="D1" gate="G$1" pin="A"/>
<wire x1="192.38" y1="330" x2="187.3" y2="330" width="0.1524" layer="91"/>
<label x="187.3" y="330" size="1.778" layer="95" rot="R0"/>
<pinref part="LED1" gate="G$1" pin="K"/>
<wire x1="260.08" y1="25" x2="265.16" y2="25" width="0.1524" layer="91"/>
<label x="265.16" y="25" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="GND"/>
<wire x1="70" y1="239.76" x2="70" y2="234.68" width="0.1524" layer="91"/>
<label x="70" y="234.68" size="1.778" layer="95" rot="R270"/>
<pinref part="LED2" gate="G$1" pin="K"/>
<wire x1="275.08" y1="255" x2="280.16" y2="255" width="0.1524" layer="91"/>
<label x="280.16" y="255" size="1.778" layer="95" rot="R0"/>
<pinref part="LED3" gate="G$1" pin="K"/>
<wire x1="385.08" y1="255" x2="390.16" y2="255" width="0.1524" layer="91"/>
<label x="390.16" y="255" size="1.778" layer="95" rot="R0"/>
<pinref part="SW3" gate="G$1" pin="2"/>
<wire x1="275.08" y1="215" x2="280.16" y2="215" width="0.1524" layer="91"/>
<label x="280.16" y="215" size="1.778" layer="95" rot="R0"/>
<pinref part="C5" gate="G$1" pin="2"/>
<wire x1="220.08" y1="215" x2="225.16" y2="215" width="0.1524" layer="91"/>
<label x="225.16" y="215" size="1.778" layer="95" rot="R0"/>
<pinref part="R2" gate="G$1" pin="2"/>
<wire x1="165.08" y1="255" x2="170.16" y2="255" width="0.1524" layer="91"/>
<label x="170.16" y="255" size="1.778" layer="95" rot="R0"/>
<pinref part="R10" gate="G$1" pin="2"/>
<wire x1="265.08" y1="70" x2="270.16" y2="70" width="0.1524" layer="91"/>
<label x="270.16" y="70" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="GND_1"/>
<wire x1="87.78" y1="122.22" x2="92.86" y2="122.22" width="0.1524" layer="91"/>
<label x="92.86" y="122.22" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="GND_15"/>
<wire x1="52.22" y1="132.38" x2="47.14" y2="132.38" width="0.1524" layer="91"/>
<label x="47.14" y="132.38" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="GND_38"/>
<wire x1="87.78" y1="152.7" x2="92.86" y2="152.7" width="0.1524" layer="91"/>
<label x="92.86" y="152.7" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="GND_39"/>
<wire x1="87.78" y1="150.16" x2="92.86" y2="150.16" width="0.1524" layer="91"/>
<label x="92.86" y="150.16" size="1.778" layer="95" rot="R0"/>
<pinref part="C6" gate="G$1" pin="2"/>
<wire x1="45.08" y1="70" x2="50.16" y2="70" width="0.1524" layer="91"/>
<label x="50.16" y="70" size="1.778" layer="95" rot="R0"/>
<pinref part="C7" gate="G$1" pin="2"/>
<wire x1="100.08" y1="70" x2="105.16" y2="70" width="0.1524" layer="91"/>
<label x="105.16" y="70" size="1.778" layer="95" rot="R0"/>
<pinref part="SW1" gate="G$1" pin="2"/>
<wire x1="320.08" y1="70" x2="325.16" y2="70" width="0.1524" layer="91"/>
<label x="325.16" y="70" size="1.778" layer="95" rot="R0"/>
<pinref part="SW2" gate="G$1" pin="2"/>
<wire x1="375.08" y1="70" x2="380.16" y2="70" width="0.1524" layer="91"/>
<label x="380.16" y="70" size="1.778" layer="95" rot="R0"/>
<pinref part="J2" gate="G$1" pin="2"/>
<wire x1="61.43" y1="30.08" x2="66.51" y2="30.08" width="0.1524" layer="91"/>
<label x="66.51" y="30.08" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="GND"/>
<wire x1="250" y1="131.11" x2="250" y2="126.03" width="0.1524" layer="91"/>
<label x="250" y="126.03" size="1.778" layer="95" rot="R270"/>
<pinref part="C8" gate="G$1" pin="2"/>
<wire x1="430.08" y1="70" x2="435.16" y2="70" width="0.1524" layer="91"/>
<label x="435.16" y="70" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="5V" class="2"><segment><pinref part="FB1" gate="G$1" pin="2"/>
<wire x1="45.08" y1="380" x2="50.16" y2="380" width="0.1524" layer="91"/>
<label x="50.16" y="380" size="1.778" layer="95" rot="R0"/>
<pinref part="TP1" gate="G$1" pin="1"/>
<wire x1="160" y1="376.19" x2="160" y2="371.11" width="0.1524" layer="91"/>
<label x="160" y="371.11" size="1.778" layer="95" rot="R270"/>
<pinref part="U1" gate="G$1" pin="VIN"/>
<wire x1="39.84" y1="331.27" x2="34.76" y2="331.27" width="0.1524" layer="91"/>
<label x="34.76" y="331.27" size="1.778" layer="95" rot="R0"/>
<pinref part="C2" gate="G$1" pin="+"/>
<wire x1="259.92" y1="330" x2="254.84" y2="330" width="0.1524" layer="91"/>
<label x="254.84" y="330" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="SW_3V3" class="2"><segment><pinref part="U1" gate="G$1" pin="VOUT"/>
<wire x1="60.16" y1="331.27" x2="65.24" y2="331.27" width="0.1524" layer="91"/>
<label x="65.24" y="331.27" size="1.778" layer="95" rot="R0"/>
<pinref part="L1" gate="G$1" pin="1"/>
<wire x1="119.84" y1="330" x2="114.76" y2="330" width="0.1524" layer="91"/>
<label x="114.76" y="330" size="1.778" layer="95" rot="R0"/>
<pinref part="D1" gate="G$1" pin="K"/>
<wire x1="207.62" y1="330" x2="212.7" y2="330" width="0.1524" layer="91"/>
<label x="212.7" y="330" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="3V3" class="2"><segment><pinref part="L1" gate="G$1" pin="2"/>
<wire x1="140.16" y1="330" x2="145.24" y2="330" width="0.1524" layer="91"/>
<label x="145.24" y="330" size="1.778" layer="95" rot="R0"/>
<pinref part="C3" gate="G$1" pin="+"/>
<wire x1="319.92" y1="330" x2="314.84" y2="330" width="0.1524" layer="91"/>
<label x="314.84" y="330" size="1.778" layer="95" rot="R0"/>
<pinref part="C4" gate="G$1" pin="1"/>
<wire x1="379.92" y1="330" x2="374.84" y2="330" width="0.1524" layer="91"/>
<label x="374.84" y="330" size="1.778" layer="95" rot="R0"/>
<pinref part="TP4" gate="G$1" pin="1"/>
<wire x1="435" y1="326.19" x2="435" y2="321.11" width="0.1524" layer="91"/>
<label x="435" y="321.11" size="1.778" layer="95" rot="R270"/>
<pinref part="U2" gate="G$1" pin="VDD"/>
<wire x1="85.24" y1="267.7" x2="90.32" y2="267.7" width="0.1524" layer="91"/>
<label x="90.32" y="267.7" size="1.778" layer="95" rot="R0"/>
<pinref part="R4" gate="G$1" pin="1"/>
<wire x1="429.92" y1="255" x2="424.84" y2="255" width="0.1524" layer="91"/>
<label x="424.84" y="255" size="1.778" layer="95" rot="R0"/>
<pinref part="R7" gate="G$1" pin="2"/>
<wire x1="155.08" y1="70" x2="160.16" y2="70" width="0.1524" layer="91"/>
<label x="160.16" y="70" size="1.778" layer="95" rot="R0"/>
<pinref part="R8" gate="G$1" pin="2"/>
<wire x1="210.08" y1="70" x2="215.16" y2="70" width="0.1524" layer="91"/>
<label x="215.16" y="70" size="1.778" layer="95" rot="R0"/>
<pinref part="R9" gate="G$1" pin="1"/>
<wire x1="124.92" y1="25" x2="119.84" y2="25" width="0.1524" layer="91"/>
<label x="119.84" y="25" size="1.778" layer="95" rot="R0"/>
<pinref part="U3" gate="G$1" pin="VDD"/>
<wire x1="52.22" y1="165.4" x2="47.14" y2="165.4" width="0.1524" layer="91"/>
<label x="47.14" y="165.4" size="1.778" layer="95" rot="R0"/>
<pinref part="C7" gate="G$1" pin="1"/>
<wire x1="89.92" y1="70" x2="84.84" y2="70" width="0.1524" layer="91"/>
<label x="84.84" y="70" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="3V3"/>
<wire x1="261.43" y1="146.35" x2="266.51" y2="146.35" width="0.1524" layer="91"/>
<label x="266.51" y="146.35" size="1.778" layer="95" rot="R0"/>
<pinref part="C8" gate="G$1" pin="1"/>
<wire x1="419.92" y1="70" x2="414.84" y2="70" width="0.1524" layer="91"/>
<label x="414.84" y="70" size="1.778" layer="95" rot="R0"/>
<pinref part="J2" gate="G$1" pin="1"/>
<wire x1="38.57" y1="30.08" x2="33.49" y2="30.08" width="0.1524" layer="91"/>
<label x="33.49" y="30.08" size="1.778" layer="95" rot="R0"/>
<pinref part="R1" gate="G$1" pin="1"/>
<wire x1="194.92" y1="25" x2="189.84" y2="25" width="0.1524" layer="91"/>
<label x="189.84" y="25" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="LED_A" class="0"><segment><pinref part="R1" gate="G$1" pin="2"/>
<wire x1="205.08" y1="25" x2="210.16" y2="25" width="0.1524" layer="91"/>
<label x="210.16" y="25" size="1.778" layer="95" rot="R0"/>
<pinref part="LED1" gate="G$1" pin="A"/>
<wire x1="249.92" y1="25" x2="244.84" y2="25" width="0.1524" layer="91"/>
<label x="244.84" y="25" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="PLC_SCLK" class="0"><segment><pinref part="U3" gate="G$1" pin="IO14"/>
<wire x1="52.22" y1="137.46" x2="47.14" y2="137.46" width="0.1524" layer="91"/>
<label x="47.14" y="137.46" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="SERIAL_1"/>
<wire x1="54.76" y1="247.38" x2="49.68" y2="247.38" width="0.1524" layer="91"/>
<label x="49.68" y="247.38" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="PLC_MISO" class="0"><segment><pinref part="U3" gate="G$1" pin="IO12"/>
<wire x1="52.22" y1="134.92" x2="47.14" y2="134.92" width="0.1524" layer="91"/>
<label x="47.14" y="134.92" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="SERIAL_3"/>
<wire x1="54.76" y1="252.46" x2="49.68" y2="252.46" width="0.1524" layer="91"/>
<label x="49.68" y="252.46" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="PLC_MOSI" class="0"><segment><pinref part="U3" gate="G$1" pin="IO13"/>
<wire x1="52.22" y1="129.84" x2="47.14" y2="129.84" width="0.1524" layer="91"/>
<label x="47.14" y="129.84" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="SERIAL_4"/>
<wire x1="54.76" y1="255" x2="49.68" y2="255" width="0.1524" layer="91"/>
<label x="49.68" y="255" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="PLC_CS" class="0"><segment><pinref part="U3" gate="G$1" pin="IO15"/>
<wire x1="87.78" y1="124.76" x2="92.86" y2="124.76" width="0.1524" layer="91"/>
<label x="92.86" y="124.76" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="SERIAL_2"/>
<wire x1="54.76" y1="249.92" x2="49.68" y2="249.92" width="0.1524" layer="91"/>
<label x="49.68" y="249.92" size="1.778" layer="95" rot="R0"/>
<pinref part="R10" gate="G$1" pin="1"/>
<wire x1="254.92" y1="70" x2="249.84" y2="70" width="0.1524" layer="91"/>
<label x="249.84" y="70" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="PLC_INT" class="0"><segment><pinref part="U3" gate="G$1" pin="IO4"/>
<wire x1="87.78" y1="132.38" x2="92.86" y2="132.38" width="0.1524" layer="91"/>
<label x="92.86" y="132.38" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="SERIAL_0"/>
<wire x1="54.76" y1="244.84" x2="49.68" y2="244.84" width="0.1524" layer="91"/>
<label x="49.68" y="244.84" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="PLC_RESET" class="0"><segment><pinref part="U3" gate="G$1" pin="IO32"/>
<wire x1="52.22" y1="150.16" x2="47.14" y2="150.16" width="0.1524" layer="91"/>
<label x="47.14" y="150.16" size="1.778" layer="95" rot="R0"/>
<pinref part="U2" gate="G$1" pin="RESET_L"/>
<wire x1="54.76" y1="257.54" x2="49.68" y2="257.54" width="0.1524" layer="91"/>
<label x="49.68" y="257.54" size="1.778" layer="95" rot="R0"/>
<pinref part="TP5" gate="G$1" pin="1"/>
<wire x1="330" y1="211.19" x2="330" y2="206.11" width="0.1524" layer="91"/>
<label x="330" y="206.11" size="1.778" layer="95" rot="R270"/></segment></net>
<net name="PLC_GPIO0" class="0"><segment><pinref part="U2" gate="G$1" pin="GPIO_0"/>
<wire x1="54.76" y1="267.7" x2="49.68" y2="267.7" width="0.1524" layer="91"/>
<label x="49.68" y="267.7" size="1.778" layer="95" rot="R0"/>
<pinref part="R5" gate="G$1" pin="1"/>
<wire x1="209.92" y1="255" x2="204.84" y2="255" width="0.1524" layer="91"/>
<label x="204.84" y="255" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="LED2_A" class="0"><segment><pinref part="R5" gate="G$1" pin="2"/>
<wire x1="220.08" y1="255" x2="225.16" y2="255" width="0.1524" layer="91"/>
<label x="225.16" y="255" size="1.778" layer="95" rot="R0"/>
<pinref part="LED2" gate="G$1" pin="A"/>
<wire x1="264.92" y1="255" x2="259.84" y2="255" width="0.1524" layer="91"/>
<label x="259.84" y="255" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="PLC_GPIO1" class="0"><segment><pinref part="U2" gate="G$1" pin="GPIO_1"/>
<wire x1="54.76" y1="265.16" x2="49.68" y2="265.16" width="0.1524" layer="91"/>
<label x="49.68" y="265.16" size="1.778" layer="95" rot="R0"/>
<pinref part="R6" gate="G$1" pin="1"/>
<wire x1="319.92" y1="255" x2="314.84" y2="255" width="0.1524" layer="91"/>
<label x="314.84" y="255" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="LED3_A" class="0"><segment><pinref part="R6" gate="G$1" pin="2"/>
<wire x1="330.08" y1="255" x2="335.16" y2="255" width="0.1524" layer="91"/>
<label x="335.16" y="255" size="1.778" layer="95" rot="R0"/>
<pinref part="LED3" gate="G$1" pin="A"/>
<wire x1="374.92" y1="255" x2="369.84" y2="255" width="0.1524" layer="91"/>
<label x="369.84" y="255" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="PLC_GPIO3" class="0"><segment><pinref part="U2" gate="G$1" pin="GPIO_3"/>
<wire x1="54.76" y1="260.08" x2="49.68" y2="260.08" width="0.1524" layer="91"/>
<label x="49.68" y="260.08" size="1.778" layer="95" rot="R0"/>
<pinref part="R4" gate="G$1" pin="2"/>
<wire x1="440.08" y1="255" x2="445.16" y2="255" width="0.1524" layer="91"/>
<label x="445.16" y="255" size="1.778" layer="95" rot="R0"/>
<pinref part="R3" gate="G$1" pin="2"/>
<wire x1="165.08" y1="215" x2="170.16" y2="215" width="0.1524" layer="91"/>
<label x="170.16" y="215" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="SW3_N" class="0"><segment><pinref part="R3" gate="G$1" pin="1"/>
<wire x1="154.92" y1="215" x2="149.84" y2="215" width="0.1524" layer="91"/>
<label x="149.84" y="215" size="1.778" layer="95" rot="R0"/>
<pinref part="SW3" gate="G$1" pin="1"/>
<wire x1="264.92" y1="215" x2="259.84" y2="215" width="0.1524" layer="91"/>
<label x="259.84" y="215" size="1.778" layer="95" rot="R0"/>
<pinref part="C5" gate="G$1" pin="1"/>
<wire x1="209.92" y1="215" x2="204.84" y2="215" width="0.1524" layer="91"/>
<label x="204.84" y="215" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="ZC_IN" class="0"><segment><pinref part="U2" gate="G$1" pin="ZC_IN"/>
<wire x1="54.76" y1="242.3" x2="49.68" y2="242.3" width="0.1524" layer="91"/>
<label x="49.68" y="242.3" size="1.778" layer="95" rot="R0"/>
<pinref part="R2" gate="G$1" pin="1"/>
<wire x1="154.92" y1="255" x2="149.84" y2="255" width="0.1524" layer="91"/>
<label x="149.84" y="255" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="ETH_SCLK" class="0"><segment><pinref part="U3" gate="G$1" pin="IO18"/>
<wire x1="87.78" y1="142.54" x2="92.86" y2="142.54" width="0.1524" layer="91"/>
<label x="92.86" y="142.54" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="SCLK"/>
<wire x1="238.57" y1="143.81" x2="233.49" y2="143.81" width="0.1524" layer="91"/>
<label x="233.49" y="143.81" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="ETH_MISO" class="0"><segment><pinref part="U3" gate="G$1" pin="IO19"/>
<wire x1="87.78" y1="140" x2="92.86" y2="140" width="0.1524" layer="91"/>
<label x="92.86" y="140" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="MISO"/>
<wire x1="238.57" y1="133.65" x2="233.49" y2="133.65" width="0.1524" layer="91"/>
<label x="233.49" y="133.65" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="ETH_MOSI" class="0"><segment><pinref part="U3" gate="G$1" pin="IO23"/>
<wire x1="87.78" y1="155.24" x2="92.86" y2="155.24" width="0.1524" layer="91"/>
<label x="92.86" y="155.24" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="MOSI"/>
<wire x1="238.57" y1="146.35" x2="233.49" y2="146.35" width="0.1524" layer="91"/>
<label x="233.49" y="146.35" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="ETH_CS" class="0"><segment><pinref part="U3" gate="G$1" pin="IO5"/>
<wire x1="87.78" y1="145.08" x2="92.86" y2="145.08" width="0.1524" layer="91"/>
<label x="92.86" y="145.08" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="!SCS"/>
<wire x1="238.57" y1="141.27" x2="233.49" y2="141.27" width="0.1524" layer="91"/>
<label x="233.49" y="141.27" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="ETH_INT" class="0"><segment><pinref part="U3" gate="G$1" pin="IO33"/>
<wire x1="52.22" y1="147.62" x2="47.14" y2="147.62" width="0.1524" layer="91"/>
<label x="47.14" y="147.62" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="!INT"/>
<wire x1="238.57" y1="138.73" x2="233.49" y2="138.73" width="0.1524" layer="91"/>
<label x="233.49" y="138.73" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="ETH_RST" class="0"><segment><pinref part="U3" gate="G$1" pin="IO26"/>
<wire x1="52.22" y1="142.54" x2="47.14" y2="142.54" width="0.1524" layer="91"/>
<label x="47.14" y="142.54" size="1.778" layer="95" rot="R0"/>
<pinref part="U4" gate="G$1" pin="!RST"/>
<wire x1="238.57" y1="136.19" x2="233.49" y2="136.19" width="0.1524" layer="91"/>
<label x="233.49" y="136.19" size="1.778" layer="95" rot="R0"/>
<pinref part="R9" gate="G$1" pin="2"/>
<wire x1="135.08" y1="25" x2="140.16" y2="25" width="0.1524" layer="91"/>
<label x="140.16" y="25" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="ESP_EN" class="0"><segment><pinref part="U3" gate="G$1" pin="EN"/>
<wire x1="52.22" y1="162.86" x2="47.14" y2="162.86" width="0.1524" layer="91"/>
<label x="47.14" y="162.86" size="1.778" layer="95" rot="R0"/>
<pinref part="R7" gate="G$1" pin="1"/>
<wire x1="144.92" y1="70" x2="139.84" y2="70" width="0.1524" layer="91"/>
<label x="139.84" y="70" size="1.778" layer="95" rot="R0"/>
<pinref part="C6" gate="G$1" pin="1"/>
<wire x1="34.92" y1="70" x2="29.84" y2="70" width="0.1524" layer="91"/>
<label x="29.84" y="70" size="1.778" layer="95" rot="R0"/>
<pinref part="SW1" gate="G$1" pin="1"/>
<wire x1="309.92" y1="70" x2="304.84" y2="70" width="0.1524" layer="91"/>
<label x="304.84" y="70" size="1.778" layer="95" rot="R0"/>
<pinref part="J2" gate="G$1" pin="5"/>
<wire x1="38.57" y1="25" x2="33.49" y2="25" width="0.1524" layer="91"/>
<label x="33.49" y="25" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="ESP_IO0" class="0"><segment><pinref part="U3" gate="G$1" pin="IO0"/>
<wire x1="87.78" y1="129.84" x2="92.86" y2="129.84" width="0.1524" layer="91"/>
<label x="92.86" y="129.84" size="1.778" layer="95" rot="R0"/>
<pinref part="R8" gate="G$1" pin="1"/>
<wire x1="199.92" y1="70" x2="194.84" y2="70" width="0.1524" layer="91"/>
<label x="194.84" y="70" size="1.778" layer="95" rot="R0"/>
<pinref part="SW2" gate="G$1" pin="1"/>
<wire x1="364.92" y1="70" x2="359.84" y2="70" width="0.1524" layer="91"/>
<label x="359.84" y="70" size="1.778" layer="95" rot="R0"/>
<pinref part="J2" gate="G$1" pin="6"/>
<wire x1="61.43" y1="25" x2="66.51" y2="25" width="0.1524" layer="91"/>
<label x="66.51" y="25" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="ESP_TXD0" class="0"><segment><pinref part="U3" gate="G$1" pin="TXD0"/>
<wire x1="87.78" y1="160.32" x2="92.86" y2="160.32" width="0.1524" layer="91"/>
<label x="92.86" y="160.32" size="1.778" layer="95" rot="R0"/>
<pinref part="J2" gate="G$1" pin="3"/>
<wire x1="38.57" y1="27.54" x2="33.49" y2="27.54" width="0.1524" layer="91"/>
<label x="33.49" y="27.54" size="1.778" layer="95" rot="R0"/></segment></net>
<net name="ESP_RXD0" class="0"><segment><pinref part="U3" gate="G$1" pin="RXD0"/>
<wire x1="87.78" y1="162.86" x2="92.86" y2="162.86" width="0.1524" layer="91"/>
<label x="92.86" y="162.86" size="1.778" layer="95" rot="R0"/>
<pinref part="J2" gate="G$1" pin="4"/>
<wire x1="61.43" y1="27.54" x2="66.51" y2="27.54" width="0.1524" layer="91"/>
<label x="66.51" y="27.54" size="1.778" layer="95" rot="R0"/></segment></net></nets></sheet></sheets></schematic>
</drawing>
</eagle>
