/* GENERATED by socal-calc/tools/xdc2c.py from socal-subsurface.xdc — do not edit.
 *
 * Source of truth is the bundle, not this file. Regenerate with:
 *     make -C socal-calc data
 *
 * 20 layers  25 corridors (266 vertices)  77 sites  15 rings (300 vertices)
 * Positions are u16 in units of 1/2000 degree; worst-case quantisation
 * error 27.7 m, against a data pack documented as 5-15 km generalized.
 */

#ifndef SOCALDATA_H
#define SOCALDATA_H

#define SC_NLAYER          20   /* layers, including the two overlay packs */
#define SC_NCOR            25   /* corridors (polylines) */
#define SC_NNODE           77   /* point sites */
#define SC_NRING           15   /* closed rings: fire perimeters + deformation bowls */
#define SC_NPT             266   /* corridor vertices */
#define SC_NRPT            300   /* ring vertices */
#define SC_NCOAST          15   /* coastline vertices */
#define SC_NRELIEF         21   /* gaussian relief control features */
#define SC_NKIND           21   /* distinct node kinds */
#define SC_STRB            4825   /* string pool bytes */
#define SC_Q               2000   /* quantisation units per degree */
#define SC_LON_BASE_M      -121300   /* lon origin, 1/1000 deg */
#define SC_LAT_BASE_M      32500   /* lat origin, 1/1000 deg */
#define SC_SPAN_LON        14320   /* frame width in quant units */
#define SC_SPAN_LAT        11500   /* frame height in quant units */
#define SC_CENTER_LON_M    -117950   /* projection centre, 1/1000 deg */
#define SC_CENTER_LAT_M    34600   /* projection centre, 1/1000 deg */
#define SC_COSLAT_Q12      3372   /* cos(centre latitude) in Q12 */
#define SC_KMDEG_Q4        1781   /* km per degree of latitude, Q4 */
#define SC_TIER_OFFICIAL   0
#define SC_TIER_COMMUNITY  1
#define SC_TIER_CONTEXT    2
#define SC_KIND_SURFACE    0
#define SC_KIND_LINE       1
#define SC_KIND_NODE       2
#define SC_KIND_RING       3

/* elevation + depth field, lifted from the bundle's socal-geo.js */
#define SC_ELEV_BASE       120   /* metres before any relief */
#define SC_EXP_MUL         6
#define SC_EXP_SHIFT       10   /* idx_q4 = (t_q16 * SC_EXP_MUL) >> SC_EXP_SHIFT */
#define SC_FRAC_AMP        45   /* metres per unit of the fractal term */
#define SC_FRAC1_BASE      -22304738   /* Q16 turns at the frame origin */
#define SC_FRAC1_LON_M     113750
#define SC_FRAC1_LON_S     10
#define SC_FRAC1_LAT_M     146326
#define SC_FRAC1_LAT_S     11
#define SC_FRAC2_BASE      -22157566
#define SC_FRAC2_LON_M     97194
#define SC_FRAC2_LON_S     11
#define SC_FRAC2_LAT_M     -83844
#define SC_FRAC2_LAT_S     9
#define SC_DEPTH_A_Q8      90   /* depthY: mag = a + b*log10(1+|m|) */
#define SC_DEPTH_B_Q8      115

/* string-pool offsets for the UI chrome */
#define SL_TITLE           4386
#define SL_SUB             4403
#define SL_SOCAL           4420
#define SL_SUBSURF         4426
#define SL_PRESS           4437
#define SL_MAP             4451
#define SL_PROF            4455
#define SL_LAYERS          4463
#define SL_DOS             4470
#define SL_INFO            4478
#define SL_OFFICIAL        4485
#define SL_COMMUNITY       4494
#define SL_CONTEXT         4504
#define SL_TIER            4512
#define SL_LAYER           4518
#define SL_KIND            4525
#define SL_DEPTH           4531
#define SL_LEN             4538
#define SL_AREA            4543
#define SL_KM              4549
#define SL_KM2             4553
#define SL_M               4558
#define SL_FT              4561
#define SL_LON             4565
#define SL_LAT             4570
#define SL_TUN             4576
#define SL_PCT             4581
#define SL_811             4586
#define SL_GEN             4610
#define SL_ELEV            4630
#define SL_MAX             4636
#define SL_MIN             4641
#define SL_TRANSECT        4646
#define SL_ALONG           4659
#define SL_ON              4671
#define SL_OFF             4674
#define SL_VIS             4678
#define SL_SLASH           4683
#define SL_SITES           4685
#define SL_CORR            4691
#define SL_RINGS           4701
#define SL_VERTS           4707
#define SL_LCD             4716
#define SL_RAM             4721
#define SL_XDC             4726
#define SL_QUANT           4747
#define SL_SEA             4763
#define SL_NONE            4767
#define SL_ZOOM            4772
#define SL_SURF            4774
#define SL_TI83            4782
#define SL_TI89            4788
#define SL_TI92            4794
#define SL_HOST            4800
#define SL_Z80             4805
#define SL_M68K            4809
#define SL_LAYERSON        4814

extern const u16 SC_PT[];
extern const u16 SC_COR_OFF[];
extern const u8 SC_COR_LAYER[];
extern const u8 SC_COR_TIER[];
extern const i16 SC_COR_DEPTH[];
extern const u16 SC_COR_KM[];
extern const u8 SC_COR_TUN[];
extern const u16 SC_COR_NAME[];
extern const u16 SC_COR_SHORT[];
extern const u16 SC_COR_FACT[];
extern const u16 SC_NODE_Q[];
extern const u8 SC_NODE_LAYER[];
extern const u8 SC_NODE_TIER[];
extern const u8 SC_NODE_KIND[];
extern const i16 SC_NODE_DEPTH[];
extern const u16 SC_NODE_NAME[];
extern const u16 SC_NODE_FACT[];
extern const u16 SC_RING_PT[];
extern const u16 SC_RING_OFF[];
extern const u8 SC_RING_LAYER[];
extern const u8 SC_RING_TIER[];
extern const u16 SC_RING_NAME[];
extern const u16 SC_RING_KM2[];
extern const u16 SC_COAST[];
extern const i16 SC_RELIEF[];
extern const u16 SC_LAYER_NAME[];
extern const u8 SC_LAYER_KIND[];
extern const u8 SC_LAYER_ON[];
extern const u16 SC_KIND_NAME[];
extern const u8 SC_STR[];

#endif
