/* SOCAL SUBSURFACE — portable core for the TI-92, TI-89 and TI-83.
 *
 * This is the calculator port of socal-subsurface.xdc: the underground
 * infrastructure theater of Southern California, reduced to one 1-bit
 * framebuffer, integer arithmetic and a keypad.
 *
 * The 1-bit runtime underneath it — types, framebuffer, 3x5 font, integer
 * helpers, key codes — is NOT forked. It is SITE-K's, from calc/core, built
 * from the same files by the same compilers:
 *
 *     calc/core/sitek.h    types, FB_MAX, DEV_*, SKK_*, PX_*, FILL_*, fb_*
 *     calc/core/tables.c   3x5 font, 64-step sine, log2 mantissa
 *     calc/core/util.c     idiv/imod, u32w/mul32/shr32, log2_q8
 *     calc/core/fb.c       pixel/line/box/text into SK_FB
 *
 * What this port adds is in socal-calc/core:
 *
 *     socaldata.[ch]  GENERATED from the .xdc by tools/xdc2c.py
 *     sctables.c      GENERATED by tools/gen_tables.py (fine sine, gaussian)
 *     geo.c           integer projection, terrain field, log depth ramp
 *     app.c           five screens and the key dispatch
 *
 * Same dialect as calc/core, enforced by calc/tools/c2js.py:
 *   integer only, no float, no libc, no malloc, no struct, no pointer
 *   arithmetic, no ternary, no switch, declarations at block top.
 */
#ifndef SOCAL_H
#define SOCAL_H

#include "sitek.h"
#include "socaldata.h"

/* ---------- screens ---------- */
#define SC_SCR_BOOT 0
#define SC_SCR_MAP 1
#define SC_SCR_PROF 2
#define SC_SCR_LAYERS 3
#define SC_SCR_DOS 4
#define SC_SCR_INFO 5
#define SC_NSCREEN 6

/* ---------- feature classes in the unified selection list ---------- */
#define SC_CLS_COR 0
#define SC_CLS_NODE 1
#define SC_CLS_RING 2

#define SC_NFEAT (SC_NCOR + SC_NNODE + SC_NRING)

/* ---------- line styles, standing in for the web app's tier colours ------- */
#define SC_STY_SOLID 0
#define SC_STY_DASH 1
#define SC_STY_DOT 2

/* Longest profile the section screen will sample (TI-92 is 240 wide). */
#define SC_PROF_MAX 232

/* ---------- live state ---------- */
extern u8 SC_SCREEN;
extern u16 SC_SEL;      /* index into the unified feature list */
extern u8 SC_ZOOM;      /* 0..3 -> 1x, 2x, 4x, 8x on the selected feature */
extern u8 SC_DEPTHX;    /* depth exaggeration step, mirrors the web slider */
extern u8 SC_PROFMODE;  /* 0 = along the route, 1 = W-E transect */
extern u8 SC_LAYCUR;    /* cursor on the LAYERS screen */
extern u8 SC_DOSLINE;   /* scroll offset on the DOSSIER screen */
extern u8 SC_LAYON[SC_NLAYER];

/* ---------- geo.c ---------- */
i32 idiv32(i32 a, i32 b);
int sc_sin_turn(i32 t_q16);
int sc_cos_turn(i32 t_q16);
i32 sc_elev_q(i32 qlon, i32 qlat);
i32 sc_elev_deg(i32 lon_m, i32 lat_m);
u16 sc_depth_mag_q8(i32 metres);
u16 sc_isqrt32(u32 v);
u16 sc_km_span(i32 dqlon, i32 dqlat);
i32 sc_lon_mdeg(u16 q);
i32 sc_lat_mdeg(u16 q);

void sc_view(void);
int sc_px(u16 q);
int sc_py(u16 q);
extern u16 SC_MX;
extern u16 SC_MY;
extern u16 SC_MW;
extern u16 SC_MH;
extern i32 SC_VX;
extern i32 SC_VY;
extern i32 SC_VW;
extern i32 SC_VH;
extern i32 SC_KX;
extern i32 SC_KY;

/* ---------- app.c ---------- */
void socal_init(u8 dev, u16 w, u16 h);
void socal_key(u8 k);
void socal_tick(void);
void socal_render(void);
void socal_set_screen(u8 scr);
u8 socal_get_screen(void);
void socal_set_sel(u16 i);
u16 socal_get_sel(void);
void socal_toggle_layer(u8 i);
u8 socal_layer_on(u8 i);
u16 socal_feat_count(void);
u8 socal_feat_class(u16 f);
u16 socal_feat_sub(u16 f);
u8 socal_feat_layer(u16 f);
u8 socal_feat_tier(u16 f);
u16 socal_feat_name(u16 f);
u16 socal_visible(void);
u16 socal_layer_name(u8 i);
u8 socal_layer_kind(u8 i);
u16 socal_kind_name(u8 k);
u16 socal_feat_qlon(u16 f);
u16 socal_feat_qlat(u16 f);
i32 socal_feat_depth(u16 f);
u16 sc_str(u8 *dst, u16 off);
u16 sc_str_at(u8 *dst, u16 at, u16 off);
u16 sc_num_at(u8 *dst, u16 at, i32 v);
u16 sc_deg_at(u8 *dst, u16 at, i32 mdeg);
u16 sc_dev_label(u8 dev);
u16 sc_dev_cpu(u8 dev);
u16 sc_dev_ram(u8 dev);
void socal_set_zoom(u8 z);
void socal_set_depthx(u8 d);
void socal_set_profmode(u8 m);
void socal_set_laycur(u8 i);
u16 sc_prof_km(void);
u16 sc_prof_n(void);
i32 sc_prof_elev(u16 i);

#endif
