#!/usr/bin/env python3
"""Turn the JCreator Ghidra probe output into a research report.

    python3 tools/jcreator_report.py <inventory.json> <reports-dir> <out.md>

The report answers one question with evidence: how did a native Win32 IDE
discover and drive a JDK, and does that contract still exist in OpenJDK?
The OpenJDK half of the answer is checked into docs/jcreator-jdk-coupling.md
and was verified against openjdk/jdk, jdk8u, jdk17u and jdk21u directly.
"""
import json
import pathlib
import re
import sys

CATEGORY_QUESTION = {
    "registry": "Does it read `Software\\JavaSoft` to find an installed JDK?",
    "tools": "Which JDK executables does it shell out to?",
    "jars": "Does it know `classes.zip` (JDK 1.1) or `tools.jar` (1.2+)?",
    "flags": "Which javac/java command-line options does it construct?",
    "env": "Does it fall back to `JAVA_HOME` / `CLASSPATH`?",
    "jni": "Does it instead load `jvm.dll` in-process via the Invocation API?",
    "diagnostic": "Does it parse javac's error output?",
    "process": "What Win32 plumbing runs a tool and captures its output?",
}

ORDER = ["registry", "jni", "tools", "jars", "flags", "env", "process", "diagnostic"]


def load_reports(directory: pathlib.Path) -> list[dict]:
    rows = []
    for path in sorted(directory.glob("*.ghidra.json")):
        try:
            rows.append(json.loads(path.read_text()))
        except (OSError, json.JSONDecodeError) as exc:
            print(f"  warning: skipping unreadable {path.name}: {exc}", file=sys.stderr)
    return rows


def uniq_texts(hits: list[dict], limit: int = 28) -> list[str]:
    """Distinct string values, shortest first — the short ones are the tokens."""
    seen = {}
    for hit in hits:
        text = hit.get("text", "").strip()
        if not text or text in seen:
            continue
        seen[text] = len(hit.get("xrefs", []))
    ordered = sorted(seen.items(), key=lambda kv: (len(kv[0]), kv[0]))
    return [f"`{t}`" + (f" ({n} xref{'s' if n != 1 else ''})" if n else "")
            for t, n in ordered[:limit]]


def registry_paths(hits: list[dict]) -> list[str]:
    """Pull anything that looks like a full registry path out of the hits."""
    found = set()
    pattern = re.compile(r"(?i)(software\\+[A-Za-z0-9 _.\\\\-]+)")
    for hit in hits:
        for match in pattern.findall(hit.get("text", "")):
            cleaned = match.strip().rstrip("\\")
            if len(cleaned) > 8:
                found.add(cleaned)
    return sorted(found)


def notable_imports(report: dict) -> list[dict]:
    return [i for i in report.get("imports", []) if i.get("notable")]


def verdict(report: dict) -> str:
    """One sentence on the discovery mechanism, from the evidence only."""
    summary = report.get("probeSummary", {})
    imports = {i["name"] for i in report.get("imports", [])}
    reg = summary.get("registry", 0)
    jni = summary.get("jni", 0)
    has_reg_api = bool(imports & {"RegOpenKeyExA", "RegOpenKeyExW",
                                  "RegQueryValueExA", "RegQueryValueExW"})
    has_proc = bool(imports & {"CreateProcessA", "CreateProcessW"})

    parts = []
    if reg and has_reg_api:
        parts.append("reads the registry **and** imports the registry API")
    elif reg:
        parts.append("carries registry path strings but the API import was not resolved")
    elif has_reg_api:
        parts.append("imports the registry API with no matching path string")
    else:
        parts.append("shows no registry-based discovery")

    if has_proc:
        parts.append("runs tools out-of-process via `CreateProcess`")
    if jni:
        parts.append(f"references the JNI invocation surface ({jni} hit(s))")
    else:
        parts.append("shows no in-process `jvm.dll` linkage")
    return "; ".join(parts) + "."


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__)
        return 2
    inventory = json.loads(pathlib.Path(sys.argv[1]).read_text())
    reports = load_reports(pathlib.Path(sys.argv[2]))
    out_path = pathlib.Path(sys.argv[3])

    L: list[str] = []
    add = L.append

    add("# JCreator and the JDK: what a native IDE had to know about Java")
    add("")
    add("Generated by `tools/jcreator_report.py` from headless Ghidra output. "
        "Static analysis only — neither binary was executed, and no JDK was "
        "installed on the runner.")
    add("")

    add("## Provenance")
    add("")
    add("| item | file | bytes | md5 | sha1 |")
    add("|---|---|---:|---|---|")
    for src in inventory.get("sources", []):
        add(f"| [`{src['identifier']}`](https://archive.org/details/{src['identifier']}) "
            f"| `{src['filename']}` | {src['size']:,} | `{src['md5']}` | `{src['sha1']}` |")
    add("")
    add("Both archives were hash-gated against the checksums the Internet "
        "Archive publishes in its own item metadata before Ghidra saw them; "
        "`tools/jcreator_fetch.py` aborts on any mismatch.")
    add("")
    for src in inventory.get("sources", []):
        add(f"- **{src['key']}** — {src['note']}")
    add("")

    if not reports:
        add("## No Ghidra reports were produced")
        add("")
        add("The analysis step emitted no `*.ghidra.json`. See the workflow log.")
        out_path.write_text("\n".join(L) + "\n")
        print(f"wrote {out_path} (no reports)")
        return 0

    add("## Binaries analyzed")
    add("")
    add("| program | format | compiler | functions | strings |")
    add("|---|---|---|---:|---:|")
    for r in reports:
        add(f"| `{r['program']}` | {r.get('executableFormat','')} "
            f"| `{r.get('compiler','')}` | {r.get('functions',0):,} "
            f"| {r.get('definedStrings',0):,} |")
    add("")

    add("## Probe summary")
    add("")
    add("Every defined string in each binary was bucketed against a fixed probe "
        "set. Counts are matching strings, not occurrences.")
    add("")
    header = "| category | question | " + " | ".join(f"`{r['program']}`" for r in reports) + " |"
    add(header)
    add("|---|---|" + "---:|" * len(reports))
    for cat in ORDER:
        cells = " | ".join(str(r.get("probeSummary", {}).get(cat, 0)) for r in reports)
        add(f"| {cat} | {CATEGORY_QUESTION[cat]} | {cells} |")
    add("")

    for r in reports:
        add(f"## `{r['program']}`")
        add("")
        add(f"- SHA-256 `{r.get('sha256','')}`")
        add(f"- MD5 `{r.get('md5','')}`")
        add(f"- Language `{r.get('language','')}`, image base `{r.get('imageBase','')}`")
        add(f"- Ghidra {r.get('ghidraVersion','')}")
        add("")
        add(f"**Verdict.** This binary {verdict(r)}")
        add("")

        probe = r.get("probe", {})

        paths = registry_paths(probe.get("registry", []))
        if paths:
            add("### Registry paths found")
            add("")
            for p in paths:
                add(f"- `{p}`")
            add("")

        imports = notable_imports(r)
        if imports:
            add("### Imports that matter")
            add("")
            add("| symbol | library | xrefs | why it matters |")
            add("|---|---|---:|---|")
            for i in sorted(imports, key=lambda i: -i.get("references", 0)):
                add(f"| `{i['name']}` | {i.get('library','')} "
                    f"| {i.get('references',0)} | {i['notable']} |")
            add("")

        for cat in ORDER:
            hits = probe.get(cat, [])
            if not hits:
                continue
            texts = uniq_texts(hits)
            if not texts:
                continue
            add(f"### {cat} — {CATEGORY_QUESTION[cat]}")
            add("")
            add(", ".join(texts))
            add("")

        decomp = r.get("decompilations", [])
        if decomp:
            ok = sum(1 for d in decomp if d.get("decompiled"))
            add(f"### Decompiled ({ok}/{len(decomp)} succeeded)")
            add("")
            add("Functions were selected because they reference probe strings, "
                "not by address order. Full C is in the evidence directory.")
            add("")
            add("| function | address | selected because |")
            add("|---|---|---|")
            for d in decomp[:24]:
                add(f"| `{d['function']}` | `{d['address']}` | {d['reason']} |")
            add("")

    add("## Cross-reference: does this contract still exist?")
    add("")
    add("See [`jcreator-jdk-coupling.md`](jcreator-jdk-coupling.md) for the "
        "OpenJDK side, verified directly against `openjdk/jdk`, `openjdk/jdk8u`, "
        "`openjdk/jdk17u` and `openjdk/jdk21u`. In short: the JDK launcher's own "
        "registry lookup lived in `java_md.c` through JDK 8, was compiled out "
        "behind a never-defined `USE_REGISTRY_LOOKUP` by JDK 17, and the last "
        "vestige was deleted in 2024. The `Java Development Kit` key that a "
        "third-party IDE needed appears nowhere in the OpenJDK tree at all.")
    add("")

    out_path.write_text("\n".join(L) + "\n")
    print(f"wrote {out_path} ({len(L)} lines, {len(reports)} binaries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
